### ISSUE TITLE
how to set up database in HPC cluster

### ISSUE THREAD

**Issue by Jennie17** [nextgenusfs/funannotate#102]
Hi,

Thanks for this beautiful tool.

While funannotate is installed in our HPC cluster, we don't have the writing access to the directory 
/usr/local/funannotate/0.7.2/DB

So when I ran the test, I get the error msg as pasted at the end.

Previously, to aviod this problem, instead of downloading the db to the default directory, I tried to install the database to my home dir, using -d option as suggested, but funannotate cannot recognize it and always reported error: database not configured properly.

Could you please advise how to configure the database when I downloaded it to my own working dir rather than the default setting in the HPC cluster environment?

Looking forward to your reply

Thank you very much!
```
$ cat funanno.e1606203
[04:34:01 PM]: OS: linux2, 24 cores, ~ 132 GB RAM. Python: 2.7.9
[04:34:02 PM]: Running funannotate v0.7.2
[04:34:02 PM]: Downloading dikarya busco models
[04:41:30 PM]: Augustus training set for botrytis_cinerea already exists, thus funannotate will use those parameters.
                If you want to re-train, provide a unique name for the --augustus_species argument
[04:41:31 PM]: AUGUSTUS (3.2.1) detected, version seems to be compatible with BRAKER1 and BUSCO
[04:41:31 PM]: Loading sequences and soft-masking genome
[04:41:31 PM]: Soft-masking: building RepeatModeler database
[04:41:41 PM]: Soft-masking: generating repeat library using RepeatModeler
[04:42:39 PM]: Soft-masking: running RepeatMasker with custom library
[04:43:12 PM]: Masked genome: 3 scaffolds; 451,050 bp; 0.74% repeats masked
[04:43:12 PM]: Aligning transcript evidence to genome with GMAP
[04:44:37 PM]: 220 transcripts aligned with GMAP
[04:44:37 PM]: Aligning transcript evidence to genome with BLAT
[04:44:39 PM]: 469 filtered BLAT alignments
[04:44:39 PM]: Mapping proteins to genome using tBlastn/Exonerate
[04:44:39 PM]: Using 9,043 proteins as queries
[04:44:39 PM]: Running pre-filter tBLASTN step
[04:44:48 PM]: Found 98 preliminary alignments
[04:44:51 PM]: Exonerate finished: found 5 alignments
[04:44:51 PM]: Running GeneMark-ES on assembly
[04:46:24 PM]: Converting GeneMark GTF file to GFF3
[04:46:24 PM]: Found 109 gene models
[04:46:24 PM]: Running Augustus gene prediction
[04:47:15 PM]: Found 186 gene models
[04:47:15 PM]: Pulling out high quality Augustus predictions
[04:47:15 PM]: Found 68 high quality predictions from Augustus (>90% exon evidence)
[04:47:15 PM]: 378 total gene models from all sources
[04:47:15 PM]: Setting up EVM partitions
[04:47:16 PM]: Generating EVM command list
[04:47:16 PM]: Running EVM commands with 5 CPUs
[04:47:26 PM]: Combining partitioned EVM outputs
[04:47:26 PM]: Converting EVM output to GFF3
[04:47:26 PM]: Collecting all EVM results
[04:47:26 PM]: 181 total gene models from EVM
[04:47:26 PM]: Predicting tRNAs
[04:47:28 PM]: Found 1 tRNA gene models
[04:47:28 PM]: Merging EVM output with tRNAscan output
[**04:47:28 PM]: Reformatting GFF file using GAG
Traceback (most recent call last):
  File "/usr/local/funannotate/0.7.2/bin/funannotate-predict.py", line 1050, in <module>
    lib.GAGprotClean(GAG_proteins_original, GAG_proteins)
  File "/usr/local/funannotate/0.7.2/lib/library.py", line 1504, in GAGprotClean
    with open(input, 'ru') as infile:
IOError: [Errno 2] No such file or directory: 'genome1/predict_misc/gag1/genome.proteins.fasta'**
$ cat  funanno.o1606203
-------------------------------------------------------
Directory not copied. Error: [Errno 13] Permission denied: '/usr/local/funannotate/0.7.2/DB/dikarya'
```

**Comment by nextgenusfs** [comment]
@Jennie17.  Is this the same error as in https://github.com/nextgenusfs/funannotate/issues/103?

**Comment by Jennie17** [comment]
Yes, it is. Thanks.

**Comment by nextgenusfs** [comment]
v1.0.0 has new database installation and management modules. You can set the environmental variable FUNANNOTATE_DB to the path of the install database, should allow for local database and system installed funannotate
