### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by ad010902** [nextgenusfs/funannotate#1031]
Hi,
I catch bug below

Traceback (most recent call last):
  File "/home/duongnguyen/.local/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/home/duongnguyen/.local/lib/python3.6/site-packages/funannotate/funannotate.py", line 717, in main
    mod.main(arguments)
  File "/home/duongnguyen/.local/lib/python3.6/site-packages/funannotate/sort.py", line 81, in main
    args.input, args.base, args.out, minlen=args.minlen, simplify=args.simplify
  File "/home/duongnguyen/.local/lib/python3.6/site-packages/funannotate/sort.py", line 37, in SortRenameHeaders
    if minlen > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by ydanylko** [comment]
Currently having the same issue after suddenly being asked to run export funannotate_db again

**Comment by ydanylko** [comment]
fix seems to be to specify a minlen, I chose 1 and mine worked, hope this helps

**Comment by IdoBar** [comment]
Would be good to set up a default number here (50 or 100) to avoid this issue.
