### ISSUE TITLE
Run InterProScan with funannotate-docker

### ISSUE THREAD

**Issue by hanhan124** [nextgenusfs/funannotate#1037]
**Are you using the latest release?**
yes

**Describe the bug**
Running InterProScan5 on 11150 proteins
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/funannotate/aux_scripts/iprscan-local.py", line 82, in checkDocker
    proc = subprocess.Popen(
  File "/venv/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/venv/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/funannotate/aux_scripts/iprscan-local.py", line 337, in <module>
    checkDocker()
  File "/venv/lib/python3.8/site-packages/funannotate/aux_scripts/iprscan-local.py", line 89, in checkDocker
    if e.errno == os.errno.ENOENT:
AttributeError: module 'os' has no attribute 'errno'

**What command did you issue?**
funannotate-docker iprscan -i fun_1908-1B -m docker --cpus 12

**OS/Install Information**
funannotate-docker --version
funannotate v1.8.17

**Comment by mwittep** [comment]
Same problem here, any news?
