### ISSUE TITLE
 CMD ERROR: diamond makedb --in /tmp/augustus.training.proteins.fa --db /tmp/aug_training.dmnd

### ISSUE THREAD

**Issue by dingcaojin** [nextgenusfs/funannotate#1039]
**Are you using the latest release?**
yes.

**Describe the bug**
augustus.training.proteins.fa is empty. I tried different pasa gff3 file and used  the soft masked genome as  reference, but it was not work.
`ls -ll /tmp
total 16
-rwxrwxrwx 1 ding ding    0 May 10 11:51 augustus.training.proteins.fa`

**What command did you issue?**
`funannotate predict -i /mnt/e/linux/ding/data/annotate/00clean/nd.mx2.np2.clean.sort.mask.fa --species "Trichoderma asperellum" --isolate MX2 --transcript_evidence /mnt/f/lab/ann/trinity_out_dir2/Trinity-GG.fasta --rna_bam /mnt/e/linux/ding/data/annotate/bam/123mx2_merged.bam --pasa_gff /mnt/e/linux/ding/data/annotate/02PASA/mx2.sqlite.assemblies.fasta.transdecoder.gff3 --out /mnt/e/linu
x/ding/data/annotate/03funannotate_1/`

**Logfiles**
-------------------------------------------------------
[May 10 10:55 AM]: OS: Ubuntu 22.04, 12 cores, ~ 16 GB RAM. Python: 3.8.15
[May 10 10:55 AM]: Running funannotate v1.8.15
[May 10 10:55 AM]: Parsed training data, run ab-initio gene predictors as follows:
  Program        Training-Method
  augustus       pasa
  codingquarry   rna-bam
  genemark       selftraining
  glimmerhmm     pasa
  snap           pasa
[May 10 11:00 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[May 10 11:00 AM]: Genome loaded: 8 scaffolds; 37,465,576 bp; 6.61% repeats masked
[May 10 11:00 AM]: Existing transcript alignments found: /mnt/e/linux/ding/data/annotate/03funannotate_1/predict_misc/transcript_alignments.gff3
[May 10 11:00 AM]: Existing RNA-seq BAM hints found: /mnt/e/linux/ding/data/annotate/03funannotate_1/predict_misc/hints.BAM.gff
[May 10 11:00 AM]: Existing protein alignments found: /mnt/e/linux/ding/data/annotate/03funannotate_1/predict_misc/protein_alignments.gff3
[May 10 11:00 AM]: Existing GeneMark annotation found: /mnt/e/linux/ding/data/annotate/03funannotate_1/predict_misc/genemark.gff
[May 10 11:00 AM]: 10,730 predictions from GeneMark
[May 10 11:00 AM]: Filtering PASA data for suitable training set
[May 10 11:00 AM]: CMD ERROR: diamond makedb --in /tmp/augustus.training.proteins.fa --db /tmp/aug_training.dmnd
[May 10 11:00 AM]: diamond v2.1.8.162 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 12
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: /tmp/augustus.training.proteins.fa
**Opening the database file... Error: Error detecting input file format. First line seems to be blank.**

**OS/Install Information**
 `funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.8.15
-------------------------------------------------------
You are running Python v 3.8.15. Now checking python packages...
biopython: 1.76
goatools: 1.3.11
matplotlib: 3.7.5
natsort: 8.4.0
numpy: 1.24.4
pandas: 1.5.3
psutil: 5.9.8
requests: 2.31.0
scikit-learn: 1.3.2
scipy: 1.10.1
seaborn: 0.13.1
All 11 python packages installed

You are running Perl v b'5.032001'. Now checking perl modules...
Carp: 1.50
Clone: 0.46
DBD::SQLite: 1.72
DBD::mysql: 4.046
DBI: 1.643
DB_File: 1.858
Data::Dumper: 2.183
File::Basename: 2.85
File::Which: 1.24
Getopt::Long: 2.54
Hash::Merge: 0.302
JSON: 4.10
LWP::UserAgent: 6.67
Logger::Simple: 2.0
POSIX: 1.94
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.14
Tie::File: 1.06
URI::Escape: 5.17
YAML: 1.31
local::lib: 2.000029
threads: 2.25
threads::shared: 1.61
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/mnt/f/database/2024/funannotate/funannotate_db
$PASAHOME=/mnt/e/linux/ding/soft/miniconda3/envs/funannotate/opt/pasa-2.5.3
$TRINITY_HOME=/mnt/e/linux/ding/soft/miniconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/mnt/e/linux/ding/soft/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/mnt/e/linux/ding/soft/miniconda3/envs/funannotate/config/
$GENEMARK_PATH=/mnt/e/linux/ding/soft/gmes_linux_64_4/gmes_linux_64_4/gmes_petap.pl/mnt/e/linux/ding/soft/gmes_linux_64_4/gmes_linux_64_4/gmes_petap.pl
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
Traceback (most recent call last):
  File "/mnt/e/linux/ding/soft/miniconda3/envs/funannotate/bin/ete3", line 5, in <module>
    from ete3.tools.ete import main
  File "/mnt/e/linux/ding/soft/miniconda3/envs/funannotate/lib/python3.8/site-packages/ete3/tools/ete.py", line 55, in <module>
    from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,
  File "/mnt/e/linux/ding/soft/miniconda3/envs/funannotate/lib/python3.8/site-packages/ete3/tools/ete_view.py", line 48, in <module>
    from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,
ImportError: cannot import name 'TextFace' from 'ete3' (/mnt/e/linux/ding/soft/miniconda3/envs/funannotate/lib/python3.8/site-packages/ete3/__init__.py)

PASA: 2.5.3
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.5.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.31.1
blat: BLAT v37x1
diamond: 2.1.8
emapper.py: 2.1.12
exonerate: exonerate 2.4.0
fasta: 36.3.8g
glimmerhmm: 3.0.4
gmap: 2023-10-10
gmes_petap.pl: 4.71_lic
hisat2: 2.2.1
hmmscan: HMMER 3.4 (Aug 2023)
hmmsearch: HMMER 3.4 (Aug 2023)
java: 17.0.3-internal
kallisto: 0.46.1
mafft: v7.520 (2023/Mar/22)
makeblastdb: makeblastdb 2.14.1+
minimap2: 2.26-r1175
pigz: 2.8
proteinortho: 6.3.1
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.18
signalp: 5.0b
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.12 (Nov 2022)
tantan: tantan 49
tbl2asn: 25.8
tblastn: tblastn 2.14.1+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: ete3 not installed`

**Comment by danielabermeo8** [comment]
Hi, I notice that your gmes_petap.pl is working, and I am having soe issues with that. Please can you explain me how do you download it, because I already have the PATH for GENEMARK but I got this error in funannotate check --show-versions:  ERROR: gmes_petap.pl not installed
I hope you can help me please
