### ISSUE TITLE
Funannotate compare 

### ISSUE THREAD

**Issue by danielabermeo8** [nextgenusfs/funannotate#1040]
Hi, I am new using funannotate and I was trying to compare two annotated genomes with funannotate compare but I got this error. 
[May 14 06:28 PM]: OS: Ubuntu 20.04, 256 cores, ~ 1057 GB RAM. Python: 3.8.15
[May 14 06:28 PM]: Running 1.8.15
[May 14 06:28 PM]: Now parsing 1 genomes
Traceback (most recent call last):
  File "/root/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/root/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/compare.py", line 265, in main
    genomeStats = lib.genomeStats(GBK)
  File "/root/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py", line 9174, in genomeStats
    from Bio.SeqUtils import GC
ImportError: cannot import name 'GC' from 'Bio.SeqUtils' (/root/miniconda3/envs/funannotate/lib/python3.8/site-packages/Bio/SeqUtils/__init__.py)

So I run funannotate check --show-versions to check what was happening and I got this. Also I enter de PATH for genemark but in this part shows that gmes_petap.pl not installed. I tried everything to download de ete3 package and genemark. 

Checking dependencies for 1.8.15
-------------------------------------------------------
You are running Python v 3.8.15. Now checking python packages...
biopython: 1.83
goatools: 1.3.11
matplotlib: 3.4.3
natsort: 8.4.0
numpy: 1.24.4
pandas: 1.5.3
psutil: 5.9.8
requests: 2.31.0
scikit-learn: 1.3.2
scipy: 1.10.1
seaborn: 0.13.2
All 11 python packages installed

You are running Perl v b'5.032001'. Now checking perl modules...
Carp: 1.50
Clone: 0.46
DBD::SQLite: 1.72
DBD::mysql: 4.046
DBI: 1.643
DB_File: 1.858
Data::Dumper: 2.183
File::Basename: 2.85
File::Which: 1.24
Getopt::Long: 2.54
Hash::Merge: 0.302
JSON: 4.10
LWP::UserAgent: 6.67
Logger::Simple: 2.0
POSIX: 1.94
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.14
Tie::File: 1.06
URI::Escape: 5.17
YAML: 1.30
local::lib: 2.000029
threads: 2.25
threads::shared: 1.61
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/juan.baez/DBermeo/Fdatabase
$PASAHOME=/root/miniconda3/envs/funannotate/opt/pasa-2.5.3
$TRINITY_HOME=/root/miniconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/root/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/root/miniconda3/envs/funannotate/config/
$GENEMARK_PATH=/home/juan.baez/DBermeo/gmes_linux_64_4/gmes_petap.pl
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
Traceback (most recent call last):
  File "/root/miniconda3/envs/funannotate/bin/ete3", line 5, in <module>
    from ete3.tools.ete import main
  File "/root/miniconda3/envs/funannotate/lib/python3.8/site-packages/ete3/tools/ete.py", line 55, in <module>
    from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,
  File "/root/miniconda3/envs/funannotate/lib/python3.8/site-packages/ete3/tools/ete_view.py", line 48, in <module>
    from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,
ImportError: cannot import name 'TextFace' from 'ete3' (/root/miniconda3/envs/funannotate/lib/python3.8/site-packages/ete3/__init__.py)
PASA: 2.5.3
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.5.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.31.1
blat: BLAT v37x1
diamond: 2.1.9
emapper.py: 2.1.12
exonerate: exonerate 2.4.0
fasta: 36.3.8g
glimmerhmm: 3.0.4
gmap: 2024-03-15
hisat2: 2.2.1
hmmscan: HMMER 3.4 (Aug 2023)
hmmsearch: HMMER 3.4 (Aug 2023)
java: 17.0.3-internal
kallisto: 0.46.1
mafft: v7.525 (2024/Mar/13)
makeblastdb: makeblastdb 2.15.0+
minimap2: 2.28-r1209
pigz: 2.8
proteinortho: 6.3.1
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.18
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.12 (Nov 2022)
tantan: tantan 49
tbl2asn: 25.8
tblastn: tblastn 2.15.0+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /sys/fs/cgroup/cpuset.
        ERROR: ete3 not installed
        ERROR: gmes_petap.pl not installed
        ERROR: signalp not installed

**Comment by ruthpg** [comment]
Hi! 
I just ran into the same issue myself, I kept getting this error with  'GC' from 'Bio.SeqUtils'. Apparently this issue was already known and was answered here --> https://github.com/nextgenusfs/funannotate/issues/1000
and it has to do with the version of biopython you are using and you likely need to change it to a previous version

For me the issue was solved by running the following command: 
`pip install biopython==1.78`
