### ISSUE TITLE
installing databases failed

### ISSUE THREAD

**Issue by jacob-israel** [nextgenusfs/funannotate#1066]
**Are you using the latest release?**
 Yes , I am using the latest funannotate version.

**Describe the bug**
when trying to install the interpro databases, an error appears and that's it. I can't install BUSCO databases like dikarya.The first databases download and install correctly, but since I try to install the interpro database, it fails and I can't install another database.

**What command did you issue?**
$ funannotate setup -f -i interpro 
or
$ funannotate setup -i all --update
-------------------------------------------------------
[Sep 02 09:57 PM]: OS: Ubuntu 24.04, 16 cores, ~ 528 GB RAM. Python: 3.12.3
[Sep 02 09:57 PM]: Running 1.8.5
[Sep 02 09:57 PM]: Database location: /data2TB/databases/funannotate
[Sep 02 09:57 PM]: Retrieving download links from GitHub Repo
[Sep 02 09:57 PM]: Parsing Augustus pre-trained species and porting to funannotate
[Sep 02 09:57 PM]: Downloading InterProScan Mapping file
[Sep 02 09:57 PM]: Downloading: http://ftp.ebi.ac.uk/pub/databases/interpro/current_release/interpro.xml.gz Bytes: 37913043
[Sep 02 10:00 PM]: Downloading: http://ftp.ebi.ac.uk/pub/databases/interpro/current_release/entry.list Bytes: 2527016
Traceback (most recent call last):
  File "/usr/local/bin/funannotate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/usr/local/lib/python3.12/dist-packages/funannotate/setupDB.py", line 704, in main
    interproDB(DatabaseInfo, args.force, args=args)
  File "/usr/local/lib/python3.12/dist-packages/funannotate/setupDB.py", line 436, in interproDB
    for x in elem.getchildren():
             ^^^^^^^^^^^^^^^^
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

**Logfiles**

**OS/Install Information**
 -  Ubuntu Linux Server 24.04 LTS

**Comment by hyphaltip** [comment]
works for me as of now w/ version `1.8.17` which is live code  -- can you confirm the network connection works for you 

```
funannotate setup -f -i interpro
-------------------------------------------------------
[Sep 02 08:45 PM]: OS: Rocky Linux 8.8, 96 cores, ~ 527 GB RAM. Python: 3.8.15
[Sep 02 08:45 PM]: Running 1.8.17
[Sep 02 08:45 PM]: Database location: /srv/projects/db/funannotate/1.8
[Sep 02 08:45 PM]: Retrieving download links from GitHub Repo
[Sep 02 08:45 PM]: Parsing Augustus pre-trained species and porting to funannotate
[Sep 02 08:46 PM]: Downloading InterProScan Mapping file
[Sep 02 08:46 PM]: Downloading: http://ftp.ebi.ac.uk/pub/databases/interpro/current_release/interpro.xml.gz Bytes: 37913043
[Sep 02 08:47 PM]: Downloading: http://ftp.ebi.ac.uk/pub/databases/interpro/current_release/entry.list Bytes: 2527016
[Sep 02 08:47 PM]: InterProScan XML: version=101.0 date=2024-07-25 records=45,899
```

**Comment by jacob-israel** [comment]
@hyphaltip yes I confirm the network connections works for me.  


 funannotate setup -f -i interpro
-------------------------------------------------------
[Sep 03 08:36 PM]: OS: Ubuntu 24.04, 16 cores, ~ 528 GB RAM. Python: 3.12.3
[Sep 03 08:36 PM]: Running 1.8.5
[Sep 03 08:36 PM]: Database location: /data2TB/databases/funannotate
[Sep 03 08:36 PM]: Retrieving download links from GitHub Repo
[Sep 03 08:36 PM]: Parsing Augustus pre-trained species and porting to funannotate
[Sep 03 08:36 PM]: Downloading InterProScan Mapping file
[Sep 03 08:36 PM]: Downloading: http://ftp.ebi.ac.uk/pub/databases/interpro/current_release/interpro.xml.gz Bytes: 37913043
[Sep 03 08:39 PM]: Downloading: http://ftp.ebi.ac.uk/pub/databases/interpro/current_release/entry.list Bytes: 2527016
Traceback (most recent call last):
  File "/usr/local/bin/funannotate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/usr/local/lib/python3.12/dist-packages/funannotate/setupDB.py", line 704, in main
    interproDB(DatabaseInfo, args.force, args=args)
  File "/usr/local/lib/python3.12/dist-packages/funannotate/setupDB.py", line 436, in interproDB
    for x in elem.getchildren():
             ^^^^^^^^^^^^^^^^
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

**Comment by hyphaltip** [comment]
I guess I would suggest upgrading from github live perhaps as I can't replicate this error wth the current code. I'm not sure what changed to support this parsing.

**Comment by gkanogiannis** [comment]
All ftp.ebi.ac.uk links need to be https, otherwise some downloads stuck at 99%
