### ISSUE TITLE
busco_db Installation Issue 

### ISSUE THREAD

**Issue by xianlord93** [nextgenusfs/funannotate#1075]
Greetings, I was having this issue when trying to install the BUSCO database. How can I solve it? Many thanks!

(prokka) [eryixian@cpu17 tinea]$ funannotate setup -b dikarya -d /home/user/eryixian/database/funannotate
             
-------------------------------------------------------
[Oct 24 01:23 PM]: OS: Rocky Linux 9.4, 128 cores, ~ 792 GB RAM. Python: 3.7.16
[Oct 24 01:23 PM]: Running 1.8.17
[Oct 24 01:23 PM]: Database location: /home/user/eryixian/database/funannotate
[Oct 24 01:23 PM]: Retrieving download links from GitHub Repo
[Oct 24 01:23 PM]: Parsing Augustus pre-trained species and porting to funannotate
Traceback (most recent call last):
  File "/home/user/eryixian/.conda/envs/prokka/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/user/eryixian/.conda/envs/prokka/lib/python3.7/site-packages/funannotate/funannotate.py", line 717, in main
    mod.main(arguments)
  File "/home/user/eryixian/.conda/envs/prokka/lib/python3.7/site-packages/funannotate/setupDB.py", line 730, in main
    meropsDB(DatabaseInfo, args.force, args=args)
  File "/home/user/eryixian/.conda/envs/prokka/lib/python3.7/site-packages/funannotate/setupDB.py", line 175, in meropsDB
    type, name, version, date, records, checksum = info.get('merops')
TypeError: cannot unpack non-iterable NoneType object

**Comment by hyphaltip** [comment]
can you try again, I was able to download this busco package today.
you can also directly download these packages from BUSCO website into your database folder.
