### ISSUE TITLE
ModuleNotFoundError: No module named 'distro' v.1.8.17

### ISSUE THREAD

**Issue by IrinaVKuznetsova** [nextgenusfs/funannotate#1082]
Hi, 

This is my first time using funannotate tool.  Installing it on HPC.
I downloaded a SIF image (v.1.8.17) from https://depot.galaxyproject.org/singularity/
Next, tried to install databases: 
`singularity run $SIF_DIR funannotate setup -d $DATABASEOUT`

getting an error:

```
Traceback (most recent call last):
  File "/opt/conda/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/funannotate/funannotate.py", line 715, in main
    mod = importlib.import_module(
  File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/conda/lib/python3.9/site-packages/funannotate/setupDB.py", line 21, in <module>
    import funannotate.library as lib
  File "/opt/conda/lib/python3.9/site-packages/funannotate/library.py", line 17, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'
```

tried container from another provider of the same version and got the same error.
If I call for the help page it works fine.
Any help would be appreciated.
Thanks

**Comment by nidhi-gohil** [comment]
I installed funannoate using conda and then tried database set up command: `funannotate setup -i all` but it is giving me the same error as above:

```
Traceback (most recent call last):
  File "miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/nidhi/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 715, in main
    mod = importlib.import_module(
  File "/home/nidhi/miniconda3/envs/funannotate/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nidhi/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/setupDB.py", line 21, in <module>
    import funannotate.library as lib
  File "/home/nidhi/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py", line 17, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'
```

I would appreciate help on this earliest, if possible.

Thanks.

**Comment by Jack-Gregory-Bioinformatics** [comment]
Hi both,

I just ran into the same issue when trying to run the database setup. I had downloaded funannotate using conda/mamba.

To resolve the issue I had to install distro to the environment using:

`conda install conda-forge::distro`

I hope this helps.

**Comment by atiweb** [comment]
Triage note: this looks resolved and likely closable.

`distro` has been declared in funannotate's `install_requires` since the v1.8 prerelease and is present in the repo Dockerfile, so a fresh `pip`/Docker install pulls it. The original failure was a prebuilt Singularity image (Galaxy depot) that predated the dependency being included; the bioconda recipe was subsequently fixed as noted in #1072. Users who hit it on conda can resolve it immediately with `conda install conda-forge::distro` (confirmed above).
