### ISSUE TITLE
SNAP error - ValueError: not enough values to unpack (expected 9, got 3)

### ISSUE THREAD

**Issue by agesantos** [nextgenusfs/funannotate#1088]
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

R: I am using the latest version available on dockerhub (without GeneMark). 

**Describe the bug**

R: I am trying to run funannotate on a fish genome assembly. 
I follow the tutorial https://funannotate.readthedocs.io/en/latest/tutorials.html 
I had to run some adjustments (see below) but everything went well until the prediction step tried to run SNAP. The error was as follows:  

-------------------------------------------------------
[Dec 27 11:16 AM]: OS: Debian GNU/Linux 10, 32 cores, ~ 66 GB RAM. Python: 3.8.12
[Dec 27 11:16 AM]: Running funannotate v1.8.17
[Dec 27 11:16 AM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[Dec 27 11:17 AM]: Found training files, will re-use these files:
  --stringtie fun/training/funannotate_train.stringtie.gtf
[Dec 27 11:17 AM]: Skipping CodingQuarry as no --rna_bam passed
[Dec 27 11:17 AM]: Parsed training data, run ab-initio gene predictors as follows:
  [4mProgram      Training-Method[0m
  augustus     busco          
  glimmerhmm   busco          
  snap         busco          
[Dec 27 11:33 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Dec 27 11:36 AM]: Genome loaded: 3,232 scaffolds; 1,871,063,696 bp; 14.10% repeats masked
[Dec 27 11:37 AM]: Existing protein alignments found: fun/predict_misc/protein_alignments.gff3
[Dec 27 11:37 AM]: Existing BUSCO results found: fun/predict_misc/busco.final.gff3 containing 3,667 predictions
[Dec 27 11:37 AM]: Existing Augustus annotations found: fun/predict_misc/augustus.gff3
[Dec 27 11:38 AM]: Pulling out high quality Augustus predictions
[Dec 27 11:38 AM]: Found 146 high quality predictions from Augustus (>90% exon evidence)
[Dec 27 11:38 AM]: Running SNAP gene prediction, using training data: fun/predict_misc/busco.final.gff3
Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 717, in main
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/predict.py", line 2382, in main
    lib.runSnap(
  File "/venv/lib/python3.8/site-packages/funannotate/library.py", line 8317, in runSnap
    zff2gff3(snapRaw, fasta, output)
  File "/venv/lib/python3.8/site-packages/funannotate/library.py", line 8076, in zff2gff3
    (
ValueError: not enough values to unpack (expected 9, got 3)

**What command did you issue?**
Copy/paste the command used.

R: Here are the commands I ran flowing the tutorial - https://funannotate.readthedocs.io/en/latest/tutorials.html 

# clean
funannotate clean -i genome.fasta --minlen 1000 -o genome.cleaned.fa 

# sort
funannotate sort -i genome.cleaned.fa --minlen 1 -b scaffold -o genome.cleaned.sorted.fa 

# mask
funannotate mask -i genome.cleaned.sorted.fa --cpus 32 -o genome.cleaned.sorted.masked.fa 

# train
funannotate train -i genome.cleaned.sorted.masked.fa -o fun \
--left Hdi_TR_F_1.fq.gz \
--right Hdi_TR_F_2.fq.gz \
--stranded RF --jaccard_clip --species "Species name" --cpus 30 

# setup
# NOTE: I had to run setup for BUSCO, using a local folder (outside the docker) with the databases as it had a permission error using the folder inside the docker. 

export AUGUSTUS_CONFIG_PATH=/home/andresantos/App/Augustus/config
funannotate setup -d /home/andresantos/App/funannotate-master/databases -b actinopterygii 

# predict
export AUGUSTUS_CONFIG_PATH=/home/andresantos/App/Augustus/config
export FUNANNOTATE_DB=/home/andresantos/App/funannotate-master/databases
funannotate predict -i genome.cleaned.sorted.masked.fa --max_intronlen 100000 --organism other --repeats2evm --busco_db actinopterygii -o fun --species "Species name" --cpus 30 

**Logfiles**
Please provide relavent log files of the error. 

-------------------------------------------------------
[Dec 27 11:16 AM]: OS: Debian GNU/Linux 10, 32 cores, ~ 66 GB RAM. Python: 3.8.12
[Dec 27 11:16 AM]: Running funannotate v1.8.17
[Dec 27 11:16 AM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[Dec 27 11:17 AM]: Found training files, will re-use these files:
  --stringtie fun/training/funannotate_train.stringtie.gtf
[Dec 27 11:17 AM]: Skipping CodingQuarry as no --rna_bam passed
[Dec 27 11:17 AM]: Parsed training data, run ab-initio gene predictors as follows:
  [4mProgram      Training-Method[0m
  augustus     busco          
  glimmerhmm   busco          
  snap         busco          
[Dec 27 11:33 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Dec 27 11:36 AM]: Genome loaded: 3,232 scaffolds; 1,871,063,696 bp; 14.10% repeats masked
[Dec 27 11:37 AM]: Existing protein alignments found: fun/predict_misc/protein_alignments.gff3
[Dec 27 11:37 AM]: Existing BUSCO results found: fun/predict_misc/busco.final.gff3 containing 3,667 predictions
[Dec 27 11:37 AM]: Existing Augustus annotations found: fun/predict_misc/augustus.gff3
[Dec 27 11:38 AM]: Pulling out high quality Augustus predictions
[Dec 27 11:38 AM]: Found 146 high quality predictions from Augustus (>90% exon evidence)
[Dec 27 11:38 AM]: Running SNAP gene prediction, using training data: fun/predict_misc/busco.final.gff3
Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 717, in main
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/predict.py", line 2382, in main
    lib.runSnap(
  File "/venv/lib/python3.8/site-packages/funannotate/library.py", line 8317, in runSnap
    zff2gff3(snapRaw, fasta, output)
  File "/venv/lib/python3.8/site-packages/funannotate/library.py", line 8076, in zff2gff3
    (
ValueError: not enough values to unpack (expected 9, got 3)

**OS/Install Information**
 -  output of `funannotate check --show-versions`

-------------------------------------------------------
Checking dependencies for 1.8.17
-------------------------------------------------------
You are running Python v 3.8.12. Now checking python packages...
biopython: 1.79
goatools: 1.4.12
matplotlib: 3.7.3
natsort: 8.4.0
numpy: 1.22.4
pandas: 2.0.3
psutil: 6.0.0
requests: 2.32.3
scikit-learn: 0.24.2
scipy: 1.5.3
seaborn: 0.13.0
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
local::lib: 2.000024
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/opt/databases
$PASAHOME=/venv/opt/pasa-2.4.1
$TRINITYHOME=/venv/opt/trinity-2.8.5
$EVM_HOME=/venv/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/usr/share/augustus/config
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.2
bamtools: bamtools 2.5.2
bedtools: bedtools v2.31.1
blat: BLAT v35
diamond: 2.1.8
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: 36.3.8g
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.1
hmmscan: HMMER 3.4 (Aug 2023)
hmmsearch: HMMER 3.4 (Aug 2023)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.526 (2024/Apr/26)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.28-r1209
pigz: 2.8
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.12
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 50
tbl2asn: 25.8
tblastn: tblastn 2.2.31+
trimal: trimAl v1.5.rev0 build[2024-05-27]
trimmomatic: 0.39
	ERROR: emapper.py not installed
	ERROR: gmes_petap.pl not installed
	ERROR: signalp not installed

**Comment by hyphaltip** [comment]
you should look at the snap output ZFF or other files to see what is going on but seems like snap has failed and funannotate cannot handle these broken output files.
