### ISSUE TITLE
funannotate setup socket error

### ISSUE THREAD

**Issue by nextgenusfs** [nextgenusfs/funannotate#125]
Kindly guide me on how to get around the following error:

```
"$ funannotate setup -d funannotate_database/
-------------------------------------------------------
[06:51:31 PM]: OS: linux2, 44 cores, ~ 132 GB RAM. Python: 2.7.11
[06:51:32 PM]: Running funannotate v1.0.2
[06:51:32 PM]: Database location: funannotate_database/
[06:51:32 PM]: Downloading Merops database
Traceback (most recent call last):
  File "/home/supermicro/funannotate/bin/funannotate-setup.py", line 418, in <module>
    meropsDB(DatabaseInfo, args.force)
  File "/home/supermicro/funannotate/bin/funannotate-setup.py", line 99, in meropsDB
    download(lib.DBURL.get('merops'), fasta)
  File "/home/supermicro/funannotate/bin/funannotate-setup.py", line 85, in download
    except SocketError as e:
NameError: global name 'SocketError' is not defined"
```

**Comment by nextgenusfs** [comment]
probably forgot to `import socket` in setup script?  not sure why this wouldn't have been caught on mac....

**Comment by nextgenusfs** [comment]
This was also a problem as merops database download file changed its name.... I think should be working now.
