### ISSUE TITLE
invalid rc parameter axes colour

### ISSUE THREAD

**Issue by AnotherSimon** [nextgenusfs/funannotate#159]
When running `funannotate compare` the following error occurs:

>...
[Mar 27 11:23 AM]: Running funannotate v1.3.0-beta
[Mar 27 11:23 AM]: Now parsing 4 genomes
[Mar 27 11:23 AM]: working on Malassezia furfur
[Mar 27 11:23 AM]: working on Malassezia furfur
[Mar 27 11:23 AM]: working on Malassezia furfur
[Mar 27 11:23 AM]: working on Malassezia furfur
[Mar 27 11:23 AM]: Summarizing secondary metabolism gene clusters
Traceback (most recent call last):
  File "/home/simon/software/funannotate/bin/funannotate-compare.py", line 288, in <module>
    lib.drawStackedBar(smdf, 'Secondary Metabolism Clusters', SM, ymax, os.path.join(args.out, 'secmet','SM.graph.pdf'))
  File "/home/simon/software/funannotate/lib/library.py", line 4698, in drawStackedBar
    import seaborn as sns
   File "/home/admin/software/lib/python2.7/site-packages/seaborn/__init__.py", line 13, in <module>
    set()
  File "/home/admin/software/lib/python2.7/site-packages/seaborn/rcmod.py", line 98, in set
    set_palette(palette, color_codes=color_codes)
  File "/home/admin/software/lib/python2.7/site-packages/seaborn/rcmod.py", line 491, in set_palette
    mpl.rcParams["axes.color_cycle"] = list(colors)
  File "/home/admin/software/lib/python2.7/site-packages/matplotlib/__init__.py", line 929, in __setitem__
    'list of valid parameters.' % (key,))
KeyError: 'axes.color_cycle is not a valid rc parameter. See rcParams.keys() for a list of valid parameters.'

**Comment by AnotherSimon** [comment]
Please ignore this issue, it was due to a broken link to libraries required for seaborn and matplotlib
