### ISSUE TITLE
No  repeats.xml

### ISSUE THREAD

**Issue by ykjyhmj** [nextgenusfs/funannotate#171]
Hi, I tried to annotate my genome with funannotate(v1.3.3). When I run the test run for the sample data, for all the genomes, it stopped at filtering out bad gene models
```
[09:32 AM]: now filtering out bad gene models (< 50 aa in length, transposable elements, etc).
Traceback (most recent call last):
  File "/mnt/sequence/mhu2/soft/funannotate-1.3.3/bin/funannotate-predict.py", line 1220, in <module>
    lib.RepeatBlast(EVM_proteins, args.cpus, 1e-10, FUNDB, os.path.join(args.out, 'predict_misc'), Blast_rep_remove)
  File "/mnt/sequence/mhu2/soft/funannotate-1.3.3/lib/library.py", line 3546, in RepeatBlast
    with open(blast_tmp, 'rU') as results:
IOError: [Errno 2] No such file or directory: 'genome3/predict_misc/repeats.xml'
```
Thanks for the help!

**Comment by ykjyhmj** [comment]
Problem sovled by update diamond from 0.8.22-2 to 0.9.21-1

**Comment by ykjyhmj** [comment]
Another problem appeared at tRNA prediction stage
```
[10:17 AM]: Predicting tRNAs
Traceback (most recent call last):
  File "/mnt/sequence/mhu2/soft/funannotate-1.3.3/bin/funannotate-predict.py", line 1232, in <module>
    lib.runtRNAscan(MaskGenome, os.path.join(args.out,'predict_misc'), tRNAscan)
  File "/mnt/sequence/mhu2/soft/funannotate-1.3.3/lib/library.py", line 3964, in runtRNAscan
    runSubprocess(cmd, '.', log)
  File "/mnt/sequence/mhu2/soft/funannotate-1.3.3/lib/library.py", line 590, in runSubprocess
    proc = subprocess.Popen(cmd, cwd=dir, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/mnt/sequence/mhu2/miniconda2/envs/genome/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/mnt/sequence/mhu2/miniconda2/envs/genome/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by nextgenusfs** [comment]
Glad you figured out the diamond version problem. Second problem probably tRNAscan installation error. Have a look at the log files which game more information about which commands were run and the errors

**Comment by ykjyhmj** [comment]
It's indeed tRNAscan installation error. It seems that funannotate doesn't check the version tRNAscan. And only when the error turns up, I realized that I didn't install tRNAscan.

**Comment by ykjyhmj** [comment]
By the way, when funannotate try to run interProscan, what file it uses as input? The genome file or the predicted protein file?

**Comment by nextgenusfs** [comment]
Just to add a little bit: if you specify the funannotate output directory as input, it will first look in the `update_results` folder if it exists, then move onto looking into the `predict_results` folder.  Otherwise it is expecting a protein sequence FASTA file.
