### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by EricFournier3** [nextgenusfs/funannotate#183]
Hi,
i have this timed out when i try to install the docker;
```
[07:02:26 PM]: Building diamond database
[07:02:27 PM]: MEROPS Database: version=12.0 date=2017-10-04 records=4,968
[07:02:27 PM]: Downloading UniProtKB/SwissProt database
Traceback (most recent call last):
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 416, in <module>
    uniprotDB(DatabaseInfo, args.force)
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 132, in uniprotDB
    download(lib.DBURL.get('uniprot'), fasta+'.gz')
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 66, in download
    u = urllib2.urlopen(url)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 1412, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 1434, in connect_ftp
    persistent=False)
  File "/home/linuxbrew/conda/lib/python2.7/urllib.py", line 875, in __init__
    self.init()
  File "/home/linuxbrew/conda/lib/python2.7/urllib.py", line 884, in init
    self.ftp.connect(self.host, self.port, self.timeout)
  File "/home/linuxbrew/conda/lib/python2.7/ftplib.py", line 135, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/home/linuxbrew/conda/lib/python2.7/socket.py", line 575, in create_connection
    raise err
urllib2.URLError: <urlopen error ftp error: [Errno 110] Connection timed out>
 ---> 1a9a2b510f71
Removing intermediate container d0fcbc7a9570
Step 8/9 : WORKDIR /home/linuxbrew/data
 ---> 41d2d6045dab
Removing intermediate container f8e96734b980
Step 9/9 : ENTRYPOINT touch $(brew --prefix)/bin/mysql.server &&     sudo chown -R linuxbrew:linuxbrew $(brew --prefix)/bin/mysql $(brew --prefix)/bin/mysqld &&     sudo chmod 777 $(brew --prefix)/bin/mysqld &&     $(brew --prefix)/bin/mysql.server start &&     mysql -uroot -e "CREATE USER 'pasa1'@'localhost' IDENTIFIED BY 'pasa1';" &&     mysql -uroot -e "GRANT ALL PRIVILEGES ON * . * TO 'pasa1'@'localhost';" &&     mysql -uroot -e "FLUSH PRIVILEGES;" && /bin/bash
 ---> Running in 154b4bf4749f
 ---> 6ee4d6e43094
Removing intermediate container 154b4bf4749f
Successfully built 6ee4d6e43094
```
Thanks for your help
Eric

**Comment by nextgenusfs** [comment]
Seems like UniProtKb/SwissProt database was not responding. I just tried locally and it seemed to work.  Does re-running it give you same error?

**Comment by EricFournier3** [comment]
after trying again, i still have the timed out;
[01:33 PM]: OS: linux2, 40 cores, ~ 528 GB RAM. Python: 2.7.14
[01:33 PM]: Running funannotate v1.3.4
[01:33 PM]: Database location: /home/linuxbrew/DB
[01:33 PM]: Downloading Merops database
[01:33 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/merops_scan.lib Bytes: 1942655
-------------------------------------------------------
[01:34 PM]: Building diamond database
[01:34 PM]: MEROPS Database: version=12.0 date=2017-10-04 records=4,968
[01:34 PM]: Downloading UniProtKB/SwissProt database
Traceback (most recent call last):
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 439, in <module>
    uniprotDB(DatabaseInfo, args.force)
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 133, in uniprotDB
    download(lib.DBURL.get('uniprot'), fasta+'.gz')
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 67, in download
    u = urllib2.urlopen(url)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 429, in open

**Comment by nextgenusfs** [comment]
Is your system or IP blocking traffic to ftp?  Not sure what else could be happening.

**Comment by nextgenusfs** [comment]
Can you download via wget?
```
wget ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/merops_scan.lib
```

**Comment by nextgenusfs** [comment]
If the above works, but it isn't working in docker then must be a docker related issue. I'm not a fan of docker for several reasons and can add this to the list..... You can then also check the same thing from the base funannotate docker image, something like:
```
docker run -it --rm -v $PWD:/home/linuxbrew/data nextgenusfs/funannotate
```
And then get try the same wget command and/or try to install databases in interactive mode, 
```
funannotate setup -d /home/linuxbrew/DB
```

**Comment by EricFournier3** [comment]
I successfully installed  all dependencies and perl modules with cpanm Getopt::Long Pod::Usage File::Basename threads threads::shared \
   Thread::Queue Carp Data::Dumper YAML Hash::Merge Logger::Simple Parallel::ForkManager \
   DBI Text::Soundex Scalar::Util::Numeric Clone JSON LWP::UserAgent DBD::mysql URI::Escape

and Bio::Perl with 
cpanm --sudo Bio::Perl   
(i can see doc with  
perldoc -l  Bio::Perl
/usr/local/share/perl5/Bio/Perl.pm
)
but funannotate is unable to find those perl modules with
funannotate check --show-versions

 ERROR: Bio::Perl not installed, install with cpanm Bio::Perl
   ERROR: Clone not installed, install with cpanm Clone
   ERROR: DBD::mysql not installed, install with cpanm DBD::mysql
   ERROR: DBI not installed, install with cpanm DBI
   ERROR: DB_File not installed, install with cpanm DB_File
   ERROR: Hash::Merge not installed, install with cpanm Hash::Merge
   ERROR: JSON not installed, install with cpanm JSON
   ERROR: LWP::UserAgent not installed, install with cpanm LWP::UserAgent
   ERROR: Logger::Simple not installed, install with cpanm Logger::Simple
   ERROR: Parallel::ForkManager not installed, install with cpanm Parallel::ForkManager
   ERROR: Scalar::Util::Numeric not installed, install with cpanm Scalar::Util::Numeric
   ERROR: Text::Soundex not installed, install with cpanm Text::Soundex
   ERROR: YAML not installed, install with cpanm YAML

Thanks for your help

**Comment by EricFournier3** [comment]
[foueri01@inspq.qc.ca@slbio00d perl5]$ pwd
/usr/local/share/perl5
[foueri01@inspq.qc.ca@slbio00d perl5]$ ls
Algorithm  Class      Getopt   Logger        ok.pm      Spiffy.pod  Thread
App        Clone      Hash     LWP           Parallel   Sub         Try
Bio        CPAN       IO       LWP.pm        Parse      TAP         x86_64-linux-thread-multi
Bundle     Data       IPC      Module        Perl       Test        YAML
Capture    Devel      JSON     Net           Pod        Test2       YAML.pm
Carp       Exception  JSON.pm  newgetopt.pl  Spiffy     Test2.pm    YAML.pod
Carp.pm    ExtUtils   libwww   Object        Spiffy.pm  Text

**Comment by nextgenusfs** [comment]
Sounds like multiple perl installations?  Something like cpanm configured with system Perl which is different version than the environment?  ‘which perl’ should let you know which one is in current environment.

**Comment by EricFournier3** [comment]
funannotate check  --show-versions
there is no default value for 'vers' in check_modules.py/def check_version1(name)

Checking external dependencies...
Traceback (most recent call last):
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.0.0/util/check_modules.py", line 222, in <module>
    ExtDeps[prog] = check_version1(prog)
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.0.0/util/check_modules.py", line 50, in check_version1
    return (vers)
UnboundLocalError: local variable 'vers' referenced before assignment

**Comment by nextgenusfs** [comment]
Looks like you have old version of funannotate v1.0.0? -- current is v1.3.4 and I'm on the verge of release v1.4.0 with full long-read transcript support.

**Comment by EricFournier3** [comment]
same error with 1.3.4
Checking external dependencies...
Traceback (most recent call last):
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/util/check_modules.py", line 242, in <module>
    ExtDeps[prog] = check_version1(prog)
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/util/check_modules.py", line 50, in check_version1
    return (vers)
UnboundLocalError: local variable 'vers' referenced before assignment

**Comment by nextgenusfs** [comment]
Not really sure how that's possible.... since if it errors it is suppose to return False, but I can add an extra layer so this error won't happen.  Curious, which one of these isn't installed? 
```
['tblastn', 'makeblastdb', 'rmblastn', 'java']
```

**Comment by nextgenusfs** [comment]
https://github.com/nextgenusfs/funannotate/commit/14bae1cadf0cae70313cc08d8e160392cb9a65b6 should bypass that error, I guess one of those programs must be returning an error I wasn't expecting.

**Comment by EricFournier3** [comment]
i have almost finish the installation but i have those two errors;

1- with 
funannotate setup -d /home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/DB
=>
[02:49 PM]: OS: linux2, 40 cores, ~ 528 GB RAM. Python: 2.7.15
[02:49 PM]: Running funannotate v1.3.4
[02:49 PM]: Database location: /home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/DB
Traceback (most recent call last):
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/bin/funannotate-setup.py", line 441, in <module>
    meropsDB(DatabaseInfo, args.force)
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/bin/funannotate-setup.py", line 118, in meropsDB
    type, name, version, date, records, checksum = info.get('merops')
TypeError: 'NoneType' object is not iterable

2- funannotate check --show-versions
Checking external dependencies...
Can't locate WUBlastSearchEngine.pm in @INC (@INC contains: /home/foueri01.qc.ca/ProjetsNGS/Funannotate/RepeatMaskerRepeatModeler/RepeatMasker /home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/RepeatMaskerRepeatModeler/RepeatModeler-open-1.0.11 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/RepeatMaskerRepeatModeler/RepeatModeler-open-1.0.11/RepeatUtil.pm line 78.
BEGIN failed--compilation aborted at /home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/RepeatMaskerRepeatModeler/RepeatModeler-open-1.0.11/RepeatUtil.pm line 78.
Compilation failed in require at /home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/RepeatMaskerRepeatModeler/RepeatModeler-open-1.0.11/RepeatModeler line 114.
BEGIN failed--compilation aborted at /home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/RepeatMaskerRepeatModeler/RepeatModeler-open-1.0.11/RepeatModeler line 114.
Traceback (most recent call last):
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/util/check_modules.py", line 260, in <module>
    ExtDeps[prog] = check_version6(prog)
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/util/check_modules.py", line 159, in check_version6
    vers = vers.split('-SE ')[-1].strip()
AttributeError: 'list' object has no attribute 'split'

I don't know why he search for WUBlastSearchEngine.pm. I configure RepeatModeler and RepeatMasker to use rmblastn.   And this module is in my path
readlink -f WUBlastSearchEngine.pm
=>
/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/RepeatMaskerRepeatModeler/RepeatMasker/WUBlastSearchEngine.pm

Thanks a lot again for your time Jon
Eric

**Comment by EricFournier3** [comment]
you can forget my first (1-) error in my previous comment. I found the problem.

**Comment by nextgenusfs** [comment]
The WUBlastSearchEngine.pm is part of repeatmasker - but I didn't think those perl modules needed to be installed globally?  I've not seen these errors before -- still seems like something with Perl and the includes. I have had Perl problems before -- I ended up using `perlbrew` to manage the local perl installations and had success that way (i.e. BioPerl would never build on my system perl and there were a few other strange issues with using homebrew perl -- I haven't tried perl from conda).

**Comment by EricFournier3** [comment]
but i still have this timed out instead

[03:07 PM]: Downloading UniProtKB/SwissProt database
Traceback (most recent call last):
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/bin/funannotate-setup.py", line 439, in <module>
    uniprotDB(DatabaseInfo, args.force)
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/bin/funannotate-setup.py", line 133, in uniprotDB
    download(lib.DBURL.get('uniprot'), fasta+'.gz')
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/bin/funannotate-setup.py", line 67, in download
    u = urllib2.urlopen(url)
  File "/home/foueri01@inspq.qc.ca/miniconda2/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/foueri01@inspq.qc.ca/miniconda2/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/foueri01@inspq.qc.ca/miniconda2/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/foueri01@inspq.qc.ca/miniconda2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/foueri01@inspq.qc.ca/miniconda2/lib/python2.7/urllib2.py", line 1413, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/home/foueri01@inspq.qc.ca/miniconda2/lib/python2.7/urllib2.py", line 1435, in connect_ftp
    persistent=False)
  File "/home/foueri01@inspq.qc.ca/miniconda2/lib/python2.7/urllib.py", line 877, in __init__
    self.init()
  File "/home/foueri01@inspq.qc.ca/miniconda2/lib/python2.7/urllib.py", line 886, in init
    self.ftp.connect(self.host, self.port, self.timeout)
  File "/home/foueri01@inspq.qc.ca/miniconda2/lib/python2.7/ftplib.py", line 135, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/home/foueri01@inspq.qc.ca/miniconda2/lib/python2.7/socket.py", line 575, in create_connection
    raise err
urllib2.URLError: <urlopen error ftp error: [Errno 110] Connection timed out>
 
should we use this url 
ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz

**Comment by nextgenusfs** [comment]
Do you think this is related to the timeout?
https://stackoverflow.com/questions/16775534/python-and-proxy-urllib2-urlerror-urlopen-error-errno-110-connection-timed

**Comment by EricFournier3** [comment]
i have been able to download all databases without any problem, except for uniprot. So, i just change the uniprot ftp site in the dictionary and it works fine;

DBURL = { 'uniprotBUG': 'ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz',
        'uniprot' : '**ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz**',
        'uniprot-releaseBUG': 'ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt',
        'uniprot-release' : '**ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt**',
        'merops': 'ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/merops_scan.lib',
        'dbCAN': 'http://csbl.bmb.uga.edu/dbCAN/download/dbCAN-fam-HMMs.txt',
        'dbCAN-tsv': 'http://csbl.bmb.uga.edu/dbCAN/download/FamInfo.txt',
        'dbCAN-log': 'http://csbl.bmb.uga.edu/dbCAN/download/readme.txt',
        'pfam': 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam-A.hmm.gz',
        'pfam-tsv': 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam-A.clans.tsv.gz',
        'pfam-log': 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam.version.gz',

**Comment by EricFournier3** [comment]
i found the bug for this
<Can't locate WUBlastSearchEngine.pm in @inc (@inc contains: /home/foueri01.qc.ca/ProjetsNGS/Funannotate/RepeatMaskerRepeatModeler/RepeatMasker >

there is a missing @ in the home path.  So i needed to add escape \ in RepModelConfig.pm  =>
 $REPEATMASKER_DIR = "/home/foueri01\@inspq.qc.ca/ProjetsNGS/Funannotate/RepeatMaskerRepeatModeler/RepeatMasker";

Everything is now installed and ready to run

Thank you again

**Comment by EricFournier3** [comment]
.

**Comment by EricFournier3** [comment]
.
