### ISSUE TITLE
 Too many levels of symbolic links

### ISSUE THREAD

**Issue by EricFournier3** [nextgenusfs/funannotate#187]
it happens when the program calls 
cmd = ['rmOutToGFF3.pl', file]
runSubprocess2(cmd, outdir2, log, rm_gff3)
=>
[foueri01@inspq.qc.ca@slbio00d Myco_20180701]$ funannotate predict -i Testing.fasta -o OutRes -s "Aspergillus fumigatus"
-------------------------------------------------------
[11:20 PM]: OS: linux2, 40 cores, ~ 528 GB RAM. Python: 2.7.15
[11:20 PM]: Running funannotate v1.3.4
[11:20 PM]: Augustus training set for aspergillus_fumigatus already exists. To re-train provide unique --augustus_species argument
[11:20 PM]: AUGUSTUS (3.2.3) detected, version seems to be compatible with BRAKER and BUSCO
[11:20 PM]: Loading sequences and soft-masking genome
[11:20 PM]: Soft-masking: building RepeatModeler database
[11:20 PM]: Soft-masking: generating repeat library using RepeatModeler
[11:21 PM]: Soft-masking: running RepeatMasker with default library (RepeatModeler found 0 models)
Traceback (most recent call last):
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/bin/funannotate-predict.py", line 367, in <module>
    lib.RepeatModelMask(Genome, args.cpus, os.path.join(args.out, 'predict_misc'), MaskGenome, debug)
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/lib/library.py", line 3816, in RepeatModelMask
    runSubprocess2(cmd, outdir2, log, rm_gff3)
  File "/home/foueri01@inspq.qc.ca/ProjetsNGS/Funannotate/FUNANNOTATE/funannotate-1.3.4/lib/library.py", line 603, in runSubprocess2
    proc = subprocess.Popen(cmd, cwd=dir, stdout=out, stderr=subprocess.PIPE)
  File "/home/foueri01@inspq.qc.ca/miniconda2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/foueri01@inspq.qc.ca/miniconda2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 40] Too many levels of symbolic links

**Comment by nextgenusfs** [comment]
I've seen a similar error before, but not in this context or at this step. In the tip repository (v1.4.0) I've dropped this repeatmasker script (which generates a GFF3 file from repeatmasker output) as well as moved repeat masking out of the `funannotate predict` step (as some people aren't able to install RepBase repeat library) - there is new command running this routine called `funannotate mask`. Although I don't think this is going to solve your problem - as my guess is this will happen again on another step.  Where I had seen this error before was running BRAKER on a docker instance where the BRAKER scripts were running several system calls to generate softlinks (`ln -s`) which at some point broke down for a reason I couldn't figure out.  But at this step in the code there doesn't seem to be any symlinks - at least not in the funannotate code. Is there something unique about the cluster you are on?  Full disclosure but I've written this without access to a cluster - so sometimes there are errors that I've never seen because people are running the code on systems I've not seen before.

**Comment by EricFournier3** [comment]
i will close this issue. I found in our system that a symlink war targeting himself.
