### ISSUE TITLE
Annotating CAZYmes using HMMer search of dbCAN version 6.0 not function.

### ISSUE THREAD

**Issue by iwangtoknow** [nextgenusfs/funannotate#203]
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**
HMMer search not worked, there is no file end with `.dbCAN.txt` in `annotate-misc` nor the dir `tmp`.
**What command did you issue?**
Copy/paste the command used.
```bash
linuxbrew@1afa44e6bcb5:~/data$ funannotate annotate -i fun_20180727 --strain BJCHM5 --cpus 10 --eggnog fun_20180727/annotate_misc/genome.proteins.fasta.emapper.annotations
```
**Logfiles**
Please provide relavent log files of the error. 
```bash
-------------------------------------------------------
[08:53 AM]: OS: linux2, 12 cores, ~ 37 GB RAM. Python: 2.7.15
[08:53 AM]: Running funannotate v1.4.2
[08:53 AM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[08:53 AM]: Output directory fun_20180727 already exists, will use any existing data.  If this is not what you want, exit, and provide a unique name for output folder
[08:53 AM]: Parsing input files
[08:53 AM]: Existing tbl found: fun_20180727/update_results/Aspergillus_nidulans_BJCHM5.tbl
[08:54 AM]: Adding Functional Annotation to Aspergillus nidulans, NCBI accession: None
[08:54 AM]: Annotation consists of: 11,060 gene models
[08:54 AM]: 11,499 protein records loaded
[08:54 AM]: Existing Pfam-A results found: fun_20180727/annotate_misc/annotations.pfam.txt
[08:54 AM]: 13,741 annotations added
[08:54 AM]: Running Diamond blastp search of UniProt DB version 2018_06
[08:54 AM]: 937 valid gene/product annotations from 1,681 total
[08:54 AM]: Existing Eggnog-mapper results found: fun_20180727/annotate_misc/eggnog.emapper.annotations
[08:54 AM]: Parsing EggNog Annotations
[08:54 AM]: 19,112 COG and EggNog annotations added
[08:54 AM]: Combining UniProt/EggNog gene and product names using Gene2Product version 1.16
[08:54 AM]: 2,056 gene name and product description annotations added
[08:54 AM]: Existing MEROPS results found: fun_20180727/annotate_misc/annotations.merops.txt
[08:54 AM]: 331 annotations added
[08:54 AM]: Annotating CAZYmes using HMMer search of dbCAN version 6.0
Traceback (most recent call last):
  File "/home/linuxbrew/funannotate/bin/funannotate-functional.py", line 781, in <module>
    dbCANsearch(splitProts, args.cpus, 1e-17, protDir, dbCAN_out)
  File "/home/linuxbrew/funannotate/bin/funannotate-functional.py", line 142, in dbCANsearch
    combineHmmerOutputs(resultList, dbCAN_out)
  File "/home/linuxbrew/funannotate/bin/funannotate-functional.py", line 70, in combineHmmerOutputs
    with open(inputList[0], 'rU') as infile:
IndexError: list index out of range
```
**OS/Install Information**
 -  output of `funannotate check --show-versions`
```bash
linuxbrew@1afa44e6bcb5:~/data$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for funannotate v1.4.2
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.68
goatools: 0.7.11
matplotlib: 2.2.2
natsort: 5.3.2
numpy: 1.13.1
pandas: 0.23.0
psutil: 5.4.5
requests: 2.14.2
scikit-learn: 0.19.0
scipy: 0.19.1
seaborn: 0.8.1
All 11 python packages installed


You are running Perl v 5.022000. Now checking perl modules...
Bio::Perl: 1.006924
Carp: 1.38
Clone: 0.39
DBD::SQLite: 1.58
DBD::mysql: 4.046
DBI: 1.641
DB_File: 1.835
Data::Dumper: 2.161
File::Basename: 2.85
File::Which: 1.20
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 2.97001
LWP::UserAgent: 6.33
Logger::Simple: 2.0
POSIX: 1.53
Parallel::ForkManager: 1.19
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 2.53
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.01
URI::Escape: 3.31
YAML: 1.26
threads: 2.21
threads::shared: 1.58
All 27 Perl modules installed


Checking external dependencies...
RepeatMasker: RepeatMasker 4.0.7
RepeatModeler: RepeatModeler 1.0.11
Trinity: 2.6.6
augustus: 3.3.1
bamtools: bamtools 2.5.0
bedtools: bedtools v2.27.1
blat: BLAT v36
diamond: diamond 0.9.21
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
gmap: 2017-06-20
gmes_petap.pl: 4.33
hisat2: 2.1.0
hmmscan: HMMER 3.1b2 (February 2015)
hmmsearch: HMMER 3.1b2 (February 2015)
java: 1.8.0_171
kallisto: 0.44.0
mafft: /home/linuxbrew/conda/bin/ete3_apps/bin/mafft: Cannot open --version.
------------------------------------------------------------------------------
  MAFFT v6.861b (2011/09/24)
  http://mafft.cbrc.jp/alignment/software/
  NAR 30:3059-3066 (2002), Briefings in Bioinformatics 9:286-298 (2008)
------------------------------------------------------------------------------
High speed:
  % mafft in > out
  % mafft --retree 1 in > out (fast)

High accuracy (for <~200 sequences x <~2,000 aa/nt):
  % mafft --maxiterate 1000 --localpair  in > out (% linsi in > out is also ok)
  % mafft --maxiterate 1000 --genafpair  in > out (% einsi in > out)
  % mafft --maxiterate 1000 --globalpair in > out (% ginsi in > out)

If unsure which option to use:
  % mafft --auto in > out

--op # :         Gap opening penalty, default: 1.53
--ep # :         Offset (works like gap extension penalty), default: 0.0
--maxiterate # : Maximum number of iterative refinement, default: 0
--clustalout :   Output: clustal format, default: fasta
--reorder :      Outorder: aligned, default: input order
--quiet :        Do not report progress
--thread # :     Number of threads. (# must be <= number of physical cores - 1)
makeblastdb: makeblastdb 2.7.1+
minimap2: 2.10-r761
nucmer: 3.1
pslCDnaFilter: no way to determine
rmblastn: rmblastn 2.2.27+
samtools: samtools 1.8
tRNAscan-SE: 2.0 (December 2017)
tbl2asn: unknown, likely 25.3
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
	ERROR: emapper.py not installed
Checking Environmental Variables...
$FUNANNOTATE_DB=/home/linuxbrew/DB
$PASAHOME=/home/linuxbrew/PASApipeline
$TRINITYHOME=/home/linuxbrew/Trinity
$EVM_HOME=/home/linuxbrew/evidencemodeler
$AUGUSTUS_CONFIG_PATH=/home/linuxbrew/augustus/config
$GENEMARK_PATH=/home/linuxbrew/gm_et_linux_64/gmes_petap
$BAMTOOLS_PATH=/usr/local/bin
All 7 environmental variables are set
```

**WANG**

**Comment by nextgenusfs** [comment]
Looks like perhaps the database isn’t installed?  What is output of funannotate database.

**Comment by iwangtoknow** [comment]
Nop, it has been installed.
```bash
Funannotate Databases currently installed:

  Database          Type        Version      Date         Num_Records   Md5checksum                     
  pfam              hmmer3      31.0         2017-02            16712   3e47eec766a99b599cb24f28c4d393f8
  gene2product      text        1.16         2018-07-11         25699   59440c22a0e296dce6879f3ef0acaf36
  interpro          xml         69.0         2018-06-21         34358   55f4f8d7c3d25eab20055a0fa0d2c3c3
  dbCAN             hmmer3      6.0          2017-09-12           421   27b211ceea0d813cf99e6f721ab54c1c
  busco_outgroups   outgroups   1.0          2018-07-17             8   6795b1d4545850a4226829c7ae8ef058
  merops            diamond     12.0         2017-10-04          4968   d923f0177c6d27c3d2886c705347adc0
  mibig             diamond     1.3          2018-07-17         24085   84b3cd16e0b3b074e4b7ee18c6aa31fd
  uniprot           diamond     2018_06      2018-06-20        557713   99662b979378958e02f53b0153f42972
  go                text        2018-07-15   2018-07-15         47235   a07e84790606702cbf2fcfdab44f3cde
  repeats           diamond     1.0          2018-07-17         11950   4e8cafc3eea47ec7ba505bb1e3465d21
```

**Comment by iwangtoknow** [comment]
Thanks Jon,
OK, I'll check my data.
There could be multiple transcripts of one gene due to alternative splicing.
```bash
linuxbrew@1afa44e6bcb5:~/data$ ls fun_20180727/
BJCHM5.masked.fa   annotate_misc     logfiles  predict_misc     training     update_results
BJCHM5.masked.fa~  annotate_results  mask_268  predict_results  update_misc
```
**WANG**

**Comment by iwangtoknow** [comment]
Hi Jon,
I have not met this error recently.
close it.
Thanks.
