### ISSUE TITLE
funannotate check produces TypeError

### ISSUE THREAD

**Issue by jorels** [nextgenusfs/funannotate#205]
Hi,

I am sorry I am coming to you but I seem to have exhausted all my options.

I have installed funannotate in an LSF but I can't seem to get it to work. When I run funannotate check I get the following:

-------------------------------------------------------
Checking dependencies for funannotate v1.4.2-b1d62e5
-------------------------------------------------------
To print all dependencies and versions: funannotate check --show-versions

You are running Python v 2.7.5. Now checking python packages...
All 11 python packages installed

You are running Perl v 5.016003. Now checking perl modules...
All 27 Perl modules installed

Checking external dependencies...
[main] unrecognized command '--version'
Traceback (most recent call last):
  File "/homes/joachim/Tools/funannotate/funannotate/util/check_modules.py", line 250, in <module>
    ExtDeps[prog] = check_version2(prog)
  File "/homes/joachim/Tools/funannotate/funannotate/util/check_modules.py", line 93, in check_version2
    if 'exonerate' in vers:
TypeError: argument of type 'bool' is not iterable.

What do you think I can do about getting it to work?

A little hint: I have also been struggling with the standalone version of gmes_petap.pl. The program keeps giving the following error:

warning on: /homes/joachim/Downloads/GeneMark/gm_et_linux_64/gmes_petap/gmhmme3  -m /nfs/nobackup/ensemblgenomes/joachim/annotation_cgppipeline/run/ES_ini/es_ini.mod   -f tr   -o /nfs/nobackup/ensemblgenomes/joachim/annotation_cgppipeline/run/ES_A_1/hmmout/dna.fa_12340.out  /nfs/nobackup/ensemblgenomes/joachim/annotation_cgppipeline/data/training/dna.fa_12340
error, file not found /homes/joachim/Downloads/GeneMark/gm_et_linux_64/gmes_petap/parse_set.pl: set.out
error on call: /homes/joachim/Downloads/GeneMark/gm_et_linux_64/gmes_petap/parse_set.pl --section ES_A --cfg  /nfs/nobackup/ensemblgenomes/joachim/annotation_cgppipeline/run.cfg  --v 

I look forward to your response.

Many thanks,

Joachim

**Comment by nextgenusfs** [comment]
Is `exonerate` installed?, i.e. what is result of `exonerate --version`?  Maybe old version of `exonerate` that doesn't have the `--version` flag?

But maybe something else entirely as seems like that part of the script dies right away when looking at the external dependencies.  Basically its using the `subprocess` python module to launch those external dependencies and try to look for version numbers -- it is of course a pain because these programs have different syntax, i.e. `--version` doesn't work on everything and thus there are several different methods employed from `subprocess` result parsing to get the desired results. Your version of Python is also quite old (released in 2013) -- wondering if the script is using something not present in your Python release.

**Comment by jorels** [comment]
Hi Jon,


Thank you very much for getting back to me.


I do have exonerate and when I run exonerate --version, I get the following output:

"exonerate from exonerate version 2.4.0

Using glib version 2.46.2

Built on Jul 26 2018"


I have also changed my default python so that when I type python --version, I now get:

Python 3.5.2

However when I run the funannotate check again, I still get the same error.

What else do you think I should try?

Many thanks,

Joachim
________________________________

**Comment by jorels** [comment]
Hi Jon,


I ran the run_unit_tests.sh file on the sample folder. The program ran for a short while and was killed. When I checked the log file, I got the following:


2018-08-01 19:20:07,149: /homes/joachim/Tools/funannotate/funannotate-1.0.0/bin/funannotate-functional.py --gff genome1/predict_results/genome_one.gff3 --fasta genome1/predict_results/genome_one.scaffolds.fa --proteins genome1/predict_results/genome_one.proteins.fa --iprscan test_data.iprscan.xml --eggnog genome1.emapper.annotations -o direct -s Aspergillus fumigatus

2018-08-01 19:20:07,193: OS: linux2, 80 cores, ~ 262 GB RAM. Python: 2.7.5
2018-08-01 19:20:07,362: Running funannotate v1.0.0
2018-08-01 19:20:07,378: Augustus species folder not found at /homes/joachim/perl5/bin:/usr/lib64/qt-3.3/bin:/ebi/lsf/ebi/9.1/linux2.6-glibc2.3-x86_64/etc:/ebi/lsf/ebi/9.1/linux2.6-glibc2.3-x86_64/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/lpp/mmfs/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/homes/joachim/Database/ncbi_blast_2.6.0/ncbi-blast-2.6.0+/bin:/homes/joachim/Tools/SPAdes-3.11.1-Linux/bin:/homes/joachim/bin:/homes/joachim/.local/bin:/homes/joachim/Tools/bbmap:/homes/joachim/Tools/Trimmomatic-0.36/trimmomatic-0.36.jar:/homes/joachim/Downloads/Quake/bin:/home/.local/bin:/homes/joachim/pear/bin/pear:/homes/joachim/Downloads/redundans:/homes/joachim/Downloads/redundans/bin:/homes/joachim/Downloads/FastUniq/source:/homes/joachim/Tools/GapCloser:/nfs/production/panda/ensemblgenomes/development/iarmean/sw/discovardenovo-52488/src:/homes/joachim/Downloads/bwa-0.5.0:/homes/joachim/Downloads/bamtools-2.4.1/bin:/homes/joachim/Downloads/Reapr_1.0.18:/nfs/panda/ensemblgenomes/external/hmmer-3/binaries:/homes/joachim/Downloads/augustus/bin:/homes/joachim/Downloads/augustus/scripts:/homes/joachim/Downloads/augustus/config/species, exiting

It seem it is not able to find the augustus species folder. The folder do exist and I have set the following environments as follows:

export FUNANNOTATE_DB=/nfs/nobackup/ensemblgenomes/joachim/annotation_funannotate/funannotate_database
export PASAHOME=/homes/joachim/Tools/funannotate/PASApipeline-v2.3.3
export TRINITYHOME=/nfs/panda/ensemblgenomes/external/trinity
export EVM_HOME=/homes/joachim/Tools/funannotate/EVidenceModeler-1.1.1
export AUGUSTUS_CONFIG_PATH=/homes/joachim/augustus/config
export GENEMARK_PATH=/homes/joachim/Downloads/GeneMark/gm_et_linux_64/gmes_petap
export BAMTOOLS_PATH=/homes/joachim//Downloads/bamtools-2.4.1/bin?

What do you think I am doing wrong?

Many thanks,

Joachim



________________________________

**Comment by nextgenusfs** [comment]
Yes, sorry about that - that bash script is what I run locally and there aren't some of those files on there so the repo doesn't become large in size.  If the first 3 examples worked out, then you should be okay for prediction step at least.  You can open that bash script and pull out the commands for `funannotate annotate` and see if that is working as well (will need to modify as per the IPRscan results).

**Comment by nextgenusfs** [comment]
But there is potentially something else wrong, i.e. the version of funannotate says v1.0.0.  So is there another install on your cluster?  Seems like something isn't quite right?

**Comment by jorels** [comment]
Hi Jon,


You are right. I have had to uninstall the former version and installed v1.0.0.


When I ran a section of funannotate predict I got the following error:


funannotate predict -i genome3.fasta -s "Genome three" --name GN3_ -o genome3 --protein_evidence proteins.fa --transcript_evidence transcripts.fa --augustus_species botrytis_cinerea --cpus 6

-------------------------------------------------------
[08:59:23 PM]: OS: linux2, 32 cores, ~ 132 GB RAM. Python: 2.7.5
[08:59:24 PM]: Running funannotate v1.0.0
[08:59:25 PM]: Augustus training set for botrytis_cinerea already exists, using existing parameters.
If you want to re-train, provide a unique name for the --augustus_species argument
[08:59:28 PM]: AUGUSTUS (3.3) detected, version seems to be compatible with BRAKER1 and BUSCO
[08:59:28 PM]: Loading sequences and soft-masking genome
[08:59:28 PM]: Soft-masking: building RepeatModeler database
[08:59:28 PM]: Soft-masking: generating repeat library using RepeatModeler
[09:00:07 PM]: Soft-masking: running RepeatMasker with default library (RepeatModeler found 0 models)

Traceback (most recent call last):
  File "/homes/joachim/Tools/funannotate/funannotate-1.0.0/bin/funannotate-predict.py", line 363, in <module>
    lib.RepeatModelMask(Genome, args.cpus, os.path.join(args.out, 'predict_misc'), MaskGenome, debug)
  File "/homes/joachim/Tools/funannotate/funannotate-1.0.0/lib/library.py", line 1797, in RepeatModelMask
    runSubprocess2(cmd, outdir2, log, rm_gff3)
  File "/homes/joachim/Tools/funannotate/funannotate-1.0.0/lib/library.py", line 391, in runSubprocess2
    proc = subprocess.Popen(cmd, cwd=dir, stdout=out, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 40] Too many levels of symbolic links?"

I don't know what the OSError means or how to deal with it.

Many thanks,

Joachim


________________________________

**Comment by jorels** [comment]
Hi


I had to install the latest funannotate after realising some of the errors I noticed have been dealt with by newer releases.


I now ran funannotate predict on one of the sample data and it came up with an Attribute error. The log is as follows:


funannotate predict -i genome1.fasta --force -s "Genome one" --name GN1_ -o genome1 --protein_evidence proteins.fa --transcript_evidence transcripts.fa --augustus_species botrytis_cinerea --cpus 16
-------------------------------------------------------
[08:31 AM]: OS: linux2, 32 cores, ~ 132 GB RAM. Python: 2.7.5
[08:31 AM]: Running funannotate v1.4.2
[08:31 AM]: Augustus training set for botrytis_cinerea already exists. To re-train provide unique --augustus_species argument
[08:31 AM]: AUGUSTUS (3.3) detected, version seems to be compatible with BRAKER and BUSCO
[08:31 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[08:31 AM]: Genome loaded: 3 scaffolds; 451,050 bp; 0.00% repeats masked
[08:31 AM]: Aligning transcript evidence to genome with minimap2
Traceback (most recent call last):
  File "/homes/joachim/Tools/funannotate/funannotate-1.4.2/bin/funannotate-predict.py", line 510, in <module>
    minimapCount = lib.bam2ExonsHints(minimapBAM, minimapGFF3, hintsM)
  File "/homes/joachim/Tools/funannotate/funannotate-1.4.2/lib/library.py", line 1409, in bam2ExonsHints
    for num,aln in enumerate(pybam.read(os.path.realpath(input))):
  File "/homes/joachim/Tools/funannotate/funannotate-1.4.2/lib/pybam.py", line 328, in __init__
    while len(header_cache) < 8: header_cache += next(self._generator)
  File "/homes/joachim/Tools/funannotate/funannotate-1.4.2/lib/pybam.py", line 173, in generator
    except: raise PybamError('\n\nCould not open "' + str(self._file.name) + '" for reading!\n')
AttributeError: read instance has no attribute '_file'
Exception AttributeError: "read instance has no attribute '_subprocess'" in <bound method read.__del__ of <lib.pybam.read instance at 0x2b039e0>> ignored?

Many thanks


________________________________

**Comment by nextgenusfs** [comment]
It looks like it can't find `transcripts.fa`.  Not sure if this is related to the realpath call or not?  Can you try adding the pull path to these files, i.e. $PWD/transcripts.fa should work. I think I've maybe seen some errors like this before on some clusters -- having to do with how the filesystem is mounted and levels of symlinks, but generally I'm clueless about these types of setups.

**Comment by jorels** [comment]
I did as you asked but still got the error:


funannotate predict -i genome1.fasta --force -s "Genome one" --name GN1_ -o genome1 --protein_evidence $PWD/proteins.fa --transcript_evidence $PWD/transcripts.fa --augustus_species botrytis_cinerea --cpus 16
-------------------------------------------------------
[05:14 PM]: OS: linux2, 32 cores, ~ 132 GB RAM. Python: 2.7.5
[05:14 PM]: Running funannotate v1.4.2
[05:14 PM]: Augustus training set for botrytis_cinerea already exists. To re-train provide unique --augustus_species argument
[05:14 PM]: AUGUSTUS (3.3) detected, version seems to be compatible with BRAKER and BUSCO
[05:14 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[05:14 PM]: Genome loaded: 3 scaffolds; 451,050 bp; 0.00% repeats masked
[05:14 PM]: Aligning transcript evidence to genome with minimap2
Traceback (most recent call last):
  File "/homes/joachim/Tools/funannotate/funannotate-1.4.2/bin/funannotate-predict.py", line 510, in <module>
    minimapCount = lib.bam2ExonsHints(minimapBAM, minimapGFF3, hintsM)
  File "/homes/joachim/Tools/funannotate/funannotate-1.4.2/lib/library.py", line 1409, in bam2ExonsHints
    for num,aln in enumerate(pybam.read(os.path.realpath(input))):
  File "/homes/joachim/Tools/funannotate/funannotate-1.4.2/lib/pybam.py", line 328, in __init__
    while len(header_cache) < 8: header_cache += next(self._generator)
  File "/homes/joachim/Tools/funannotate/funannotate-1.4.2/lib/pybam.py", line 173, in generator
    except: raise PybamError('\n\nCould not open "' + str(self._file.name) + '" for reading!\n')
AttributeError: read instance has no attribute '_file'
Exception AttributeError: "read instance has no attribute '_subprocess'" in <bound method read.__del__ of <lib.pybam.read instance at 0x2dd99e0>> ignored?


________________________________

**Comment by nextgenusfs** [comment]
I'm unable to replicate this behavior locally.  I setup a python 2.7.5 virtual environment with conda and ran the following:
```
$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for funannotate v1.4.2-9eeef3d
-------------------------------------------------------
You are running Python v 2.7.5. Now checking python packages...
biopython: 1.68
goatools: 0.8.4
matplotlib: 2.2.2
natsort: 5.3.3
numpy: 1.13.1
pandas: 0.23.3
psutil: 5.4.6
requests: 2.19.1
scikit-learn: 0.19.0
scipy: 0.19.1
seaborn: 0.9.0
All 11 python packages installed


You are running Perl v 5.026001. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.42
Clone: 0.39
DBD::SQLite: 1.56
DBD::mysql: 4.046
DBI: 1.641
DB_File: 1.84
Data::Dumper: 2.167
File::Basename: 2.85
File::Which: 1.22
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 2.97001
LWP::UserAgent: 6.33
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 1.19
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 2.62
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.24
threads: 2.21
threads::shared: 1.58
All 27 Perl modules installed


Checking external dependencies...
RepeatMasker: RepeatMasker 4.0.7
RepeatModeler: RepeatModeler 1.0.11
Trinity: 2.5.1
augustus: 3.2.1
bamtools: bamtools 2.4.1
bedtools: bedtools v2.27.1
blat: BLAT v35
diamond: diamond 0.9.19
emapper.py: emapper-1.0.3
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
gmap: 2017-06-20
gmes_petap.pl: 4.30
hisat2: 2.0.5
hmmscan: HMMER 3.1b2 (February 2015)
hmmsearch: HMMER 3.1b2 (February 2015)
java: 1.8.0_92
kallisto: 0.43.1
mafft: v7.313 (2017/Nov/15)
makeblastdb: makeblastdb 2.7.1+
minimap2: 2.11-r797
nucmer: 3.1
pslCDnaFilter: no way to determine
rmblastn: rmblastn 2.2.27+
samtools: samtools 1.8
tRNAscan-SE: 1.23 (April 2002)
tbl2asn: unknown, likely 25.3
tblastn: tblastn 2.7.1+
trimal: trimAl v1.4.rev15 build[2013-12-17]
All 30 external dependencies are installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/usr/local/share/funannotate
$PASAHOME=/Users/jon/software/PASApipeline
$TRINITYHOME=/usr/local/opt/trinity
$EVM_HOME=/Users/jon/software/evidencemodeler
$AUGUSTUS_CONFIG_PATH=/Users/jon/software/augustus/config
$GENEMARK_PATH=/Users/jon/software/gmes_petap
$BAMTOOLS_PATH=/Users/jon/software/bamtools-2.4.0/bin
All 7 environmental variables are set
-------------------------------------------------------
```
```
$ funannotate predict -i genome1.fasta --force -s "Genome one" --name GN1_ -o genome1 --protein_evidence proteins.fa --transcript_evidence transcripts.fa --augustus_species botrytis_cinerea --cpus 6
-------------------------------------------------------
[Aug 03 08:59 AM]: OS: MacOSX 10.13.6, 8 cores, ~ 17 GB RAM. Python: 2.7.5
[Aug 03 08:59 AM]: Running funannotate v1.4.2-9eeef3d
[Aug 03 08:59 AM]: Augustus training set for botrytis_cinerea already exists. To re-train provide unique --augustus_species argument
[Aug 03 08:59 AM]: AUGUSTUS (3.2.1) detected, version seems to be compatible with BRAKER and BUSCO
[Aug 03 08:59 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Aug 03 08:59 AM]: Genome loaded: 3 scaffolds; 451,050 bp; 0.00% repeats masked
[Aug 03 08:59 AM]: Aligning transcript evidence to genome with minimap2
[Aug 03 08:59 AM]: Found 198 alignments, wrote GFF3 and Augustus hints to file
[Aug 03 08:59 AM]: Mapping proteins to genome using Diamond blastx/Exonerate
[Aug 03 08:59 AM]: Using 9,043 proteins as queries
[Aug 03 08:59 AM]: Running Diamond pre-filter search
[Aug 03 08:59 AM]: Found 520 preliminary alignments
[Aug 03 08:59 AM]: Exonerate finished: found 98 alignments
[Aug 03 08:59 AM]: Running GeneMark-ES on assembly
[Aug 03 09:00 AM]: Converting GeneMark GTF file to GFF3
[Aug 03 09:00 AM]: Found 113 gene models
[Aug 03 09:00 AM]: Running Augustus gene prediction
[Aug 03 09:01 AM]: Found 178 gene models
[Aug 03 09:01 AM]: Pulling out high quality Augustus predictions
[Aug 03 09:01 AM]: Found 84 high quality predictions from Augustus (>90% exon evidence)
[Aug 03 09:01 AM]: Summary of gene models passed to EVM (weights):
-------------------------------------------------------
Augustus models (1):	99
Genemark models (1):	113
HiQ models (5):		88
Pasa models (1):	0
Total models:		300
-------------------------------------------------------
[Aug 03 09:01 AM]: Setting up EVM partitions
[Aug 03 09:01 AM]: Generating EVM command list
[Aug 03 09:01 AM]: Running EVM commands with 5 CPUs
[Aug 03 09:01 AM]: Combining partitioned EVM outputs
[Aug 03 09:01 AM]: Converting EVM output to GFF3
[Aug 03 09:01 AM]: Collecting all EVM results
[Aug 03 09:01 AM]: 176 total gene models from EVM
[Aug 03 09:01 AM]: Generating protein fasta files from 176 EVM models
[Aug 03 09:01 AM]: now filtering out bad gene models (< 50 aa in length, transposable elements, etc).
[Aug 03 09:02 AM]: Found 52 gene models to remove: 0 too short; 0 span gaps; 52 transposable elements
[Aug 03 09:02 AM]: 124 gene models remaining
[Aug 03 09:02 AM]: Predicting tRNAs
[Aug 03 09:02 AM]: Found 1 tRNA gene models
[Aug 03 09:02 AM]: 1 tRNAscan models are valid (non-overlapping)
[Aug 03 09:02 AM]: Generating GenBank tbl annotation file
[Aug 03 09:02 AM]: Converting to final Genbank format
[Aug 03 09:02 AM]: Collecting final annotation files for 125 total gene models
[Aug 03 09:02 AM]: Funannotate predict is finished, output files are in the genome1/predict_results folder
[Aug 03 09:02 AM]: Your next step might be functional annotation, suggested commands:
-------------------------------------------------------
Run InterProScan (Docker required): 
funannotate iprscan -i genome1 -m docker -c 6

Run antiSMASH: 
funannotate remote -i genome1 -m antismash -e youremail@server.edu

Annotate Genome: 
funannotate annotate -i genome1 --cpus 6 --sbt yourSBTfile.txt
-------------------------------------------------------
```
Everything runs as it should. So it doesn't appear to be the Python version or the code.  I don't know what to try next.
