### ISSUE TITLE
Call to ExoConverter failed

### ISSUE THREAD

**Issue by AntoineHo** [nextgenusfs/funannotate#209]
Hello, after running the following command:
`funannotate predict -i genome.cleaned.sorted.masked.fa -o predict/ --species "MyGenera" --transcript_evidence allmRNA.evidence.fa --protein_evidence proteins.fa --cpus 10 --busco_db metazoa`
I get the following output:
```
-------------------------------------------------------
[12:40 PM]: OS: linux2, 12 cores, ~ 33 GB RAM. Python: 2.7.15
[12:40 PM]: Running funannotate v1.4.2
[12:40 PM]: GeneMark is not installed, proceeding with only Augustus ab-initio predictions
[12:40 PM]: AUGUSTUS (3.3.1) detected, version seems to be compatible with BRAKER and BUSCO
[12:40 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[12:40 PM]: Genome loaded: 753 scaffolds; 147,758,537 bp; 3.00% repeats masked
[12:40 PM]: Aligning transcript evidence to genome with minimap2
[12:41 PM]: Found 66,850 alignments, wrote GFF3 and Augustus hints to file
[12:41 PM]: Mapping proteins to genome using Diamond blastx/Exonerate
[12:41 PM]: Using 1,675 proteins as queries
[12:41 PM]: Running Diamond pre-filter search
[12:42 PM]: Found 14,857 preliminary alignments
Traceback (most recent call last):
  File "/home/antoine/tools/funannotate-1.4.2/bin/funannotate-p2g.py", line 252, in <module>
    subprocess.call([ExoConverter, exonerate_raw], stdout = output, stderr = FNULL)
  File "/home/antoine/anaconda3/envs/fun-py27/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/antoine/anaconda3/envs/fun-py27/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/antoine/anaconda3/envs/fun-py27/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[12:44 PM]: Running BUSCO to find conserved gene models for training Augustus
^C
```

It seems that ExoConverter is missing but I do not know what it is and that Genemark is not installed although I double checked and I have gmes-petap.pl in $PATH. When I do `gmes_petap.pl` I have the following:

```
GeneMark-ES Suite version 4.35
   includes transcript (GeneMark-ET) and protein (GeneMark-EP) based training and prediction
```

Any ideas ?

**Comment by hyphaltip** [comment]
Can you check that EVM installed and is right version?
`ExoConverter = os.path.join(EVM, 'EvmUtils', 'misc', 'exonerate_gff_to_alignment_gff3..pl’)`

**Comment by AntoineHo** [comment]
I checked the `ExoConverter` path and there was a typo. Thank you for pointing EVM variable.
