### ISSUE TITLE
Check external depndencies fails

### ISSUE THREAD

**Issue by bbalog87** [nextgenusfs/funannotate#225]
**I have installed all dependencies according the the manual. However, funannotate check fails with the following error**

```
Checking external dependencies...
Traceback (most recent call last):
  File "/home/jnguinka/funannotate-1.0.0/util/check_modules.py", line 227, in <module>
    ExtDeps[prog] = check_version1(prog)
  File "/home/jnguinka/funannotate-1.0.0/util/check_modules.py", line 50, in check_version1
    vers = subprocess.Popen([name, '-version'], stdout=subprocess.PIPE).communicate()[0].split('\n')[0]
TypeError: a bytes-like object is required, not 'str'  ```


My OS: linux(ubuntu).

Best,

**Comment by nextgenusfs** [comment]
Use most recent version and it is python 2 only.

**Comment by bbalog87** [comment]
Thanky for replying.
Actually, I have tried the most recent python 2 release : Python 2.7.15rc1.
Unfortunately I get another error;

```
Checking dependencies for funannotate v1.0.0
-------------------------------------------------------
To print all dependencies and versions: funannotate check --show-versions

You are running Python v 2.7.15rc1. Now checking python packages...
All 11 python packages installed


You are running Perl v 5.026001. Now checking perl modules...
All 24 Perl modules installed


Checking external dependencies...
Traceback (most recent call last):
  File "/home/jnguinka/funannotate-1.0.0/util/check_modules.py", line 230, in <module>
    ExtDeps[prog] = check_version2(prog)
  File "/home/jnguinka/funannotate-1.0.0/util/check_modules.py", line 93, in check_version2
    return (vers)
UnboundLocalError: local variable 'vers' referenced before assignment
```

**Comment by nextgenusfs** [comment]
I meant the most recent version of funannotate which is v1.5.0.
