### ISSUE TITLE
funannotate-update failed with message: 'module' object has no attribute 'runNormalization'.

### ISSUE THREAD

**Issue by yingzhang121** [nextgenusfs/funannotate#230]
**Are you using the latest release?**
Not sure about the version of latest release, but I am using version 1.5.0

**Describe the bug**
Basically speaking, I have a successful fuannotate run, and already got the initial prediction.
However at the end of the log file of my successful run, it said:

[03:37 PM]: Funannotate predict is finished, output files are in the zm/predict_results folder
[03:37 PM]: Your next step to capture UTRs and update annotation using PASA:

funannotate update -i zm --cpus 24 \
        --left illumina_forward_RNAseq_R1.fastq.gz \
        --right illumina_forward_RNAseq_R2.fastq.gz \
        --jaccard_clip

So I used the same RNA-Seq data for my trinity run to run the funannotate update function.

funannotate update -i zm --cpus 24 \
        --left ZM_Comb_R1.fastq.gz \
        --right ZM_Comb_R2.fastq.gz \
        --jaccard_clip

This job failed after running for nearly 2 hours, and the log file is below:
[11:24 AM]: OS: linux2, 24 cores, ~ 66 GB RAM. Python: 2.7.15
[11:24 AM]: Running funannotate v1.5.0
[11:24 AM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
[12:02 PM]: Reannotating Dreissena polymorpha, NCBI accession: None
[12:02 PM]: Previous annotation consists of: 339,932 protein coding gene models and 8,711 non-coding gene models
[12:02 PM]: Adapter and Quality trimming PE reads with Trimmomatic
Traceback (most recent call last):
  File "/panfs/roc/msisoft/funannotate/1.5.0/bin/funannotate-update.py", line 1784, in <module>
    left_norm, right_norm, single_norm = lib.runNormalization(trim_reads, args.memory)
AttributeError: 'module' object has no attribute 'runNormalization'

**What command did you issue?**
Again, the command is:

funannotate update -i zm --cpus 24 \
        --left ZM_Comb_R1.fastq.gz \
        --right ZM_Comb_R2.fastq.gz \
        --jaccard_clip

**Logfiles**
Again, the log file is

11:24 AM]: OS: linux2, 24 cores, ~ 66 GB RAM. Python: 2.7.15
[11:24 AM]: Running funannotate v1.5.0
[11:24 AM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
[12:02 PM]: Reannotating Dreissena polymorpha, NCBI accession: None
[12:02 PM]: Previous annotation consists of: 339,932 protein coding gene models and 8,711 non-coding gene models
[12:02 PM]: Adapter and Quality trimming PE reads with Trimmomatic
Traceback (most recent call last):
  File "/panfs/roc/msisoft/funannotate/1.5.0/bin/funannotate-update.py", line 1784, in <module>
    left_norm, right_norm, single_norm = lib.runNormalization(trim_reads, args.memory)
AttributeError: 'module' object has no attribute 'runNormalization'

**OS/Install Information**
-------------------------------------------------------
Checking dependencies for funannotate v1.5.0
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.70
goatools: 0.7.11
matplotlib: 2.1.1
natsort: 5.2.0
numpy: 1.12.1
pandas: 0.22.0
psutil: 5.4.3
requests: 2.18.4
scikit-learn: 0.19.0
scipy: 0.19.1
seaborn: 0.8.1
All 11 python packages installed

You are running Perl v 5.026001. Now checking perl modules...
Bio::Perl: 1.007001
Carp: 1.38
Clone: 0.39
DBD::SQLite: 1.58
DBD::mysql: 4.046
DBI: 1.634
DB_File: 1.842
Data::Dumper: 2.167
File::Basename: 2.85
File::Which: 1.21
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 2.97001
LWP::UserAgent: 6.15
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 1.19
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.11
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.26
threads: 2.21
threads::shared: 1.58
All 27 Perl modules installed

Checking external dependencies...
Traceback (most recent call last):
  File "/panfs/roc/msisoft/funannotate/1.5.0/util/check_modules.py", line 260, in <module>
    ExtDeps[prog] = check_version2(prog)
  File "/panfs/roc/msisoft/funannotate/1.5.0/util/check_modules.py", line 66, in check_version2
    vers = vers.split(' called')[0].replace('version', '')
AttributeError: 'list' object has no attribute 'split'

**Comment by nextgenusfs** [comment]
Thanks. This is fixed here: https://github.com/nextgenusfs/funannotate/commit/ee6a46acd6830eb76339f7b22c99999726241154. Will be fixed in next release. You could try to the dev version by cloning repository or make the same small change in the script. You should be able to issue same command. And did you use funannotate train prior to predict?  If so, then scripts will reuse any available data.
