### ISSUE TITLE
dbCAN url open failed

### ISSUE THREAD

**Issue by iwangtoknow** [nextgenusfs/funannotate#231]
Hi Jon,
I try to setup DB to build docker image, but
``` bash

[02:31 AM]: Downloading dbCAN database
Traceback (most recent call last):
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 443, in <module>
    dbCANDB(DatabaseInfo, args.force)
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 162, in dbCANDB
    download(lib.DBURL.get('dbCAN'), os.path.join(FUNDB,'dbCAN.tmp'))
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 67, in download
    u = urllib2.urlopen(url)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
Removing intermediate container 18e4e64fdb7d
 ---> 86a1ef84fcad
Step 8/9 : WORKDIR /home/linuxbrew/data
 ---> Running in 353c6fa54742
Removing intermediate container 353c6fa54742
 ---> 29fc1f3b05b3
Step 9/9 : ENTRYPOINT /bin/bash
 ---> Running in 25c84de9012f
Removing intermediate container 25c84de9012f
 ---> f0063c891aef
Successfully built f0063c891aef
Successfully tagged funannotate:latest
```
Is the url for dbCAN outdated?
I try twice, results same.

**WANG**

**Comment by nextgenusfs** [comment]
Yes, same error as #224.  Working on updating the links now.

**Comment by nextgenusfs** [comment]
just updated the docker image -- should be live in a few minutes.  let me know if that fixes the issue.

**Comment by iwangtoknow** [comment]
Thanks, Jon
Sorry for a long time not here, busy in wet experiments, I'll be back soon.

**WANG**
