### ISSUE TITLE
funannotate utils gbk2parts

### ISSUE THREAD

**Issue by mswyers** [nextgenusfs/funannotate#233]
**Are you using the latest release?**
```
$ brew upgrade funannotate
Error: nextgenusfs/tap/funannotate 1.5.1 already installed

```

**Describe the bug**
Attempting to use funannotate utils gbk2parts on a gbk file generated by a prokaryotic antiSMASH query.

**What command did you issue?**
`$ funannotate util gbk2parts -g ctg1.final.gbk -o s1-2c`

**Logfiles**
```
$ funannotate util gbk2parts -g ctg1.final.gbk -o s1-2c
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/funannotate/1.5.1/libexec/util/gbk2parts.py", line 28, in <module>
    lib.gb2parts(args.gbk, tblout, gffout, protout, transout, dnaout)
  File "/home/linuxbrew/.linuxbrew/Cellar/funannotate/1.5.1/libexec/lib/library.py", line 2301, in gb2parts
    gb_feature_add2dict(f, record, genes)
  File "/home/linuxbrew/.linuxbrew/Cellar/funannotate/1.5.1/libexec/lib/library.py", line 2518, in gb_feature_add2dict
    log.info("putative transcript from %s has no ID\n(%s %s %s)" % (locusTag, locusTag, ID, Parent))
NameError: global name 'log' is not defined

```

```
**OS/Install Information**
 -  output of `funannotate check --show-versions`
$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for funannotate v1.5.0
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.72
goatools: 0.8.4
matplotlib: 2.0.2
natsort: 5.3.3
numpy: 1.15.0
pandas: 0.23.3
psutil: 5.4.6
requests: 2.19.1
scikit-learn: 0.19.2
scipy: 1.1.0
seaborn: 0.9.0
All 11 python packages installed


You are running Perl v 5.028000. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.50
Clone: 0.39
DBD::SQLite: 1.58
DBD::mysql: 4.046
DBI: 1.641
DB_File: 1.84
Data::Dumper: 2.170
File::Basename: 2.85
File::Which: 1.22
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 2.97001
LWP::UserAgent: 6.35
Logger::Simple: 2.0
POSIX: 1.84
Parallel::ForkManager: 1.20
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.08
Text::Soundex: 3.05
Thread::Queue: 3.13
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.26
threads: 2.22
threads::shared: 1.58
All 27 Perl modules installed


Checking external dependencies...
RepeatMasker: RepeatMasker 4.0.7
RepeatModeler: RepeatModeler 1.0.8
Trinity: 2.8.3
augustus: 3.3.1
bamtools: bamtools 2.5.1
bedtools: bedtools v2.27.1
blat: BLAT v36
diamond: diamond 0.9.22
emapper.py: emapper-1.0.3
ete3: 3.1.1
exonerate: exonerate 2.2.0
gmap: 2018-07-04
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 9.0.4
kallisto: 0.44.0
mafft: v7.407 (2018/Jul/23)
makeblastdb: makeblastdb 2.7.1+
minimap2: 2.13-r850
nucmer: 3.1
pslCDnaFilter: no way to determine
rmblastn: rmblastn 2.2.27+
samtools: samtools 1.9
stringtie: 1.3.4d
tRNAscan-SE: 1.3.1 (January 2012)
tbl2asn: unknown, likely 25.3
tblastn: tblastn 2.7.1+
trimal: trimAl v1.4.rev15 build[2013-12-17]
	ERROR: CodingQuarry not installed
	ERROR: fasta not installed
	ERROR: gmes_petap.pl not installed
Checking Environmental Variables...
$FUNANNOTATE_DB=/home/seq/fundb
$PASAHOME=/home/seq/PASApipeline-v2.3.3
$TRINITYHOME=/home/linuxbrew/.linuxbrew/opt/trinity
$EVM_HOME=/home/linuxbrew/.linuxbrew/opt/evidencemodeler
$AUGUSTUS_CONFIG_PATH=/home/linuxbrew/.linuxbrew/opt/augustus/config
$GENEMARK_PATH=/home/seq/gmes_petap
$BAMTOOLS_PATH=/home/linuxbrew/.linuxbrew/opt/bamtools
All 7 environmental variables are set
```

**Comment by mswyers** [comment]
To go along with the trimal errors: according to linuxbrew I have fasta installed and up-to-date, gmes_petap.pl is in my $PATH. Not sure about CodingQuarry, however. Not sure how related these are to this error.

**Comment by nextgenusfs** [comment]
Those install errors aren’t related to the error, the python error should be a quick fix — however I think this is erroring because of the genbank file format. Can you share that genbank file?  Email is fine.
