### ISSUE TITLE
Funannotate Update Error

### ISSUE THREAD

**Issue by PlantDr430** [nextgenusfs/funannotate#245]
This is in addition to the additional PASA errors I was having and wanted to test you Funannotate update to see if I was getting any errors there. I used alternative gene models to train AUGUSTUS (CodingQuarry). To get a final predicted results for update testing.

When I ran Update I got and error of too many values to unpack.

stephenwyka@bspmgenomics:/data/wyka/Cpur20_refined/Cpur20_1_update$ /data/wyka/funannotate-master/funannotate update -i Cpur20_1_fun_output/ --cpus 24 --left Cpur20_w_filtered_1P.fastq.gz --right Cpur20_w_filtered_2P.fastq.gz --jaccard_clip --min_protlen 100 --no_trimmomatic --no_normalize_reads
-------------------------------------------------------
[05:38 PM]: OS: linux2, 24 cores, ~ 264 GB RAM. Python: 2.7.12
[05:38 PM]: Running funannotate v1.5.1
[05:38 PM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
Traceback (most recent call last):
  File "/data/wyka/funannotate-master/bin/funannotate-update.py", line 1621, in <module>
    locustag, genenumber, justify = gbk2pasaNEW(GBK, gffout, trnaout, fastaout, spliceout, exonout, proteinsout)
  File "/data/wyka/funannotate-master/bin/funannotate-update.py", line 259, in gbk2pasaNEW
    tag, count = lastTag.split('_')
ValueError: too many values to unpack

stephenwyka@bspmgenomics:/data/wyka/Cpur20_refined/Cpur20_1_update$

**Comment by PlantDr430** [comment]
Actually, I think I know what the problem is. I left a command on to change the locus tags on and forgot to turn it off. Sorry
