### ISSUE TITLE
meropsDB: urllib2.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#254]
Dear nextgenusfs,

I have download and trying to install the docker image. It seems to throw an error related to issues https://github.com/nextgenusfs/funannotate/issues/125

Is this issue something to worry about? - It will it work anyway?

cheers,

Pete

**Are you using the latest release?**
Yes. Docker image downloaded: 10th Jan 2019

**Describe the bug**
Error:

in your user's path and review the RepeatModeler documentation here:
   /home/linuxbrew/repeatmodeler/README

[10:54 AM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.14
[10:54 AM]: Running funannotate v1.5.0
[10:54 AM]: Database location: /home/linuxbrew/DB
[10:54 AM]: Downloading Merops database
Traceback (most recent call last):
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 441, in <module>
-------------------------------------------------------
    meropsDB(DatabaseInfo, args.force)
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 100, in meropsDB
    download(lib.DBURL.get('merops'), fasta)
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 67, in download
    u = urllib2.urlopen(url)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 1405, in ftp_open
    raise URLError(msg)
urllib2.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
Removing intermediate container 9baf117fa279
 ---> 339efce8ce59
Step 8/9 : WORKDIR /home/linuxbrew/data
 ---> Running in 7d465e9b1468
Removing intermediate container 7d465e9b1468
 ---> d3e3f84bc74c
Step 9/9 : ENTRYPOINT /bin/bash
 ---> Running in 63e60cd39b15
Removing intermediate container 63e60cd39b15
 ---> f3b80db8ae93
Successfully built f3b80db8ae93
Successfully tagged funannotate:latest

**What command did you issue?**
.docker build -t funannotate -f Dockerfile .

**OS/Install Information**
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"

**Comment by peterthorpe5** [comment]
Moreover:  funannotate setup -d $HOME/funannotate_db     fails with the same error. 

$ funannotate setup -d $HOME/funannotate_db
-------------------------------------------------------
[11:21 AM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.14
[11:21 AM]: Running funannotate v1.5.0
[11:21 AM]: Database location: /home/linuxbrew/funannotate_db
[11:21 AM]: Downloading Merops database
Traceback (most recent call last):
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 441, in <module>
    meropsDB(DatabaseInfo, args.force)
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 100, in meropsDB
    download(lib.DBURL.get('merops'), fasta)
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 67, in download
    u = urllib2.urlopen(url)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 1405, in ftp_open
    raise URLError(msg)
urllib2.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

**Comment by nextgenusfs** [comment]
Hi @peterthorpe5, so the error is related to the docker images not being able to access the MEROPS resource?  But you can access the MEROPS resource from outside docker?  Is it only the MEROPS data? 
 Perhaps you are behind a firewall and it is a proxy issue?  I'm not a docker user actually -- just provided an image per request that I could get to work on my system (which was Mac OSX at the time). So if there are some improvements/enhancements/etc to the docker build to avoid this issue that would be welcomed. 

Here is the links that are being used by `funannotate setup` if that helps you with any additional troubleshooting:
```
'uniprot': 'ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz',
'uniprot-release': 'ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt',
'merops': 'ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/merops_scan.lib',
'dbCAN': 'http://cys.bios.niu.edu/dbCAN2/download/Databases/dbCAN-HMMdb-V7.txt',
'dbCAN-tsv': 'http://cys.bios.niu.edu/dbCAN2/download/Databases/CAZyDB.07312018.fam-activities.txt',
'dbCAN-log': 'http://cys.bios.niu.edu/dbCAN2/download/Databases/dbCAN-old@UGA/readme.txt',
'pfam': 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam-A.hmm.gz',
'pfam-tsv': 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam-A.clans.tsv.gz',
'pfam-log': 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam.version.gz',
'outgroups': 'https://osf.io/r9sne/download?version=1',
'repeats': 'https://osf.io/vp87c/download?version=1',
'go-obo': 'http://purl.obolibrary.org/obo/go.obo', 
'mibig': 'https://mibig.secondarymetabolites.org/MIBiG_prot_seqs_1.4.fasta',
'interpro': 'ftp://ftp.ebi.ac.uk/pub/databases/interpro/interpro.xml.gz',
'gene2product': 'https://raw.githubusercontent.com/nextgenusfs/gene2product/master/ncbi_cleaned_gene_products.txt'
```
On our HPC we have some firewall issues as well, especially for `ftp`.  You can check access to these resources on the cmd line with `wget` inside and outside of docker, perhaps that can give you a clue.

**Comment by peterthorpe5** [comment]
Hi Jon,

None of the downloads for me would work inside the docker image. I went through the code and I tried then systematically. So it was not just the MEROPS data. But worked fine outside docker, on the same machine.  I am sorry I don't know enough about error to suggest a fix. Does that make sense?

Pete
________________________________

**Comment by nextgenusfs** [comment]
So that sounds like a Docker configuration issue then?  Sounds like you can't get to the internet then from Docker at all?
