### ISSUE TITLE
busco.final.gff3 not found

### ISSUE THREAD

**Issue by timkahlke** [nextgenusfs/funannotate#263]
Version v1.5.2-8a16cb0
OS Ubuntu 16.04

funannotate-predict can't find/does not create the busco.final.gff3 file and I can't figure out why. There are no errors in any log file. I also checked issue #45 but that doesn't apply as gff3_file_to_proteins.pl works fine for me.

Any idea what could be the problem?

**Funannotate output**
```[09:52 AM]: OS: linux2, 32 cores, ~ 132 GB RAM. Python: 2.7.12
[09:52 AM]: Running funannotate v1.5.2-8a16cb0
[09:52 AM]: AUGUSTUS (3.3.1) detected, version seems to be compatible with BRAKER and BUSCO
[09:52 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[09:52 AM]: Genome loaded: 2,506 scaffolds; 45,285,476 bp; 33.14% repeats masked
[09:52 AM]: Existing protein alignments found: cm_40/predict_misc/protein_alignments.gff3
[09:52 AM]: Running GeneMark-ES on assembly
[10:00 AM]: Converting GeneMark GTF file to GFF3
[10:00 AM]: Found 15,363 gene models
[10:00 AM]: Running BUSCO to find conserved gene models for training Augustus
[10:00 AM]: Multi-threading in tblastn v2.7.1 is unstable, running in single threaded mode for BUSCO
[10:05 AM]: 109 valid BUSCO predictions found, now formatting for EVM
[10:05 AM]: 107 total gene models from EVM
[10:05 AM]: Checking BUSCO protein models for accuracy
Traceback (most recent call last):
  File "/home/c3_admin/github/funannotate/bin/funannotate-predict.py", line 998, in <module>
    total = lib.countGFFgenes(busco_final)
  File "/home/c3_admin/github/funannotate/lib/library.py", line 1094, in countGFFgenes
    with open(input, 'rU') as f:
IOError: [Errno 2] No such file or directory: 'genome/predict_misc/busco.final.gff3'
```

**Busco log finishes with**
```INFO    ****************** Start a BUSCO 2.0 analysis, current time: 01/23/2019 10:06:00 ******************
INFO    The lineage dataset is: protists_ensembl (eukaryota)
INFO    Mode is: proteins
INFO    To reproduce this run: python /home/c3_admin/github/funannotate/util/funannotate-BUSCO2.py -i /home/c3_admin/data/c/genome/predict_misc/busco.evm.proteins.fa -o c_c3 -l /home/c3_admin/apps/funannotate_databases/protists/ -m proteins -c 16 -sp anidulans
INFO    Check dependencies...
INFO    Check input file...
INFO    Delete the current result folder and start a new run
INFO    Temp directory is ./tmp/
INFO    Running HMMER on the proteins:
INFO    01/23/2019 10:06:00 =>  0% of predictions performed (215 to be done)
INFO    01/23/2019 10:06:00 =>  10% of predictions performed (24/215 candidate proteins)
INFO    01/23/2019 10:06:00 =>  20% of predictions performed (49/215 candidate proteins)
INFO    01/23/2019 10:06:00 =>  30% of predictions performed (68/215 candidate proteins)
INFO    01/23/2019 10:06:00 =>  40% of predictions performed (90/215 candidate proteins)
INFO    01/23/2019 10:06:00 =>  50% of predictions performed (110/215 candidate proteins)
INFO    01/23/2019 10:06:00 =>  60% of predictions performed (135/215 candidate proteins)
INFO    01/23/2019 10:06:00 =>  70% of predictions performed (153/215 candidate proteins)
INFO    01/23/2019 10:06:00 =>  80% of predictions performed (176/215 candidate proteins)
INFO    01/23/2019 10:06:00 =>  90% of predictions performed (197/215 candidate proteins)
INFO    01/23/2019 10:06:01 =>  100% of predictions performed
INFO    Results:
INFO    C:48.4%[S:48.4%,D:0.0%],F:0.0%,M:51.6%,n:215
INFO    104 Complete BUSCOs (C)
INFO    104 Complete and single-copy BUSCOs (S)
INFO    0 Complete and duplicated BUSCOs (D)
INFO    0 Fragmented BUSCOs (F)
INFO    111 Missing BUSCOs (M)
INFO    215 Total BUSCO groups searched

INFO    BUSCO analysis done. Total running time: 0.878084897995 seconds
INFO    Results written in /home/c3_admin/data/c/genome/predict_misc/busco_proteins/run_c_genome/
```

**Last lines of funannotate-predict.log**
```[01/23/19 10:05:57]: bedtools intersect -a /home/c3_admin/data/c/genome/predict_misc/protein_alignments.gff3 -b genome/predict_misc/buscos.bed
[01/23/19 10:05:57]: 107 total gene models from EVM
[01/23/19 10:05:57]: Checking BUSCO protein models for accuracy
[01/23/19 10:05:57]: /home/c3_admin/apps/EVidenceModeler-1.1.1/EvmUtils/gff3_file_to_proteins.pl /home/c3_admin/data/c/genome/predict_misc/busco.evm.gff3 /home/c3_admin/data/c/genome/predict_misc/genome.softmasked.fa
```

**Content of directory predict-misc**
```drwxrwxr-x    4 c3_admin c3_admin      4096 Jan 23 10:00 busco
-rw-rw-r--    1 c3_admin c3_admin     67689 Jan 23 10:05 busco_augustus.gff3
-rw-rw-r--    1 c3_admin c3_admin     83495 Jan 23 10:05 busco_augustus.tmp
-rw-rw-r--    1 c3_admin c3_admin     91766 Jan 23 08:48 busco.evm.gff3
-rw-rw-r--    1 c3_admin c3_admin     61342 Jan 23 10:06 busco.evm.proteins.fa
-rw-rw-r--    1 c3_admin c3_admin         0 Jan 23 10:05 busco_genemark.gff3
-rw-rw-r--    1 c3_admin c3_admin     67689 Jan 23 10:05 busco_predictions.gff3
drwxrwxr-x    4 c3_admin c3_admin      4096 Jan 23 08:48 busco_proteins
-rw-rw-r--    1 c3_admin c3_admin         0 Jan 23 10:05 busco_proteins.gff3
-rw-rw-r--    1 c3_admin c3_admin      4978 Jan 23 10:05 buscos.bed
-rw-rw-r--    1 c3_admin c3_admin        79 Jan 23 10:05 busco_weights.txt
drwxrwxr-x 2508 c3_admin c3_admin     90112 Jan 23 08:44 EVM_busco
-rw-rw-r--    1 c3_admin c3_admin   3253799 Jan 18 15:28 exonerate.out
drwxrwxr-x    6 c3_admin c3_admin      4096 Jan 23 10:00 genemark
-rw-rw-r--    1 c3_admin c3_admin   7937432 Jan 23 10:00 genemark.evm.gff3
-rw-rw-r--    1 c3_admin c3_admin   7937432 Jan 23 10:00 genemark.evm.gff3.bak
-rw-rw-r--    1 c3_admin c3_admin   8031801 Jan 23 10:00 genemark.gff
-rw-rw-r--    1 c3_admin c3_admin   7937432 Jan 23 10:00 genemark.temp.gff
-rw-rw-r--    1 c3_admin c3_admin  46233908 Jan 23 09:52 genome.softmasked.fa
-rw-rw-r--    1 c3_admin c3_admin    919162 Jan 23 09:55 gmhmm.mod
-rw-rw-r--    1 c3_admin c3_admin     30794 Jan 23 09:52 hints.ALL.gff
-rw-rw-r--    1 c3_admin c3_admin    474267 Jan 23 09:52 hints.all.sort.tmp
-rw-rw-r--    1 c3_admin c3_admin    474267 Jan 23 09:52 hints.all.tmp
-rw-rw-r--    1 c3_admin c3_admin    474267 Jan 23 09:52 hints.P.gff
-rw-rw-r--    1 c3_admin c3_admin  60222918 Jan 18 15:28 p2g.diamond.out
-rw-rw-r--    1 c3_admin c3_admin    594375 Jan 23 09:34 protein_alignments.gff3
-rw-rw-r--    1 c3_admin c3_admin    594375 Jan 23 09:34 protein_alignments.gff3.old
-rw-rw-r--    1 c3_admin c3_admin 206870941 Jan 23 09:52 proteins.combined.fa
-rw-rw-r--    1 c3_admin c3_admin 206870941 Jan 23 09:34 proteins.combined.fa.old
-rw-rw-r--    1 c3_admin c3_admin   1028681 Jan 23 09:52 repeatmasker.bed
-rw-rw-r--    1 c3_admin c3_admin     38988 Jan 23 09:52 scaffold.sort.order.txt
-rw-rw-r--    1 c3_admin c3_admin     50412 Jan 23 09:52 scaffold.sort.rename.txt
```

**Comment by timkahlke** [comment]
The `busco_proteins` folder has a run_xxx folder folder with 2 *.tsv files. a txt file and `hmmer_output` full of hmmer output files (obviously :) ). There's also an empty `tmp` folder in it.

Interestingly, the command creates the busco.final.gff3 and predict seems to run now ... unfortunately, now it exits with "Not enough gene models to train Augustus (220 required), exiting" .. I guess I'm back to start and have to look for other options.

**Comment by nextgenusfs** [comment]
@hyphaltip tip did you add option to train with fewer gene models from busco?

**Comment by nextgenusfs** [comment]
There is a currently undocumentated option that could help, you can use `--min_training_models` and set it to something like 100 and see if it will run.  The other option is to use a different busco_db that has more models, but in your case seems like for protists you may need to just reduce the min training models;
```
$ funannotate outgroups --show_buscos
-----------------------------
BUSCO DB tree: (# of models)
-----------------------------
eukaryota (303)
	metazoa (978)
		nematoda (982)
		arthropoda (1066)
			insecta (1658)
			endopterygota (2442)
			hymenoptera (4415)
			diptera (2799)
		vertebrata (2586)
			actinopterygii (4584)
			tetrapoda (3950)
			aves (4915)
			mammalia (4104)
		euarchontoglires (6192)
			laurasiatheria (6253)
	fungi (290)
		dikarya (1312)
			ascomycota (1315)
				pezizomycotina (3156)
					eurotiomycetes (4046)
					sordariomycetes (3725)
					saccharomycetes (1759)
						saccharomycetales (1711)
			basidiomycota (1335)
		microsporidia (518)
	embryophyta (1440)
	protists (215)
		alveolata_stramenophiles (234)
```

**Comment by hyphaltip** [comment]
Yes. Use --min_training_models 50 or something like that

E.g see it used in here.
https://github.com/zygolife/LCG_Assembly/blob/master/Annotation/pipeline/02_predict_optimize.sh

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by timkahlke** [comment]
Awesome thanks for that. I'll definitely give it a shot.

**Comment by timkahlke** [comment]
Also, to enlighten/amuse you, I found the error: my `/usr/bin/env` points to the python3 executable. And because I always start funannotate specifically with "python2 funannotate-predict ..." I didn't realize the problem until now when it produced a sequence of weird errors like the one I reported.

Thanks for the BUSCO tip anyways.
