### ISSUE TITLE
Licensing issues: Kent-tools and blat

### ISSUE THREAD

**Issue by mswyers** [nextgenusfs/funannotate#264]
**Are you using the latest release?**
```
$ funannotate check
-------------------------------------------------------
Checking dependencies for funannotate v1.5.0
-------------------------------------------------------
```

**Describe the bug**
We're looking to have funannotate run for us through a core facility that has very strict policy on licensing. While kent-tools and blat are offered via brewsci or bioconda seemingly without license, this is just because someone uploaded their licensed version for everyone else to download. The core doesn't want to take any chances, legally, so requires us to personally have licensing for everything. The problem is we don't want to pay thousands of dollars for a couple projects. 

My question is: are these completely necessary for funannotate to function? If so, are there any workarounds to these packages?

**OS/Install Information**
 -  output of `funannotate check --show-versions`

```$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for funannotate v1.5.0
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.73
goatools: 0.8.12
matplotlib: 2.2.3
natsort: 5.5.0
numpy: 1.15.4
pandas: 0.23.4
psutil: 5.4.8
requests: 2.19.1
scikit-learn: 0.20.2
scipy: 1.1.0
seaborn: 0.9.0
All 11 python packages installed


You are running Perl v 5.028001. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.50
Clone: 0.41
DBD::SQLite: 1.62
DBD::mysql: 4.049
DBI: 1.642
DB_File: 1.84
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.00
LWP::UserAgent: 6.36
Logger::Simple: 2.0
POSIX: 1.84
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.08
Text::Soundex: 3.05
Thread::Queue: 3.13
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.27
threads: 2.22
threads::shared: 1.59
All 27 Perl modules installed


Checking external dependencies...
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/ete3", line 7, in <module>
    from ete3.tools.ete import main
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_2/lib/python2.7/site-packages/ete3/tools/ete.py", line 55, in <module>
    from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_2/lib/python2.7/site-packages/ete3/tools/ete_view.py", line 48, in <module>
    from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,
ImportError: cannot import name TextFace
RepeatMasker: RepeatMasker 4.0.7
RepeatModeler: RepeatModeler 1.0.8
Trinity: 2.8.3
augustus: 3.3.2
bamtools: bamtools 2.5.1
bedtools: bedtools v2.27.1
blat: BLAT v36
diamond: diamond 0.9.24
emapper.py: emapper-1.0.3
exonerate: exonerate 2.2.0
fasta: no way to determine
gmap: 2018-07-04
gmes_petap.pl: 4.38
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 1.8.0_181
kallisto: 0.44.0
mafft: v7.407 (2018/Jul/23)
makeblastdb: makeblastdb 2.8.1+
minimap2: 2.15-r905
nucmer: 3.1
pslCDnaFilter: no way to determine
rmblastn: rmblastn 2.2.27+
samtools: samtools 1.9
stringtie: 1.3.4d
tRNAscan-SE: 2.0 (December 2017)
tbl2asn: unknown, likely 25.3
tblastn: tblastn 2.8.1+
trimal: trimAl v1.4.rev15 build[2013-12-17]
	ERROR: CodingQuarry not installed
	ERROR: ete3 not installed
Checking Environmental Variables...
$FUNANNOTATE_DB=/home/seq/fundb
$PASAHOME=/home/seq/PASApipeline-v2.3.3
$TRINITYHOME=/home/linuxbrew/.linuxbrew/opt/trinity
$EVM_HOME=/home/linuxbrew/.linuxbrew/opt/evidencemodeler
$AUGUSTUS_CONFIG_PATH=/home/linuxbrew/.linuxbrew/opt/augustus/config
$GENEMARK_PATH=/home/seq/gmes_petap
$BAMTOOLS_PATH=/home/linuxbrew/.linuxbrew/opt/bamtools
All 7 environmental variables are set 
```

Ignore the ete3 error, we aren't using RNAseq data so I haven't bothered with it.

Thanks in advance.

**Comment by nextgenusfs** [comment]
Okay, so by default `blat` and `pslCDnaFilter` are not used -- they are controlled in `funannotate predict` by the `--aligners` option.  So you shouldn't need either installed to run the default pipeline.
