### ISSUE TITLE
Dbcan url error

### ISSUE THREAD

**Issue by hainguyenres** [nextgenusfs/funannotate#277]
Hello!  I am getting the dbCAN url error which I realized was reported before.  It does not seem to be fixed still... Was wondering if you could look into this?  I am running using the Dockerfile.  Thanks.
Hai

[05:57 PM]: OS: linux2, 4 cores, ~ 2 GB RAM. Python: 2.7.15
[05:57 PM]: Running funannotate v1.5.2
[05:57 PM]: Database location: /home/linuxbrew/DB
[05:57 PM]: Downloading Merops database
[05:57 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/merops_scan.lib Bytes: 1942655
-------------------------------------------------------
[05:57 PM]: Building diamond database
[05:57 PM]: MEROPS Database: version=12.0 date=2017-10-04 records=4,968
[05:57 PM]: Downloading UniProtKB/SwissProt database
[05:57 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz Bytes: 88408361
[05:58 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt Bytes: 151
[05:58 PM]: Building diamond database
[05:58 PM]: UniProtKB Database: version=2019_02 date=2019-02-13 records=559,228
[05:58 PM]: Downloading dbCAN database
Traceback (most recent call last):
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 443, in <module>
    dbCANDB(DatabaseInfo, args.force)
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 162, in dbCANDB
    download(lib.DBURL.get('dbCAN'), os.path.join(FUNDB,'dbCAN.tmp'))
  File "/home/linuxbrew/funannotate/bin/funannotate-setup.py", line 67, in download
    u = urllib2.urlopen(url)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/home/linuxbrew/conda/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/home/linuxbrew/conda/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/home/linuxbrew/conda/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/home/linuxbrew/conda/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

**Comment by nextgenusfs** [comment]
The links were updated a few months ago.  And when I created the docker image they were also functional a few weeks ago.  It may just be a temporary outage.  If it is still not working tomorrow I'll take a look.

**Comment by nextgenusfs** [comment]
Okay, well looks like they moved it again about 5 days ago.  I updated the links and rebuilding the docker image now -- hopefully will be uploaded in a few hours.  The updated docker image should read v1.5.3.

**Comment by nextgenusfs** [comment]
Okay, looks like should be updated now.  Reopen if problem persists.

**Comment by hainguyenres** [comment]
Thanks Jon!  I tried it today and everything installed as it should.

**Comment by geennaam400** [comment]
Hi, this error is back it seems. Funannotate setup keeps hanging at "Downloading dbCAN database"
Command used: funannotate setup -d <path_to_db>
