### ISSUE TITLE
database

### ISSUE THREAD

**Issue by gengce** [nextgenusfs/funannotate#279]
(python2) [root@localgc src]# funannotate setup -d /home/funannotate/FunDB -u -i dbCAN  -f -b all
-------------------------------------------------------
[06:04 PM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.15
[06:04 PM]: Running funannotate v1.5.2
[06:04 PM]: Database location: /home/funannotate/FunDB
[06:04 PM]: Downloading dbCAN database
Traceback (most recent call last):
  File "/home/funannotate/bin/funannotate-setup.py", line 443, in <module>
    dbCANDB(DatabaseInfo, args.force)
  File "/home/funannotate/bin/funannotate-setup.py", line 162, in dbCANDB
    download(lib.DBURL.get('dbCAN'), os.path.join(FUNDB,'dbCAN.tmp'))
  File "/home/funannotate/bin/funannotate-setup.py", line 67, in download
    u = urllib2.urlopen(url)
  File "/root/miniconda3/envs/python2/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/root/miniconda3/envs/python2/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/root/miniconda3/envs/python2/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/root/miniconda3/envs/python2/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/root/miniconda3/envs/python2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/root/miniconda3/envs/python2/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 502: Bad Gateway
(python2) [root@localgc src]# funannotate setup -d /home/funannotate/FunDB -u -i uniprot  -f -b all
-------------------------------------------------------
[06:05 PM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.15
[06:05 PM]: Running funannotate v1.5.2
[06:05 PM]: Database location: /home/funannotate/FunDB
[06:05 PM]: Downloading UniProtKB/SwissProt database
[06:05 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz Bytes: 88408361
[06:08 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt Bytes: 151
[06:08 PM]: Building diamond database
[06:08 PM]: UniProtKB Database: version=2019_02 date=2019-02-13 records=559,228
[06:08 PM]: Funannoate setup complete. Add this to ~/.bash_profile or ~/.bash_aliases:

	export FUNANNOTATE_DB=/home/funannotate/FunDB

(python2) [root@localgc src]# funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for funannotate v1.5.2
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.72
goatools: 0.8.12
matplotlib: 2.2.3
natsort: 6.0.0
numpy: 1.16.2
pandas: 0.24.2
psutil: 5.6.1
requests: 2.21.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.50
Clone: 0.41
DBD::SQLite: 1.60
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.843
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.37
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.11
Text::Soundex: 3.05
Thread::Queue: 3.13
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.27
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking external dependencies...
CodingQuarry: 2.0
RepeatMasker: RepeatMasker version development-$Id: RepeatMasker,v 1.332 2017/04/17 19:01:11 rhubley Exp $
RepeatModeler: RepeatModeler 1.0.11
Trinity: 2.5.1
augustus: 3.2.3
bamtools: bamtools 2.4.1
bedtools: bedtools v2.27.1
blat: BLAT v36
diamond: diamond 0.9.24
emapper.py: emapper-1.0.3-3-g3e22728
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
gmap: 2018-07-04
gmes_petap.pl: 4.38
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 1.8.0_121
kallisto: 0.44.0
mafft: v7.427 (2019/Mar/24)
makeblastdb: makeblastdb 2.6.0+
minimap2: 2.16-r922
nucmer: 3.1
pslCDnaFilter: no way to determine
rmblastn: rmblastn 2.6.0+
samtools: samtools 1.9
stringtie: 1.3.5
tRNAscan-SE: 2.0.2 (February 2019)
tbl2asn: unknown, likely 25.3
tblastn: tblastn 2.6.0+
trimal: trimAl v1.4.rev15 build[2013-12-17]
All 32 external dependencies are installed

**Comment by nextgenusfs** [comment]
I think this was fixed yesterday with v1.5.3. https://github.com/nextgenusfs/funannotate/issues/277
