### ISSUE TITLE
predict hanve some errors in my computer

### ISSUE THREAD

**Issue by gengce** [nextgenusfs/funannotate#280]
(python2) [root@localgc sample_data]# bash run_unit_tests.sh
funannotate predict -i genome1.fasta --force -s "Genome one" --name GN1_ -o genome1 --protein_evidence proteins.fa --transcript_evidence transcripts.fa --augustus_species botrytis_cinerea --cpus 6
-------------------------------------------------------
[03:12 PM]: OS: linux2, 8 cores, ~ 33 GB RAM. Python: 2.7.15
[03:12 PM]: Running funannotate v1.5.3
[03:12 PM]: Augustus training set for botrytis_cinerea already exists. To re-train provide unique --augustus_species argument
[03:12 PM]: AUGUSTUS (3.2.3) detected, version seems to be compatible with BRAKER and BUSCO
[03:12 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[03:12 PM]: Genome loaded: 3 scaffolds; 451,050 bp; 0.00% repeats masked
[03:12 PM]: Aligning transcript evidence to genome with minimap2
[03:12 PM]: Found 198 alignments, wrote GFF3 and Augustus hints to file
[03:12 PM]: Mapping proteins to genome using Diamond blastx/Exonerate
[03:12 PM]: Using 9,043 proteins as queries
[03:12 PM]: Running Diamond pre-filter search
[03:12 PM]: Found 520 preliminary alignments
[03:12 PM]: Exonerate finished: found 102 alignments
**Traceback (most recent call last):
  File "/home/funannotate/bin/funannotate-predict.py", line 654, in <module>
    lib.runSubprocess5(cmd, '.', lib.log, allhintstmp_sort, hints_all)
  File "/home/funannotate/lib/library.py", line 732, in runSubprocess5
    proc = subprocess.Popen(cmd, cwd=dir, stdin=infile, stdout=out, stderr=subprocess.PIPE)
  File "/root/miniconda3/envs/python2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/root/miniconda3/envs/python2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception**
OSError: [Errno 2] No such file or directory
funannotate predict -i genome2.fasta --force -s "Genome two" --name GN2_ -o genome2 --protein_evidence proteins.fa --transcript_evidence transcripts.fa --augustus_species botrytis_cinerea --cpus 6
-------------------------------------------------------

**Comment by nextgenusfs** [comment]
This is relict of old code the bash script won’t run due to some missing files, use funannotate test.

**Comment by gengce** [comment]
thank you very much
