### ISSUE TITLE
No such file or directory: './annotate_misc/genome.tbl'

### ISSUE THREAD

**Issue by shenweima** [nextgenusfs/funannotate#297]
I want to use `funannotate annotate` command to annotate my gene function, but some error happens.
My order is :
```
funannotate annotate --gff /data2/Fshare/FastaAndIndex/iwgsc_refseqv1.1_genes_2017July06/IWGSC_v1.1_HC_20170706.gff3 --fasta /data2/Fshare/FastaAndIndex/IWGSC_v1.0_bwa/161010_Chinese_Spring_v1.0_pseudomolecules.fasta -s "Triticum aestivum" -d /data -o ./
```
the log:
```
-------------------------------------------------------
[05:53 PM]: OS: linux2, 28 cores, ~ 791 GB RAM. Python: 2.7.15
[05:53 PM]: Running funannotate v1.5.3
[05:53 PM]: Parsing annotation and preparing annotation files.
Traceback (most recent call last):
  File "/home/linuxbrew/funannotate/bin/funannotate-functional.py", line 467, in <module>
    GeneCounts = lib.convertgff2tbl(GFF, prefix, Scaffolds, Proteins, Transcripts, annotTBL)
  File "/home/linuxbrew/funannotate/lib/library.py", line 1695, in convertgff2tbl
    dicts2tbl(renamedGenes, scaff2genes, scaffLen, 'CFMR', '12345', [], tblout)
  File "/home/linuxbrew/funannotate/lib/library.py", line 1861, in dicts2tbl
    with open(output, 'w') as tbl:
IOError: [Errno 2] No such file or directory: '/data2/user_data/funannotate/annotate_misc/genome.tbl'
```

**Comment by nextgenusfs** [comment]
Did it create temp directories, looks like it is looking in a folder that doesn’t exist. Pass a name to the -o flag and see what happens.
