### ISSUE TITLE
miBig downloads

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#300]
**Are you using the latest release?**
yes

**Describe the bug**
miBig URLs seem to have changed?

https://mibig.secondarymetabolites.org/#!/download lists the FASTA download as 
https://dl.secondarymetabolites.org/mibig/mibig_json_1.4.tar.gz
but the URL in library.py is
```
lib/library.py:183:        'mibig': 'https://mibig.secondarymetabolites.org/MIBiG_prot_seqs_1.4.fasta',
```
I think need to email them - all the FASTA links are also to JSON downloads for all versions so maybe something changed on their end. Contact link doesn't give a contact page but I emailed help@secondarymetabolites.org and await a response.

**What command did you issue?**

`funannotate setup -u -i mibig`

**Logfiles**
```
funannotate setup -u -i mibig
-------------------------------------------------------
[09:50 AM]: OS: linux2, 16 cores, ~ 132 GB RAM. Python: 2.7.12
[09:50 AM]: Running funannotate v1.6.0-2fe943e
[09:50 AM]: Database location: /opt/linux/centos/7.x/x86_64/pkgs/funannotate/share
[09:50 AM]: Checking for newer versions of database files
Traceback (most recent call last):
  File "/bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/funannotate/git-live/bin/funannotate-setup.py", line 453, in <module>
    mibigDB(DatabaseInfo, args.force)
  File "/bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/funannotate/git-live/bin/funannotate-setup.py", line 295, in mibigDB
    if check4newDB('mibig', info):
  File "/bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/funannotate/git-live/bin/funannotate-setup.py", line 55, in check4newDB
    newmd5 = calcmd5remote(lib.DBURL.get(name))
  File "/bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/funannotate/git-live/bin/funannotate-setup.py", line 33, in calcmd5remote
    remote = urllib2.urlopen(url)
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/envs/funannotate/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/envs/funannotate/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/envs/funannotate/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/envs/funannotate/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/envs/funannotate/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/envs/funannotate/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**OS/Install Information**
 -  output of `funannotate check --show-versions`

**Comment by hyphaltip** [comment]
This is fixed by commit f07ce706

**Comment by FatihSarigol** [comment]
In case anybody needs to stay with an earlier funannotate version like me, changing the link in library.py as the commit states did the work!

**Comment by nextgenusfs** [comment]
Just dropping a note here — but we should move these links into a JSON file that can be checked at runtime if most up to date and download if necessary. That way we don’t have to hard code paths and tag a new release when database links change.
