### ISSUE TITLE
annotate fails to create SM cluster output

### ISSUE THREAD

**Issue by mswyers** [nextgenusfs/funannotate#316]
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**
using funannotate annotate fails at the very end when creating the SM cluster output file. Everything up until then is fine. My annotate_results folder has all of the other output files except for the SM clusters.

**What command did you issue?**
```
$ funannotate annotate -i predict/ --iprscan predict/annotate_misc/iprscan.xml --antismash predict/annotate_misc/antismash/contig_1.final.gbk -s "Tolypocladium" -o results/
```

**Logfiles**
The funannotate-annotate logfile actually doesn't show the error, but this is what comes up in the command window:
```
[03:45 PM]: Cross referencing SM cluster hits with MIBiG database version 1.4
[03:45 PM]: Creating tab-delimited SM cluster output
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/funannotate/1.5.3/libexec/bin/funannotate-functional.py", line 1167, in <module>
    actualStart = int(start) + int(Offset.get(base)) + 1 #account for python numbering shift?
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**OS/Install Information**
 -  output of `funannotate check --show-versions`

```

$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for funannotate v1.5.3
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.74
goatools: 0.9.7
matplotlib: 2.2.4
natsort: 6.0.0
numpy: 1.16.4
pandas: 0.24.2
psutil: 5.6.3
requests: 2.22.0
scikit-learn: 0.20.4
scipy: 1.2.2
seaborn: 0.9.0
All 11 python packages installed


You are running Perl v 5.030000. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.50
Clone: 0.43
DBD::SQLite: 1.64
DBD::mysql: 4.050
DBI: 1.642
DB_File: 1.843
Data::Dumper: 2.174
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.51
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.88
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.13
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.22
threads::shared: 1.6
All 27 Perl modules installed


Checking external dependencies...
Traceback (most recent call last):
  File "/home/seq/emapper.py", line 19, in <module>
    from eggnogmapper.common import *
ImportError: No module named eggnogmapper.common
Soundex.c: loadable library and perl binaries are mismatched (got handshake key 0xce00080, needed 0xcd00080)
diamond v0.9.25.126 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

RepeatModeler: RepeatModeler 1.0.8
Trinity: 2.8.3
augustus: 3.3.2
bamtools: bamtools 2.5.1
bedtools: bedtools v2.28.0
blat: BLAT v36
diamond: diamond 0.9.25
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
gmap: 2019-06-10
gmes_petap.pl: 4.38
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 11.0.1
kallisto: 0.46.0
mafft: v7.407 (2018/Jul/23)
makeblastdb: makeblastdb 2.9.0+
minimap2: 2.17-r941
nucmer: 3.1
pslCDnaFilter: no way to determine
rmblastn: rmblastn 2.2.27+
samtools: samtools 1.9
stringtie: 1.3.6
tRNAscan-SE: 2.0.3 (April 2019)
tbl2asn: unknown, likely 25.3
tblastn: tblastn 2.9.0+
trimal: trimAl v1.4.rev15 build[2013-12-17]
	ERROR: CodingQuarry not installed
	ERROR: RepeatMasker not installed
	ERROR: emapper.py not installed
Checking Environmental Variables...
$FUNANNOTATE_DB=/home/seq/fundb
$PASAHOME=/home/seq/PASApipeline-v2.3.3
$TRINITYHOME=/home/linuxbrew/.linuxbrew/opt/trinity
$EVM_HOME=/home/linuxbrew/.linuxbrew/opt/evidencemodeler
$AUGUSTUS_CONFIG_PATH=/home/linuxbrew/.linuxbrew/opt/augustus/config
$GENEMARK_PATH=/home/seq/gmes_petap
$BAMTOOLS_PATH=/home/linuxbrew/.linuxbrew/opt/bamtools
All 7 environmental variables are set
```

I'm not sure how to rid myself of the Soundex.c perl binaries mismatch, I've completely removed perl and all its packages from linuxbrew and reinstalled them but the error still persists.

When I use cpan to search for the package it only shows the version I have built through linuxbrew and nowhere else, so not sure where the mismatch is coming from. This might be completely unrelated to what's going on though.

Thanks,

Michael

**Comment by nextgenusfs** [comment]
Which version of antismash?  Update funannotate to latest version.

**Comment by mswyers** [comment]
Homebrew lists 1.5.3 as the latest version, I uninstalled funannotate and did the manual build and just added it to my $PATH so I'm on version 1.6.0 as of now.

 Somehow my iprscan.xml file got deleted between annotation attempts, so i'm re-running that right now so my inputs are the same - unless I can feed the annotations.iprscan.txt into annotate?

**Comment by nextgenusfs** [comment]
Okay well I guess I haven’t updated homebrew, current version is 1.6.0. I don’t know if it still works for install and will probably drop support for homebrew all together.

**Comment by mswyers** [comment]
Re-ran without including the iprscan data and got the same error:
```

[04:32:02 PM]: Cross referencing SM cluster hits with MIBiG database version 1.4
[04:32:02 PM]: Creating tab-delimited SM cluster output
Traceback (most recent call last):
  File "/home/seq/funannotate/bin/funannotate-functional.py", line 1141, in <module>
    actualStart = int(start) + int(Offset.get(base)) + 1 #account for python numbering shift?
TypeError: int() argument must be a string or a number, not 'NoneType'

```

**Comment by nextgenusfs** [comment]
I think this is fixed in newest version. Can’t recall exactly but changed several parts of antismash parser to deal with v5 that changed formats.

**Comment by mswyers** [comment]
Gotcha. I'll update antismash and re-run and see what happens.

**Comment by nextgenusfs** [comment]
New antismash will only work with newest funannotate

**Comment by nextgenusfs** [comment]
I updated home-brew recipe.  It won't be tested, so no clue if it works or not. I would advise to move to a conda based install.

**Comment by nextgenusfs** [comment]
homebrew no longer supported, however, conda is now available.
