### ISSUE TITLE
augustus or busco issue

### ISSUE THREAD

**Issue by tarah28** [nextgenusfs/funannotate#322]
Hello! I am really excited to test this pipeline on some fungal genomes I've been working with - thank you so much for writing this. I am at the gene prediction stage and having trouble that I can't seem to get past. Not sure if it is an issue with Augustus or Busco, any help is much appreciated. 
`funannotate check --show-versions`
"-------------------------------------------------------
Checking dependencies for funannotate v1.6.0-df4262f
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.68
goatools: 0.9.7
matplotlib: 2.2.4
natsort: 6.0.0
numpy: 1.16.4
pandas: 0.24.2
psutil: 5.6.3
requests: 2.22.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.13
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking external dependencies...
CodingQuarry: 2.0
RepeatMasker: RepeatMasker 4.0.9
RepeatModeler: RepeatModeler version DEV
Trinity: 2.8.5
augustus: 3.2.2
bamtools: bamtools 2.5.1
bedtools: bedtools v2.28.0
blat: BLAT v36
diamond: diamond 0.9.24
emapper.py: 1.0.3-40-g41a8498
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.35
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 11.0.1
kallisto: 0.46.0
mafft: v7.407 (2018/Jul/23)
makeblastdb: makeblastdb 2.9.0+
minimap2: 2.17-r941
nucmer: 3.1
pslCDnaFilter: no way to determine
rmblastn: rmblastn 2.9.0+
salmon: salmon 0.14.1
samtools: samtools 1.9
stringtie: 1.3.6
tRNAscan-SE: 2.0.3 (April 2019)
tbl2asn: unknown, likely 25.3
tblastn: tblastn 2.9.0+
trimal: trimAl v1.4.rev15 build[2013-12-17]
	ERROR: snap not installed
Checking Environmental Variables...
$FUNANNOTATE_DB=/home/tlynch/programs/funannotate/
$PASAHOME=/home/tlynch/miniconda2/envs/funannotate/opt/pasa-2.3.3
$TRINITYHOME=/home/tlynch/miniconda2/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/tlynch/miniconda2/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/tlynch/miniconda2/pkgs/augustus-3.2.2-0/config
$GENEMARK_PATH=/home/tlynch/programs/GeneMark_ES/gmes_petap/
$BAMTOOLS_PATH=/home/tlynch/miniconda2/envs/funannotate/bin/bamtools
All 7 environmental variables are set"
`funannotate predict -i uamh3398_msk.fasta -o uamh_pred_v2 --species "Blastomyces species" --strain UAMH3398 --busco_seed_species histoplasma --cpus 12
`
"-------------------------------------------------------
[02:45 PM]: OS: linux2, 12 cores, ~ 66 GB RAM. Python: 2.7.15
[02:45 PM]: Running funannotate v1.6.0-df4262f
[02:45 PM]: ERROR: AUGUSTUS (3.2.2) is not installed properly and this version not work with BUSCO, this is a problem with Augustus compliatation, you may need to compile manually on linux2.
[02:45 PM]: AUGUSTUS (3.2.2) detected, version seems to be compatible with BRAKER and BUSCO
[02:45 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[02:45 PM]: Genome loaded: 5,315 scaffolds; 30,424,174 bp; 3.95% repeats masked
[02:45 PM]: Mapping proteins to genome using Diamond blastx/Exonerate
[02:45 PM]: Using 548,006 proteins as queries
[02:45 PM]: Running Diamond pre-filter search
[02:48 PM]: Found 445,028 preliminary alignments
[03:41 PM]: Exonerate finished: found 1,701 alignments
[03:41 PM]: Running GeneMark-ES on assembly
[03:54 PM]: Converting GeneMark GTF file to GFF3
[03:54 PM]: Found 10,352 gene models
[03:54 PM]: Running BUSCO to find conserved gene models for training Augustus
[03:54 PM]: Multi-threading in tblastn v2.9.0 is unstable, running in single threaded mode for BUSCO
[03:57 PM]: BUSCO training of Augusus failed, check busco logs, exiting
 "
I've attached the busco.log
[busco.log](https://github.com/nextgenusfs/funannotate/files/3580271/busco.log)

**Comment by nextgenusfs** [comment]
Most likely Augustus. Does the script have write access to the Augustus species directory?

This is from the busco log, any info in there?
 WARNING	BUSCO did not find any match. Do not forget to check the file /home/tlynch/Documents/Emmonsia/test/uamh_pred_v2/predict_misc/busco/run_blastomyces_species_uamh3398/augustus_output/augustus.log

**Comment by nextgenusfs** [comment]
Oh. I didn’t read the log closely — you need a different version of Augustus. I think v3.3 works on Linux.

**Comment by tarah28** [comment]
I tried installing a newer version of Augustus but it wouldn't work with bioconda (incompatibilities). Can I install augustus without comparative gene prediction capability or does funannotate need that?

**Comment by nextgenusfs** [comment]
It does not need the comparative gene prediction -- needs to be able to run the `--proteinprofile` method, which for unknown reasons doesn't compile in some versions (and its sporadic).  For example the only version that works with OSX is 3.2.1.  The Linux versions mostly work, but apparently this 3.2.2 one does not.  Funannotate runs a check of the proteinprofile functionality and was suppose to have quit gracefully after it determined that your version was not functional.

**Comment by nextgenusfs** [comment]
FYI -- on our centOS cluster I'm running v3.3.2 which was manually compiled as well and that is working for me at the moment.

**Comment by tarah28** [comment]
Thanks so much for getting back to me! I installed Augustus version 3.3.2 and it seemed to run further but now I have an issue with snap :(. When I run funannotate check it says that snap is not installed but it is and I symlinked the executable to be named 'snap' instead of 'snap-aligner'. The path was put in my .bashrc file - I'm not sure what else to do? 
-------------------------------------------------------
[12:53 PM]: OS: linux2, 12 cores, ~ 66 GB RAM. Python: 2.7.15
[12:53 PM]: Running funannotate v1.6.0-df4262f
[12:53 PM]: AUGUSTUS (3.3.2) detected, version seems to be compatible with BRAKER and BUSCO
[12:53 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[12:54 PM]: Genome loaded: 5,315 scaffolds; 30,424,174 bp; 3.95% repeats masked
[12:54 PM]: Mapping proteins to genome using Diamond blastx/Exonerate
[12:54 PM]: Using 548,006 proteins as queries
[12:54 PM]: Running Diamond pre-filter search
[12:57 PM]: Found 445,028 preliminary alignments
[01:50 PM]: Exonerate finished: found 1,704 alignments
[01:50 PM]: Running GeneMark-ES on assembly
[02:02 PM]: Converting GeneMark GTF file to GFF3
[02:02 PM]: Found 10,245 gene models
[02:02 PM]: Running BUSCO to find conserved gene models for training Augustus
[02:02 PM]: Multi-threading in tblastn v2.9.0 is unstable, running in single threaded mode for BUSCO
[02:14 PM]: 1,256 valid BUSCO predictions found, now formatting for EVM
[02:15 PM]: Setting up EVM partitions
[02:15 PM]: Generating EVM command list
[02:15 PM]: Running EVM commands with 11 CPUs
[02:17 PM]: Combining partitioned EVM outputs
[02:17 PM]: Converting EVM output to GFF3
[02:23 PM]: Collecting all EVM results
[02:23 PM]: 1,249 total gene models from EVM
[02:23 PM]: Checking BUSCO protein models for accuracy
[02:23 PM]: 1,248 BUSCO predictions validated
[02:23 PM]: Training Augustus using BUSCO gene models
[02:24 PM]: Augustus initial training results:
  Feature       Specificity   Sensitivity
  nucleotides   99.5%         95.8%      
  exons         87.9%         83.1%      
  genes         71.2%         62.7%      
[02:24 PM]: Running Augustus gene prediction
[02:28 PM]: Found 8,912 gene models
[02:28 PM]: Pulling out high quality Augustus predictions
[02:28 PM]: Found 77 high quality predictions from Augustus (>90% exon evidence)
[02:28 PM]: Skipping CodingQuarry as there are no RNA-seq data
Traceback (most recent call last):
  File "/home/tlynch/programs/funannotate/bin/funannotate-predict.py", line 1181, in <module>
    if lib.snap_run_check(SnapPredictions, FinalTrainingModels, StartWeights['snap']):
  File "/home/tlynch/programs/funannotate/lib/library.py", line 4999, in snap_run_check
    lob.info('Snap failed, dependency not in $PATH: {:}'.format(x))
NameError: global name 'lob' is not defined

**Comment by tarah28** [comment]
The predict_results folder is empty

**Comment by nextgenusfs** [comment]
Oh... that is a typo by me, it should have just continued without snap.  Install snap and glimmerhmm with conda? `conda install snap glimmerhmm`

**Comment by nextgenusfs** [comment]
OKay, typo is fixed in master https://github.com/nextgenusfs/funannotate/commit/297abc4e471214de9940ce5fd8cc577536ac552a.  If you run a `git pull` on the cloned funannotate repo it should be fixed.

**Comment by hyphaltip** [comment]
Snap-aligner is different from Snap the gene predictor (by Ian Korf) so make sure you have the predictor installed if you want to include it.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by tarah28** [comment]
Thanks so much @nextgenusfs and @hyphaltip! That seemed to fix it! I really appreciate your help.
