### ISSUE TITLE
NameError: name 'genome' is not defined

### ISSUE THREAD

**Issue by shenweima** [nextgenusfs/funannotate#334]
`
[11:39 PM]: OS: linux2, 28 cores, ~ 791 GB RAM. Python: 2.7.15

[11:39 PM]: Running funannotate v1.6.0-603d2f1

[11:45 PM]: Previous annotation consists of: 107,891 protein coding gene models and 0 non-coding gene models

[11:45 PM]: Existing BAM alignments found: test/update_misc/transcript.alignments.bam

[11:45 PM]: Converting transcript alignments to GFF3 format

[11:46 PM]: Running PASA alignment step using 578,119 transcripts

[11:50 PM]: Running PASA annotation comparison step 1

[03:25 PM]: Running PASA annotation comparison step 2

[06:17 AM]: Generating relative expression values to PASA transcripts

Traceback (most recent call last):
  File "/home/linuxbrew/funannotate-1.6.0/bin/funannotate-update.py", line 1946, in <module>
    cmd = [os.path.join(PASA, 'misc_utilities', 'gff3_file_to_proteins.pl'), PASA_gff, genome, 'cDNA']

NameError: name 'genome' is not defined

`

**Comment by nextgenusfs** [comment]
From the bug issue template....

**What command did you issue?**
Copy/paste the command used.

**Logfiles**
Please provide relavent log files of the error.

**Comment by shenweima** [comment]
Command
`/home/linuxbrew/funannotate-1.6.0/funannotate update --gff IWGSC_v1.1_HC_20170706.gff3 --fasta /data2/Fshare/FastaAndIndex/IWGSC_v1.0_bwa/161010_Chinese_Spring_v1.0_pseudomolecules.fasta --species "Triticum aestivum" --pacbio_isoseq /data2/user_data/transcript/PacBioFullLengthcDNA.fasta --cpus 6 -o test --sbt template.sbt`

Logfiles
Sorry, I have deleted it.  the last line in the logfile is `Generating relative expression values to PASA transcripts`

**Comment by shenweima** [comment]
> From the bug issue template....
> 
> **What command did you issue?**
> Copy/paste the command used.
> 
> **Logfiles**
> Please provide relavent log files of the error.

I rerun this command`/home/linuxbrew/funannotate-1.6.0/funannotate update --gff IWGSC_v1.1_HC_20170706.gff3 --fasta /data2/Fshare/FastaAndIndex/IWGSC_v1.0_bwa/161010_Chinese_Spring_v1.0_pseudomolecules.fasta --species "Triticum aestivum" --pacbio_isoseq /data2/user_data/transcript/PacBioFullLengthcDNA.fasta --cpus 6 -o test --sbt template.sbt`
Other error was found:
```
[12:00 AM]: OS: linux2, 28 cores, ~ 791 GB RAM. Python: 2.7.15
[12:00 AM]: Running funannotate v1.6.0-603d2f1
[12:07 AM]: Previous annotation consists of: 107,891 protein coding gene models and 0 non-coding gene models
[12:07 AM]: Aligning long reads to genome with minimap2
Traceback (most recent call last):
  File "/home/linuxbrew/funannotate-1.6.0/bin/funannotate-update.py", line 1894, in <module>
    trinity_transcripts, cleanTranscripts = mapTranscripts(fastaout, long_clean, cleanTranscripts, tmpdir, trinityBAM, allBAM)
  File "/home/linuxbrew/funannotate-1.6.0/bin/funannotate-update.py", line 881, in mapTranscripts
    return trinityCombined, trinityCombinedClean
UnboundLocalError: local variable 'trinityCombined' referenced before assignment
```
Logfle:
[funannotate-update.log](https://github.com/nextgenusfs/funannotate/files/3695123/funannotate-update.log)

**Comment by nextgenusfs** [comment]
Believe this has been fixed, reopen if still an issue in latest release.
