### ISSUE TITLE
augustus: error while loading shared libraries: libboost_iostreams.so.1.60.0

### ISSUE THREAD

**Issue by Homap** [nextgenusfs/funannotate#339]
Hello,

Thank you very much for this great tool.

I am running `funannotate predict` on the Linux system. I first got the following error message and the program crashed:
`[11:25 AM]: ERROR: augustus: error while loading shared libraries: libboost_iostreams.so.1.60.0: cannot open shared object file: No such file or directory is not installed properly for BRAKER (check bam2hints/filterBam compilation)`

I looked through the github page and I found out that I could create a symbolic link of the `script `directory in the `bin` directory in the `augustus `directory and that could make it work. I now get this error but the program **does not** crash and continues as follows:

```
[02:30 PM]: augustus: error while loading shared libraries: libboost_iostreams.so.1.60.0: cannot open shared object file: No such file or directory detected, version seems to be compatible with BRAKER and BUSCO
[02:31 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[02:31 PM]: Genome loaded: 3,465 scaffolds; 1,060,359,000 bp; 7.92% repeats masked
[02:32 PM]: Existing transcript alignments found: fun2/predict_misc/transcript_alignments.gff3
[02:32 PM]: Extracting hints from RNA-seq BAM file using bam2hints
[02:32 PM]: Mapping proteins to genome using Diamond blastx/Exonerate
[02:32 PM]: Using 548,288 proteins as queries
[02:32 PM]: Running Diamond pre-filter search
```
Does this mean the Augustus error was solved or the issue is still remaining to be solved?

Thank you in advance,
Homa

**Comment by hyphaltip** [comment]
Can you do a `ldd augustus` on your augustus executable.
Try this if you have augustus in your path already.   It looks like it is compiled against a library which doesn't exist - depends on how you installed your augustus - if you downloaded it pre-compiled or built it yourself and need to make sure the LD_LIBRARY_PATH has the BOOST library in your LD_LIBRARY_PATH
```
ldd $(which augustus)
```

**Comment by Homap** [comment]
Hi,

This is the output I get when I type `ldd augustus`:
```
-bash-4.1$ ldd augustus                                                         
./augustus: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./augustus)
./augustus: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./augustus)
./augustus: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./augustus)
        linux-vdso.so.1 =>  (0x00007ffdc7ff4000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x0000003321200000)
        libm.so.6 => /lib64/libm.so.6 (0x000000331ee00000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003320a00000)
        libc.so.6 => /lib64/libc.so.6 (0x000000331ea00000)
        /lib64/ld-linux-x86-64.so.2 (0x000000331e600000)

```
Thank you!

**Comment by hyphaltip** [comment]
I think you would be best served by compiling it yourself or check the download version it isn’t matched to your version or Linux I don’t think.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by hyphaltip** [comment]
or install libstd++ package - what operation system/linux version are you using?

**Comment by Homap** [comment]
I work on a remote linux machine with this configuration:  
Linux version 2.6.32-696.30.1.el6.x86_64

I tried another installation of augustus on the machine. It still generates the error for Augustus but it does not stop. It continues and stops at another error. Do you think this error is connected to the fact that augustus is probably not working?

```
Starting job 28358138 ("Predict") on c8-27 at Wed Oct 16 13:20:43 CEST 2019
-------------------------------------------------------
[01:20 PM]: OS: linux2, 32 cores, ~ 66 GB RAM. Python: 2.7.15
[01:20 PM]: Running funannotate v1.6.0-dfd805f
[01:20 PM]: Found training files, will re-use these files:
  --rna_bam fun2/training/funannotate_train.coordSorted.bam
  --pasa_gff fun2/training/funannotate_train.pasa.gff3
  --stringtie fun2/training/funannotate_train.stringtie.gtf
  --transcript_alignments fun2/training/funannotate_train.transcripts.gff3
**[01:20 PM]: ERROR: AUGUSTUS (3.2.2) is not installed properly and this version not work with BUSCO, this is a problem with Augustus compliatation, you may need to compile manually on linux2.**
[01:20 PM]: AUGUSTUS (3.2.2) detected, version seems to be compatible with BRAKER and BUSCO
[01:21 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[01:23 PM]: Genome loaded: 3,465 scaffolds; 1,060,359,000 bp; 7.92% repeats masked
[01:23 PM]: Existing transcript alignments found: fun2/predict_misc/transcript_alignments.gff3
[01:23 PM]: Existing RNA-seq BAM hints found: fun2/predict_misc/hints.BAM.gff
[01:24 PM]: Existing protein alignments found: fun2/predict_misc/protein_alignments.gff3
[01:24 PM]: Filtering PASA data for suitable training set
Traceback (most recent call last):
  File "/projects/cees/in_progress/Pallavi/funannotate/bin/funannotate-predict.py", line 770, in <module>
    totalTrain = lib.selectTrainingModels(PASA_GFF, MaskGenome, os.path.join(args.out, 'predict_misc', 'pasa.training.tmp.f.good.gtf'), FinalTrainingModels)
  File "/projects/cees/in_progress/Pallavi/funannotate/lib/library.py", line 6806, in selectTrainingModels
    with open('aug.blast.txt', 'rU') as blast:
**IOError: [Errno 2] No such file or directory: 'aug.blast.txt'**
```

**Comment by Homap** [comment]
It was version problem with augustus. I installed augustus-3.2.3 and now it is working.

conda install -c bioconda augustus=3.2.3

**Comment by nothingisimpossib** [comment]
conda install -c bioconda augustus=3.2.3
install this version of augustus=3.2.3 will solve the problem
