### ISSUE TITLE
funannotate predict: IOError: [Errno 2] No such file or directory: aug.blast.txt

### ISSUE THREAD

**Issue by Homap** [nextgenusfs/funannotate#345]
Hello,

Thank you again for the great software. I'm running the `funannotate predict` step and every time, I get an error that `aug.blast.txt` does not exist. I don't know how to track down the error. Here is the progress report of `funannotate predict` and the error:
```
Starting job 28419455 ("Predict") on c31-6 at Fri Oct 25 20:44:44 CEST 2019
-------------------------------------------------------
[08:44 PM]: OS: linux2, 40 cores, ~ 66 GB RAM. Python: 2.7.15
[08:44 PM]: Running funannotate v1.6.0-dfd805f
[08:44 PM]: Found training files, will re-use these files:
  --rna_bam fun3/training/funannotate_train.coordSorted.bam
  --pasa_gff fun3/training/funannotate_train.pasa.gff3
  --stringtie fun3/training/funannotate_train.stringtie.gtf
  --transcript_alignments fun3/training/funannotate_train.transcripts.gff3
[08:44 PM]: AUGUSTUS (3.2.3) detected, version seems to be compatible with BRAKER and BUSCO
[08:45 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[08:46 PM]: Genome loaded: 3,465 scaffolds; 1,060,359,000 bp; 9.01% repeats masked
[08:47 PM]: Existing transcript alignments found: fun3/predict_misc/transcript_alignments.gff3
[08:47 PM]: Existing RNA-seq BAM hints found: fun3/predict_misc/hints.BAM.gff
[08:47 PM]: Mapping proteins to genome using Diamond blastx/Exonerate
[08:47 PM]: Using 548,288 proteins as queries
[08:47 PM]: Running Diamond pre-filter search
[09:22 PM]: Found 532,712 preliminary alignments
[12:36 AM]: Exonerate finished: found 8,598 alignments
[12:38 AM]: Filtering PASA data for suitable training set
Traceback (most recent call last):
  File "/projects/cees/in_progress/Pallavi/funannotate/bin/funannotate-predict.py", line 770, i
n <module>
    totalTrain = lib.selectTrainingModels(PASA_GFF, MaskGenome, os.path.join(args.out, 'predict
_misc', 'pasa.training.tmp.f.good.gtf'), FinalTrainingModels)
  File "/projects/cees/in_progress/Pallavi/funannotate/lib/library.py", line 6806, in selectTra
iningModels
    with open('aug.blast.txt', 'rU') as blast:
IOError: [Errno 2] No such file or directory: 'aug.blast.txt'
```
Thank you very much,
All the best,
Homa

**Comment by nextgenusfs** [comment]
Probably a diamond issue as it’s trying to check the training models to make sure they are unique. Please run funannotate test -t rna-seq —cpus 24

See if you get the error when training from the test set.

**Comment by Homap** [comment]
Hi, 

Sorry for my delay. Here is the error I get when I run:
```
./funannotate-test.py --tests 'rna-seq' --cpus 24

Starting job 28454412 ("Predict") on c9-9 at Wed Oct 30 10:55:22 CET 2019
#########################################################
Running funannotate RNA-seq training/prediction unit testing
Downloading: https://osf.io/t7j83/download?version=1 Bytes: 542753017
CMD: funannotate train -i test.softmasked.fa --single rna-seq.illumina.fastq.gz --nanopore_mrna rna-seq.nanopore.fastq.gz -o rna-seq --cpus 24 --jaccard_clip --species Awesome rna
#########################################################
Traceback (most recent call last):
  File "./../../../../Pallavi/funannotate/bin/funannotate-test.py", line 338, in <module>
    runRNAseqTest()
  File "./../../../../Pallavi/funannotate/bin/funannotate-test.py", line 304, in runRNAseqTest
    '--species', "Awesome rna"], tmpdir)    
  File "./../../../../Pallavi/funannotate/bin/funannotate-test.py", line 67, in runCMD
    subprocess.call(cmd, cwd=dir)
  File "/usit/abel/u1/annaru/miniconda3/envs/funannotate/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usit/abel/u1/annaru/miniconda3/envs/funannotate/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usit/abel/u1/annaru/miniconda3/envs/funannotate/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

Thank you for your help,
Homa

**Comment by nextgenusfs** [comment]
Okay, well the test error is related to permissions it seems.

But the original error I think is due to diamond versions.  If the databases in $FUNANNOTATE_DB were created with a different version of diamond than you are running, it will error out (somewhat silently in funannotate) so you won't see the error.  Basically there are different "versions" of diamond databases, named version 1,2,3.  v0.9.10 - v0.9.24 use database version 2, while the newest versions use database version 3.  In the development code I've built a check for this, but likely if you rebuild the databases using `funannotate setup` I think the diamond search should hopefully be fixed. 

I've also recently run into a different diamond problem that I think is specific to Mac OSX, but I'm not entirely sure -- basically diamond search fails due to a compilation error with Apple Clang.

Hopefully you've already got this figured out.

**Comment by nextgenusfs** [comment]
stale, reopen if still an issue.

**Comment by Homap** [comment]
Thank you for your help. I just downloaded the new `funannotate` version and that solved the problem.
