### ISSUE TITLE
Error! Diamond repeat database was created with different version of diamond, please re-run funannotate setup

### ISSUE THREAD

**Issue by jimie0311** [nextgenusfs/funannotate#358]
Hi, 
I am using funannotate v1.7 which was installed as the below. A error wa showed up after running the test. Please give me any suggestions. Thanks.
Jimie
```
conda create -n funannotate phyton=2.7 funannotate
conda activate funannotate
funannotate setup -i all -d data/Liangjunmin/funannotate_db
echo "export FUNANNOTATE_DB=/data/Liangjunmin/funannotate_db" > /data/Liangjunmin/opt/biosoft/miniconda3-for-pb-assembly/envs/funannotate/etc/conda/activate.d/funannotate.sh
echo "unset FUNANNOTATE_DB" > /data/Liangjunmin/opt/biosoft/miniconda3-for-pb-assembly/envs/funannotate/etc/conda/deactivate.d/funannotate.sh

#install genemark-ES#
tar zxf ~/software/gm_et_linux_64.tar.gz -C ~/opt/biosoft/
tar zxf ~/software/gm_et_linux_64.tar.gz -C ~/opt/biosoft/
gzip -dc ~/software/gm_key_64.gz > ~/.gm_key
echo "export GENEMARK_PATH=/data/Liangjunmin/opt/biosoft/gm_et_linux_64/gmes_petap/” > /data/Liangjunmin/opt/biosoft/miniconda3-for-pb-assembly/envs/funannotate/etc/conda/deactivate.d/funannotate.sh 
conda activate funannotate
```
#test the example#
```
(funannotate) Liangjunmin@dell:~/funannotate_db$ funannotate test -t all --cpus 12
#########################################################
Running `funannotate clean` unit testing: minimap2 mediated assembly duplications
Downloading: https://osf.io/8pjbe/download?version=1 Bytes: 252076                                                                           CMD: funannotate clean -i test.clean.fa -o test.exhaustive.fa --exhaustive
#########################################################
-----------------------------------------------
6 input contigs, 6 larger than 500 bp, N50 is 427,039 bp
Checking duplication of 6 contigs
-----------------------------------------------
scaffold_91 appears duplicated: 100% identity over 100% of the contig. contig length: 8858
scaffold_73 appears duplicated: 100% identity over 100% of the contig. contig length: 15153
scaffold_27 appears duplicated: 100% identity over 100% of the contig. contig length: 427039
-----------------------------------------------
6 input contigs; 6 larger than 500 bp; 3 duplicated; 3 written to file
#########################################################
SUCCESS: `funannotate clean` test complete.
#########################################################

#########################################################
Running `funannotate mask` unit testing: RepeatModeler --> RepeatMasker
Downloading: https://osf.io/hbryz/download?version=1 Bytes: 375687                                                            CMD: funannotate mask -i test.fa -o test.masked.fa --cpus 12
#########################################################
-------------------------------------------------------
[02:21 PM]: OS: linux2, 160 cores, ~ 1056 GB RAM. Python: 2.7.15
[02:21 PM]: Running funanotate v1.7.1
[02:21 PM]: Soft-masking simple repeats with tantan
[02:21 PM]: Repeat soft-masking finished: 
Masked genome: /data/Liangjunmin/funannotate_db/test-mask_157068/test.masked.fa
num scaffolds: 2
assembly size: 1,216,048 bp
masked repeats: 50,965 bp (4.19%)
-------------------------------------------------------
#########################################################
SUCCESS: `funannotate mask` test complete.
#########################################################

#########################################################
Running `funannotate predict` unit testing                                                                                                                        CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --augustus_species saccharomyces --cpus 12 --species Awesome testicus]]]]]]]]]]]]#########################################################
-------------------------------------------------------
[02:21 PM]: OS: linux2, 160 cores, ~ 1056 GB RAM. Python: 2.7.15
[02:21 PM]: Running funannotate v1.7.1
[02:21 PM]: Diamond repeat database was created with different version of diamond, please re-run funannotate setup
#########################################################
Traceback (most recent call last):
  File "/data/Liangjunmin/opt/biosoft/miniconda3_for_pb-assembly/envs/funannotate/bin/funannotate", line 657, in <module>
    main()
  File "/data/Liangjunmin/opt/biosoft/miniconda3_for_pb-assembly/envs/funannotate/bin/funannotate", line 647, in main
    mod.main(arguments)
  File "/data/Liangjunmin/opt/biosoft/miniconda3_for_pb-assembly/envs/funannotate/lib/python2.7/site-packages/funannotate/test.py", line 389, in main
    runPredictTest(args)
  File "/data/Liangjunmin/opt/biosoft/miniconda3_for_pb-assembly/envs/funannotate/lib/python2.7/site-packages/funannotate/test.py", line 152, in runPredictTest
    tmpdir, 'annotate', 'predict_results', 'Awesome_testicus.gff3')) <= 1800
  File "/data/Liangjunmin/opt/biosoft/miniconda3_for_pb-assembly/envs/funannotate/lib/python2.7/site-packages/funannotate/test.py", line 40, in countGFFgenes
    with open(input, 'rU') as f:
IOError: [Errno 2] No such file or directory: 'test-predict_157068/annotate/predict_results/Awesome_testicus.gff3'
```

# output of `funannotate check --show-versions
```
Checking dependencies for 1.7.1
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.68
goatools: 0.9.9
matplotlib: 2.2.4
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.6.7
requests: 2.22.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed


You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/data/Liangjunmin/funannotate_db
$PASAHOME=/data/Liangjunmin/opt/biosoft/miniconda3_for_pb-assembly/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/data/Liangjunmin/opt/biosoft/miniconda3_for_pb-assembly/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/data/Liangjunmin/opt/biosoft/miniconda3_for_pb-assembly/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/data/Liangjunmin/opt/biosoft/miniconda3_for_pb-assembly/envs/funannotate/config/
$GENEMARK_PATH=/data/Liangjunmin/opt/biosoft/gm_et_linux_64/gmes_petap/
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.1
blat: BLAT v36
diamond: 0.9.14
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 11.0.1
kallisto: 0.46.1
mafft: v7.455 (2019/Dec/7)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.12
pslCDnaFilter: no way to determine
salmon: salmon 0.15.0
samtools: samtools 1.9
snap: 2006-07-28
stringtie: 2.0
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: emapper.py not installed
	ERROR: gmes_petap.pl not installed
	ERROR: signalp not installed
```

**Comment by nextgenusfs** [comment]
Others users have said that `funannotate setup --force -i all` is not deleting the diamond databases, so for right now upi can do this manually and then re-run funannotate setup, i.e.
```
rm $FUNANNOTE_DB/*.dmnd
funannotate setup -i all --force
```
That should rebuild the databases with the version of diamond you have installed. 

Also -- if you have not done so already you probably will need to change the shebang line for all perl scripts in genemark from `/usr/bin/perl` to `/usr/bin/env perl`.

**Comment by jimie0311** [comment]
Thanks for your quick reply. I already solved.

conda install -n funannotate diamond=0.9.19
funannotate setup -i all

2019-12-18 


Junmin Liang (Tel: +86 64806139)
State Key Laboratory of Mycology
Institute of Microbiology, Chinese Academy of Sciences
No. 1 Beichen West Road, Chaoyang District, Beijing, China



发件人：Jon Palmer <notifications@github.com>
发送时间：2019-12-17 23:02
主题：Re: [nextgenusfs/funannotate] Error! Diamond repeat database was created with different version of diamond, please re-run funannotate setup (#358)
收件人："nextgenusfs/funannotate"<funannotate@noreply.github.com>
抄送："jimie0311"<junminliang0311@163.com>,"Author"<author@noreply.github.com>

Others users have said that funannotate setup --force -i all is not deleting the diamond databases, so for right now upi can do this manually and then re-run funannotate setup, i.e.
rm $FUNANNOTE_DB/*.dmnd
funannotate setup -i all --force

That should rebuild the databases with the version of diamond you have installed.
Also -- if you have not done so already you probably will need to change the shebang line for all perl scripts in genemark from /usr/bin/perl to /usr/bin/env perl.
