### ISSUE TITLE
funannotate setup exit without download database

### ISSUE THREAD

**Issue by DomeJoyce** [nextgenusfs/funannotate#380]
Hi, I installed via conda.
Then following the full guide I'm stacked at importing the database.

Here the command:

funannotate setup -d /home/software/funannotate_db
-------------------------------------------------------
[06:08 PM]: OS: linux2, 40 cores, ~ 330 GB RAM. Python: 2.7.15
[06:08 PM]: Running 1.7.2
[06:08 PM]: Database location: /home/software/funannotate_db
[06:08 PM]: Parsing Augustus pre-trained species and porting to funannotate
[06:08 PM]: Downloading Merops database
Traceback (most recent call last):
  File "/home/software/anaconda3/envs/funannotate/bin/funannotate", line 657, in <module>
    main()
  File "/home/software/anaconda3/envs/funannotate/bin/funannotate", line 647, in main
    mod.main(arguments)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 652, in main
    meropsDB(DatabaseInfo, args.force, args=args)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 112, in meropsDB
    download(resources.DBURL.get('merops'), fasta)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 66, in download
    u = urllib2.urlopen(url)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/urllib2.py", line 1413, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/urllib2.py", line 1435, in connect_ftp
    persistent=False)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/urllib.py", line 877, in __init__
    self.init()
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/urllib.py", line 886, in init
    self.ftp.connect(self.host, self.port, self.timeout)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/ftplib.py", line 135, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/socket.py", line 575, in create_connection
    raise err
urllib2.URLError: <urlopen error ftp error: [Errno 110] Connection timed out>

and then i run also the following:

`funannotate setup -d $HOME/funannotate_db
-------------------------------------------------------
[06:03 PM]: OS: linux2, 40 cores, ~ 330 GB RAM. Python: 2.7.15
[06:03 PM]: Running 1.7.2
[06:03 PM]: Database location: /home/domenico/funannotate_db
[06:03 PM]: Parsing Augustus pre-trained species and porting to funannotate
Traceback (most recent call last):
  File "/home/software/anaconda3/envs/funannotate/bin/funannotate", line 657, in <module>
    main()
  File "/home/software/anaconda3/envs/funannotate/bin/funannotate", line 647, in main
    mod.main(arguments)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 652, in main
    meropsDB(DatabaseInfo, args.force, args=args)
  File "/home/software/anaconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 132, in meropsDB
    type, name, version, date, records, checksum = info.get('merops')
TypeError: 'NoneType' object is not iterable`

And this is appening for all the -i *db I'm trying to download.

Can you please help me to fix it?

Many thanks,

Domenico

**OS/Install Information**
 funannotate check --show-version
-------------------------------------------------------
Checking dependencies for 1.7.2
-------------------------------------------------------
To print all dependencies and versions: funannotate check --show-versions

You are running Python v 2.7.15. Now checking python packages...
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
All 27 Perl modules installed

Checking Environmental Variables...
	ERROR: FUNANNOTATE_DB not set. export FUNANNOTATE_DB=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
All 36 external dependencies are installed

**Comment by hyphaltip** [comment]
Did you try setting the end variable as the error mentions?

We Do need to check why -d isn’t succeeding if the env is not set.

Environmental Variables...
ERROR: FUNANNOTATE_DB not set. export FUNANNOTATE_DB=/path/

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by euduca** [comment]
Hi @DomeJoyce,

I had to install funannotate on another server because (I don't know why) my university blocks ftp access from some locations.

So, luckily for me, I have access to another HPC at another university.
I ran the command "funannotate setup" and, in the end, transferred all the folders / files, using SCP, to my "FUNANNOTATE_DB" folder (in my server).  

Best,

Duca.

**Comment by nextgenusfs** [comment]
If the downloads are failing due to proxy issues there is also the -w option which will use wget instead of the python requests module- it’s easier to configure your proxy settings with wget.

**Comment by DomeJoyce** [comment]
thank you for the fast answer.
After i added the funannotate_db at path/../envs/funannotate/etc/conda/activate.d and ../conda/deactivate.d and after i used the -w flag, it worked perfectly.

Many thanks,

Domenico
