### ISSUE TITLE
funannotate 1.8.0 (python3) - checkAugustusFunc() fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by TomHarrop** [nextgenusfs/funannotate#387]
**Are you using the latest release?**

I'm trying to use funannotate 1.8.0 from the python3 branch (commit 8e2e0a1) inside a singularity container. I installed funannotate inside the container with `pip3 install git+git://github.com/nextgenusfs/funannotate.git@8e2e0a1`. 

**Describe the bug**

- running `funannotate predict` fails at `checkAugustusFunc()` with `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 80: ordinal not in range(128)`
- `augustus` seems to be installed fine, but funannotate check fails (see log)
- directly running the augustus command that `checkAugustusFunc()` uses seems to work fine inside the container:

```
$ augustus --species=anidulans --proteinprofile=/usr/local/lib/python3.5/dist-packages/funannotate/config/EOG092C0B3U.prfl /usr/local/lib/python3.5/dist-packages/funannotate/config/busco_test.fa

# This output was generated with AUGUSTUS (version 3.3.3).
# AUGUSTUS is a gene prediction tool written by M. Stanke (mario.stanke@uni-greifswald.de),
# O. Keller, S. König, L. Gerischer, L. Romoth and Katharina Hoff.
# Please cite: Mario Stanke, Mark Diekhans, Robert Baertsch, David Haussler (2008),
# Using native and syntenically mapped cDNA alignments to improve de novo gene finding
# Bioinformatics 24: 637-644, doi 10.1093/bioinformatics/btn013
# No extrinsic information on sequences given.
# Initializing the parameters using config directory /opt/augustus-3.3.3/config/ ...
Warning: Block unknown_E is not significant enough, removed from profile.
Warning: Block unknown_F is not significant enough, removed from profile.
Warning: Block unknown_H is not significant enough, removed from profile.
Warning: Block unknown_AC is not significant enough, removed from profile.
# Using protein profile unknown
# --[0..117]--> unknown_A (9) <--[2..25]--> unknown_B (27) <--[1..16]--> unknown_C (8) <--[0..1]--> unknown_D (15) <--[18..100]--> unknown_G (19) <--[8..25]--> unknown_I (32) <--[0..1]--> unknown_J (33) <--[1..16]--> unknown_K (38) <--[1..3]--> unknown_L (14) <--[0..5]--> unknown_M (59) <--[0..19]--> unknown_N (23) <--[0..145]--> unknown_O (23) <--[3..18]--> unknown_P (27) <--[1..44]--> unknown_Q (12) <--[10..82]--> unknown_R (13) <--[10..106]--> unknown_S (18) <--[1..11]--> unknown_T (32) <--[2..5]--> unknown_U (12) <--[0..1]--> unknown_V (32) <--[7..18]--> unknown_W (13) <--[3..8]--> unknown_X (87) <--[0..1]--> unknown_Y (12) <--[2..33]--> unknown_Z (40) <--[0..11]--> unknown_AA (16) <--[3..30]--> unknown_AB (19) <--[8..47]--> unknown_AD (23) <--[0..1]--> unknown_AE (13) <--[0..38]--
# anidulans version. Using default transition matrix.
# Looks like /usr/local/lib/python3.5/dist-packages/funannotate/config/busco_test.fa is in fasta format.
# We have hints for 0 sequences and for 0 of the sequences in the input set.
#
# ----- prediction on sequence number 1 (length = 3801, name = example) -----
#
# Predicted genes for sequence number 1 on both strands
# start gene g1
example AUGUSTUS    gene    788 3077    0.88    +   .   g1
example AUGUSTUS    transcript  788 3077    0.88    +   .   g1.t1
example AUGUSTUS    start_codon 788 790 .   +   0   transcript_id "g1.t1"; gene_id "g1";
example AUGUSTUS    CDS 788 996 1   +   0   transcript_id "g1.t1"; gene_id "g1";
example AUGUSTUS    CDS 1049    3077    0.88    +   1   transcript_id "g1.t1"; gene_id "g1";
example AUGUSTUS    stop_codon  3075    3077    .   +   0   transcript_id "g1.t1"; gene_id "g1";
# protein sequence = [MDISDLIEPPQKRLKTEDISSADEVVLPAGGITPQTDNEIDEQLSKEIEVGITEFVSADNEGFAGILKKRYTDFLVNE
# ILPSGKVLHLTNTTAPNTNDEATPVQADKKPAEDKPKEPETPAEKLPAPVEFQLAEEDEALLDTLFGTQNTKKIVALHKKALANPKTKPSDLGRLNTV
# VVNDRDQRIKMHQAIRRIFNSQIESSTDSEGMMVISVAANRNKKNPQGGGGGRERPRVNWDELGGQYLHFTIYKENKDTMEVISFIARQLKMNPKSFQ
# FAGTKDRRGVTVQRACAYRLQADRLAKLNRTLRNAVVGDFEYQPHGLELGDLYGNEFVVTLRECEVPGINIQDPASAVAKTKELVNTSLKNLYQRGYF
# NYYGLQRFGSFATRTDTVGVKILQDDFKGACDAILDYSPHILAAAQAELGQGEGEGATPTNISSEDKARALAIHIFRTTDRVTDALEKMPRKFSAESN
# IIRHLGRSKNDYLGALQTIPRNLRLMYVHAYQSLVWNLAVGERWRLYGDRVVEGDLVLIHEHRDKDGNSSYTTPAPGAGASGETTTIDADGEIIIVPQ
# EHDSAFAVEDTFTRARALTAAEANSGLYSIFDIVLPLPGFDVLYPPNKMTDFYKEFMGSSRGGGLDPFNMRRKWKDASLSGSYRKVLSRMGRDYSVDV
# VLYSRDEEQFVRTDLENLTLKTRDGGDVDLEKKEGKSEGDKLAVVLKFQLGSSQYATMALRELMRGKVKAYKPDFGGGR]
# end gene g1
###
# command line:
# augustus --species=anidulans --proteinprofile=/usr/local/lib/python3.5/dist-packages/funannotate/config/EOG092C0B3U.prfl /usr/local/lib/python3.5/dist-packages/funannotate/config/busco_test.fa
```

**What command did you issue?**

```
funannotate predict \
    -i /path/to/output/010_prepare/repeatmasker/asw-cleaned_sorted.fasta.masked \
    -s ASW \
    --transcript_evidence data/Trinity.fasta \
    -o /path/to/output/020_funannotate \
    -d /path/to/data/funannotate_db/fundb_20200227 \
    --cpus 60 
    --augustus_species lbonariensis \
    --busco_seed_species tribolium2012 \
    --busco_db endopterygota \
    --organism other \
    --repeats2evm \
    --max_intronlen 10000
```

**Logfiles**

```
-------------------------------------------------------
[02:17 PM]: OS: debian 9.12, 144 cores, ~ 1056 GB RAM. Python: 3.5.3
[02:17 PM]: Running funannotate v1.8.0
[02:17 PM]: Found training files, will re-use these files:
  --rna_bam /Volumes/archive/deardenlab/tomharrop/projects/asw-annotate/output/020_funannotate/training/funannotate_train.coordSorted.bam
  --pasa_gff /Volumes/archive/deardenlab/tomharrop/projects/asw-annotate/output/020_funannotate/training/funannotate_train.pasa.gff3
  --transcript_alignments /Volumes/archive/deardenlab/tomharrop/projects/asw-annotate/output/020_funannotate/training/funannotate_train.transcripts.gff3
[02:17 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     pasa           
  genemark     selftraining   
  glimmerhmm   pasa           
  snap         pasa           
Traceback (most recent call last):
  File "/usr/local/bin/funannotate", line 658, in <module>
    main()
  File "/usr/local/bin/funannotate", line 648, in main
    mod.main(arguments)
  File "/usr/local/lib/python3.5/dist-packages/funannotate/predict.py", line 536, in main
    augustus_version, augustus_functional = lib.checkAugustusFunc()
  File "/usr/local/lib/python3.5/dist-packages/funannotate/library.py", line 970, in checkAugustusFunc
    stdout=subprocess.PIPE, universal_newlines=True).communicate()
  File "/usr/lib/python3.5/subprocess.py", line 788, in communicate
    stdout = self.stdout.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 80: ordinal not in range(128)
```

**OS/Install Information**

```
$ augustus --version
AUGUSTUS (3.3.3) is a gene prediction tool
written by M. Stanke, O. Keller, S. König, L. Gerischer and L. Romoth.
```
 
(`salmon` and `trimmomatic` are both installed but are failing `check`.)

```
-------------------------------------------------------
Checking dependencies for 1.8.0
-------------------------------------------------------
You are running Python v 3.5.3. Now checking python packages...
biopython: 1.76
goatools: 1.0.2
matplotlib: 3.0.3
natsort: 7.0.1
numpy: 1.18.1
pandas: 0.25.3
psutil: 5.7.0
requests: 2.12.4
scikit-learn: 0.22.1
scipy: 1.4.1
seaborn: 0.9.1
All 11 python packages installed


You are running Perl v b'5.024001'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.40
Clone: 0.38
DBD::SQLite: 1.54
DBD::mysql: 4.041
DBI: 1.636
DB_File: 1.835
Data::Dumper: 2.160
File::Basename: 2.85
File::Which: 1.21
Getopt::Long: 2.48
Hash::Merge: 0.200
JSON: 2.90
LWP::UserAgent: 6.15
Logger::Simple: 2.0
POSIX: 1.65
Parallel::ForkManager: 1.19
Pod::Usage: 1.68
Scalar::Util::Numeric: 0.40
Storable: 2.56_01
Text::Soundex: 3.04
Thread::Queue: 3.09
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.21
threads: 2.07
threads::shared: 1.51
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/funannotate_db
$PASAHOME=/pasa
$TRINITYHOME=/usr/bin
$EVM_HOME=/evm
$AUGUSTUS_CONFIG_PATH=/opt/augustus-3.3.3/config
$GENEMARK_PATH=/genemark
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
    ERROR: augustus found but error running augustus
version : 0.7.2
PASA: 2.3.3
CodingQuarry: 2.0
Trinity: Trinity version: v2.2.0
bamtools: bamtools 2.4.1
bedtools: bedtools v2.26.0
blat: BLAT v36x5
diamond: 0.9.22
emapper.py: 8fc976e
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-01-14
gmes_petap.pl: 4.48_3.60_lic
hisat2: 2.0.5
hmmscan: HMMER 3.1b2 (February 2015)
hmmsearch: HMMER 3.1b2 (February 2015)
java: 1.8.0_242
kallisto: 0.46.0
mafft: v7.307 (2017/Jan/6)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.15-r905
pslCDnaFilter: no way to determine
samtools: samtools 1.3.1
snap: 2006-07-28
stringtie: 1.3.6
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
    ERROR: augustus not installed
    ERROR: proteinortho not installed
    ERROR: salmon not installed
    ERROR: signalp not installed
    ERROR: trimmomatic not installed
```

**Comment by nextgenusfs** [comment]
Thanks @TomHarrop  - that branch is not quite ready yet, it was working in py3 and I was in the process of going back and trying to make it py2/py3 compatible (which is a huge unicode pain in the a$$).  Perhaps I should abandon py2 compatibility all together.  Certainly would accept PRs!

**Comment by TomHarrop** [comment]
Yep, gotcha. I'll see if I can work this issue out and send a PR if I do. Meanwhile I'll keep working on getting a py2 container up and running.

One thing I was confused about in the deps - of the following, which do I have to install for py2, and which are safe to install with py3?

```
        biopython 
        ete3 
        goatools 
        lxml 
        matplotlib 
        natsort 
        numpy 
        pandas
        psutil 
        PyQt5
        QtPy 
        requests 
        scikit-learn 
        scipy 
        seaborn 
        six
```
(e.g. I know I can install PyQt5 with pip3, using the py2 version of funannotate, but I presume bioipython, numpy, pandas etc. will need the py2 versions?)

**Comment by hyphaltip** [comment]
Hi Tom
 We also have a singularity container box Jordan in our Hpc group has been working on. If that helps.
https://github.com/jdhayes/funbox

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by TomHarrop** [comment]
Thanks, mine is [here](https://github.com/TomHarrop/funannotate-singularity) if you want to compare. `conda install` didn't work for me so I'm building from the [Dfam TE tools](https://github.com/Dfam-consortium/TETools) container.

**Comment by nextgenusfs** [comment]
@TomHarrop per the dependencies -- I think the problem with the Conda recipe on some systems was the `ete3` package.  As of the latest conda release/build (python2 v1.7.4), I removed `ete3` as a dependency.  It is only used in `funannotate compare` if you run `--run_dnds` option.  Does the conda install work in your container with v1.7.4?

And I think I'm going to forge ahead with the py3 not being compatible with py2.7 -- it is very close, but I just don't have the time.  In terms of functionality there won't be much difference initially between v1.8.0 (py3) and v1.7.4 (py2) - so users should still be able to install a version that can work with their setup (I hope).

**Comment by nextgenusfs** [comment]
@TomHarrop I've tried with python 3.5.5, python 3.6.7, and python 3.7.6 with the current python3 branch running Augustus 3.2.1 and I don't see this `UnicodeDecodeError`.  I'm also on macOS, but that shouldn't matter I don't think.... I'm not sure what to fix.

**Comment by TomHarrop** [comment]
OK, thanks for looking into it. The TE-tools Docker container uses Debian stretch, which is why I have a 5-year-old `python3` in my container. I'll see if I can get 3.6 or 3.7 in there and let you know if that solves the issue.

I tried `conda install funannotate=1.7.4` with miniconda 4.7.12. It thought about it for about half and hour but didn't find a solution.

**Comment by nextgenusfs** [comment]
This builds fine for me on `docker`:
```
FROM continuumio/miniconda3:latest

RUN conda config --add channels defaults && conda config --add channels bioconda &&\
	conda config --add channels conda-forge && conda update -n base -c defaults conda

RUN conda create -n funannotate --yes "funannotate=1.7.4" && conda clean -afy

ENTRYPOINT ["bash"]
```

**Comment by nextgenusfs** [comment]
And here is a working version with install of the databases.
```
FROM continuumio/miniconda3:latest

RUN conda config --add channels defaults && conda config --add channels bioconda &&\
	conda config --add channels conda-forge && conda update -n base -c defaults conda

RUN conda create -n funannotate --yes "funannotate=1.7.4" && conda clean -afy

ENV FUNANNOTATE_DB=/home/funannotate_db

RUN mkdir -p /home/funannotate_db

RUN echo "source activate funannotate" > ~/.bashrc

SHELL ["conda", "run", "-n", "funannotate", "/bin/bash", "-c"]

RUN funannotate setup -i all 
```

**Comment by TomHarrop** [comment]
Thanks for your efforts on this. I'm testing that conda recipe with a singularity container. I can't get `conda install` to work, and it's a bit of a wrestle to get conda to activate inside a singularity container when you run it with `singularity exec`, but it seems to be working.

```
$ singularity run funannotate-conda_1.7.4.sif 
-------------------------------------------------------
Checking dependencies for 1.7.4
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 1.0.2
matplotlib: 2.2.4
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.23.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed


You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/home/funannotate_db
$PASAHOME=/opt/conda/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/opt/conda/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/opt/conda/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/opt/conda/envs/funannotate/config/
$GENEMARK_PATH=/genemark
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
emapper.py: 593db3c
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.48_3.60_lic
hisat2: 2.1.0
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 11.0.1-internal
kallisto: 0.46.2
mafft: v7.455 (2019/Dec/7)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.14
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.9
snap: 2006-07-28
stringtie: 2.1.1
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: ete3 not installed
	ERROR: signalp not installed
```

Would there be any interest in including it in the funannotate repo as a Dockerfile, so it can be built automatically when you release a new version? I can do a PR if you think that's useful.

**Comment by nextgenusfs** [comment]
If we can have a Dockerfile that will autobuild when a new release is tagged and doesn't require me to build/troubleshoot then yes I'm interested in adding it.  I used to have one, but it was too much work for me to maintain in the format I had it in -- I don't use docker/singularity currently so I'm not very good at it.  Generally I find for something like funannotate it doesn't work particularily well due to the large size of resources that are required (ie databases are large, and you also want a system that has InterProScan and EggNog Mapper to use all of its functionality, which are very large for containers).
