### ISSUE TITLE
InterProScan fails;  too few genes/products annotations; antiSMASH parser fails; funannotate compare fails

### ISSUE THREAD

**Issue by gskrasnov** [nextgenusfs/funannotate#412]
Dear John,

I have launched funannotate pipeline to annotate Fusarium Oxysporum genome, and I encountered several issues. I would like to describe them consequentially.

**First,** InterProScan fails:

`funannotate iprscan --input train.results --method docker --cpus 64 `

Log:
```
Running InterProScan5 on 19321 proteins
Downloading InterProScan Docker images:
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.32/info: dial unix /var/run/docker.sock: connect: permission denied). Using system default: https://index.docker.io/v1/
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.32/images/create?fromImage=blaxterlab%2Finterproscan&tag=latest: dial unix /var/run/docker.sock: connect: permission denied
Docker InterProScan container is ready.
Downloading: https://raw.githubusercontent.com/ebi-pf-team/interproscan/5.22-61.0/core/jms-implementation/support-mini-x86-32/interproscan.properties Bytes: 12090                                       PrTraceback (most recent call last):
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/iprscan-local.py", line 361, in <module>
    combine_xml(final_list, finalOut)
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/iprscan-local.py", line 54, in combine_xml
    tree.write(output, encoding='utf-8', xml_declaration=True)
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/lib/python2.7/xml/etree/ElementTree.py", line 817, in write
    self._root, encoding, default_namespace
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/lib/python2.7/xml/etree/ElementTree.py", line 876, in _namespaces
    iterate = elem.getiterator # cET compatibility
AttributeError: 'NoneType' object has no attribute 'getiterator'
```

******************************************

**Second,** there are too few gene products annotations (maybe incorrect UniProt file?)

`funannotate annotate --input train.results --cpus 64 --sbt FOxy.sbt --species "Fusarium oxysporum" --strain 39`

Log:
```
[01:02 PM]: OS: linux2, 64 cores, ~ 1057 GB RAM. Python: 2.7.15
[01:02 PM]: Running 1.7.4
[01:02 PM]: Found existing output directory train.results. Warning, will re-use any intermediate files found.
[01:02 PM]: Parsing input files
[01:02 PM]: Existing tbl found: train.results/update_results/Fusarium_oxysporum_39.tbl
[01:03 PM]: Adding Functional Annotation to Fusarium oxysporum, NCBI accession: None
[01:03 PM]: Annotation consists of: 19,351 gene models
[01:03 PM]: 19,321 protein records loaded
[01:03 PM]: Existing Pfam-A results found: train.results/annotate_misc/annotations.pfam.txt
[01:03 PM]: 19,718 annotations added
[01:03 PM]: Running Diamond blastp search of UniProt DB version 2020_01
[01:03 PM]: 1,032 valid gene/product annotations from 1,421 total
[01:03 PM]: Existing Eggnog-mapper results found: train.results/annotate_misc/eggnog.emapper.annotations
[01:03 PM]: Parsing EggNog Annotations
[01:03 PM]: 12,423 COG and EggNog annotations added
[01:03 PM]: Combining UniProt/EggNog gene and product names using Gene2Product version 1.55
[01:03 PM]: 1,032 gene name and product description annotations added
[01:03 PM]: Existing MEROPS results found: train.results/annotate_misc/annotations.merops.txt
[01:03 PM]: 539 annotations added
[01:03 PM]: Existing CAZYme results found: train.results/annotate_misc/annotations.dbCAN.txt
[01:03 PM]: 1,357 annotations added
[01:03 PM]: Existing BUSCO2 results found: train.results/annotate_misc/annotations.busco.txt
[01:03 PM]: 1,334 annotations added
[01:03 PM]: Skipping phobius predictions, try funannotate remote -m phobius
[01:03 PM]: Existing SignalP results found: train.results/annotate_misc/signalp.results.txt
[01:03 PM]: 1,744 secretome and 0 transmembane annotations added
[01:03 PM]: Parsing InterProScan5 XML file
[01:03 PM]: Now parsing antiSMASH v5 results, finding SM clusters
[01:03 PM]: Found 51 clusters, 117 biosynthetic enyzmes, and 204 smCOGs predicted by antiSMASH
[01:03 PM]: Found 0 duplicated annotations, adding 40,159 valid annotations
[01:03 PM]: Converting to final Genbank format, good luck!
[01:06 PM]: Creating AGP file and corresponding contigs file
[01:06 PM]: Cross referencing SM cluster hits with MIBiG database version 1.4
[01:06 PM]: Creating tab-delimited SM cluster output
[01:07 PM]: Writing genome annotation table.
[01:07 PM]: Funannotate annotate has completed successfully!
```

Hence, there are only 1,032 gene/product annotations (total 19,321 protein records)

******************************************

**Third,** antiSMASH parser fails for contig named "C0758_mito"

` funannotate annotate --input train.results --cpus 64 --sbt FOxy.sbt --species "Fusarium oxysporum" --strain 39`

Log:

```
[12:59 PM]: OS: linux2, 64 cores, ~ 1057 GB RAM. Python: 2.7.15
[12:59 PM]: Running 1.7.4
[12:59 PM]: Found existing output directory train.results. Warning, will re-use any intermediate files found.
[12:59 PM]: Parsing input files
[12:59 PM]: Existing tbl found: train.results/update_results/Fusarium_oxysporum_39.tbl
[12:59 PM]: Adding Functional Annotation to Fusarium oxysporum, NCBI accession: None
[12:59 PM]: Annotation consists of: 19,351 gene models
[12:59 PM]: 19,321 protein records loaded
[12:59 PM]: Existing Pfam-A results found: train.results/annotate_misc/annotations.pfam.txt
[12:59 PM]: 19,718 annotations added
[12:59 PM]: Running Diamond blastp search of UniProt DB version 2020_01
[01:00 PM]: 1,032 valid gene/product annotations from 1,421 total
[01:00 PM]: Existing Eggnog-mapper results found: train.results/annotate_misc/eggnog.emapper.annotations
[01:00 PM]: Parsing EggNog Annotations
[01:00 PM]: 12,423 COG and EggNog annotations added
[01:00 PM]: Combining UniProt/EggNog gene and product names using Gene2Product version 1.55
[01:00 PM]: 1,032 gene name and product description annotations added
[01:00 PM]: Existing MEROPS results found: train.results/annotate_misc/annotations.merops.txt
[01:00 PM]: 539 annotations added
[01:00 PM]: Existing CAZYme results found: train.results/annotate_misc/annotations.dbCAN.txt
[01:00 PM]: 1,357 annotations added
[01:00 PM]: Existing BUSCO2 results found: train.results/annotate_misc/annotations.busco.txt
[01:00 PM]: 1,334 annotations added
[01:00 PM]: Skipping phobius predictions, try funannotate remote -m phobius
[01:00 PM]: Existing SignalP results found: train.results/annotate_misc/signalp.results.txt
[01:00 PM]: 1,744 secretome and 0 transmembane annotations added
[01:00 PM]: Parsing InterProScan5 XML file
[01:00 PM]: Now parsing antiSMASH v5 results, finding SM clusters
Traceback (most recent call last):
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/lib/python2.7/site-packages/funannotate/annotate.py", line 928, in main
    AntiSmashBed, AntiSmash_annotations)
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 6021, in ParseAntiSmash
    numericalContig = int(record.id.rsplit('_', 1)[-1])
ValueError: invalid literal for int() with base 10: 'mito'
```

Contig name is "C0758_mito"

******************************************

**Fourth,** funannotate compare fails:

`funannotate compare -i train.results --cpus 64`

Log:
```
[01:43 PM]: OS: linux2, 64 cores, ~ 1057 GB RAM. Python: 2.7.15
[01:43 PM]: Running 1.7.4
[01:44 PM]: Now parsing 1 genomes
[01:44 PM]: working on Fusarium oxysporum 39
[01:45 PM]: Summarizing secondary metabolism gene clusters
[01:45 PM]: Summarizing PFAM domain results
[01:45 PM]: Summarizing InterProScan results
[01:45 PM]: Loading InterPro descriptions
[01:45 PM]: Summarizing MEROPS protease results
[01:45 PM]: Summarizing CAZyme results
[01:45 PM]: No COG annotations found
[01:45 PM]: Summarizing secreted protein results
Traceback (most recent call last):
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/lib/python2.7/site-packages/funannotate/compare.py", line 688, in main
    args.out, 'signalp', 'signalp.pdf'))
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 6834, in drawbarplot
    fig = plt.figure()
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/lib/python2.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/lib/python2.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/mnt/raid/illumina/geo/progs/miniconda/envs/funannotate/lib/python2.7/lib-tk/Tkinter.py", line 1819, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

I run funannotate at remote server via SSH

I placed the annotation folder here - [http://85.89.102.15/temp/Annotation/train.results/](http://85.89.102.15/temp/Annotation/train.results/)

Thank you in advance,
George

**Comment by nextgenusfs** [comment]
1. IPRscan data -- it looks like you were unable to pull the docker image perhaps due to proxy issues?  Or the docker image is gone?  I have not tried in awhile.

2. too many hypothetical proteins -- I've answer this several times, this is by design. https://github.com/nextgenusfs/funannotate/issues/295

3. you should remove mitochondrial contigs, they cannot be annotated with funannotate.  But that error is not related to that.  I will make a note, but its trying to parse the antiSMASH results which renames the clusters.  changing that contig name would be the immediate fix (but remove mitochondrial contigs if that is what that is).

4. This looks like a Matplotlib error -- not exactly sure why as I haven't seen this one yet.

**Comment by mswyers** [comment]
1. The docker fail is because you've installed docker but didn't give it permissions, so it isn't pulling the image properly.

You need to create the docker group and add your user to that docker group before running iprscan.

$ sudo groupadd docker

$ sudo usermod -aG docker {username}
