### ISSUE TITLE
funannotate compare: numpy error. cannot convert float NaN to integer

### ISSUE THREAD

**Issue by peterthorpe5** [nextgenusfs/funannotate#431]
**Are you using the latest release?**
yes: version:     1.7.4. Installed using conda. 29th May 2020

**Describe the bug**
n = int(2 ** np.ceil((eta2 - eta1) / halfpi))
ValueError: cannot convert float NaN to integer

**What command did you issue?**
funannotate compare -i GPALLINDL_Lindley.gbk Gpal_newton_newton.gbk --database ./databases/ --run_dnds full -o newton_vs_lind2
**Logfiles**
[06/03/20 19:44:18]: /home/pjt6/Desktop/pjt6/conda/envs/funannotate/bin/funannotate compare -i GPALLINDL_Lindley.gbk Gpal_newton_newton.gbk --database ./databases/ --run_dnds full -o newton_vs_lind2

[06/03/20 19:44:18]: OS: linux2, 8 cores, ~ 16 GB RAM. Python: 2.7.15
[06/03/20 19:44:18]: Running 1.7.4
[06/03/20 19:44:21]: Input files/folders: ['GPALLINDL_Lindley.gbk', 'Gpal_newton_newton.gbk']

[06/03/20 19:44:21]: Now parsing 2 genomes
[06/03/20 19:44:28]: working on GPALLINDL
[06/03/20 19:45:09]: working on Gpal_newton
[06/03/20 19:45:40]: No secondary metabolite annotations found
[06/03/20 19:45:40]: Summarizing PFAM domain results
[06/03/20 19:45:41]: Summarizing InterProScan results
[06/03/20 19:45:45]: Loading InterPro descriptions
[06/03/20 19:45:50]: Summarizing MEROPS protease results
[06/03/20 19:45:51]: found 38/114 MEROPS familes with stdev >= 1.000000
[06/03/20 19:45:51]: Summarizing CAZyme results
[06/03/20 19:45:51]: found 25/121 CAZy familes with stdev >= 1.000000
[06/03/20 19:45:52]: Summarizing COG results
**OS/Install Information**
 -  output of `funannotate check --show-versions`
$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.7.4
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.68
goatools: 1.0.5
matplotlib: 2.2.5
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.23.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$PASAHOME=/home/pjt6/Desktop/pjt6/conda/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/pjt6/Desktop/pjt6/conda/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/pjt6/Desktop/pjt6/conda/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/pjt6/Desktop/pjt6/conda/envs/funannotate/config/
	ERROR: FUNANNOTATE_DB not set. export FUNANNOTATE_DB=/path/to/dir
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.0
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 11.0.1-internal
kallisto: 0.46.2
mafft: v7.467 (2020/May/14)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.15.0
samtools: samtools 1.9
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: emapper.py not installed
	ERROR: gmes_petap.pl not installed
	ERROR: signalp not installed

Dear Jon,

As always. Love the tool. I am trying the compare feature. Great stuff, I have it mostly working on another data set. But this fails with "ascii code error" - which you had fixed in the latest relase. So I got the latest. 

However, this fails with numpy at summerising the COG stage. Seee below. Happy to share th efiles, but they are 180MB,

cheers,

Pete

[07:45 PM]: Summarizing COG results
Traceback (most recent call last):
  File "/home/pjt6/Desktop/pjt6/conda/envs/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "/home/pjt6/Desktop/pjt6/conda/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/home/pjt6/Desktop/pjt6/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/compare.py", line 643, in main
    args.out, 'cogs', 'COGS.graph.pdf'))
  File "/home/pjt6/Desktop/pjt6/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 6815, in donutplot
    plt.pie(data[0], labels=names, colors=color_palette)
  File "/home/pjt6/Desktop/pjt6/conda/envs/funannotate/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3343, in pie
    frame=frame, rotatelabels=rotatelabels, data=data)
  File "/home/pjt6/Desktop/pjt6/conda/envs/funannotate/lib/python2.7/site-packages/matplotlib/__init__.py", line 1870, in inner
    return func(ax, *args, **kwargs)
  File "/home/pjt6/Desktop/pjt6/conda/envs/funannotate/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 2911, in pie
    **wedgeprops)
  File "/home/pjt6/Desktop/pjt6/conda/envs/funannotate/lib/python2.7/site-packages/matplotlib/patches.py", line 1070, in __init__
    self._recompute_path()
  File "/home/pjt6/Desktop/pjt6/conda/envs/funannotate/lib/python2.7/site-packages/matplotlib/patches.py", line 1082, in _recompute_path
    arc = Path.arc(theta1, theta2)
  File "/home/pjt6/Desktop/pjt6/conda/envs/funannotate/lib/python2.7/site-packages/matplotlib/path.py", line 874, in arc
    n = int(2 ** np.ceil((eta2 - eta1) / halfpi))
ValueError: cannot convert float NaN to integer

**Comment by peterthorpe5** [comment]
FIXED: The problem was the the two different genomes had been annotated at different times using the online eggnog. So, I re ran those and it is now running. 

cheers, Pete
