### ISSUE TITLE
UnboundLocalError: local variable 'block_size' referenced before assignment

### ISSUE THREAD

**Issue by jguhlin** [nextgenusfs/funannotate#432]
**Are you using the latest release?**
Yes - 1.7.4 from Anaconda

**Describe the bug**
I think the training step is generating a funannotate_train.coordSorted.bam file that is empty:
josephguhlin@biochemcompute1 /V/a/d/g/V/2_rnaseq> ls -lahL VelvetWorm/training/funannotate_train.coordSorted.bam                                                                                                                  (funannotate-new)
-rw-r--r-- 1 josephguhlin deardenlab 216 Jun 11 23:48 VelvetWorm/training/funannotate_train.coordSorted.bam

And then it errors out on the next step. This could be because I'm using minimap2 as the aligner (BLAT crashes due to large genome). I'm trying again but with gmap now.

hisat2 bam contained data, but trinity and transcript do not.

josephguhlin@biochemcompute1 /V/a/d/g/V/2/V/training> ls -lahL *bam                                                                                                                                                               (funannotate-new)

-rw-r--r-- 1 josephguhlin deardenlab  216 Jun 11 23:48 funannotate_train.coordSorted.bam
-rw-r--r-- 1 josephguhlin deardenlab 6.8G Jun 11 18:28 hisat2.coordSorted.bam
-rw-r--r-- 1 josephguhlin deardenlab  216 Jun 11 23:48 transcript.alignments.bam
-rw-r--r-- 1 josephguhlin deardenlab  216 Jun 11 23:48 trinity.alignments.bam

**What command did you issue?**
For training:

nice funannotate train \
        -i ../1_masked/polished_1.fasta.masked \
        -o VelvetWorm \
        -l *R1*.gz \
        -r *R2*.gz \
        --max_intronlen 30000 \
        --species "Peripatus" \
        --cpus 64 \
        --aligners minimap2

For predict (where the error occurs):

nice nice nice \
        funannotate predict -i ../1_masked/polished_1.fasta.masked \
                -o VelvetWorm -s "Peripatus" --cpus 64 \
                --busco_seed_species fly \
                --optimize_augustus \
                --busco_db arthropoda \
                --organism other \
                --ploidy 1 \
                --max_intronlen 30000

**Logfiles**

[08:27 AM]: OS: linux2, 144 cores, ~ 1056 GB RAM. Python: 2.7.15
[08:27 AM]: Running funannotate v1.7.4
[08:27 AM]: Found training files, will re-use these files:
  --rna_bam VelvetWorm/training/funannotate_train.coordSorted.bam
  --pasa_gff VelvetWorm/training/funannotate_train.pasa.gff3
  --stringtie VelvetWorm/training/funannotate_train.stringtie.gtf
  --transcript_alignments VelvetWorm/training/funannotate_train.transcripts.gff3
[08:27 AM]: Parsed training data, run ab-initio gene predictors as follows:
Traceback (most recent call last):
  File "/Volumes/userdata/staff_users/josephguhlin/anaconda3/envs/funannotate-new/bin/funannotate", line 660, in <module>
    main()
  File "/Volumes/userdata/staff_users/josephguhlin/anaconda3/envs/funannotate-new/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/Volumes/userdata/staff_users/josephguhlin/anaconda3/envs/funannotate-new/lib/python2.7/site-packages/funannotate/predict.py", line 651, in main
    if not lib.BamHeaderTest(args.input, args.rna_bam):
  File "/Volumes/userdata/staff_users/josephguhlin/anaconda3/envs/funannotate-new/lib/python2.7/site-packages/funannotate/library.py", line 1386, in BamHeaderTest
    bam = pybam.read(bamin)
  File "/Volumes/userdata/staff_users/josephguhlin/anaconda3/envs/funannotate-new/lib/python2.7/site-packages/funannotate/pybam.py", line 384, in __init__
    header_cache += next(self._generator)
  File "/Volumes/userdata/staff_users/josephguhlin/anaconda3/envs/funannotate-new/lib/python2.7/site-packages/funannotate/pybam.py", line 321, in generator
    16+subfield_len+block_size-extra_len-19]
UnboundLocalError: local variable 'block_size' referenced before assignment

**OS/Install Information**
 -  output of `funannotate check --show-versions`

-------------------------------------------------------
Checking dependencies for 1.7.4
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.68
goatools: 1.0.5
matplotlib: 2.2.5
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.23.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
   ERROR: Text::Soundex not installed, install with cpanm Text::Soundex

Checking Environmental Variables...
$FUNANNOTATE_DB=/Volumes/archive/deardenlab/guhlin/software/funannotate/db
$PASAHOME=/Volumes/archive/deardenlab/guhlin/software/PASApipeline-v2.3.3
$TRINITYHOME=/Volumes/archive/deardenlab/guhlin/software/trinityrnaseq-Trinity-v2.8.4
$EVM_HOME=/Volumes/archive/deardenlab/guhlin/software/EVidenceModeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/Volumes/archive/deardenlab/guhlin/software/augustus-3.3.1/config
$GENEMARK_PATH=/Volumes/archive/deardenlab/guhlin/software/gm_et_linux_64/gmes_petap
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.3.3
CodingQuarry: 2.0
Trinity: 2.8.4
augustus: 3.3.1
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v35
diamond: 0.9.22
exonerate: exonerate 2.2.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2018-07-04
gmes_petap.pl: 4.35
hisat2: 2.1.0
hmmscan: HMMER 3.2.1 (June 2018)
hmmsearch: HMMER 3.2.1 (June 2018)
java: 11.0.1-internal
kallisto: 0.44.0
mafft: v7.407 (2018/Jul/23)
makeblastdb: makeblastdb 2.9.0+
minimap2: 2.17-r954-dirty
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.15.0
samtools: samtools 1.9-34-g8390769
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0 (December 2017)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.9.0+
trimal: trimAl v1.4.rev22 build[2015-05-21]
trimmomatic: 0.39
        ERROR: emapper.py not installed
        ERROR: ete3 not installed
        ERROR: signalp not installed

**Comment by jguhlin** [comment]
I think I've figured this out. The assembly is too large for minimap2 so it doesn't output certain headers. The solution is to pass -T to samtools commands to fix it. I'm running it now, and if it works will submit a PR if that's ok?
