### ISSUE TITLE
Funannotate update fails at final step of comparing annotation

### ISSUE THREAD

**Issue by JoelShore** [nextgenusfs/funannotate#441]
OK ignore this issue.
I re-ran the entire analysis beginning at the TRAIN stage, and ran successive commands out of that folder,
and it ran successfully to completion.

Thanks

**Are you using the latest release?**
Yes I believe so, I'm using funannotate v1.7.4

**Describe the bug** 
funannotate update almost runs to completion but fails just after parsing Genbank files while comparing annotations and running update.py script indicating index out of range. All of the results files appear to have been produced except for the ..pasa-reannotation.txt file.

**What command did you issue?**
funannotate update -i Turnera_subulata.gbk -o output --pasa_config alignAssembly.config --left_norm trimmed_left.fastq.gz.normalized.fq --right_norm trimmed_right.fastq.gz.normalized.fq --trinity trinity.fasta.clean --no_normalize_reads --no_trimmomatic --cpus 7 --memory 30G --max_intronlen 10000 --sbt Tsubtemplate.sbt --species Turnera subulata

Note that I am using sqlite and the script ran happily with 7 cpus at least up to the time of its failure.

**Logfiles**
...
[06/24/20 12:59:19]: Converting transcript alignments to GFF3 format
[06/24/20 12:59:56]: Converting Trinity transcript alignments to GFF3 format
[06/24/20 13:00:33]: PASA database is SQLite: /home/joel/funupdate/Turnera_subulata
[06/24/20 13:00:33]: /home/joel/miniconda3/envs/funannotate/bin/cdbfasta output/update_misc/genome.fa
[06/24/20 13:00:34]: 7889 entries from file output/update_misc/genome.fa were indexed in file output/update_misc/genome.fa.cidx

[06/24/20 13:00:34]: Running PASA annotation comparison step 1
[06/24/20 13:00:34]: /home/joel/miniconda3/envs/funannotate/opt/pasa-2.4.1/Launch_PASA_pipeline.pl -c /home/joel/funupdate/output/update_misc/pasa/annotCompare.txt -g /home/joel/funupdate/output/update_misc/genome.fa -t /home/joel/funupdate/output/update_misc/trinity.fasta.clean -A -L --CPU 7 --annots /home/joel/funupdate/output/update_misc/genome.gff3
[06/24/20 17:38:00]: Running PASA annotation comparison step 2
[06/24/20 17:38:00]: /home/joel/miniconda3/envs/funannotate/opt/pasa-2.4.1/Launch_PASA_pipeline.pl -c /home/joel/funupdate/output/update_misc/pasa/annotCompare.txt -g /home/joel/funupdate/output/update_misc/genome.fa -t /home/joel/funupdate/output/update_misc/trinity.fasta.clean -A -L --CPU 7 --annots /home/joel/funupdate/output/update_misc/pasa/Turnera_subulata.gene_structures_post_PASA_updates.32205.gff3
[06/25/20 04:53:59]: copying final PASA GFF3 to output: output/update_misc/pasa/Turnera_subulata.gene_structures_post_PASA_updates.3307.gff3
[06/25/20 04:53:59]: Using Kallisto TPM data to determine which PASA gene models to select at each locus
[06/25/20 04:53:59]: Building Kallisto index
[06/25/20 04:53:59]: /home/joel/miniconda3/envs/funannotate/opt/pasa-2.4.1/misc_utilities/gff3_file_to_proteins.pl output/update_misc/pasa_final.gff3 output/update_misc/genome.fa cDNA
[06/25/20 04:54:55]: kallisto index -i output/update_misc/getBestModel/bestModel output/update_misc/getBestModel/transcripts.fa
[06/25/20 04:56:51]: 
[build] loading fasta file output/update_misc/getBestModel/transcripts.fa
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
        from 58 target sequences
[build] warning: replaced 319 non-ACGUT characters in the input sequence
        with pseudorandom nucleotides
[build] counting k-mers ... done.
[build] building target de Bruijn graph ...  done 
[build] creating equivalence classes ...  done
[build] target de Bruijn graph has 388208 contigs and contains 51570504 k-mers 

[06/25/20 04:56:51]: Mapping reads using pseudoalignment in Kallisto
[06/25/20 04:56:51]: kallisto quant -i output/update_misc/getBestModel/bestModel -o output/update_misc/getBestModel/kallisto --plaintext -t 7 trimmed_left.fastq.gz.normalized.fq trimmed_right.fastq.gz.normalized.fq
[06/25/20 04:57:38]: 
[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 61,022
[index] number of k-mers: 51,570,504
[index] number of equivalence classes: 143,712
[quant] running in paired-end mode
[quant] will process pair 1: trimmed_left.fastq.gz.normalized.fq
                             trimmed_right.fastq.gz.normalized.fq
[quant] finding pseudoalignments for the reads ... done
[quant] processed 10,230,419 reads, 7,794,076 reads pseudoaligned
[quant] estimated average fragment length: 269.121
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 920 rounds
[06/25/20 04:57:39]: Parsing Kallisto results. Keeping alt-splicing transcripts if expressed at least 10.0% of highest transcript per locus.
[06/25/20 04:57:44]: Wrote 57,006 transcripts derived from 49,427 protein coding loci.
[06/25/20 04:57:44]: bedtools intersect -v -a output/update_misc/genome.trna.gff3 -b output/update_misc/bestmodels.gff3
[06/25/20 04:58:33]: Validating gene models (renaming, checking translations, filtering, etc)
[06/25/20 04:58:55]: Writing 50,412 loci to TBL format: dropped 0 overlapping, 1 too short, and 0 frameshift gene models
[06/25/20 04:58:57]: Converting to Genbank format
[06/25/20 04:58:57]: /home/joel/miniconda3/envs/funannotate/bin/python /home/joel/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/tbl2asn_parallel.py -i output/update_misc/tbl2asn/genome.tbl -f output/update_misc/genome.fa -o output/update_misc/tbl2asn --sbt Tsubtemplate.sbt -d output/update_results/Turnera_subulata.discrepency.report.txt -s Turnera subulata -t -l paired-ends -v 1 -c 7
[06/25/20 05:00:57]: Collecting final annotation files
[06/25/20 05:02:17]: Parsing GenBank files...comparing annotation

-------------------------------------------------------
Traceback (most recent call last):
  File "/home/joel/miniconda3/envs/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "/home/joel/miniconda3/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/home/joel/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 2292, in main
    compareAnnotations2(GBK, final_gbk, Changes, args=args)
  File "/home/joel/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 1324, in compareAnnotations2
    newGenes[gene[2]]['CDS'], newGenes[gene[2]]['mRNA'], newGenes[gene[2]]['strand'])
  File "/home/joel/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 1377, in findUTRs
    refInterlap = InterLap(mrna[i])
IndexError: list index out of range

**OS/Install Information**
(funannotate) joel@jub18:~/funupdate$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.7.4
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 1.0.5
matplotlib: 2.2.4
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.23.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/joel/funannotate_db
$PASAHOME=/home/joel/miniconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/joel/miniconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/joel/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/joel/miniconda3/envs/funannotate/config/
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.0
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 11.0.1-internal
kallisto: 0.46.2
mafft: v7.467 (2020/May/14)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.9
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: emapper.py not installed
	ERROR: ete3 not installed
	ERROR: gmes_petap.pl not installed
	ERROR: signalp not installed

**Comment by nextgenusfs** [comment]
Thanks for following up.

**Comment by JoelShore** [comment]
You're most welcome, and thanks very much for all your work on this. It
must be a very daunting task to respond to all these issues, many of which
(such as mine) are not the result of "bugs" but rather my incompetence.

Cheers

Joel
