### ISSUE TITLE
 Diamond repeat database was created with different version of diamond, please re-run funannotate setup

### ISSUE THREAD

**Issue by madhubioinfo** [nextgenusfs/funannotate#447]
I have installed Funannoate using conda and there was no error and i setup my database also. There was no error, when i try to test and the original dataset this is the error its showing
9:48 PM]: Running funannotate v1.7.4
[09:48 PM]: Diamond repeat database was created with different version of diamond, please re-run funannotate setup
#########################################################
Traceback (most recent call last):
  File "/home/madhu/envs/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "/home/madhu/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/home/madhu/envs/funannotate/lib/python2.7/site-packages/funannotate/test.py", line 389, in main
    runPredictTest(args)
  File "/home/madhu/envs/funannotate/lib/python2.7/site-packages/funannotate/test.py", line 152, in runPredictTest
    tmpdir, 'annotate', 'predict_results', 'Awesome_testicus.gff3')) <= 1800
  File "/home/madhu/envs/funannotate/lib/python2.7/site-packages/funannotate/test.py", line 40, in countGFFgenes
    with open(input, 'rU') as f:
IOError: [Errno 2] No such file or directory: 'test-predict_1375/annotate/predict_results/Awesome_testicus.gff3'
[funannotate-setup.log](https://github.com/nextgenusfs/funannotate/files/4854588/funannotate-setup.log)

I have attached the log file of setup I don't see any error . Help me to fix this error, Thanks in advance

**Comment by madhubioinfo** [comment]
I have individually installed repeat database that worked fine
