### ISSUE TITLE
Setup databse ValueError: unconverted data remains: 20

### ISSUE THREAD

**Issue by theo-llewellyn** [nextgenusfs/funannotate#448]
Hello,

I'm getting an error I dont understand on the setup database step of installation. Most of the databases seem to have downloaded correctly but I get the following error even when adding -w:

Traceback (most recent call last):
  File "/rdsgpfs/general/user/tbl19/home/anaconda3/envs/funannotate-env/bin/funannotate", line 660, in <module>
    main()
  File "/rdsgpfs/general/user/tbl19/home/anaconda3/envs/funannotate-env/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/rds/general/user/tbl19/home/anaconda3/envs/funannotate-env/lib/python2.7/site-packages/funannotate/setupDB.py", line 662, in main
    interproDB(DatabaseInfo, args.force, args=args)
  File "/rds/general/user/tbl19/home/anaconda3/envs/funannotate-env/lib/python2.7/site-packages/funannotate/setupDB.py", line 432, in interproDB
    iprdate, "%d-%b-%y").strftime("%Y-%m-%d")
  File "/rds/general/user/tbl19/home/anaconda3/envs/funannotate-env/lib/python2.7/_strptime.py", line 335, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 20

I used the following command:
-------------------------------------------------------
funannotate setup -d funannotate_db

Here is the output of that command:
-------------------------------------------------------
[05:48 PM]: OS: linux2, 24 cores, ~ 198 GB RAM. Python: 2.7.18
[05:48 PM]: Running 1.7.4
[05:48 PM]: Database location: funannotate_db
[05:48 PM]: Parsing Augustus pre-trained species and porting to funannotate
[05:48 PM]: Downloading Merops database
[05:48 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/merops_scan.lib Bytes: 1957603
[05:48 PM]: Building diamond database
[05:48 PM]: MEROPS Database: version=12.0 date=2017-10-04 records=5,009
[05:48 PM]: Downloading UniProtKB/SwissProt database
[05:48 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz Bytes: 89387983
[05:48 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt Bytes: 151
[05:48 PM]: Building diamond database
[05:49 PM]: UniProtKB Database: version=2020_03 date=2020-06-17 records=562,755
[05:49 PM]: Downloading dbCAN database
[05:49 PM]: Downloading: http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-HMMdb-V7.txt Bytes: 87673048
[05:49 PM]: Downloading: http://bcb.unl.edu/dbCAN2/download/Databases/CAZyDB.07312018.fam-activities.txt Bytes: 59480
[05:49 PM]: Downloading: http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-old@UGA/readme.txt Bytes: 6680
[05:49 PM]: Creating dbCAN HMM database
[05:49 PM]: dbCAN Database: version=8.0 date=2019-08-08 records=607
[05:49 PM]: Downloading Pfam database
[05:49 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam-A.hmm.gz Bytes: 274119400
[05:49 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam-A.clans.tsv.gz Bytes: 335058
[05:49 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam//current_release/Pfam.version.gz Bytes: 116
[05:49 PM]: Creating Pfam HMM database
[05:51 PM]: Pfam Database: version=33.1 date=2020-04 records=18,259
[05:51 PM]: Downloading Repeat database
[05:51 PM]: Downloading: https://osf.io/vp87c/download?version=1 Bytes: 6325661
[05:52 PM]: Building diamond database
[05:52 PM]: Repeat Database: version=1.0 date=2020-07-01 records=11,950
[05:52 PM]: Downloading GO Ontology database
[05:52 PM]: Downloading: http://purl.obolibrary.org/obo/go.obo Bytes: 33848074
[05:52 PM]: GO ontology version=2020-06-01 date=2020-06-01 records=47,358
[05:52 PM]: Downloading MiBIG Secondary Metabolism database
[05:52 PM]: Downloading: https://dl.secondarymetabolites.org/mibig/mibig_prot_seqs_1.4.fasta Bytes: 21244378
[05:52 PM]: Building diamond database
[05:52 PM]: MiBIG Database: version=1.4 date=2020-07-01 records=31,023
[05:52 PM]: Downloading InterProScan Mapping file
[05:52 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/interpro/interpro.xml.gz Bytes: 26189725
Traceback (most recent call last):
  File "/rdsgpfs/general/user/tbl19/home/anaconda3/envs/funannotate-env/bin/funannotate", line 660, in <module>
    main()
  File "/rdsgpfs/general/user/tbl19/home/anaconda3/envs/funannotate-env/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/rds/general/user/tbl19/home/anaconda3/envs/funannotate-env/lib/python2.7/site-packages/funannotate/setupDB.py", line 662, in main
    interproDB(DatabaseInfo, args.force, args=args)
  File "/rds/general/user/tbl19/home/anaconda3/envs/funannotate-env/lib/python2.7/site-packages/funannotate/setupDB.py", line 432, in interproDB
    iprdate, "%d-%b-%y").strftime("%Y-%m-%d")
  File "/rds/general/user/tbl19/home/anaconda3/envs/funannotate-env/lib/python2.7/_strptime.py", line 335, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 20

Here is the output of check versions command:
-------------------------------------------------------

Checking dependencies for 1.7.4
You are running Python v 2.7.18. Now checking python packages...
biopython: 1.74
goatools: 1.0.6
matplotlib: 2.2.3
natsort: 6.2.0
numpy: 1.16.6
pandas: 0.24.2
psutil: 5.6.7
requests: 2.24.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/rds/general/user/tbl19/home/anaconda3/envs/funannotate-env/funannotate_db
$PASAHOME=/rds/general/user/tbl19/home/anaconda3/envs/funannotate-env/opt/pasa-2.4.1
$TRINITY_HOME=/rds/general/user/tbl19/home/anaconda3/envs/funannotate-env/opt/trinity-2.8.5
$EVM_HOME=/rds/general/user/tbl19/home/anaconda3/envs/funannotate-env/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/rds/general/user/tbl19/home/anaconda3/envs/funannotate-env/config/
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir

Checking external dependencies...
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.0
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 1.8.0_152-release
kallisto: 0.46.0
mafft: v7.470 (2020/Jun/20)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.18
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: emapper.py not installed
	ERROR: ete3 not installed
	ERROR: gmes_petap.pl not installed
	ERROR: samtools not installed
	ERROR: signalp not installed

Any help would be much appreciated.

Best,
Theo

**Comment by theo-llewellyn** [comment]
This is being run in a conda environment set up using:

conda create -n funannotate python=2.7 funannotate

**Comment by nextgenusfs** [comment]
The problem is with the interpro xml file -- they changed the date format.  The current code in master has this fixed, amongst many other changes.  I think its reasonably stable.  You can install master like this from within your conda environment:
```
python -m pip install git+https://github.com/nextgenusfs/funannotate.git
```

**Comment by theo-llewellyn** [comment]
Great! That solved it. Thank you.
Theo
