### ISSUE TITLE
proteinortho failed with code 33792 during compare.py

### ISSUE THREAD

**Issue by cwb14** [nextgenusfs/funannotate#450]
I am using a `miniconda` installation of `funannotate version 1.7.4`  on 25 fungal genomes using a linux server. I am having an issue with `compare.py` at the `proteinortho` step. The terminal error prints:

```
[11:23 AM]: Running orthologous clustering tool, ProteinOrtho.  This may take awhile...
-------------------------------------------------------
Traceback (most recent call last):
  File "/storage/home/cwb14/work/miniconda3/envs/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "/storage/home/cwb14/work/miniconda3/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/storage/home/cwb14/work/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/compare.py", line 837, in main
    df = pd.read_csv(protOrthoTSV, sep='\t', header=0)
  File "/storage/home/cwb14/work/miniconda3/envs/funannotate/lib/python2.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/storage/home/cwb14/work/miniconda3/envs/funannotate/lib/python2.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/storage/home/cwb14/work/miniconda3/envs/funannotate/lib/python2.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/storage/home/cwb14/work/miniconda3/envs/funannotate/lib/python2.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/storage/home/cwb14/work/miniconda3/envs/funannotate/lib/python2.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: [Errno 2] File funannotate_compare/protortho/funannotate.poff.tsv does not exist: 'funannotate_compare/protortho/funannotate.poff.tsv'
```

Here is the `funannotate-compare.log` report.
```
sh: line 1: 93690 Illegal instruction     (core dumped) OMP_PROC_BIND=true /storage/home/cwb14/work/miniconda3/envs/funannotate/bin//proteinortho_clustering -minspecies 1 -ram 775428 -kmere 1 -debug 0 -cpus 20 -weighted 1 -verbose 1 -conn 0.1 -purity 1e-07 -rmgraph './proteinortho_cache_funannotate/funannotate.removed_blast-graph' funannotate.blast-graph* > 'funannotate.proteinortho.tsv'

Parameter-vector : (version=6.0.18,step=0,verbose=1,debug=1,exactstep3=0,synteny=1,duplication=2,cs=3,alpha=0.5,connectivity=0.1,cpus=20,evalue=1e-05,purity=1e-07,coverage=50,identity=25,blastmode=diamond,sim=0.95,report=3,keep=0,force=0,selfblast=1,twilight=0,singles=1,clean=0,blastOptions=,nograph=0,xml=0,desc=0,tmp_path=./proteinortho_cache_funannotate/,blastversion=0.9.21,binpath=,makedb=diamond makedb --in,blast=,jobs_todo=325,project=funannotate,po_path=/storage/home/cwb14/work/miniconda3/envs/funannotate/bin/,run_id=,threads_per_process=1,useMcl=0,freemem=775428)

[Error]  'proteinortho_clustering' failed with code 33792. (Please visit https://gitlab.com/paulklemm_PHD/proteinortho/wikis/Error%20Code)
Maybe your operating system does not support the statically compiled version, please try recompiling proteinortho with 'make clean' and 'make' (and 'make install PREFIX=...').
```

I've searched the web and tried a  few things, but I can't seem to shake this error. I'm gunna try a fresh installation of `funannotate` without installing `phyml` or `ete3`. In the meantime, any advice is appreciated. Thank you!

**Comment by nextgenusfs** [comment]
proteinortho seems to be the problem. Did you try installing a different version?  Perhaps downgrading proteinortho could help?

**Comment by cwb14** [comment]
I downgraded from 6.0.18 to 6.0.16 and it seems to have worked! Thanks for the advice.
