### ISSUE TITLE
Fun Annotate EggNog mapper failed

### ISSUE THREAD

**Issue by vcastroagudin** [nextgenusfs/funannotate#455]
Hello,

I am runanning Funannotate annotate, and despite the process ended succesfully I found in the log file that something is failing with emapper.

The file says 
;[07/13/20 12:33:44]: Running Eggnog-mapper
[07/13/20 12:33:44]: emapper.py -m diamond -i /home/vanina/jobs/funannotate/CT1-new_run/Prediction_CT1nm/annotate_misc/genome.proteins.fasta -o eggnog --cpu 16
[07/13/20 12:33:44]: #  emapper-1.0.3
# ./emapper.py  -m diamond -i /home/vanina/jobs/funannotate/CT1-new_run/Prediction_CT1nm/annotate_misc/genome.proteins.fasta -o eggnog --cpu 16
[1;33m  /home/vanina/conda/envs/funannotate/bin/diamond blastp -d /home/vanina/eggnog-mapper/data/eggnog_proteins.dmnd -q /home/vanina/jobs/funannotate/CT1-new_run/Prediction_CT1nm/annotate_misc/genome.proteins.fasta --more-sensitive --threads 16 -e 0.001000 -o /home/vanina/jobs/funannotate/CT1-new_run/Prediction_CT1nm/annotate_misc/emappertmp_dmdn_RUrFvb/7637402aeca9435a9be07d887875b54b --top 3[0m

[07/13/20 12:33:44]: Error: Database was built with a different version of Diamond and is incompatible.
Traceback (most recent call last):
  File "/home/vanina/eggnog-mapper/emapper.py", line 1001, in <module>
    main(args)
  File "/home/vanina/eggnog-mapper/emapper.py", line 216, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "/home/vanina/eggnog-mapper/emapper.py", line 353, in dump_diamond_matches
    raise e
subprocess.CalledProcessError: Command '/home/vanina/conda/envs/funannotate/bin/diamond blastp -d /home/vanina/eggnog-mapper/data/eggnog_proteins.dmnd -q /home/vanina/jobs/funannotate/CT1-new_run/Prediction_CT1nm/annotate_misc/genome.proteins.fasta --more-sensitive --threads 16 -e 0.001000 -o /home/vanina/jobs/funannotate/CT1-new_run/Prediction_CT1nm/annotate_misc/emappertmp_dmdn_RUrFvb/7637402aeca9435a9be07d887875b54b --top 3' returned non-zero exit status 1

[07/13/20 12:33:44]: No Eggnog-mapper results found.

I hae both EggNog version, however, I run EggNog Mapper v1 (database v4.5) with funannotate as per your suggestion. 

What an I doing wrong? How can I fix this issue?

Thanks,

Vanina

**Comment by nextgenusfs** [comment]
https://github.com/eggnogdb/eggnog-mapper/issues/48
