### ISSUE TITLE
Funannotate does not check the error code of external processes.

### ISSUE THREAD

**Issue by lukasjelonek** [nextgenusfs/funannotate#459]
**Are you using the latest release?**
funannotate 1.7.4

**Describe the bug**
Funannotate does not check the error code of external processes. This leads to problems further downstream. My actual problem was running `funannotate predict` with protein-evidence. Unfortunately my data had some artefacts that lead to problems with the diamond database build. The funannoate diamond step did not fail (although the external diamond process failed with an error), but the next downstream step.

It would be an improvement to check the error code of the process (everything != 0 is an error) and to directly notify the user about a failed tool run or least save the log at some place for further debugging.

My workaround was to remove the redirection of the diamond output from `library.runSubprocess4` and to check the diamond error message. With help of that I was able to easily find the problems with my evidence files: Some sequences had `.` as the last character and diamond is not able to handle this.

**What command did you issue?**
```
funannotate predict -i [...] -o fun --species  [...] --protein_evidence 000827265.1.faa 
```

The problematic part were sequences like this:

```
>rna-SCHCODRAFT_255410 gene=SCHCODRAFT_255410
MCRFVIYKGTSPVQLSHLLTRPCHSIINQAFDSRLRLDHRRPMNGDGFGVGWYDCQADDELGHQPCIFTS
VTPAWNNVNLQRLAEKIKSPLVFGHVRATTAGSLSLDNCHPFTHGKLMWMHNGGIADFPRIKRRLQTELP
DVAFNMVQGNTDSEWAFAVFLSKLPDPNAKSFKTAELRQAMTETIAHINRLTEEAGSTEPSLMNFCVTDG
ESVIATRYVSSRTDEAASLWFSSGTTFSEYADGGHYKMAKEDKRENIIMVASEPLTFERADWMEIKTNNM
IVITPKMNVLQIPIIDKYYVQPSHPDAALRNSDFAQEKGYLNPHQSAQAVAVH.
```

My workaround was to remove `stdout` and `stderr` direction to `FNULL` and to take a look at the diamond output, which quickly reveals the problem:

```
diamond v0.9.21.122 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 32
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: [...]/fun/predict_misc/proteins.combined.fa
Opening the database file...  [0.000208s]
Loading sequences...  [0.000242s]
Error: Error reading input stream at line 2: Invalid character (.) in sequence
```

**Logfiles**
```
-------------------------------------------------------
[10:22 AM]: OS: linux2, 64 cores, ~ 528 GB RAM. Python: 2.7.15
[10:22 AM]: Running funannotate v1.7.4
[10:22 AM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[10:22 AM]: Found training files, will re-use these files:
  --rna_bam fun/training/funannotate_train.coordSorted.bam
  --pasa_gff fun/training/funannotate_train.pasa.gff3
  --stringtie fun/training/funannotate_train.stringtie.gtf
  --transcript_alignments fun/training/funannotate_train.transcripts.gff3
[10:22 AM]: Parsed training data, run ab-initio gene predictors as follows:
[10:22 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
  Program        Training-Method
  augustus       pasa
  codingquarry   rna-bam
  glimmerhmm     pasa
  snap           pasa
[10:22 AM]: Genome loaded: 2,939 scaffolds; 41,302,601 bp; 0.61% repeats masked
[10:22 AM]: Parsed 13,893 transcript alignments from: fun/training/funannotate_train.transcripts.gff3
[10:22 AM]: Creating transcript EVM alignments and Augustus transcripts hintsfile
[10:22 AM]: Existing RNA-seq BAM hints found: fun/predict_misc/hints.BAM.gff
[10:23 AM]: Mapping 759,832 proteins to genome using diamond and exonerate
Traceback (most recent call last):
  File "[...]/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/funannotate-p2g.py", line 266, in <module>
    Hits = parseDiamond(BlastResult)
  File "[...]/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/funannotate-p2g.py", line 107, in parseDiamond
    with open(blastresult, 'rU') as input:
IOError: [Errno 2] No such file or directory: 'p2g_44296/diamond.matches.tab'
Traceback (most recent call last):
  File "[...]/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "[...]/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "[...]/funannotate/lib/python2.7/site-packages/funannotate/predict.py", line 951, in main
    lib.exonerate2hints(Exonerate, hintsP)
  File "[...]/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 3315, in exonerate2hints
    with open(file, 'r') as input:

```

**Comment by nextgenusfs** [comment]
Okay, thanks.  Yes the logging isn't great.  But I think we can check the error code in subprocess.Popen like this:
```
p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
stdout, stderr = p.communicate()
if p.returncode != 0:  
   print(stdout)
   print(stderr)
   sys.exit(1)
else:
   return 0
```
The FNULL was there in that general function to just not print a bunch of text to the terminal or logfile.  But looking at the return code would be a good thing to do, and then printing error and gracefully exiting.....

I'll see if I can add this type of behavior to subprocess calls -- should help capture a lot of silent errors assuming that the myriad of external dependencies are returning 0/1 appropriately.....

**Comment by nextgenusfs** [comment]
Okay, so this will be better I think?  Just running a few more tests and then I'll push to master. You can install master in your conda env, although you'll need to re-run setup as there was a change in interpro database causing setup to fail. A few more tests and I'll tag a new version, although I think current code in master is very close (also py3 compatible). 
```
$ funannotate predict -i test.softmasked.fa --protein_evidence ../funannotate/sample_data/bad_protein.fa -o fail_test --cpus 6 --augustus_species saccharomyces --cpus 7 --species "Awesome testicus"
-------------------------------------------------------
[Aug 02 09:36 PM]: OS: MacOSX 10.14.6, 8 cores, ~ 17 GB RAM. Python: 3.7.6
[Aug 02 09:36 PM]: Running funannotate v1.8.0
[Aug 02 09:36 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     pretrained     
  genemark     selftraining   
  glimmerhmm   busco          
  snap         busco          
[Aug 02 09:36 PM]: CodingQuarry will be skipped --> --rna_bam required for training
[Aug 02 09:36 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Aug 02 09:36 PM]: Genome loaded: 6 scaffolds; 3,776,588 bp; 19.75% repeats masked
[Aug 02 09:36 PM]: Mapping 1 proteins to genome using diamond and exonerate
[Aug 02 09:36 PM]: CMD ERROR: diamond makedb --threads 7 --in /Users/jon/test-predict_65290/fail_test/predict_misc/proteins.combined.fa --db diamond
diamond v0.9.35.136 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 7
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: /Users/jon/test-predict_65290/fail_test/predict_misc/proteins.combined.fa
Opening the database file...  [0s]
Loading sequences...  [0s]
Error: Error reading input stream at line 2: Invalid character (.) in sequence

```

**Comment by peterthorpe5** [comment]
Sorry if this is obvious, DIamond doesnt like "." as stops in sequences.

**Comment by lukasjelonek** [comment]
@nextgenusfs Thanks for the quick change. I will install and test it today. Regarding the code and the output it will, for sure, help to find problems more quickly.

In my experience most common linux/unix tools return 0/non-0 appropriately. Until now I only experienced one java-based-tool that did the opposite.
