### ISSUE TITLE
python 3.8+ doesn't use platform.linux_distribution

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#462]
```
funannotate setup -i all -u
-------------------------------------------------------
Traceback (most recent call last):
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/envs/funannotate-1.8/bin/funannotate", line 668, in <module>
    main()
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/envs/funannotate-1.8/bin/funannotate", line 658, in main
    mod.main(arguments)
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/envs/funannotate-1.8/lib/python3.8/site-packages/funannotate/setupDB.py", line 608, in main
    lib.SystemInfo()
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/envs/funannotate-1.8/lib/python3.8/site-packages/funannotate/library.py", line 6073, in SystemInfo
    system_os = systemOS()
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda3/4.3.31/envs/funannotate-1.8/lib/python3.8/site-packages/funannotate/library.py", line 6065, in systemOS
    linux_version = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

**Comment by hyphaltip** [comment]
Should be fixed with this commit ee9e71111b43d51c46c3da41e4dc17e5920f2e88 on branch fix_distro_for_python3.8
