### ISSUE TITLE
iprscan fails

### ISSUE THREAD

**Issue by wywye** [nextgenusfs/funannotate#472]
Hello, I am running `funnannotate iprscan` in the local mode. Using the following command:
`funannotate iprscan -i fun -m local --iprscan_path /home/wyatte/Chlamydomonas_reinhardtii/funannotat_test/interproscan-5.30-69.0 -c 24`

I tried running `funnannotate iprscan` using interproscan-5.46-81.0 (java 11) and read that there are compatibility issues using recent versions of Interproscan so I downgraded to interproscan-5.30-69.0 (java 1.8). However, I still receive the same error messages.

**Logfiles**
`Running InterProScan5 on 15707 proteins
Important: you need to manually configure your interproscan.properties file for embedded workers.
Will try to launch 24 interproscan processes, adjust -c,--cpus for your system
Traceback (most recent call last):
  File "/home/wyatte/.conda/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/iprscan-local.py", line 361, in <module>
    combine_xml(final_list, finalOut)
  File "/home/wyatte/.conda/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/iprscan-local.py", line 54, in combine_xml
    tree.write(output, encoding='utf-8', xml_declaration=True)
  File "/home/wyatte/.conda/envs/funannotate/lib/python2.7/xml/etree/ElementTree.py", line 817, in write
    self._root, encoding, default_namespace
  File "/home/wyatte/.conda/envs/funannotate/lib/python2.7/xml/etree/ElementTree.py", line 876, in _namespaces
    iterate = elem.getiterator() # cET compatibility
AttributeError: 'NoneType' object has no attribute 'getiterator'`

**OS/Install Information**
 -  output of `funannotate check --show-versions`
`-------------------------------------------------------
Checking dependencies for 1.8.0
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 1.0.6
matplotlib: 2.2.5
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.24.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed
You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/wyatte/funannotate_db
$PASAHOME=/home/wyatte/.conda/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/wyatte/Trinity-v2.5.1
$EVM_HOME=/home/wyatte/.conda/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/wyatte/.conda/envs/funannotate/config/
$GENEMARK_PATH=/home/wyatte/gmes_petap
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
emapper.py: 2.0.1
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.33
hisat2: 2.0.5
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 1.8.0_111
kallisto: 0.46.2
mafft: v7.471 (2020/Jul/3)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.18
pslCDnaFilter: no way to determine
salmon: salmon 0.15.0
samtools: samtools 1.10
signalp: 4.1
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 36 external dependencies are installed`

Thank you for your time and help!

**Comment by nextgenusfs** [comment]
`--iprscan_path` is expecting the `interproscan.sh` file -- by default it will just use `interproscan.sh` if it is available in the $PATH, if not, then you should specify the path to that shell script.  It looks like you provided a location to a folder, not the shell script.

**Comment by wywye** [comment]
I edited the script and have the same error. 

Running InterProScan5 on 15707 proteins
Important: you need to manually configure your interproscan.properties file for embedded workers.
Will try to launch 24 interproscan processes, adjust -c,--cpus for your system
Traceback (most recent call last):
  File "/home/wyatte/.conda/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/iprscan-local.py", line 361, in <module>
    combine_xml(final_list, finalOut)
  File "/home/wyatte/.conda/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/iprscan-local.py", line 54, in combine_xml
    tree.write(output, encoding='utf-8', xml_declaration=True)
  File "/home/wyatte/.conda/envs/funannotate/lib/python2.7/xml/etree/ElementTree.py", line 817, in write
    self._root, encoding, default_namespace
  File "/home/wyatte/.conda/envs/funannotate/lib/python2.7/xml/etree/ElementTree.py", line 876, in _namespaces
    iterate = elem.getiterator # cET compatibility
AttributeError: 'NoneType' object has no attribute 'getiterator'
	Command being timed: "funannotate iprscan -i fun -m local --iprscan_path /home/wyatte/Chlamydomonas_reinhardtii/funannotat_test/interproscan-5.30-69.0/interproscan.sh -c 24"

**Comment by nextgenusfs** [comment]
okay, what about the log files that each run generates?  It seems to be exiting very quickly and not finishing any of the jobs. there should be a log file for each run in the temp directory.

**Comment by wywye** [comment]
The only log file that mentions iprscan is located at `/fun/annotate_misc` which contains a file named `iprscan.xml`. 
`iprscan.xml` file contains: `<?xml version='1.0' encoding='utf-8'?>`

logfiles outputted from funannotate runs:
augustus-parallel.log  augustus_training.log  funannotate-EVM.log  funannotate-p2g.log  funannotate-predict.log  funannotate-train.log  funannotate-trinity.log  funannotate-update.log

Each step seems to have run correctly with results being printed to each log file. I have pasted a few lines from the update and trinity log files below.
 
funannotate update results:
Total Gene Models:	15,590
Total transcripts:	15,983
New Gene Models:	768
No Change:		6,131
Update UTRs:		8,592
Exons Changed:		88
Exons/CDS Changed:	11
Dropped Models:		1
CDS AED:		0.016
mRNA AED:		0.094

funannotate-trinity.log contains:
[08/25/20 18:22:45]: 6995703 reads; of these:
  6995703 (100.00%) were paired; of these:
    1146237 (16.38%) aligned concordantly 0 times
    5118713 (73.17%) aligned concordantly exactly 1 time
    730753 (10.45%) aligned concordantly >1 times
    ----
    1146237 pairs aligned concordantly 0 times; of these:
      72506 (6.33%) aligned discordantly 1 time
    ----
    1073731 pairs aligned 0 times concordantly or discordantly; of these:
      2147462 mates make up the pairs; of these:
        1343427 (62.56%) aligned 0 times
        660328 (30.75%) aligned exactly 1 time
        143707 (6.69%) aligned >1 times
90.40% overall alignment rate

**Comment by nextgenusfs** [comment]
In the working directory where you launched `funannotate iprscan` it should create a tmp folder called `iprscan_PID` the PID is the process ID number so that the folder name is unique. That is where the temp results should be.

**Comment by wywye** [comment]
Ah yes, thank you for helping with that. Here is one of the log files `Chlamydomonas_reinhardtii.proteins_10.log`:

01/09/2020 14:40:36:361 Welcome to InterProScan-5.30-69.0
01/09/2020 14:40:51:707 Running InterProScan v5 in STANDALONE mode... on Linux
01/09/2020 14:41:12:056 Loading file /panfs/biopan03/home/wyatte/Chlamydomonas_reinhardtii/funannotat_test/iprscan_24322/Chlamydomonas_reinhardtii.proteins_10.fasta
01/09/2020 14:41:12:060 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-1.5,Pfam-31.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-3,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
2020-09-01 14:41:23,404 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://interproscan.lanl.gov:9090 is not avaliable, NoRouteToHostException : No route to host (Host unreachable),  using proxy: false
2020-09-01 14:41:23,414 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:319] WARN - Problem with lookup service while on the step: Checking lookup client and server are in sync
2020-09-01 14:41:23,415 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:321] WARN -

The following problem was encountered by the pre-calculated match lookup service:
No route to host (Host unreachable)
Pre-calculated match lookup service failed - analysis proceeding to run locally
============================================================

The pre-calculated match lookup service has been configured in the interproscan.properties file.
  precalculated match lookup service url : http://interproscan.lanl.gov:9090
  precalculated match lookup service proxy host :   proxy port : 3128

Unfortunately the web service has failed. Check the configuration of this service
in the interproscan.properties file and, if necessary, set the following property to look like this:

precalculated.match.lookup.service.url=

If the problem persists, check if this is a firewall or proxy issue. If it is a proxy issue, then setting
the following property in the interproscan.properties file should work:

precalculated.match.lookup.service.proxy.host=
precalculated.match.lookup.service.proxy.port=

If this still does not work please inform the InterPro team of this error
by sending an email to:

interhelp@ebi.ac.uk

In the meantime, the analysis will continue to run locally.


2020-09-01 14:41:35,426 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://interproscan.lanl.gov:9090 is not avaliable, NoRouteToHostException : No route to host (Host unreachable),  using proxy: false
2020-09-01 14:41:47,454 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://interproscan.lanl.gov:9090 is not avaliable, NoRouteToHostException : No route to host (Host unreachable),  using proxy: false
2020-09-01 14:41:59,478 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://interproscan.lanl.gov:9090 is not avaliable, NoRouteToHostException : No route to host (Host unreachable),  using proxy: false
2020-09-01 14:42:10,500 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://interproscan.lanl.gov:9090 is not avaliable, NoRouteToHostException : No route to host (Host unreachable),  using proxy: false
2020-09-01 14:42:20,520 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://interproscan.lanl.gov:9090 is not avaliable, NoRouteToHostException : No route to host (Host unreachable),  using proxy: false
2020-09-01 14:42:30,540 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://interproscan.lanl.gov:9090 is not avaliable, NoRouteToHostException : No route to host (Host unreachable),  using proxy: false
2020-09-01 14:42:40,560 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://interproscan.lanl.gov:9090 is not avaliable, NoRouteToHostException : No route to host (Host unreachable),  using proxy: false
2020-09-01 14:42:50,580 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://interproscan.lanl.gov:9090 is not avaliable, NoRouteToHostException : No route to host (Host unreachable),  using proxy: false
2020-09-01 14:43:01,602 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.business.sequence.BerkeleyPrecalculatedProteinLookup:425] WARN - lookupUp service at http://interproscan.lanl.gov:9090 is not avaliable, NoRouteToHostException : No route to host (Host unreachable),  using proxy: false
2020-09-01 14:43:09,325 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: IOException thrown when attempting to run binary
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:172)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy107.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "python3": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at uk.ac.ebi.interpro.scan.io.cli.CommandLineConversationImpl.runCommand(CommandLineConversationImpl.java:146)
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:170)
	... 23 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 25 more
2020-09-01 14:43:09,329 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepMobiDBRunBinary
2020-09-01 14:43:09,378 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:143] WARN - StepInstance 60 is being re-run following a failure.
01/09/2020 14:46:21:566 25% completed
2020-09-01 14:53:25,208 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: IOException thrown when attempting to run binary
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:172)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy107.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "python3": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at uk.ac.ebi.interpro.scan.io.cli.CommandLineConversationImpl.runCommand(CommandLineConversationImpl.java:146)
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:170)
	... 23 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 25 more
2020-09-01 14:53:25,210 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepHamapHMMRunPFSearch
2020-09-01 14:53:25,347 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:143] WARN - StepInstance 22 is being re-run following a failure.
2020-09-01 14:53:30,355 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: IOException thrown when attempting to run binary
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:172)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy107.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "python3": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at uk.ac.ebi.interpro.scan.io.cli.CommandLineConversationImpl.runCommand(CommandLineConversationImpl.java:146)
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:170)
	... 23 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 25 more
2020-09-01 14:53:30,356 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepHamapHMMRunPFSearch
2020-09-01 14:53:30,413 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:143] WARN - StepInstance 22 is being re-run following a failure.
2020-09-01 14:53:35,426 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: IOException thrown when attempting to run binary
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:172)
	at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy107.executeInTransaction(Unknown Source)
	at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "python3": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at uk.ac.ebi.interpro.scan.io.cli.CommandLineConversationImpl.runCommand(CommandLineConversationImpl.java:146)
	at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:170)
	... 23 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 25 more
2020-09-01 14:53:35,427 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepHamapHMMRunPFSearch
2020-09-01 14:53:35,542 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 22 : Run pfsearch for selected proteins for proteins 1 to 951 has failed irretrievably.  Available StackTraces follow.
2020-09-01 14:53:35,543 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2020-09-01 14:53:35,544 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:258] ERROR - Exception thrown by StandaloneBlackBoxMaster:
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
	at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
	at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:134)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:377)
2020-09-01 14:53:36,194 [main] [uk.ac.ebi.interpro.scan.jms.master.AbstractMaster:249] WARN - Unable to delete temporary directory /panfs/biopan03/home/wyatte/Chlamydomonas_reinhardtii/funannotat_test/iprscan_24322/temp/n0821_20200901_144051670_7e5t
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

**Comment by nextgenusfs** [comment]
I typically turn off the pre-calc lookup.  And there are several other paths you need to specify in the interproscan properties file. Go through their install docs until you have a working installation....

**Comment by wywye** [comment]
Will do, thank you!
