### ISSUE TITLE
Error installing interpro database in funannotate 1.7.4

### ISSUE THREAD

**Issue by ferninfm** [nextgenusfs/funannotate#475]
Dear Jon,

I seem to come across the same error configuring the interpro database in funannotate v 1.7.4.
It seems to be an issue with reading the date. The xml.gz file is downloaded and unzipped, but then it crashes.

The error is consistently happening both in a standalone linux new install and within a docker container I pulled from reslp/funannotate_docker

Do you have any idea on what can be happening or how I can solve it?

Thanks for everything...

Fernando

**In the container**

``` bash

Singularity> funannotate setup -i interpro -d /data/database

-------------------------------------------------------
[12:11 PM]: OS: linux2, 64 cores, ~ 528 GB RAM. Python: 2.7.17
[12:11 PM]: Running 1.7.4
[12:11 PM]: Database location: /data/database
[12:11 PM]: Parsing Augustus pre-trained species and porting to funannotate
Traceback (most recent call last):
  File "/usr/local/bin/funannotate", line 660, in <module>
    main()
  File "/usr/local/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/usr/local/lib/python2.7/dist-packages/funannotate/setupDB.py", line 662, in main
    interproDB(DatabaseInfo, args.force, args=args)
  File "/usr/local/lib/python2.7/dist-packages/funannotate/setupDB.py", line 434, in interproDB
    type, name, version, date, records, checksum = info.get('interpro')
TypeError: 'NoneType' object is not iterable

Singularity> funannotate database

Funannotate Databases currently installed:

  Database          Type        Version      Date         Num_Records   Md5checksum
  gene2product      text        1.64         2020-08-25         33640   aa985b947a9758cc696421923f654a27
  pfam              hmmer3      33.1         2020-04            18259   228db640818af54066a1c23404a3ba38
  dbCAN             hmmer3      9.0          2020-08-04           607   51c724c1f9ac45687f08d0faa689ed58
  busco_outgroups   outgroups   1.0          2020-09-11             8   6795b1d4545850a4226829c7ae8ef058
  merops            diamond     12.0         2017-10-04          5009   a6dd76907896708f3ca5335f58560356
  mibig             diamond     1.4          2020-09-11         31023   118f2c11edde36c81bdea030a0228492
  uniprot           diamond     2020_04      2020-08-12        563082   da5725f3aa16b176d6dcf4e7ba7c1ea1
  go                text        2020-08-11   2020-08-11         47224   e57e1d7dd6f503cc87d77dcc6ec7d903
  repeats           diamond     1.0          2020-09-11         11950   4e8cafc3eea47ec7ba505bb1e3465d21

```

**Standalone** (conda install in Ubuntu 16.04)

``` bash

funannotate setup -i interpro -d /usr/local/src/funannotateDB --force

-------------------------------------------------------

[12:17 PM]: OS: linux2, 32 cores, ~ 198 GB RAM. Python: 2.7.15
[12:17 PM]: Running 1.7.4
[12:17 PM]: Database location: /usr/local/src/funannotateDB
[12:17 PM]: Parsing Augustus pre-trained species and porting to funannotate
[12:17 PM]: Downloading InterProScan Mapping file
[12:17 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/interpro/interpro.xml.gz Bytes: 25703455
Traceback (most recent call last):
  File "/home/fernando/anaconda2/envs/funannotate/bin//funannotate", line 660, in <module>
    main()
  File "/home/fernando/anaconda2/envs/funannotate/bin//funannotate", line 650, in main
    mod.main(arguments)
  File "/home/fernando/anaconda2/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 663, in main
    interproDB(DatabaseInfo, args.force, args=args)
  File "/home/fernando/anaconda2/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 433, in interproDB
    iprdate, "%d-%b-%y").strftime("%Y-%m-%d")
  File "/home/fernando/anaconda2/envs/funannotate/lib/python2.7/_strptime.py", line 335, in _strptime
    data_string[found.end():])

```

As you can imagine the problem is common to all `funannotate setup` processes. Curiously enough I managed to port an interproscan v 73.0 from an earlier funannotate install for the local install which is functioning.

**Comment by nextgenusfs** [comment]
Yes it is broken due to inter pro changing a format. If you install the master from git and then reissue the setup command with --force it should work as expected. We are just making sure the last few tests cases are working before tagging a new release.
