### ISSUE TITLE
Trinity read normalization issue 

### ISSUE THREAD

**Issue by hychenIG** [nextgenusfs/funannotate#476]
I run the funannotate train, it's present issue like this 
[06:07 PM]: Running read normalization with Trinity
Traceback (most recent call last):
  File "/home/conda/envs/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "/home/conda/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/home/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/train.py", line 914, in main
    stranded=args.stranded, min_coverage=args.min_coverage, coverage=args.coverage)
  File "/home/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/train.py", line 87, in runNormalization
    lib.runSubprocess2(cmd, '.', lib.log, SENormalLog)
  File "/home/conda/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 654, in runSubprocess2
    cmd, cwd=dir, stdout=out, stderr=subprocess.PIPE)
  File "/home/conda/envs/funannotate/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/conda/envs/funannotate/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

How can I fix this issue

**Comment by nextgenusfs** [comment]
Probably something wrong with your Trinity install.  The log file should have some more information.

**Comment by hychenIG** [comment]
> Probably something wrong with your Trinity install or your reads aren't in the right format for Trinity. The log file should have some more information.

I fix it with change of the TRINITYHOME variable
