### ISSUE TITLE
funannotate predict failed

### ISSUE THREAD

**Issue by SolayMane** [nextgenusfs/funannotate#478]
I run the prediction step after a training step using rna seq data

the  command as below:
funannotate predict -i data/foa_M13_clean-noMIT.fa.masked -o fun/ -s "Genus species" --strain "X44" --cpus 36

**Logfiles**
[09/18/20 11:24:10]: OS: linux2, 36 cores, ~ 264 GB RAM. Python: 2.7.15
[09/18/20 11:24:10]: Running funannotate v1.8.0
[09/18/20 11:24:10]: GeneMark path: /home/inras/software/genmark/gmes_linux_64
[09/18/20 11:24:10]: Full path to gmes_petap.pl: /home/inras/software/genmark/gmes_linux_64/gmes_petap.pl
[09/18/20 11:24:10]: GeneMark appears to be functional? True
[09/18/20 11:24:11]: Found training files, will re-use these files:
  --rna_bam fun/training/funannotate_train.coordSorted.bam
  --pasa_gff fun/training/funannotate_train.pasa.gff3
  --stringtie fun/training/funannotate_train.stringtie.gtf
  --transcript_alignments fun/training/funannotate_train.transcripts.gff3
[09/18/20 11:24:11]: {u'genemark': 1, u'hiq': 2, u'glimmerhmm': 1, u'pasa': 6, u'snap': 1, u'transcripts': 1, u'proteins': 1, u'codingquarry': 2, u'augustus': 1}
[09/18/20 11:24:11]: {u'genemark': u'selftraining', u'snap': u'pasa', u'glimmerhmm': u'pasa', u'codingquarry': u'rna-bam', u'augustus': u'pasa'}
[09/18/20 11:24:11]: Parsed training data, run ab-initio gene predictors as follows:
[09/18/20 11:24:12]: perl /home/inras/anaconda3/envs/funannotate/opt/evidencemodeler-1.1.1/EvmUtils/gff3_gene_prediction_file_validator.pl /disk1/FOA/fun/predict_misc/pasa_predictions.gff3
[09/18/20 11:24:13]: {u'genemark': 1, u'hiq': 2, u'glimmerhmm': 1, u'pasa': 6, u'snap': 1, u'transcripts': 1, u'proteins': 1, u'codingquarry': 2, u'augustus': 1}

***Output of the command**:
[11:33 AM]: OS: linux2, 36 cores, ~ 264 GB RAM. Python: 2.7.15
[11:33 AM]: Running funannotate v1.8.0
[11:33 AM]: Found training files, will re-use these files:
  --rna_bam fun/training/funannotate_train.coordSorted.bam
  --pasa_gff fun/training/funannotate_train.pasa.gff3
  --stringtie fun/training/funannotate_train.stringtie.gtf
  --transcript_alignments fun/training/funannotate_train.transcripts.gff3
[11:33 AM]: Parsed training data, run ab-initio gene predictors as follows:
  Program        Training-Method
  augustus       pasa
  codingquarry   rna-bam
  genemark       selftraining
  glimmerhmm     pasa
  snap           pasa
Traceback (most recent call last):
  File "/home/inras/anaconda3/envs/funannotate/bin/funannotate", line 670, in <module>
    main()
  File "/home/inras/anaconda3/envs/funannotate/bin/funannotate", line 660, in main
    mod.main(arguments)
  File "/home/inras/anaconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/predict.py", line 685, in main
    if not lib.BamHeaderTest(args.input, args.rna_bam):
  File "/home/inras/anaconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 1525, in BamHeaderTest
    for line in execute(cmd):
  File "/home/inras/anaconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 551, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '[u'samtools', u'idxstats', u'/disk1/FOA/fun/training/trinity.alignments.bam']' returned non-zero exit status 1

**OS/Install Information**
Checking dependencies for 1.8.0
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 1.0.6
matplotlib: 2.2.4
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.24.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.30
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/disk1/funannotate_db
$PASAHOME=/home/inras/anaconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/inras/anaconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/inras/anaconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/inras/anaconda3/envs/funannotate/config/
$GENEMARK_PATH=/home/inras/software/genmark/gmes_linux_64
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
emapper.py: /home/inras/anaconda3/envs/funannotate/bin/diamond /home/inras/software/eggnog-mapper
emapper-2.0.1b-2-g816e190

ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.57_lic
hisat2: 2.2.0
hmmscan: HMMER 3.3.1 (Jul 2020)
hmmsearch: HMMER 3.3.1 (Jul 2020)
java: 11.0.8-internal
kallisto: 0.46.2
mafft: v7.471 (2020/Jul/3)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.18
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.7
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.6 (May 2020)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: signalp not installed

**Comment by hyphaltip** [comment]
It seems like your trinity step failed? can you check the results from that and also the log file from the 'train' step?

**Comment by SolayMane** [comment]
tail -n 30 fun/logfiles/funannotate-train.log:


[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 17,793
[index] number of k-mers: 14,142,752
[index] number of equivalence classes: 27,514
[quant] running in paired-end mode
[quant] will process pair 1: fun/training/trimmomatic/trimmed_left.fastq.gz
                             fun/training/trimmomatic/trimmed_right.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 8,781,543 reads, 3,582,524 reads pseudoaligned
[quant] estimated average fragment length: 206.482
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 972 rounds


[09/18/20 08:17:50]: Parsing expression value results. Keeping best transcript at each locus.
[09/18/20 08:18:28]: Wrote 10,898 PASA gene models
[09/18/20 08:18:28]: PASA database name: Botrytics_sp_X2
[09/18/20 08:18:28]: Trinity/PASA has completed, you are now ready to run funanotate predict, for example:

The outputs seem to be ok

**Comment by nextgenusfs** [comment]
I think it is your version of samtools, see if you can upgrade to a new version from 1.7 and if that fixes the issue.

**Comment by SolayMane** [comment]
Thank you very much for your reply. I upgraded samtools to 1.11 and it works!
