### ISSUE TITLE
Failed prediction due to missing hints file

### ISSUE THREAD

**Issue by KnudNorNielsen** [nextgenusfs/funannotate#482]
My funannotate predict fails, apparently due to a missing hints file. How should I go about fixing this problem?
Best regards
Knud

Error 
```
funannotate predict -i ${i}.masked.fa -o fun.predict.${i} --species "MAT_haplotig_Macr"
-------------------------------------------------------
[11:25 AM]: OS: linux2, 40 cores, ~ 198 GB RAM. Python: 2.7.15
[11:25 AM]: Running funannotate v1.6.0
[11:25 AM]: AUGUSTUS (3.3.1) detected, version seems to be compatible with BRAKER and BUSCO
[11:25 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[11:25 AM]: Genome loaded: 2 scaffolds; 40,605 bp; 7.81% repeats masked
[11:25 AM]: Mapping proteins to genome using Diamond blastx/Exonerate
[11:25 AM]: Using 548,006 proteins as queries
[11:25 AM]: Running Diamond pre-filter search
[11:28 AM]: Found 62 preliminary alignments
[11:28 AM]: Exonerate finished: found 0 alignments
Traceback (most recent call last):
  File "/services/tools/funannotate/1.6.0/bin/funannotate-predict.py", line 684, in <module>
    lib.sortHints(allhintstmp, allhintstmp_sort)
  File "/services/tools/funannotate/1.6.0/lib/library.py", line 6965, in sortHints
    with open(input, 'rU') as infile:
IOError: [Errno 2] No such file or directory: 'fun.predict.MATregion_APN-SLA_haplotigs/predict_misc/hints.all.tmp'
[knunie@g-04-c0257 MATregion_APN-SLA_haplotigs]$
```

Environment
```
1) tools              10) ncbi-rmblastn/2.10.0+  19) kentUtils/381        28) evm/1.1.1           37) glimmerhmm/3.0.4
 2) anaconda2/4.4.0    11) RepeatMasker/4.0.7     20) diamond/0.9.24       29) pasapipeline/2.3.3  38) salmon/0.14.1
 3) recon/1.08         12) RepeatModeler/1.0.11   21) exonerate/2.4.0      30) mafft/7.402         39) stringtie/1.3.0
 4) trf/4.09           13) trinityrnaseq/2.8.5    22) fasta/36.3.8g        31) minimap2/2.6        40) codingquarry/2.0
 5) hmmer/3.2.1        14) lp_solve/5.5.2.5       23) gmap/20150623        32) trimal/1.4.1        41) funannotate/1.6.0
 6) mummer/3.23        15) suitesparse/5.7.2      24) hisat2/2.1.0         33) tbl2asn/20190117
 7) nseg/20000620      16) augustus/3.3.1         25) kallisto/0.44.0      34) trnascan-se/1.3.1
 8) RepeatScout/1.0.5  17) bamtools/2.5.1         26) genemark-es/4.61     35) samtools/1.9
 9) perl/5.20.2        18) bedtools/2.28.0        27) eggnog-mapper/1.0.3  36) snap/20190716
```

**Comment by hyphaltip** [comment]
So there are no hints because you have such a small genome since this is a targeted genome annotation I am assuming based on naming and the 2 contigs. You see that when exonerate finds no alignments.
you might be able to 'force' it by doing a `touch fun.predict.MATregion_APN-SLA_haplotigs/predict_misc/hints.all.tmp` so there is that at least exists.

@nextgenusfs might have ideas if this file open statement can be better protected.

**Comment by nextgenusfs** [comment]
I don't have the time to go back and debug old versions (this one 1.6.0). Starting in v1.7.x(?) using the pretrained parameters can be used to predict on small number of contigs. If this is still an issue with latest release I can try to fix.

**Comment by CDRism** [comment]
Hello - I am having a problem with missing hints file as well, albeit not with a small genome. Here is my code and the output I receive 

funannotate predict -i scelnum3.fna -s "Sceloporus tristichus" -o Chromosomes_NEW_TRI --busco_seed_species human --busco_db tetrapoda \
--organism other --repeats2evm --cpus 40 --max_intronlen 500000 --optimize_augustus

 Loading genome assembly and parsing soft-masked repetitive sequences
  Program      Training-Method
  augustus     busco
  genemark     selftraining
  glimmerhmm   busco
  snap         busco
[04:37 PM]: Genome loaded: 596 scaffolds; 323,480,233 bp; 37.09% repeats masked
[04:37 PM]: Mapping 551,648 proteins to genome using diamond and exonerate
[04:39 PM]: Found 0 preliminary alignments --> aligning with exonerate
[04:39 PM]: Exonerate finished: found 0 alignments
Traceback (most recent call last):
  File "/apps/software/standard/core/funannotate/1.8.3/bin/funannotate", line 713, in <module>
    main()
  File "/apps/software/standard/core/funannotate/1.8.3/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/apps/software/standard/core/funannotate/1.8.3/lib/python2.7/site-packages/funannotate/predict.py", line 1014, in main
    lib.sortHints(allhintstmp, allhintstmp_sort)
  File "/apps/software/standard/core/funannotate/1.8.3/lib/python2.7/site-packages/funannotate/library.py", line 8486, in sortHints
    with open(input, 'r') as infile:
IOError: [Errno 2] No such file or directory: u'Chromosomes_NEW_TRI/predict_misc/hints.all.tmp'

After training, when I look in the predict_misc folder, I see the following:

ab_initio_parameters  genome.softmasked.fa  p2g.diamond.out          proteins.combined.fa  scaffold.sort.order.txt
assembly-gaps.bed     hints.P.gff           protein_alignments.gff3  repeatmasker.bed      scaffold.sort.rename.txt

Any advice? This is funannotate version 1.8.3
