### ISSUE TITLE
1.8.1 python error: TypeError: __init__() got an unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by KnudNorNielsen** [nextgenusfs/funannotate#486]
Running funannotate v 1.8.1 command 'funannotate annotate' I run into a python error:

```
funannotate annotate -i fun.predict.${name} -o fun.ann.${name}
-------------------------------------------------------
[12:49 PM]: OS: CentOS Linux 7, 40 cores, ~ 198 GB RAM. Python: 3.6.10
[12:49 PM]: Running 1.8.1
[12:49 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[12:49 PM]: Found existing output directory fun.predict.MAT_haplotigs_polished. Warning, will re-use any intermediate files found.
[12:49 PM]: Parsing input files
[12:49 PM]: Existing tbl found: fun.predict.MAT_haplotigs_polished/predict_results/MAT_haplotig_Macr.tbl
[12:49 PM]: Adding Functional Annotation to MAT_haplotig_Macr, NCBI accession: None
[12:49 PM]: Annotation consists of: 998 gene models
[12:49 PM]: 990 protein records loaded
[12:49 PM]: Existing Pfam-A results found: fun.predict.MAT_haplotigs_polished/annotate_misc/annotations.pfam.txt
[12:49 PM]: 1,065 annotations added
[12:49 PM]: Running Diamond blastp search of UniProt DB version 2020_04
[12:49 PM]: 79 valid gene/product annotations from 102 total
[12:49 PM]: Running Eggnog-mapper
[12:49 PM]: CMD ERROR: emapper.py -m diamond -i /home/projects/cu_10081/generateddata/Metarhizium_acridum_ARSEF324_Assembly/haplotigs_from_polished/MAT_haplotigs_polished/fun.predict.MAT_haplotigs_polished/annotate_misc/genome.proteins.fasta -o eggnog --cpu 2
[12:49 PM]: #  emapper-2.0.1 / eggNOG DB version: 2.0
# emapper.py  -m diamond -i /home/projects/cu_10081/generateddata/Metarhizium_acridum_ARSEF324_Assembly/haplotigs_from_polished/MAT_haplotigs_polished/fun.predict.MAT_haplotigs_polished/annotate_misc/genome.proteins.fasta -o eggnog --cpu 2
  /services/tools/funannotate/1.8.1/bin/diamond blastp -d /services/tools/eggnog-mapper/2.0.2-rf1/data/eggnog_proteins.dmnd -q /home/projects/cu_10081/generateddata/Metarhizium_acridum_ARSEF324_Assembly/haplotigs_from_polished/MAT_haplotigs_polished/fun.predict.MAT_haplotigs_polished/annotate_misc/genome.proteins.fasta --more-sensitive --threads 2 -e 0.001 -o /home/projects/cu_10081/generateddata/Metarhizium_acridum_ARSEF324_Assembly/haplotigs_from_polished/MAT_haplotigs_polished/fun.predict.MAT_haplotigs_polished/annotate_misc/emappertmp_dmdn_q6j5g72s/9ef81960035e4493b97d54b225326b9b --query-cover 0 --subject-cover 0 --top 3

[12:49 PM]: Traceback (most recent call last):
  File "/services/tools/funannotate/1.8.1/bin/emapper.py", line 420, in <module>
    emapper.run(args, args.input, args.annotate_hits_table)
  File "/services/tools/eggnog-mapper/2.0.2-rf1/eggnogmapper/emapper.py", line 116, in run
    annot = self.search(args, infile)
  File "/services/tools/eggnog-mapper/2.0.2-rf1/eggnogmapper/emapper.py", line 88, in search
    pjoin(self._current_dir, self.hmm_hits_file))
  File "/services/tools/eggnog-mapper/2.0.2-rf1/eggnogmapper/search/diamond.py", line 55, in search
    self._search(in_file, seed_orthologs_file)
  File "/services/tools/eggnog-mapper/2.0.2-rf1/eggnogmapper/search/diamond.py", line 69, in _search
    raise e
  File "/services/tools/eggnog-mapper/2.0.2-rf1/eggnogmapper/search/diamond.py", line 64, in _search
    cmd = self.run_diamond(in_file, output_file)
  File "/services/tools/eggnog-mapper/2.0.2-rf1/eggnogmapper/search/diamond.py", line 93, in run_diamond
    completed_process = subprocess.run(cmd, capture_output=True, check=True, shell=True)
  File "/services/tools/funannotate/1.8.1/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**OS/Install Information**
Looking at the installation info there are to issues, one with recognizing augustus which is installed and another with recognizing the perl DB file which is also installed!
If you have any insights on these issues then please let me know,  but I don't think that they are linked to the python error posted above.

```
funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.8.1
-------------------------------------------------------
You are running Python v 3.6.10. Now checking python packages...
biopython: 1.78
goatools: 1.0.6
matplotlib: 3.3.1
natsort: 7.0.1
numpy: 1.19.1
pandas: 1.1.1
psutil: 5.7.2
requests: 2.24.0
scikit-learn: 0.23.2
scipy: 1.5.2
seaborn: 0.11.0
All 11 python packages installed


You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.42
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
Data::Dumper: 2.167
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.49
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 2.62
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
   ERROR: DB_File not installed, install with cpanm DB_File


Checking Environmental Variables...
$FUNANNOTATE_DB=/home/people/knunie/cu_10081/generateddata/funannotate/funannotate_db
$PASAHOME=/services/tools/funannotate/1.8.1/opt/pasa/
$TRINITY_HOME=/services/tools/funannotate/1.8.1/trinity/
$EVM_HOME=/services/tools/funannotate/1.8.1/evidencemodeler/
$AUGUSTUS_CONFIG_PATH=/services/tools/funannotate/1.8.1/config
$GENEMARK_PATH=/services/tools/genemark-es/4.61
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
        ERROR: augustus found but error running augustus
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 2.0.4
emapper.py: 2.0.1
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.61_lic
hisat2: 2.2.1
hmmscan: HMMER 3.3.1 (Jul 2020)
hmmsearch: HMMER 3.3.1 (Jul 2020)
java: 1.8.0_152-release
kallisto: 0.46.0
mafft: v7.471 (2020/Jul/3)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.22
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.10
signalp: 4.1
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.6 (May 2020)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: augustus not installed
```
Please notice that there are two different error given regarding augustus
ERROR: augustus found but error running augustus
ERROR: augustus not installed

Cheers
Knud

**Comment by nextgenusfs** [comment]
Few things -- the DB_File from conda appears to be broken and seems to have something to do with compiling on the conda GCC (this needs to be fixed on conda but I haven't had a chance to open issue or look into why, might just need to fix the build command in that recipe)- it looks like that on my system as well but at runtime will die. So might need to install that locally - it's a dependency of PASA. The code does not support eggnog mapper 2 yet because the output format doesn't appear to be stable (I've opened a few issues with them for the last 6-8 months and it seems like a new version coming at some point), problem is that eggnog v1 is python2 only. So to run in same environment would need to go back to py2 and install eggnog v1 with database 4.5 backend.

**Comment by nextgenusfs** [comment]
Oh and forgot about Augustus - what is the output if you just run it manually from command line? Does it work properly and just the version check is broken or is there compile issue with Augustus?

**Comment by KnudNorNielsen** [comment]
Yes, I can run Augustus/3.3.3 manually form command line

In testing whether 'fuannotate predict' would run augustus dispite the error message I ran into a new issue: 

```
$ funannotate predict -i ${i}.masked.fa -o fun.predict.${i}_test --species "MAT_haplotig_Macr" --augustus_species fusarium --busco_seed_species fusarium --cpus 10
-------------------------------------------------------
[04:23 PM]: OS: CentOS Linux 7, 40 cores, ~ 198 GB RAM. Python: 3.6.10
[04:23 PM]: Running funannotate v1.8.1
[04:23 PM]: EvidenceModeler $EVM_HOME variable is not correct
EVM scripts not found in $EVM_HOME: /services/tools/funannotate/1.8.1/evidencemodeler/
```
There simply was no evidencemodeler folder in this path. This was fix by exporting the path to an installation 'independent' installation of evm/1.1.1

But augustus woun't run within funannotate
```
export EVM_HOME=/services/tools/evm/1.1.1
$ funannotate predict -i ${i}.masked.fa -o fun.predict.${i}_test --species "MAT_haplotig_Macr" --augustus_species fusarium --busco_seed_species fusarium --cpus 10
-------------------------------------------------------
[04:27 PM]: OS: CentOS Linux 7, 40 cores, ~ 198 GB RAM. Python: 3.6.10
[04:27 PM]: Running funannotate v1.8.1
[04:27 PM]: Skipping CodingQuarry as no --rna_bam passed
[04:27 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     pretrained
  genemark     selftraining
  glimmerhmm   busco
  snap                busco
Traceback (most recent call last):
  File "/services/tools/funannotate/1.8.1/bin/funannotate", line 688, in <module>
    main()
  File "/services/tools/funannotate/1.8.1/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/services/tools/funannotate/1.8.1/lib/python3.6/site-packages/funannotate/predict.py", line 566, in main
    augustus_version, augustus_functional = lib.checkAugustusFunc()
  File "/services/tools/funannotate/1.8.1/lib/python3.6/site-packages/funannotate/library.py", line 1033, in checkAugustusFunc
    stdout=subprocess.PIPE, universal_newlines=True).communicate()
  File "/services/tools/funannotate/1.8.1/lib/python3.6/subprocess.py", line 850, in communicate
    stdout = self.stdout.read()
  File "/services/tools/funannotate/1.8.1/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 80: ordinal not in range(128)
```

PS: I have fixed the DB_File error (at least in according to 'funannotate check')  by loading a local perl/5.30.2 module.

**Comment by nextgenusfs** [comment]
First one about EVM -- was the $EVM_HOME set by conda? Or was that something done manually?

Yuck -- sorry about this.  Looks like a unicode py2/3 issue. Let me see if I can replicate, what version of Augustus?

**Comment by nextgenusfs** [comment]
Oh, it looks like it might be dying on checking the Augustus version -- which would explain why it was not showing up in `funannotate check`.  This is what it is trying to run:
```
    p1 = subprocess.Popen(['augustus', '--version'], stderr=subprocess.STDOUT,
                          stdout=subprocess.PIPE, universal_newlines=True).communicate()
    stdout, stderr = p1
    if isinstance(stdout, str):
        try:
            stdout = stdout.decode('ascii', 'ignore').encode('ascii')
        except AttributeError:
            pass
    version = stdout.split(' is ')[0]
```

**Comment by KnudNorNielsen** [comment]
Regarding the EVM then I don't know how the $EVM_HOME was originally created I assumed it was by conda - I can ask the HPC team, they are not that informative, but I can try. If I set manually then it works.

I used Agustus/3.3.3

**Comment by nextgenusfs** [comment]
Would you be able to run this on your system interactively? I'm not able to replicate this error locally, but something must be different/changed with v3.3.3 and how it is reporting the version.
```
$ python
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:33:30) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> p1 = subprocess.Popen(['augustus', '--version'], stderr=subprocess.STDOUT, stdout=subprocess.PIPE, universal_newlines=True).communicate()
>>> p1
('AUGUSTUS (3.2.1) is a gene prediction tool\nwritten by M. Stanke, O. Keller, S. König, L. Gerischer and L. Romoth.\n', None)
>>> 
```

**Comment by KnudNorNielsen** [comment]
```
$ python
Python 3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 23:13:11)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> p1 = subprocess.Popen(['augustus', '--version'], stderr=subprocess.STDOUT, stdout=subprocess.PIPE, universal_newlines=True).communicate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/services/tools/funannotate/1.8.1/lib/python3.6/subprocess.py", line 850, in communicate
    stdout = self.stdout.read()
  File "/services/tools/funannotate/1.8.1/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 80: ordinal not in range(128)
>>> p1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'p1' is not defined
>>>

```


My HPC support have setup a python 2.7 funannotate 1.8.1 session and that works, through all steps of the pipeline from clean to annotate.

```
$ module load tools genemark-es/4.61 signalp/4.1c funannotate/1.8.1_py27 perl/5.30.2
$ funannotate check
-------------------------------------------------------
Checking dependencies for 1.8.1
-------------------------------------------------------
To print all dependencies and versions: funannotate check --show-versions

You are running Python v 2.7.15. Now checking python packages...
All 11 python packages installed


You are running Perl v 5.030002. Now checking perl modules...
All 27 Perl modules installed


Checking Environmental Variables...
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
All 36 external dependencies are installed
```
```
$ module purge
$ module load tools genemark-es/4.61 signalp/4.1c funannotate/1.8.1 perl/5.30.2
$ funannotate check
-------------------------------------------------------
Checking dependencies for 1.8.1
-------------------------------------------------------
To print all dependencies and versions: funannotate check --show-versions

You are running Python v 3.6.10. Now checking python packages...
All 11 python packages installed


You are running Perl v b'5.030002'. Now checking perl modules...
All 27 Perl modules installed


Checking Environmental Variables...
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
        ERROR: augustus found but error running augustus
        ERROR: augustus not installed
```

**Comment by nextgenusfs** [comment]
Okay, yes its the most annoying and difficult of the py2/3 unicode decode errors to get working in both python2 and python3 -- its just the single character in `König` that causes the problem.  

I guess python2 likely still "better" for now since you can use eggnog mapper v1 than.
