### ISSUE TITLE
Signalp 5 list index out of range

### ISSUE THREAD

**Issue by SolayMane** [nextgenusfs/funannotate#494]
I run 
funannotate annotate -i Foa44 --cpus 36 --rename "K9L59"

and I get this error :
[08:28 AM]: OS: linux2, 36 cores, ~ 264 GB RAM. Python: 2.7.15
[08:28 AM]: Running 1.8.1
[08:28 AM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[08:28 AM]: Found existing output directory Foa44. Warning, will re-use any intermediate files found.
[08:28 AM]: Parsing input files
[08:28 AM]: Existing tbl found: Foa44/update_results/Fusarium_oxysporum.tbl
[08:28 AM]: Adding Functional Annotation to Fusarium oxysporum , NCBI accession: None
[08:28 AM]: Annotation consists of: 17,517 gene models
[08:28 AM]: 17,611 protein records loaded
[08:28 AM]: Existing Pfam-A results found: Foa44/annotate_misc/annotations.pfam.txt
[08:28 AM]: 18,707 annotations added
[08:28 AM]: Running Diamond blastp search of UniProt DB version 2020_04
[08:29 AM]: 1,072 valid gene/product annotations from 1,479 total
[08:29 AM]: Running Eggnog-mapper
[08:54 AM]: Parsing EggNog Annotations
[08:54 AM]: 11,233 COG and EggNog annotations added
[08:54 AM]: Combining UniProt/EggNog gene and product names using Gene2Product version 1.64
[08:54 AM]: 1,072 gene name and product description annotations added
[08:54 AM]: Existing MEROPS results found: Foa44/annotate_misc/annotations.merops.txt
[08:54 AM]: 539 annotations added
[08:54 AM]: Existing CAZYme results found: Foa44/annotate_misc/annotations.dbCAN.txt
[08:54 AM]: 775 annotations added
[08:54 AM]: Existing BUSCO2 results found: Foa44/annotate_misc/annotations.busco.txt
[08:54 AM]: 1,344 annotations added
[08:54 AM]: Skipping phobius predictions, try funannotate remote -m phobius
[08:54 AM]: Predicting secreted proteins with SignalP
Traceback (most recent call last):
  File "/home/inras/anaconda3/envs/funannotate/bin/funannotate", line 688, in <module>
    main()
  File "/home/inras/anaconda3/envs/funannotate/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/home/inras/anaconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/annotate.py", line 899, in main
    lib.parseSignalP(signalp_out, secreted_out)
  File "/home/inras/anaconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 5507, in parseSignalP
    if col[9] == 'Y':  # then there is signal peptide
IndexError: list index out of range

**Logfiles**
the end of the log file indicating that the signalP step which is concerned:

[10/06/20 08:59:05]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_16.fa
[10/06/20 08:59:17]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_2.fa
[10/06/20 08:59:29]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_17.fa
[10/06/20 08:59:41]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_39.fa
[10/06/20 08:59:53]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_34.fa
[10/06/20 09:00:05]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_38.fa
[10/06/20 09:00:17]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_14.fa
[10/06/20 09:00:29]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_15.fa
[10/06/20 09:00:41]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_18.fa
[10/06/20 09:00:53]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_29.fa
[10/06/20 09:01:05]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_30.fa
[10/06/20 09:01:17]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_31.fa
[10/06/20 09:01:29]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_24.fa
[10/06/20 09:01:41]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_20.fa
[10/06/20 09:01:53]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_11.fa
[10/06/20 09:02:05]: signalp -org euk -format short -fasta Foa44/annotate_misc/signalp_tmp/chunk_35.fa

**Comment by SolayMane** [comment]
@nextgenusfs  I need your help,

Checking dependencies for 1.8.1
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 1.0.6
matplotlib: 2.2.4
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.24.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed


You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.302
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.30
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/disk1/funannotate_db
$PASAHOME=/home/inras/anaconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/inras/anaconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/inras/anaconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/inras/anaconda3/envs/funannotate/config/
$GENEMARK_PATH=/home/inras/software/genmark/gmes_linux_64
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
emapper.py: /home/inras/anaconda3/envs/funannotate/bin/diamond /home/inras/software/eggnog-mapper
emapper-2.0.1b-2-g816e190

ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.57_lic
hisat2: 2.2.0
hmmscan: HMMER 3.3.1 (Jul 2020)
hmmsearch: HMMER 3.3.1 (Jul 2020)
java: 11.0.8-internal
kallisto: 0.46.2
mafft: v7.471 (2020/Jul/3)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.18
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.11
signalp: 5.0b
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.6 (May 2020)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 36 external dependencies are installed

**Comment by SolayMane** [comment]
here is the signalP output https://drive.google.com/file/d/1oLXg7wJk0a_kpeDoijLhZCdHug6ez8s6/view?usp=sharing

**Comment by nextgenusfs** [comment]
Oh, well its clearly not capturing the output properly -- this looks like stderr output. What is the help menu for signalp on your system look like? Might be missing a stdout option or something like that.

**Comment by SolayMane** [comment]
here is the help :

Usage of signalp:
  -batch int
        Number of sequences that the tool will run simultaneously. Decrease or increase size depending on your system memory. (default 10000)
  -fasta string
        Input file in fasta format.
  -format string
        Output format. 'long' for generating the predictions with plots, 'short' for the predictions without plots. (default "short")
  -gff3
        Make gff3 file of processed sequences.
  -mature
        Make fasta file with mature sequence.
  -org string
        Organism. Archaea: 'arch', Gram-positive: 'gram+', Gram-negative: 'gram-' or Eukarya: 'euk' (default "euk")
  -plot string
        Plots output format. When long output selected, choose between 'png', 'eps' or 'none' to get just a tabular file. (default "png")
  -prefix string
        Output files prefix. (default "Input file prefix")
  -stdout
        Write the prediction summary to the STDOUT.
  -tmp string
        Specify temporary file directory. (default "System default tmpdir")
  -verbose
        Verbose output. Specify '-verbose=false' to avoid printing. (default true)
  -version
        Prints version.

**Comment by ferninfm** [comment]
SignalP version 5.0b Linux x86_64
funannotate 1.8.1

I have the same problem as above reading the signalp output.
The logged signalp results are also the stdoutput log file and not the results

**Comment by ferninfm** [comment]
It seems you are piping the stdout from signalp. I am not sure this is the elegant solution you want, but it is the be the one you need

in library.py line 5471 you need to add the `-stdout flag. See below.

```
def signalP(input, tmpdir, output):
    # split input file into chunks, 20 should mean < 200 proteins per chunk
    from funannotate.check import check_version7
    version = check_version7('signalp')
    if '.' in version:
        version = int(version.split('.')[0])
    if version > 4:
        cmd = ['signalp', '-stdout', '-org', 'euk', '-format', 'short', '-fasta']
```

P.S. I tested it and it works.

**Comment by SolayMane** [comment]
It works! Thank you very much @ferninfm and @nextgenusfs  for your help.

**Comment by ferninfm** [comment]
Because the issue has been closed I insist just in case Just in case @nextgenusfs overlooks it. Since I decided not to make pull request.

You just need adding flag -stdout flag to the script running signalp 5.0 
 ```
 def signalP(input, tmpdir, output):
     # split input file into chunks, 20 should mean < 200 proteins per chunk
     from funannotate.check import check_version7
     version = check_version7('signalp')
     if '.' in version:
         version = int(version.split('.')[0])
     if version > 4:
         cmd = ['signalp', '-stdout', '-org', 'euk', '-format', 'short', '-fasta']
 ```
 
 P.S. I tested it and it works.

**Comment by nextgenusfs** [comment]
Great thanks I will push to master.
