### ISSUE TITLE
iprscan DB update failing

### ISSUE THREAD

**Issue by estolle** [nextgenusfs/funannotate#496]
Hi there,

I tried updating all my databases but encountered a problem with the interproscan one. Any idea what this error could mean?

My command (funannotate 1.7.4 in conda)
funannotate setup --wget --update --install interpro --database /scratch/funannotatedb

interpro.xml.gz            100%[======================================>]  24,51M  2,77MB/s    in 7,3s    

2020-10-05 00:54:47 (3,35 MB/s) - ‘/scratch/funannotatedb/interpro.xml.gz’ saved [25703455]

Traceback (most recent call last):
  File "/home/ek/.conda/envs/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "/home/ek/.conda/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/home/ek/.conda/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 662, in main
    interproDB(DatabaseInfo, args.force, args=args)
  File "/home/ek/.conda/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 432, in interproDB
    iprdate, "%d-%b-%y").strftime("%Y-%m-%d")
  File "/home/ek/.conda/envs/funannotate/lib/python2.7/_strptime.py", line 335, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 20

Many thanks
Eckart

**Comment by nextgenusfs** [comment]
Thanks for reporting. This is known problem as interpro changed their format unfortunately. The fix is to upgrade funannotate to more recent version, you can do this from your environment with pip to update funannotate and then rerun funannotate setup to get the correct database files.

**Comment by estolle** [comment]
Awesome, updating to 1.8.1 inside my conda env worked! Thank you. IProScan is working now smoothly (as well as updating the DB).

**Comment by estolle** [comment]
Hi again, quick update.

IPRscan worked for a long while but then the resulting xml was empty. Turns out it was a missing library:

bin/blast/ncbi-blast-2.9.0+/rpsbproc: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory

apt-get install elfutils
or
conda install elfutils

then it worked. I just updated the conda funannotate from 1.7.4. to 1.8.1 via pip --upgrade so perhaps elfutils is already part of the conda recipe? If not, perhaps its worth adding?

I later encountered another error which was previously reported (  #384 )- an encoding error when making the tbl output of the final annotationss, but I am not sure how I can fix it or find the entry causing the problem.

[04:20 PM]: 1,108 secretome and 3,349 transmembane annotations added
[04:20 PM]: Parsing InterProScan5 XML file
[04:20 PM]: Found 0 duplicated annotations, adding 113,761 valid annotations
[04:20 PM]: Converting to final Genbank format, good luck!
[04:26 PM]: Creating AGP file and corresponding contigs file
[04:26 PM]: Writing genome annotation table.
Traceback (most recent call last):
  File "/home/ek/.conda/envs/funannotate/bin/funannotate", line 688, in <module>
    main()
  File "/home/ek/.conda/envs/funannotate/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/home/ek/.conda/envs/funannotate/lib/python2.7/site-packages/funannotate/annotate.py", line 1459, in main
    final_annotation)
  File "/home/ek/.conda/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 7412, in annotationtable
    outfile.write('%s\n' % '\t'.join(result))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 175: ordinal not in range(128)

**Comment by nextgenusfs** [comment]
The first issue is not related to funannotate but rather your InterProScan install -- funannotate only uses an old version of blast and all the other searches are done with diamond. So seems like your InterProScan is configured to use blast 2.9.0 which apparently was missing that dependency (these settings all controlled in the`interproscan.properties` file).

God I hate these py2/py3 unicode/decode errors.  Its like chasing your tail....  Are you able to track down where the \u2019 character is in the annotation?  Probably the place to look would be the *.tbl file in the annotate_results folder.

**Comment by estolle** [comment]
Thanks for the quick reply and the pointers to look up the entry. 

seems the unicode character \u2019 (U+2019) is the single right quote mark ’ and its in the interproscan output. It appears that there is a single entry where they use it for 3' / 5' names instead the usually used "'". I tried to replace this character using sed, but seems the error persists.

cat iprscan.xml | grep "’"
          <entry ac="IPR043371" desc="cAMP-specific 3’,5’-cyclic phosphodiesterase 4" name="PDE4" type="FAMILY">
- this is the problematic entry
- other similar entries use "'" and not right single quotation, eg:           <entry ac="IPR002073" desc="3'5'-cyclic nucleotide phosphodiesterase, catalytic domain" name="PDEase_catalytic_dom" type="DOMAIN">

- changing it to "'"
sed -i "s/’/'/g" iprscan.xml

- error persists
[03:42 PM]: Creating AGP file and corresponding contigs file
[03:42 PM]: Writing genome annotation table.
Traceback (most recent call last):
  File "/home/ek/.conda/envs/funannotate/bin/funannotate", line 688, in <module>
    main()
  File "/home/ek/.conda/envs/funannotate/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/home/ek/.conda/envs/funannotate/lib/python2.7/site-packages/funannotate/annotate.py", line 1459, in main
    final_annotation)
  File "/home/ek/.conda/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 7412, in annotationtable
    outfile.write('%s\n' % '\t'.join(result))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 175: ordinal not in range(128)

I solved it by creating a new conda environment : conda creat --name funannotate181 funannotate elfutils python=3

**Comment by nextgenusfs** [comment]
So you do not get the error in python3 correct?  Error is only there in python2?

**Comment by estolle** [comment]
Yes indeed. In python3 it worked, in python2 this single entry caused the problem.
