### ISSUE TITLE
funannotate compare fails to open log file and shows duplicated print to screen

### ISSUE THREAD

**Issue by ferninfm** [nextgenusfs/funannotate#500]
funannotate 1.8.1

funannotate crashes with the following message

```
funannotate compare -i whatever_folders --cpus 32 --run_dnds full --ml_method iqtree
Traceback (most recent call last):
  File "/home/fernando/anaconda2/envs/funannotate/bin/funannotate", line 688, in <module>
    main()
  File "/home/fernando/anaconda2/envs/funannotate/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/home/fernando/anaconda2/envs/funannotate/lib/python2.7/site-packages/funannotate/compare.py", line 73, in main
    lib.setupLogging(log_name)
  File "/home/fernando/anaconda2/envs/funannotate/lib/python2.7/site-packages/funannotate/library.py", line 1217, in setupLogging
    fhnd = logging.FileHandler(LOGNAME)
  File "/home/fernando/anaconda2/envs/funannotate/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/fernando/anaconda2/envs/funannotate/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/fernando/Documents/10_Pyrenodesmia_genomes_final/05_funannotate/04_predicted/funannotate_compare/funannotate-compare.log'
```

I manually created the folder and the log file with nano and absurdly works.
There is clearly a bug in setupLogging which scapes me.

So, The temporary fix if anyone comes across the same error and needs it to work NOW. Create output folder and logfile yourself.

**Comment by ferninfm** [comment]
I also cannot work out why its printing twice on the screen....
```
-------------------------------------------------------
[12:30 PM]: OS: linux2, 32 cores, ~ 198 GB RAM. Python: 2.7.15
-------------------------------------------------------
[12:30 PM]: OS: linux2, 32 cores, ~ 198 GB RAM. Python: 2.7.15
[12:30 PM]: OS: linux2, 32 cores, ~ 198 GB RAM. Python: 2.7.15
[12:30 PM]: Running 1.8.1
[12:30 PM]: Running 1.8.1
[12:30 PM]: Now parsing 23 genomes
[12:30 PM]: Now parsing 23 genomes
.....
```

**Comment by nextgenusfs** [comment]
Okay thanks for letting me know. I thought I had fixed that in master

**Comment by nextgenusfs** [comment]
So this wasn't a fix then? https://github.com/nextgenusfs/funannotate/commit/2520c60e35fa4f8e8956d80b93e8b43ddcdf0143.  It did fix it locally for me.

**Comment by ferninfm** [comment]
Hmmm... Aye... sorry I am not up to date with Master in this machine... Too many things at once...

**Comment by ferninfm** [comment]
I updated to master.
logging is fixed, duplicated screen log is not. I still do not understand how this happens from your code....
