### ISSUE TITLE
funannotate util contrast missing dependency (interlap)

### ISSUE THREAD

**Issue by ferninfm** [nextgenusfs/funannotate#502]
One more trivial thing. v. 1.8.2

Dependency went missing. Installed it manually, it seems to work.

```funannotate util contrast -r Xone.gff -f Xtwo.fasta
Traceback (most recent call last):
  File "/home/fernando/anaconda2/envs/funannotate/bin/funannotate", line 688, in <module>
    main()
  File "/home/fernando/anaconda2/envs/funannotate/bin/funannotate", line 674, in main
    package_name, info[cmdName]['dir'], info[cmdName]['cmd']))
  File "/home/fernando/anaconda2/envs/funannotate/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/fernando/anaconda2/envs/funannotate/lib/python2.7/site-packages/funannotate/utilities/contrast.py", line 10, in <module>
    from interlap import InterLap
ImportError: No module named interlap
```

**Comment by nextgenusfs** [comment]
Oh, thanks for reporting. That should be funannotate.interlap in the import. Will fix shortly.
