### ISSUE TITLE
Can't find trimmomatic.jar when running funannotate train 

### ISSUE THREAD

**Issue by Juliana-Soto24** [nextgenusfs/funannotate#530]
Hi, 
I am trying to run funannotate train but I am getting the warning that trimmomatic is missing and I already set up and exported the PATH for this tool  

-------------------------------------------------------
[04:03 PM]: OS: Ubuntu 18.04, 36 cores, ~ 72 GB RAM. Python: 3.6.9
[04:03 PM]: Running 1.8.1
[04:03 PM]: Missing Dependencies: fasta, trimmomatic.  Please install missing dependencies and re-run script

Since trimmomatic needs java, is there a different way to run it or indicate in the funannotate train commands?

Thanks, 

Juliana

**Comment by nextgenusfs** [comment]
So for `fasta` -- you can just symlink `fasta36` to `fasta` (this is a PASA requirement). 

As per `trimmomatic` its looking for a script by that name.  Conda does this by using the following python script, I think you could also just use a bash script that comes with the original trimmomatic distribution.  Simplest fix if you have conda installed in this environment would just be to install it with conda, ie `conda install -n yourenv trimmomatic`.

If you don't want/need to run `trimmomatic` on the RNA-seq reads, then just pass `--no-trimmomatic` to the `funannotate train` script. 

For reference, this is the wrapper script used.
```
$ cat /Users/jon/miniconda3/envs/py3-funannotate/bin/trimmomatic
#!/usr/bin/env python
#
# Wrapper script for Java Conda packages that ensures that the java runtime
# is invoked with the right options. Adapted from the bash script (http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in/246128#246128).

#
# Program Parameters
#
import os
import subprocess
import sys
import shutil
from os import access
from os import getenv
from os import X_OK
jar_file = 'trimmomatic.jar'


default_jvm_mem_opts = ['-Xms512m', '-Xmx1g']

# !!! End of parameter section. No user-serviceable code below this line !!!


def real_dirname(path):
    """Return the symlink-resolved, canonicalized directory-portion of path."""
    return os.path.dirname(os.path.realpath(path))


def java_executable():
    """Return the executable name of the Java interpreter."""
    java_home = getenv('JAVA_HOME')
    java_bin = os.path.join('bin', 'java')

    if java_home and access(os.path.join(java_home, java_bin), X_OK):
        return os.path.join(java_home, java_bin)
    else:
        return 'java'


def jvm_opts(argv):
    """Construct list of Java arguments based on our argument list.

    The argument list passed in argv must not include the script name.
    The return value is a 3-tuple lists of strings of the form:
      (memory_options, prop_options, passthrough_options)
    """
    mem_opts = []
    prop_opts = []
    pass_args = []
    exec_dir = None

    for arg in argv:
        if arg.startswith('-D'):
            prop_opts.append(arg)
        elif arg.startswith('-XX'):
            prop_opts.append(arg)
        elif arg.startswith('-Xm'):
            mem_opts.append(arg)
        elif arg.startswith('--exec_dir='):
            exec_dir = arg.split('=')[1].strip('"').strip("'")
            if not os.path.exists(exec_dir):
                shutil.copytree(real_dirname(sys.argv[0]), exec_dir, symlinks=False, ignore=None)
        else:
            pass_args.append(arg)

    # In the original shell script the test coded below read:
    #   if [ "$jvm_mem_opts" == "" ] && [ -z ${_JAVA_OPTIONS+x} ]
    # To reproduce the behaviour of the above shell code fragment
    # it is important to explictly check for equality with None
    # in the second condition, so a null envar value counts as True!

    if mem_opts == [] and getenv('_JAVA_OPTIONS') is None:
        mem_opts = default_jvm_mem_opts

    return (mem_opts, prop_opts, pass_args, exec_dir)


def main():
    java = java_executable()
    """
    PeptideShaker updates files relative to the path of the jar file.
    In a multiuser setting, the option --exec_dir="exec_dir"
    can be used as the location for the peptide-shaker distribution.
    If the exec_dir dies not exist,
    we copy the jar file, lib, and resources to the exec_dir directory.
    """
    (mem_opts, prop_opts, pass_args, exec_dir) = jvm_opts(sys.argv[1:])
    jar_dir = exec_dir if exec_dir else real_dirname(sys.argv[0])

    if pass_args != [] and pass_args[0].startswith('eu'):
        jar_arg = '-cp'
    else:
        jar_arg = '-jar'

    jar_path = os.path.join(jar_dir, jar_file)

    java_args = [java] + mem_opts + prop_opts + [jar_arg] + [jar_path] + pass_args

    sys.exit(subprocess.call(java_args))


if __name__ == '__main__':
    main()
```

**Comment by Juliana-Soto24** [comment]
Thanks for sending this information

**Comment by Juliana-Soto24** [comment]
I have a new error with Trinity:
This is the command I am running:
funannotate train -i SBI4263.nanopore.scaffold.order.fasta -o train --single_norm SRR6966973.fastq.gz --jaccard_clip --species "Pichia kudriavzevii" --cpus 36

[01/12/21 10:52:44]: Building Hisat2 genome index
[01/12/21 10:52:44]: hisat2-build -p 36 train/training/genome.fasta train/training/hisat2.genome
[01/12/21 10:52:48]: Aligning reads to genome using Hisat2
[01/12/21 10:52:48]: hisat2 -p 36 --max-intronlen 3000 --dta -x train/training/hisat2.genome -U /EFS/FungalGenomes/Pichia/06.Funannotate/SRR6966973.fastq.gz | samtools sort --reference
 train/training/genome.fasta -@ 18 -o train/training/hisat2.coordSorted.bam -
[01/12/21 11:01:28]: Running genome-guided Trinity, logfile: train/training/Trinity-gg.log
[01/12/21 11:01:28]: Clustering of reads from BAM and preparing assembly commands
[01/12/21 11:01:28]: Trinity --no_distributed_trinity_exec --genome_guided_bam train/training/hisat2.coordSorted.bam --genome_guided_max_intron 3000 --CPU 36 --max_memory 50G --output 
train/training/trinity_gg --jaccard_clip
[01/12/21 11:01:28]: CMD ERROR: Trinity --no_distributed_trinity_exec --genome_guided_bam train/training/hisat2.coordSorted.bam --genome_guided_max_intron 3000 --CPU 36 --max_memory 50
G --output train/training/trinity_gg --jaccard_clip
[01/12/21 11:01:28]: (None, b'')

Thanks for the feedback!

Juliana

**Comment by nextgenusfs** [comment]
It is hard for me to troubleshoot installation issues when custom data is used, can you run the test dataset and let me know if that fails/passes?
```
funannotate test -t rna-seq --cpus 24
```
But there should be a trinity.log file that will have more information.

**Comment by Juliana-Soto24** [comment]
I run it and I have this error: 

 funannotate test -t rna-seq --cpus 24
#########################################################
Running funannotate RNA-seq training/prediction unit testing
Downloading: https://osf.io/t7j83/download?version=1 Bytes: 542753017
CMD: funannotate train -i test.softmasked.fa --single rna-seq.illumina.fastq.gz --nanopore_mrna rna-seq.nanopore.fastq.gz -o rna-seq --cpus 24 --jaccard_clip --species Awesome rna
#########################################################
-------------------------------------------------------
[02:21 PM]: OS: Ubuntu 18.04, 36 cores, ~ 72 GB RAM. Python: 3.6.9
[02:21 PM]: Running 1.8.1
[02:21 PM]: Adapter and Quality trimming SE reads with Trimmomatic
[02:22 PM]: Running read normalization with Trinity
[02:22 PM]: CMD ERROR: /EFS/tools/trinityrnaseq-SAVE01/util/insilico_read_normalization.pl --PARALLEL_STATS --JM 50G --min_cov 5 --max_cov 50 --seqType fq --output rna-seq/training/normalize --CPU 24 --single rna-seq/training/trimmomatic/trimmed_single.fastq.gz
[02:22 PM]: (None, b'')
#########################################################
Now running `funannotate predict` using RNA-seq training data
CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o rna-seq --cpus 24 --min_training_models 150 --species Awesome rna
#########################################################
-------------------------------------------------------
[02:22 PM]: OS: Ubuntu 18.04, 36 cores, ~ 72 GB RAM. Python: 3.6.9
[02:22 PM]: Running funannotate v1.8.1
[02:22 PM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[02:22 PM]: Skipping CodingQuarry as $QUARRY_PATH not found as ENV
[02:22 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     busco          
  glimmerhmm   busco          
  snap         busco          
[02:22 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[02:23 PM]: Genome loaded: 6 scaffolds; 3,776,588 bp; 19.75% repeats masked
[02:23 PM]: Mapping 1,065 proteins to genome using diamond and exonerate
[02:23 PM]: Found 1,784 preliminary alignments --> aligning with exonerate
[02:24 PM]: Exonerate finished: found 1,357 alignments
[02:24 PM]: Running BUSCO to find conserved gene models for training ab-initio predictors
[02:24 PM]: Multi-threading in tblastn v2.6.0 is unstable, running in single threaded mode for BUSCO
[02:28 PM]: 175 valid BUSCO predictions found, validating protein sequences
[02:28 PM]: 175 BUSCO predictions validated
[02:28 PM]: Training Augustus using BUSCO gene models
[02:29 PM]: Augustus initial training results:
  Feature       Specificity   Sensitivity
  nucleotides   99.8%         87.3%      
  exons         67.9%         60.9%      
  genes         79.0%         59.4%      
[02:29 PM]: Running Augustus gene prediction using awesome_rna parameters
[02:29 PM]: 1,238 predictions from Augustus
[02:29 PM]: Pulling out high quality Augustus predictions
[02:29 PM]: Found 297 high quality predictions from Augustus (>90% exon evidence)
[02:29 PM]: Snap failed, dependency not in $PATH: fathom
[02:29 PM]: GlimmerHMM failed, dependency not in $PATH: trainGlimmerHMM
[02:29 PM]: Summary of gene models passed to EVM (weights):
  Source         Weight   Count
  Augustus       1        941  
  Augustus HiQ   2        297  
  Total          -        1238 

[02:29 PM]: EVM: partitioning input to ~ 35 genes per partition
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 431, in <module>
    partitions=args.no_partitions)
  File "/usr/local/lib/python3.6/dist-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 110, in create_partitions
    interGenes = gene_blocks_to_interlap(genes)
  File "/usr/local/lib/python3.6/dist-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 25, in gene_blocks_to_interlap
    cols = gene_model[1].split('\t')
IndexError: list index out of range

[02:29 PM]: Evidence modeler has failed, exiting
Traceback (most recent call last):
  File "/usr/local/bin/funannotate", line 688, in <module>
    main()
  File "/usr/local/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/usr/local/lib/python3.6/dist-packages/funannotate/predict.py", line 1718, in main
    os.remove(EVM_out)
FileNotFoundError: [Errno 2] No such file or directory: '/EFS/FungalGenomes/Pichia/06.Funannotate/test-rna_seq_3237/rna-seq/predict_misc/evm.round1.gff3'
Traceback (most recent call last):
  File "/usr/local/bin/funannotate", line 688, in <module>
    main()
  File "/usr/local/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/usr/local/lib/python3.6/dist-packages/funannotate/test.py", line 408, in main
    runRNAseqTest(args)
  File "/usr/local/lib/python3.6/dist-packages/funannotate/test.py", line 347, in runRNAseqTest
    tmpdir, 'rna-seq', 'predict_results', 'Awesome_rna.gff3')) <= 1830
  File "/usr/local/lib/python3.6/dist-packages/funannotate/test.py", line 44, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-rna_seq_3237/rna-seq/predict_results/Awesome_rna.gff3'

It seems that now the problem is with EVM 

Thanks for your help!!
