### ISSUE TITLE
funannotate-runEVM.py - Fails when parsing genes.<PID>.bed

### ISSUE THREAD

**Issue by SusanECorbett** [nextgenusfs/funannotate#536]
My predict_misc/EVM/genes.<PID>.bed file was generated with more than three columns and funannotate-runEVM.py cannot parse it.
Line 146: chr, start, end = line.split('\t')
gives
ValueError: too many values to unpack (expected 3)

**Comment by nextgenusfs** [comment]
What version of funannotate, what install method, what commands did you run?

**Comment by kmkocot** [comment]
Greetings. I am having the same issue with funannotate v1.8.3. I hope it's helpful that I chimed in on this issue rather than starting a new one. I installed funannotate using pip and to the best of my knowledge, all the dependencies are installed and working normally. I am testing my installation using funannotate test. Here is the command used and the resulting output:
`wirenia@wirenia:~/Desktop/funannotate_test$ funannotate test -t all --cpus 38 --debug
#########################################################
Running `funannotate clean` unit testing: minimap2 mediated assembly duplications
Downloading: https://osf.io/8pjbe/download?version=1 Bytes: 252076
CMD: funannotate clean -i test.clean.fa -o test.exhaustive.fa --exhaustive
#########################################################
-----------------------------------------------
6 input contigs, 6 larger than 500 bp, N50 is 427,039 bp
Checking duplication of 6 contigs
-----------------------------------------------
scaffold_73 appears duplicated: 100% identity over 100% of the contig. contig length: 15153
scaffold_91 appears duplicated: 100% identity over 100% of the contig. contig length: 8858
scaffold_27 appears duplicated: 100% identity over 100% of the contig. contig length: 427039
-----------------------------------------------
6 input contigs; 6 larger than 500 bp; 3 duplicated; 3 written to file
#########################################################
SUCCESS: `funannotate clean` test complete.
#########################################################

#########################################################
Running `funannotate mask` unit testing: RepeatModeler --> RepeatMasker
Downloading: https://osf.io/hbryz/download?version=1 Bytes: 375687
CMD: funannotate mask -i test.fa -o test.masked.fa --cpus 38
#########################################################
-------------------------------------------------------
[05:16 PM]: OS: Ubuntu 18.04, 40 cores, ~ 66 GB RAM. Python: 3.6.9
[05:16 PM]: Running funanotate v1.8.3
[05:16 PM]: Soft-masking simple repeats with tantan
[05:16 PM]: Repeat soft-masking finished: 
Masked genome: /home/wirenia/Desktop/funannotate_test/test-mask_18416/test.masked.fa
num scaffolds: 2
assembly size: 1,216,048 bp
masked repeats: 50,965 bp (4.19%)
-------------------------------------------------------
#########################################################
SUCCESS: `funannotate mask` test complete.
#########################################################

#########################################################
Running `funannotate predict` unit testing
Downloading: https://osf.io/te2pf/download?version=1 Bytes: 1489808
CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --augustus_species saccharomyces --cpus 38 --species Awesome testicus
#########################################################
-------------------------------------------------------
[05:16 PM]: OS: Ubuntu 18.04, 40 cores, ~ 66 GB RAM. Python: 3.6.9
[05:16 PM]: Running funannotate v1.8.3
[05:16 PM]: Skipping CodingQuarry as no --rna_bam passed
[05:16 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     pretrained     
  genemark     selftraining   
  glimmerhmm   busco          
  snap         busco          
[05:16 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[05:16 PM]: Genome loaded: 6 scaffolds; 3,776,588 bp; 19.75% repeats masked
[05:16 PM]: Mapping 1,065 proteins to genome using diamond and exonerate
[05:16 PM]: Found 1,784 preliminary alignments --> aligning with exonerate
[05:16 PM]: Exonerate finished: found 1,421 alignments
[05:16 PM]: Running GeneMark-ES on assembly
[05:18 PM]: 1,532 predictions from GeneMark
[05:18 PM]: Running BUSCO to find conserved gene models for training ab-initio predictors
[05:18 PM]: Multi-threading in tblastn v2.6.0 is unstable, running in single threaded mode for BUSCO
[05:20 PM]: 373 valid BUSCO predictions found, validating protein sequences
[05:21 PM]: 370 BUSCO predictions validated
[05:21 PM]: Running Augustus gene prediction using saccharomyces parameters
[05:22 PM]: 1,490 predictions from Augustus
[05:22 PM]: Pulling out high quality Augustus predictions
[05:22 PM]: Found 367 high quality predictions from Augustus (>90% exon evidence)
[05:22 PM]: Running SNAP gene prediction, using training data: annotate/predict_misc/busco.final.gff3
[05:22 PM]: 1,517 predictions from SNAP
[05:22 PM]: Running GlimmerHMM gene prediction, using training data: annotate/predict_misc/busco.final.gff3
[05:23 PM]: 1,766 predictions from GlimmerHMM
[05:23 PM]: Summary of gene models passed to EVM (weights):
  Source         Weight   Count
  Augustus       1        1335 
  Augustus HiQ   2        368  
  GeneMark       1        1532 
  GlimmerHMM     1        1766 
  snap           1        1517 
  Total          -        6518 
[05:23 PM]: EVM: partitioning input to ~ 35 genes per partition
Traceback (most recent call last):
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 433, in <module>
    partitions=args.no_partitions)
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 146, in create_partitions
    chr, start, end = line.split('\t')
ValueError: too many values to unpack (expected 3)
[05:23 PM]: Evidence modeler has failed, exiting
Traceback (most recent call last):
  File "/home/wirenia/.local/bin/funannotate", line 713, in <module>
    main()
  File "/home/wirenia/.local/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/predict.py", line 1730, in main
    os.remove(EVM_out)
FileNotFoundError: [Errno 2] No such file or directory: '/home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/evm.round1.gff3'
#########################################################
Traceback (most recent call last):
  File "/home/wirenia/.local/bin/funannotate", line 713, in <module>
    main()
  File "/home/wirenia/.local/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/test.py", line 404, in main
    runPredictTest(args)
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/test.py", line 160, in runPredictTest
    tmpdir, 'annotate', 'predict_results', 'Awesome_testicus.gff3')) <= 1800
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/test.py", line 44, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-predict_18416/annotate/predict_results/Awesome_testicus.gff3'
`

The funannotate-predict.log file looks like this:
`[01/31/21 17:16:22]: /home/wirenia/.local/bin/funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --augustus_species saccharomyces --cpus 38 --species Awesome testicus

[01/31/21 17:16:22]: OS: Ubuntu 18.04, 40 cores, ~ 66 GB RAM. Python: 3.6.9
[01/31/21 17:16:22]: Running funannotate v1.8.3
[01/31/21 17:16:22]: GeneMark path: /usr/bin/gm_et_linux_64
[01/31/21 17:16:22]: Full path to gmes_petap.pl: /usr/bin/gm_et_linux_64/gmes_petap.pl
[01/31/21 17:16:22]: GeneMark appears to be functional? True
[01/31/21 17:16:22]: {'augustus': 1, 'hiq': 2, 'genemark': 1, 'pasa': 6, 'codingquarry': 0, 'snap': 1, 'glimmerhmm': 1, 'proteins': 1, 'transcripts': 1}
[01/31/21 17:16:22]: Skipping CodingQuarry as no --rna_bam passed
[01/31/21 17:16:22]: {'augustus': 'pretrained', 'genemark': 'selftraining', 'snap': 'busco', 'glimmerhmm': 'busco'}
[01/31/21 17:16:22]: Parsed training data, run ab-initio gene predictors as follows:
[01/31/21 17:16:23]: {'augustus': 1, 'hiq': 2, 'genemark': 1, 'pasa': 6, 'codingquarry': 0, 'snap': 1, 'glimmerhmm': 1, 'proteins': 1, 'transcripts': 1}
[01/31/21 17:16:23]: Loading genome assembly and parsing soft-masked repetitive sequences
[01/31/21 17:16:23]: Genome loaded: 6 scaffolds; 3,776,588 bp; 19.75% repeats masked
[01/31/21 17:16:36]: join_mult_hints.pl
[01/31/21 17:16:36]: Running GeneMark-ES on assembly
[01/31/21 17:16:36]: /usr/bin/gm_et_linux_64/gmes_petap.pl --ES --max_intron 3000 --soft_mask 2000 --cores 38 --sequence /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/genome.softmasked.fa --fungus
[01/31/21 17:18:10]: (None, b'')
[01/31/21 17:18:10]: perl /home/wirenia/EVidenceModeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl annotate/predict_misc/genemark.gff
[01/31/21 17:18:11]: 1,532 predictions from GeneMark
[01/31/21 17:18:11]: Running BUSCO to find conserved gene models for training ab-initio predictors
[01/31/21 17:18:11]: Multi-threading in tblastn v2.6.0 is unstable, running in single threaded mode for BUSCO
[01/31/21 17:18:11]: /usr/bin/python3.6 /home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-BUSCO2.py -i /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/genome.softmasked.fa -m genome --lineage /home/wirenia/blast_dbs/dikarya -o saccharomyces -c 38 --species anidulans -f --local_augustus /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/ab_initio_parameters/augustus
[01/31/21 17:20:24]: 373 valid BUSCO predictions found, validating protein sequences
[01/31/21 17:21:13]: 370 BUSCO predictions validated
[01/31/21 17:21:13]: Running Augustus gene prediction using saccharomyces parameters
[01/31/21 17:22:26]: perl /home/wirenia/EVidenceModeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl annotate/predict_misc/augustus.gff3
[01/31/21 17:22:26]: Pulling out high quality Augustus predictions
[01/31/21 17:22:26]: Found 367 high quality predictions from Augustus (>90% exon evidence)
[01/31/21 17:22:26]: Running SNAP gene prediction, using training data: annotate/predict_misc/busco.final.gff3
[01/31/21 17:22:26]: 370 gene models to train snap on 6 scaffolds
[01/31/21 17:22:26]: fathom /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/snap.training.zff /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/snap-training.scaffolds.fasta -categorize 1000 -min-intron 10 -max-intron 3000
[01/31/21 17:22:27]: fathom uni.ann uni.dna -export 1000 -plus
[01/31/21 17:22:27]: forge export.ann export.dna
[01/31/21 17:22:27]: perl /usr/bin/hmm-assembler.pl snap-trained annotate/predict_misc/snaptrain
[01/31/21 17:22:27]: snap /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/snap-trained.hmm /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/genome.softmasked.fa
[01/31/21 17:22:45]: 1,517 predictions from SNAP
[01/31/21 17:22:45]: Running GlimmerHMM gene prediction, using training data: annotate/predict_misc/busco.final.gff3
[01/31/21 17:22:45]: trainGlimmerHMM /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/genome.softmasked.fa /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/glimmer.exons -d annotate/predict_misc/glimmerhmm
[01/31/21 17:23:41]: perl /home/wirenia/GlimmerHMM/bin/glimmhmm.pl /home/wirenia/GlimmerHMM/bin/glimmerhmm /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/genome.softmasked.fa /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/glimmerhmm -g
[01/31/21 17:23:53]: 1,766 predictions from GlimmerHMM
[01/31/21 17:23:53]: Prediction sources: ['Augustus', 'HiQ', 'GeneMark', 'GlimmerHMM', 'snap']
[01/31/21 17:23:53]: Summary of gene models: {'total': 6518, 'Augustus': 1335, 'HiQ': 368, 'GeneMark': 1532, 'GlimmerHMM': 1766, 'snap': 1517}
[01/31/21 17:23:53]: EVM Weights: {'Augustus': 1, 'HiQ': 2, 'GeneMark': 1, 'GlimmerHMM': 1, 'snap': 1, 'proteins': 1}
[01/31/21 17:23:53]: Summary of gene models passed to EVM (weights):
[01/31/21 17:23:53]: Launching EVM via funannotate-runEVM.py
[01/31/21 17:23:53]: /usr/bin/python3.6 /home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-runEVM.py -w /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/weights.evm.txt -c 38 -g /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/gene_predictions.gff3 -d /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/EVM -f /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/genome.softmasked.fa -l annotate/logfiles/funannotate-EVM.log -m 10 -o /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/evm.round1.gff3 --EVM_HOME /home/wirenia/EVidenceModeler-1.1.1 -p /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/protein_alignments.gff3
[01/31/21 17:23:54]: Evidence modeler has failed, exiting`

I treid to run that last command that failed (and wrap my head around an issue it is having the EVM log file) and here's what I got:
`wirenia@wirenia:~/Desktop/funannotate_test$ /usr/bin/python3.6 /home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-runEVM.py -w /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/weights.evm.txt -c 38 -g /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/gene_predictions.gff3 -d /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/EVM -f /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/genome.softmasked.fa -l annotate/logfiles/funannotate-EVM.log -m 10 -o /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/evm.round1.gff3 --EVM_HOME /home/wirenia/EVidenceModeler-1.1.1 -p /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/predict_misc/protein_alignments.gff3
Traceback (most recent call last):
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 396, in <module>
    lib.setupLogging(log_name)
  File "/home/wirenia/.local/lib/python3.6/site-packages/funannotate/library.py", line 1216, in setupLogging
    fhnd = logging.FileHandler(LOGNAME)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/wirenia/Desktop/funannotate_test/annotate/logfiles/funannotate-EVM.log'
wirenia@wirenia:~/Desktop/funannotate_test$ ls /home/wirenia/Desktop/funannotate_test/annotate/logfiles/funannotate-EVM.log
ls: cannot access '/home/wirenia/Desktop/funannotate_test/annotate/logfiles/funannotate-EVM.log': No such file or directory
wirenia@wirenia:~/Desktop/funannotate_test$ ls /home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/logfiles/funannotate-EVM.log
/home/wirenia/Desktop/funannotate_test/test-predict_18416/annotate/logfiles/funannotate-EVM.log
`

Thank you,
Kevin

**Comment by kmkocot** [comment]
Forgive the crazy formatting... I tried to use the insert code feature but it's not cooperating.
