### ISSUE TITLE
File not found with log files issue

### ISSUE THREAD

**Issue by Lamm-a** [nextgenusfs/funannotate#543]
**The error**

```
Traceback (most recent call last):
  File "/services/tools/funannotate/1.8.3/bin/funannotate", line 713, in <module>
    main()
  File "/services/tools/funannotate/1.8.3/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/services/tools/funannotate/1.8.3/lib/python3.6/site-packages/funannotate/mask.py", line 129, in main
    os.remove(log_name)
FileNotFoundError: [Errno 2] No such file or directory: 'funannotate-mask.log'
```

**The input command**
`funannotate mask -i $input -o $outfile --cpus 2`

The inputs are variable but some variation of `/path/to/inputFile/<someFile>.fasta ` and `/path/to/outputFile/<someFile>_masked.fasta
`
**Version info**

v1.8.3

**Comment by nextgenusfs** [comment]
what is the result of `funannotate test -t mask`?

**Comment by Lamm-a** [comment]
It seems to be the expected result:
```
#########################################################
Running `funannotate mask` unit testing: RepeatModeler --> RepeatMasker
Downloading: https://osf.io/hbryz/download?version=1 Bytes: 375687                                   CMD: funannotate mask -i test.fa -o test.masked.fa --cpus 2
#########################################################
-------------------------------------------------------
[08:44 AM]: OS: CentOS Linux 7, 40 cores, ~ 1585 GB RAM. Python: 3.6.10
[08:44 AM]: Running funanotate v1.8.3
[08:44 AM]: Soft-masking simple repeats with tantan
[08:44 AM]: Repeat soft-masking finished:
Masked genome: /home/people/robmur/test-mask_40892/test.masked.fa
num scaffolds: 2
assembly size: 1,216,048 bp
masked repeats: 50,965 bp (4.19%)
-------------------------------------------------------
#########################################################
SUCCESS: `funannotate mask` test complete.
#########################################################
```

**Comment by Lamm-a** [comment]
I have managed to resolve the issue and it is now working. I do however sometimes now get this on some runs:

```
[09:29 AM]: OS: CentOS Linux 7, 40 cores, ~ 198 GB RAM. Python: 3.6.10
[09:29 AM]: Running funanotate v1.8.3
[09:29 AM]: Soft-masking simple repeats with tantan
[09:30 AM]: Repeat soft-masking finished:
Masked genome: /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/funannotate-output/IC0034_sorted_masked.fasta
num scaffolds: 1,672
assembly size: 58,150,346 bp
masked repeats: 1,928,522 bp (3.32%)
--- Logging error ---
Traceback (most recent call last):
  File "/services/tools/funannotate/1.8.3/lib/python3.6/logging/__init__.py", line 998, in emit
    self.flush()
  File "/services/tools/funannotate/1.8.3/lib/python3.6/logging/__init__.py", line 978, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Call stack:
  File "/services/tools/funannotate/1.8.3/bin/funannotate", line 713, in <module>
    main()
  File "/services/tools/funannotate/1.8.3/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/services/tools/funannotate/1.8.3/lib/python3.6/site-packages/funannotate/mask.py", line 190, in main
    os.path.abspath(args.out), scaffolds, GenomeLength, maskedSize, percentMask*100))
Message: 'Repeat soft-masking finished: \nMasked genome: /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/funannotate-output/IC0034_sorted_masked.fasta\nnum scaffolds: 1,672\nassembly size: 58,150,346 bp\nmasked repeats: 1,928,522 bp (3.32%)'
Arguments: ()
```
The masking seems to finish but with some errors I can only assume it then handles itself?
