### ISSUE TITLE
NameError: name 'LAUNCHPASA' is not defined

### ISSUE THREAD

**Issue by Lamm-a** [nextgenusfs/funannotate#550]
**The error**
When running `funannotate train` this error keeps occurring:

```
[11:56 AM]: OS: CentOS Linux 7, 40 cores, ~ 198 GB RAM. Python: 3.6.10
[11:56 AM]: Running 1.8.3
Traceback (most recent call last):
  File "/services/tools/funannotate/1.8.3/bin/funannotate", line 713, in <module>
    main()
  File "/services/tools/funannotate/1.8.3/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/services/tools/funannotate/1.8.3/lib/python3.6/site-packages/funannotate/train.py", line 748, in main
    'kallisto', LAUNCHPASA, os.path.join(PASA, 'bin', 'seqclean')]
NameError: name 'LAUNCHPASA' is not defined
```

**Input command**

`funannotate train -i $input -o $outdir --left $rnaLeft --right $rnaRight --stranded no`

all variables are just variations of file paths to sorted and masked (in that order) genomes.
The RNA are trimmed to q30 and nothing further has been done to them.

**Version info**

v1.8.3

**Comment by nextgenusfs** [comment]
I'm going to suggest the same thing to test the install, 'funannotate test -t rna-seq'.

**Comment by Lamm-a** [comment]
This is the response:

```
CMD: funannotate train -i test.softmasked.fa --single rna-seq.illumina.fastq.gz --nanopore_mrna rna-seq.nanopore.fastq.gz -o rna-seq --cpus 2 --jaccard_clip --species Awesome rna]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]#########################################################]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]-------------------------------------------------------]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]][03:26 PM]: OS: CentOS Linux 7, 40 cores, ~ 1585 GB RAM. Python: 3.6.10]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]][03:26 PM]: Running 1.8.3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]Traceback (most recent call last):]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]  File "/services/tools/funannotate/1.8.3/bin/funannotate", line 713, in <module>]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]    main()]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]  File "/services/tools/funannotate/1.8.3/bin/funannotate", line 703, in main]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]    mod.main(arguments)]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]  File "/services/tools/funannotate/1.8.3/lib/python3.6/site-packages/funannotate/train.py", line 748, in main]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]    'kallisto', LAUNCHPASA, os.path.join(PASA, 'bin', 'seqclean')]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]NameError: name 'LAUNCHPASA' is not defined]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]#########################################################]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]Now running `funannotate predict` using RNA-seq training data]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o rna-seq --cpus 2 --min_training_models 150 --species Awesome rna]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]#########################################################]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]-------------------------------------------------------]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]][03:26 PM]: OS: CentOS Linux 7, 40 cores, ~ 1585 GB RAM. Python: 3.6.10]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]][03:26 PM]: Running funannotate v1.8.3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]][03:26 PM]: Funannotate database not properly configured, run funannotate setup.]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]Traceback (most recent call last):]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]  File "/services/tools/funannotate/1.8.3/bin/funannotate", line 713, in <module>]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]    main()]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]  File "/services/tools/funannotate/1.8.3/bin/funannotate", line 703, in main]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]    mod.main(arguments)]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]  File "/services/tools/funannotate/1.8.3/lib/python3.6/site-packages/funannotate/test.py", line 408, in main]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]    runRNAseqTest(args)]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]  File "/services/tools/funannotate/1.8.3/lib/python3.6/site-packages/funannotate/test.py", line 347, in runRNAseqTest]]]]]]]]]]]]]]]]]]]]]]]]]]]]]    tmpdir, 'rna-seq', 'predict_results', 'Awesome_rna.gff3')) <= 1830]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]  File "/services/tools/funannotate/1.8.3/lib/python3.6/site-packages/funannotate/test.py", line 44, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-rna_seq_10273/rna-seq/predict_results/Awesome_rna.gff3'
```

**Comment by Lamm-a** [comment]
Would you have any more advice on what is happening here?

**Comment by nextgenusfs** [comment]
Seems like you are behind a proxy/firewall of some sort. 
```
$ funannotate test

Usage:       funannotate test <arguments>
version:     1.8.4

Description: This is a script that runs several unit tests.  It will download data and run
             several different tests to determine if installion is functioning properly. If
             you cannot download from the machine funannotate is installed at - then download
             the 7 tar.gz files from https://osf.io/bj7v4/files/ and run script from directory

Arguments:
  -t, --tests    Test sets to run. [all,clean,mask,predict,busco,rna-seq,annotate,compare]
  --cpus         Number of cpus to use. Default: 2
  --debug        Keep output files
```
From the help: `then download the 7 tar.gz files from https://osf.io/bj7v4/files/ and run script from directory`

**Comment by Lamm-a** [comment]
is there a way to specify where the `funannotate test` will download stuff. it seems to default to `$HOME` ?
