### ISSUE TITLE
Can not use until command convert gff3 to tbl format!

### ISSUE THREAD

**Issue by sunnycqcn** [nextgenusfs/funannotate#557]
Hello Jon,
Recently, I want to convert some gff3 files to tbl format or gbk format. I used the command as following:
`funannotate util gff2tbl -g ZS11.fa -f ZS11.gff3`
Howerver, I get the error as following:
`Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/bin/funannotate", line 713, in <module>
    main()
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/bin/funannotate", line 703, in main
    mod.main(arguments)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/utilities/gff2tbl.py", line 335, in main
    Genes = lib.gff2dict(args.gff3, args.fasta, Genes)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/library.py", line 4168, in gff2dict
    contig, source, feature, start, end, score, strand, phase, attributes = line.split('\t')
ValueError: not enough values to unpack (expected 9, got 1)
`
Thanks,
Fuyou

**Comment by nextgenusfs** [comment]
Looks like you have some non-standard lines in your GFF3 file. You can see which lines have less than 8 tabs with awk:
```
awk -F'\t' 'NF<=8 {print}' your_file.gff3
```

**Comment by sunnycqcn** [comment]
Hello Jon,
Thanks.
Maybe you are right. I have fixed using agat tools.
`agat_convert_sp_gxf2gxf.pl --gff Rsa.gff3 -o Rsa.Z.gff3`
Fuyou
