### ISSUE TITLE
Interproscan5 not screening 

### ISSUE THREAD

**Issue by danielardaniela** [nextgenusfs/funannotate#564]
Are you using the latest release?
v1.8.3

Describe the bug
I have run interproscan on two separate machine with an empty output. The print out appears as below: 
`cat iprscan

</protein-matches>`
I thought there were just no hits, so I used the file as input for funannotate annotate function and recieve the error below: 

`funannotate annotate -i fun_predict6 --eggnog eggnog.tsv --iprscan iprscan --cpus 15
-------------------------------------------------------
[07:16 PM]: OS: CentOS 6.10, 48 cores, ~ 265 GB RAM. Python: 3.5.1
[07:16 PM]: Running 1.8.3
[07:16 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[07:16 PM]: Found existing output directory fun_predict6. Warning, will re-use any intermediate files found.
[07:16 PM]: Parsing input files
[07:16 PM]: Existing tbl found: fun_predict6/update_results/hvir.tbl
[07:17 PM]: Adding Functional Annotation to hvir, NCBI accession: None
[07:17 PM]: Annotation consists of: 24,927 gene models
[07:17 PM]: 24,710 protein records loaded
[07:17 PM]: Existing Pfam-A results found: fun_predict6/annotate_misc/annotations.pfam.txt
[07:17 PM]: 18,026 annotations added
[07:17 PM]: Running Diamond blastp search of UniProt DB version 2021_01
[07:17 PM]: 1,133 valid gene/product annotations from 2,036 total
[07:17 PM]: Existing Eggnog-mapper results found: fun_predict6/annotate_misc/eggnog.emapper.annotations
[07:17 PM]: Parsing EggNog Annotations
[07:17 PM]: 5,571 COG and EggNog annotations added
[07:17 PM]: Combining UniProt/EggNog gene and product names using Gene2Product version 1.65
[07:17 PM]: 1,133 gene name and product description annotations added
[07:17 PM]: Existing MEROPS results found: fun_predict6/annotate_misc/annotations.merops.txt
[07:17 PM]: 608 annotations added
[07:17 PM]: Existing CAZYme results found: fun_predict6/annotate_misc/annotations.dbCAN.txt
[07:17 PM]: 235 annotations added
[07:17 PM]: Existing BUSCO2 results found: fun_predict6/annotate_misc/annotations.busco.txt
[07:17 PM]: 624 annotations added
[07:17 PM]: Skipping phobius predictions, try funannotate remote -m phobius
[07:17 PM]: Existing SignalP results found: fun_predict6/annotate_misc/signalp.results.txt
[07:17 PM]: 1,633 secretome and 0 transmembane annotations added
[07:17 PM]: Parsing InterProScan5 XML file
[07:17 PM]: CMD ERROR: /usr/local/bin/python3.5 /home/alice/.local/lib/python3.5/site-packages/funannotate/aux_scripts/iprscan2annotations.py fun_predict6/annotate_misc/iprscan.xml fun_predict6/annotate_misc/annotations.iprscan.txt
[07:17 PM]: Traceback (most recent call last):
  File "/home/alice/.local/lib/python3.5/site-packages/funannotate/aux_scripts/iprscan2annotations.py", line 32, in <module>
    for _, elem in tree:
  File "/usr/local/lib/python3.5/xml/etree/ElementTree.py", line 1289, in __next__
    for event in self._parser.read_events():
  File "/usr/local/lib/python3.5/xml/etree/ElementTree.py", line 1272, in read_events
    raise event
  File "/usr/local/lib/python3.5/xml/etree/ElementTree.py", line 1230, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1
`

I'm not sure if this is an interproscan error or an error with reading the file. 
Thank you in advance!

**Comment by nextgenusfs** [comment]
The error here is because you didn't pass an XML file to `--iprscan`.  So quite clearly your interproscan runs failed.

**Comment by danielardaniela** [comment]
Originally, I ran the funannotate iprscan function with the output as ipr.xml and still ran into the same problem. 
` funannotate iprscan -i fun_predict6 -m local -o ipr.xml --iprscan_path /home/alice/software/interproscan/interproscan.sh --cpus 15
`
In this case I just did not include the output flag so I was provided with a file just called interproscan, but I also experience the same problem with the xml file. Sorry for not indicating that initially

**Comment by nextgenusfs** [comment]
Check your interproscan install -- can you run their test data successfully?
