### ISSUE TITLE
Missing hints file

### ISSUE THREAD

**Issue by CDRism** [nextgenusfs/funannotate#575]
Hello - I am having a problem with missing hints file. This was addressed before (https://github.com/nextgenusfs/funannotate/issues/482), but I don't have a small genome. Here is my code and the output I receive

funannotate predict -i scelnum3.fna -s "xxx" -o Chromosomes_NEW_TRI --busco_seed_species human --busco_db tetrapoda
--organism other --repeats2evm --cpus 40 --max_intronlen 500000 --optimize_augustus

(where xxx has a species name instead)

Loading genome assembly and parsing soft-masked repetitive sequences
Program Training-Method
augustus busco
genemark selftraining
glimmerhmm busco
snap busco
[04:37 PM]: Genome loaded: 596 scaffolds; 323,480,233 bp; 37.09% repeats masked
[04:37 PM]: Mapping 551,648 proteins to genome using diamond and exonerate
[04:39 PM]: Found 0 preliminary alignments --> aligning with exonerate
[04:39 PM]: Exonerate finished: found 0 alignments
Traceback (most recent call last):
File "/apps/software/standard/core/funannotate/1.8.3/bin/funannotate", line 713, in
main()
File "/apps/software/standard/core/funannotate/1.8.3/bin/funannotate", line 703, in main
mod.main(arguments)
File "/apps/software/standard/core/funannotate/1.8.3/lib/python2.7/site-packages/funannotate/predict.py", line 1014, in main
lib.sortHints(allhintstmp, allhintstmp_sort)
File "/apps/software/standard/core/funannotate/1.8.3/lib/python2.7/site-packages/funannotate/library.py", line 8486, in sortHints
with open(input, 'r') as infile:
IOError: [Errno 2] No such file or directory: u'Chromosomes_NEW_TRI/predict_misc/hints.all.tmp'

After training, when I look in the predict_misc folder, I see the following:

ab_initio_parameters genome.softmasked.fa p2g.diamond.out proteins.combined.fa scaffold.sort.order.txt
assembly-gaps.bed hints.P.gff protein_alignments.gff3 repeatmasker.bed scaffold.sort.rename.txt

My training code was as follows: 

funannotate train -i scelnum3.fna -o Chromosomes_NEW_TRI \
--left_norm left.fastq \
--right_norm right.fastq \
--max_intronlen 500000 \
--species "xxx" \
--cpus 40

The logs from funannotate-trinity.log said

 /apps/software/standard/core/funannotate/1.8.3/lib/python2.7/site-packages/funannotate/aux_scripts/trinity.py -f Chromosomes_NEW_TRI/training/genome.fasta -o Chromosomes_NEW_TRI/training/trinity.fasta -b Chromosomes_NEW_TRI/training/hisat2.coordSorted.bam -t Chromosomes_NEW_TRI/training --stranded no --max_intronlen 500000 --cpus 40 --TRINITYHOME  --memory 50G --logfile Chromosomes_NEW_TRI/logfiles/funannotate-trinity.log -l left.fastq -r right.fastq

[03/20/21 13:55:17]: Existig Hisat2 alignments found: Chromosomes_NEW_TRI/training/hisat2.coordSorted.bam
[03/20/21 13:55:17]: Running genome-guided Trinity, logfile: Chromosomes_NEW_TRI/training/Trinity-gg.log
[03/20/21 13:55:17]: Clustering of reads from BAM and preparing assembly commands
[03/20/21 13:55:17]: Trinity --no_distributed_trinity_exec --genome_guided_bam Chromosomes_NEW_TRI/training/hisat2.coordSorted.bam --genome_guided_max_intron 500000 --CPU 40 --max_memory 50G --output Chromosomes_NEW_TRI/training/trinity_gg
[03/20/21 13:55:19]: Assembling 29,892 Trinity clusters using 39 CPUs
[03/20/21 15:32:25]: perl /sfs/lustre/bahamut/scratch/cdr4ua/allreads/util/support_scripts/GG_partitioned_trinity_aggregator.pl Trinity_GG
[03/20/21 15:32:25]: CMD ERROR: perl /sfs/lustre/bahamut/scratch/cdr4ua/allreads/util/support_scripts/GG_partitioned_trinity_aggregator.pl Trinity_GG
[03/20/21 15:32:25]: (None, 'Can\'t open perl script "/sfs/lustre/bahamut/scratch/cdr4ua/allreads/util/support_scripts/GG_partitioned_trinity_aggregator.pl": No such file or directory\n')

Any advice? This is funannotate version 1.8.3

**Comment by nextgenusfs** [comment]
Hmm, well I guess what version of Trinity and does `/sfs/lustre/bahamut/scratch/cdr4ua/allreads/util/support_scripts/GG_partitioned_trinity_aggregator.pl` this file perl script not exist?  Seems like a Trinity issue on the training step.  So did `funannotate train` finish correctly?  

If you have the log files from these runs that will be more informative than the stdout.

**Comment by CDRism** [comment]
Thanks for getting back to me.

Trinity v2.11.0

Here is the output from funannotate-train.log (I hope this is what you were asking for)

[03/20/21 13:55:04]: OS: linux2, 40 cores, ~ 395 GB RAM. Python: 2.7.15
[03/20/21 13:55:04]: Running 1.8.3
[03/20/21 13:55:16]: Input reads: (None, None, None)
[03/20/21 13:55:16]: Trimmomatic will be skipped
[03/20/21 13:55:16]: Quality trimmed reads: (None, None, None)
[03/20/21 13:55:16]: Read normalization will be skipped
[03/20/21 13:55:16]: Normalized reads: ('left.fastq', 'right.fastq', None)
[03/20/21 13:55:16]: Long reads: (None, None, None)
[03/20/21 13:55:16]: Long reads FASTA format: (None, None, None)
[03/20/21 13:55:16]: Long SeqCleaned reads: (None, None, None)
[03/20/21 15:32:25]: ERROR: Trinity de novo assembly failed

**Comment by nextgenusfs** [comment]
Okay, so hopefully makes sense where problem is?  Trinity failed, so seems like a Trinity issue -- you should be able to see the logs in trinity.log and see which commands it ran.  The predict error is related to train not finishing correctly.

**Comment by CDRism** [comment]
I see. So do you think the issue is with the perl script posted in my first comment? I assumed the perl scripts were a part of the wrapper. Am I missing a folder that I am supposed to populate before running my train function?

**Comment by nextgenusfs** [comment]
No that is part of Trinity -- so its something with your install, version, etc.

**Comment by CDRism** [comment]
Got it, thanks. I will contact our cluster support staff.
