### ISSUE TITLE
Error during funannotate compare 

### ISSUE THREAD

**Issue by padosory** [nextgenusfs/funannotate#579]
Hello.
I am having the following errors when I perform comparative analysis. 

funannotate compare -i gbk -o compare --cpus 32 --run_dnds full
-------------------------------------------------------
[02:30 PM]: OS: linux2, 48 cores, ~ 1056 GB RAM. Python: 2.7.15
[02:30 PM]: Running 1.7.4
[02:30 PM]: Now parsing 1 genomes
[02:30 PM]: working on Trichoderma simmonsii
[02:30 PM]: Summarizing secondary metabolism gene clusters
[02:30 PM]: Summarizing PFAM domain results
[02:30 PM]: Summarizing InterProScan results
[02:30 PM]: Loading InterPro descriptions
[02:30 PM]: Summarizing MEROPS protease results
[02:30 PM]: Summarizing CAZyme results
[02:30 PM]: Summarizing COG results
Traceback (most recent call last):
  File "/home/yiy/.conda/envs/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "/home/yiy/.conda/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/home/yiy/.conda/envs/funannotate/lib/python2.7/site-packages/funannotate/compare.py", line 650, in main
    COGSdf.columns = LongNames
  File "/home/yiy/.conda/envs/funannotate/lib/python2.7/site-packages/pandas/core/generic.py", line 5080, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/yiy/.conda/envs/funannotate/lib/python2.7/site-packages/pandas/core/generic.py", line 638, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/yiy/.conda/envs/funannotate/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 155, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 16 elements, new values have 14 elements

**Comment by hyphaltip** [comment]
can you include what version of funannotate - I assume you just have a folder of gbk format files? have you run `funannotate annotate` step on all the gbk files?

**Comment by ddiazescandon** [comment]
I'm getting problems at the same step comparing a mixed dataset of gbff and local gbk.
(kind of unrelated with this current issue)  

[01:21 AM]: OS: linux2, 32 cores, ~ 248 GB RAM. Python: 2.7.15                                                                       
[01:21 AM]: Running 1.8.1                                                                                                            
[01:21 AM]: Now parsing 79 genomes 
[01:42 AM]: Summarizing secondary metabolism gene clusters
[01:42 AM]: Summarizing PFAM domain results
[01:42 AM]: Summarizing InterProScan results 
[01:43 AM]: Loading InterPro descriptions
[01:43 AM]: Summarizing MEROPS protease results
[01:43 AM]: Merops annotation was run with older database than currently installed, please re-run 
[01:43 AM]: Merops annotation was run with older database than currently installed, please re-run 
[01:43 AM]: found 28/107 MEROPS familes with stdev >= 1.000000
[01:43 AM]: Summarizing CAZyme results
[01:43 AM]: found 50/216 CAZy familes with stdev >= 1.000000
[01:43 AM]: Summarizing COG results
Traceback (most recent call last):
  File "/data/diazesca/miniconda/envs/funannotate-env/bin/funannotate", line 688, in <module>
    main()
  File "/data/diazesca/miniconda/envs/funannotate-env/bin/funannotate", line 678, in main
    mod.main(arguments)
  File "/data/diazesca/miniconda/envs/funannotate-env/lib/python2.7/site-packages/funannotate/compare.py", line 655, in main
    args.out, 'cogs', 'COGS.graph.pdf'))
  File "/data/diazesca/miniconda/envs/funannotate-env/lib/python2.7/site-packages/funannotate/library.py", line 7729, in donutplot
    plt.pie(data[0], labels=names, colors=color_palette)
  File "/data/diazesca/miniconda/envs/funannotate-env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3343, in pie
    frame=frame, rotatelabels=rotatelabels, data=data)
  File "/data/diazesca/miniconda/envs/funannotate-env/lib/python2.7/site-packages/matplotlib/__init__.py", line 1870, in inner
    return func(ax, *args, **kwargs)
  File "/data/diazesca/miniconda/envs/funannotate-env/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 2911, in pie
    **wedgeprops)
  File "/data/diazesca/miniconda/envs/funannotate-env/lib/python2.7/site-packages/matplotlib/patches.py", line 1070, in __init__
    self._recompute_path()
  File "/data/diazesca/miniconda/envs/funannotate-env/lib/python2.7/site-packages/matplotlib/patches.py", line 1082, in _recompute_pa
th
    arc = Path.arc(theta1, theta2)
  File "/data/diazesca/miniconda/envs/funannotate-env/lib/python2.7/site-packages/matplotlib/path.py", line 874, in arc
    n = int(2 ** np.ceil((eta2 - eta1) / halfpi))
ValueError: cannot convert float NaN to integer

**Comment by padosory** [comment]
The funannotate version is 1.7.4.
O.K. I will re-annnotate already annotated references using funannotate annotate. 
Thanks.
