### ISSUE TITLE
No module named library

### ISSUE THREAD

**Issue by hychenIG** [nextgenusfs/funannotate#584]
Hi, I face some issues after I updated to v1.8.6. where I run 'funannotate check' and funannotate setup' I get the follow feedback: 

Traceback (most recent call last):
  File "/home/intact/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/intact/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/funannotate.py", line 704, in main
    '{:}.{:}'.format(package_name, info[cmdName]['cmd']))
  File "/home/intact/miniconda3/envs/funannotate/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/intact/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/check.py", line 11, in <module>
    import funannotate.library as lib
ImportError: No module named library

Traceback (most recent call last):
  File "/home/intact/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/intact/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/funannotate.py", line 704, in main
    '{:}.{:}'.format(package_name, info[cmdName]['cmd']))
  File "/home/intact/miniconda3/envs/funannotate/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/intact/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 21, in <module>
    import funannotate.library as lib
ImportError: No module named library

Please help me with this, thanks!
Hongyu

**Comment by nextgenusfs** [comment]
Something seems wrong with your install - it should be installed in site-packages. Are you able to upgrade to python3?

**Comment by hychenIG** [comment]
I install this through miniconda. I have python2 and python3 in my system. but the package using python2. how to switch the python2 to python3.

**Comment by nextgenusfs** [comment]
Remove it and reinstall with py3

conda env remove -n funannotate 


conda create -n funannotate "python=3" funannotate

**Comment by hychenIG** [comment]
I have a issue with conda 'Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.' and then is 'Collecting package metadata (repodata.json): done'  stack in Solving environment. 

Even I removed miniconda and reinstall it

**Comment by nextgenusfs** [comment]
You might try mamba, conda install -n base mamba. And then mamba is a drop in replacement for conda.

**Comment by hychenIG** [comment]
Thank you, the problem has been fixed.
