### ISSUE TITLE
Database setup failing

### ISSUE THREAD

**Issue by fmobegi** [nextgenusfs/funannotate#596]
I Am unable to complete the setup of funannnotate databases. getting the following error

```
funannotate setup -d $HOME/funannotate_db
-------------------------------------------------------
[May 14 03:06 AM]: OS: Ubuntu 21.04, 12 cores, ~ 33 GB RAM. Python: 3.8.7
[May 14 03:06 AM]: Running 1.8.7
[May 14 03:06 AM]: Database location: /home/fredrick/funannotate_db
[May 14 03:06 AM]: Retrieving download links from GitHub Repo
[May 14 03:06 AM]: Parsing Augustus pre-trained species and porting to funannotate
Traceback (most recent call last):
  File "/home/fredrick/.local/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/home/fredrick/.local/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/home/fredrick/.local/lib/python3.8/site-packages/funannotate/setupDB.py", line 694, in main
    meropsDB(DatabaseInfo, args.force, args=args)
  File "/home/fredrick/.local/lib/python3.8/site-packages/funannotate/setupDB.py", line 139, in meropsDB
    type, name, version, date, records, checksum = info.get('merops')
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by fmobegi** [comment]
setting up the database location and running `funannotate setup -i all --update` bypassed the error. But the `funannotate setup -d $HOME/funannotate_db` doesn't work
