### ISSUE TITLE
EVM failed

### ISSUE THREAD

**Issue by Thatguy027** [nextgenusfs/funannotate#598]
Hello,
I ran into an issue that I am struggling to get around and am hoping you might have some insight! The requested details are below, please let me know if you need any more detail.
Thanks!
Stefan

**Are you using the latest release?**
funannotate v1.8.7. All dependencies and environmental variables found, except an issue with `signalp` 

**Describe the bug**
Error in `funannotate predict` at the `funannotate-runEVM.py` step

Error in predict.log:
```
[05/22/21 15:56:47]: 27,435 predictions from SNAP
[05/22/21 15:56:47]: Running GlimmerHMM gene prediction, using training data: ./predict_misc/busco.final.gff3
[05/22/21 15:56:48]: trainGlimmerHMM /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/genome.softmasked.fa /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/glimmer.exons -d ./predict_misc/glimmerhmm
[05/22/21 16:01:46]: perl /u/project/kruglyak/thatguy0/conda/envs/funannotate/bin/glimmhmm.pl /u/project/kruglyak/thatguy0/conda/envs/funannotate/bin/glimmerhmm /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/genome.softmasked.fa /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/glimmerhmm -g
[05/22/21 16:10:42]: 26,067 predictions from GlimmerHMM
[05/22/21 16:10:45]: Prediction sources: ['HiQ', 'Augustus', 'GeneMark', 'GlimmerHMM', 'snap']
[05/22/21 16:10:47]: Summary of gene models: {'total': 93734, 'HiQ': 8531, 'Augustus': 8629, 'GeneMark': 23072, 'GlimmerHMM': 26067, 'snap': 27435}
[05/22/21 16:10:47]: EVM Weights: {'HiQ': 2, 'Augustus': 1, 'GeneMark': 1, 'GlimmerHMM': 1, 'snap': 1, 'proteins': 1, 'transcripts': 1}
[05/22/21 16:10:47]: Summary of gene models passed to EVM (weights):
[05/22/21 16:10:47]: Launching EVM via funannotate-runEVM.py
[05/22/21 16:10:47]: /u/project/kruglyak/thatguy0/conda/envs/funannotate/bin/python /u/project/kruglyak/thatguy0/conda/envs/funannotate/lib/python3.7/site-packages/funannotate/aux_scripts/funannotate-runEVM.py -w /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/weights.evm.txt -c 8 -g /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/gene_predictions.gff3 -d /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/EVM -f /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/genome.softmasked.fa -l ./logfiles/funannotate-EVM.log -m 10 -i 1500 -o /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/evm.round1.gff3 --EVM_HOME /u/project/kruglyak/thatguy0/conda/envs/funannotate/opt/evidencemodeler-1.1.1 -p /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/protein_alignments.gff3 -t /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/transcript_alignments.gff3
[05/22/21 16:10:56]: Evidence modeler has failed, exiting
```

Error when running command in log:
```
(funannotate) [thatguy0@n6457 fun_predict]$ /u/project/kruglyak/thatguy0/conda/envs/funannotate/bin/python /u/project/kruglyak/thatguy0/conda/envs/funannotate/lib/python3.7/site-packages/funannotate/aux_scripts/funannotate-runEVM.py \
> -w /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/weights.evm.txt \
> -c 8 \
> -g /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/gene_predictions.gff3 \
> -d /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/EVM \
> -f /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/genome.softmasked.fa \
> -l ./logfiles/funannotate-EVM.log -m 10 -i 1500 \
> -o /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/evm.round1.gff3 \
> --EVM_HOME /u/project/kruglyak/thatguy0/conda/envs/funannotate/opt/evidencemodeler-1.1.1 \
> -p /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/protein_alignments.gff3 \
> -t /u/project/kruglyak/thatguy0/genomics/rnaseq/trinity_out_dir_genome_assisted/funannotate_run/fun_predict/predict_misc/transcript_alignments.gff3
[May 24 10:57 AM]: EVM: partitioning input to ~ 35 genes per partition using min 1500 bp interval
Traceback (most recent call last):
  File "/u/project/kruglyak/thatguy0/conda/envs/funannotate/lib/python3.7/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 484, in <module>
    partitions=args.no_partitions)
  File "/u/project/kruglyak/thatguy0/conda/envs/funannotate/lib/python3.7/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 224, in create_partitions
    splitTup, idx = getBreakPoint(v, loc, direction='reverse', gap=interval)
TypeError: cannot unpack non-iterable bool object
```

**What command did you issue?**
```
funannotate train -i XZ1516_renamed.fasta -o fun_XZ1516 \
    --left ../../XZ1516_GZ_B5_A8_CKDL190141490-1a-AK1952-AK2044_HV3TFDSXX_L3_1.fq.gz \
    --right ../../XZ1516_GZ_B5_A8_CKDL190141490-1a-AK1952-AK2044_HV3TFDSXX_L3_2.fq.gz \
    --stranded no --species "caenorhabditis" \
    --strain XZ1516 --cpus 8

#[May 21 05:53 PM]: PASA database name: caenorhabditis_XZ1516
#[May 21 05:53 PM]: Trinity/PASA has completed, you are now ready to run funanotate predict, for example:
#
#  funannotate predict -i XZ1516_renamed.fasta -o fun_XZ1516 -s "caenorhabditis" --strain XZ1516 --cpus 8

funannotate predict -i ../XZ1516_renamed.fasta \
	--species "caenorhabditis" \
	--isolate XZ1516 \
	--transcript_evidence ../fun_XZ1516/training/trinity.fasta.clean \
	--rna_bam ../Aligned.sortedByCoord.out.bam \
	--busco_db nematoda \
	--cpus 8 \
	--organism other \
	--busco_seed_species caenorhabditis \
	-o .
```

**Logfiles**
[logfiles.zip](https://github.com/nextgenusfs/funannotate/files/6534168/logfiles.zip)

**OS/Install Information**
```
(funannotate) [thatguy0@n6457 fun_predict]$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.8.7
-------------------------------------------------------
You are running Python v 3.7.10. Now checking python packages...
biopython: 1.78
goatools: 1.0.15
matplotlib: 3.4.2
natsort: 7.1.1
numpy: 1.20.2
pandas: 1.2.4
psutil: 5.8.0
requests: 2.25.1
scikit-learn: 0.24.2
scipy: 1.6.3
seaborn: 0.11.1
All 11 python packages installed


You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.302
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.13
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.30
threads: 2.21
threads::shared: 1.56
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/u/project/kruglyak/thatguy0/funannotate_db
$PASAHOME=/u/project/kruglyak/thatguy0/conda/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/u/project/kruglyak/thatguy0/conda/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/u/project/kruglyak/thatguy0/conda/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/u/project/kruglyak/thatguy0/conda/envs/funannotate/config/
$GENEMARK_PATH=/u/project/kruglyak/thatguy0/bin/gmes_linux_64/
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
	ERROR: signalp found but error running signalp
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.8
emapper.py: 2.1.2
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.65_lic
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.1
kallisto: 0.46.1
mafft: v7.475 (2020/Nov/23)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.18-r1015
proteinortho: 6.0.30
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.10
snap: 2006-07-28
stringtie: 2.1.5
tRNAscan-SE: 2.0.7 (Oct 2020)
tantan: tantan 26
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: signalp not installed
```

**Comment by nextgenusfs** [comment]
Thanks @Thatguy027 for detailed bug report.  I think this was recently fixed in master via this commit: https://github.com/nextgenusfs/funannotate/commit/29076c52ad955a54c0772cff519862f7c563cec5. Can you try to install the latest from master via pip and see if the issue is resolved?
```
python -m pip install git+https://github.com/nextgenusfs/funannotate.git --upgrade --no-deps --force
```

**Comment by Thatguy027** [comment]
Awesome, thanks for the quick response - running the predict command and it is showing a progress bar, which is further along than before. Hopefully this is the last error to troubleshoot!

Thanks again!

**Comment by Thatguy027** [comment]
Pipeline got passed the EVM step - closing.

Thanks!!
