### ISSUE TITLE
Funannotate v188 update "Died  on PASA_alignment_assembler.pm"

### ISSUE THREAD

**Issue by HenrivdGeest** [nextgenusfs/funannotate#609]
**Version**
I am using funannotate 1.88, with singularity

**Describe the bug**
Funannotate update crashes on "/venv/opt/pasa-2.4.1/scripts/cDNA_annotation_comparer.dbi " error reading input file

**What command did you issue?**
`funannotate_v188.simg funannotate update -i funannotate --cpus 1 --left /dev/shm/funannotate_tmp_**/normalized_rna_seq/left.norm.fq.gz --right /dev/shm/funannotate_tmp_**/normalized_rna_seq/right.norm.fq.gz --no_normalize_reads --no_trimmomatic --max_intronlen 20000 --trinity funannotate/training/trinity.fasta --pasa_db mysql
`
**Logfiles**
Please provide relavent log files of the error. see below

**OS/Install Information**
 -  output of `funannotate check --show-versions`
 ```
- Checking dependencies for 1.8.8
-------------------------------------------------------
You are running Python v 3.7.10. Now checking python packages...
biopython: 1.78
goatools: 1.0.15
matplotlib: 3.4.2
natsort: 7.1.1
numpy: 1.20.3
pandas: 1.2.4
psutil: 5.8.0
requests: 2.25.1
scikit-learn: 0.24.2
scipy: 1.6.2
seaborn: 0.11.1
All 11 python packages installed


You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.15
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/opt/databases
$PASAHOME=/venv/opt/pasa-2.4.1
$TRINITYHOME=/venv/opt/trinity-2.8.5
$EVM_HOME=/venv/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/venv/config
        ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
.....
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_CTYPE = "C.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Traceback (most recent call last):
  File "/venv/bin/ete3", line 6, in <module>
    from ete3.tools.ete import main
  File "/venv/lib/python3.7/site-packages/ete3/tools/ete.py", line 55, in <module>
    from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,
  File "/venv/lib/python3.7/site-packages/ete3/tools/ete_view.py", line 48, in <module>
    from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,
ImportError: cannot import name 'TextFace' from 'ete3' (/venv/lib/python3.7/site-packages/ete3/__init__.py)
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.8
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.475 (2020/Nov/23)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.18-r1015
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.10
snap: 2006-07-28
stringtie: 2.1.5
tRNAscan-SE: 2.0.7 (Oct 2020)
tantan: tantan 26
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: emapper.py not installed
        ERROR: ete3 not installed
        ERROR: gmes_petap.pl not installed
        ERROR: signalp not installed

```

I am using funannotate to annotate a plant genomes. Although other plants went fine with my installation, this one keeps on failing at the update step. I tried with and without mysql, getting my reference file renamed, tried 3 different file systems, where the latter is using the memory drive (/dev/shm). Also I tried running the update command with many cpus, but also with just 1 cpu. Neither of my tests succeeded. The training step and the predict step did went fine, without errors.

```
funannotate_v188.simg funannotate update -i funannotate --cpus 1 --left /dev/shm/funannotate_plant/normalized_rna_seq/left.norm.fq.gz --right /dev/shm/funannotate_tplant/normalized_rna_seq/right.norm.fq.gz --no_normalize_reads --no_trimmomatic --max_intronlen 20000 --trinity funannotate/training/trinity.fasta --pasa_db mysql
-------------------------------------------------------
[Jun 22 01:42 PM]: OS: Debian GNU/Linux 10, 256 cores, ~ 991 GB RAM. Python: 3.7.10
[Jun 22 01:42 PM]: Running 1.8.8
[Jun 22 01:42 PM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
[Jun 22 01:42 PM]: Found relevant files in funannotate/training, will re-use them:
        Forward reads: funannotate/training/left.fq.gz
        Reverse reads: funannotate/training/right.fq.gz
        Trinity results: funannotate/training/funannotate_train.trinity-GG.fasta
        PASA config file: funannotate/training/pasa/alignAssembly.txt
        BAM alignments: funannotate/training/funannotate_train.coordSorted.bam
        StringTie GTF: funannotate/training/funannotate_train.stringtie.gtf
[Jun 22 01:43 PM]: Reannotating plant, NCBI accession: None
[Jun 22 01:43 PM]: Previous annotation consists of: 46,299 protein coding gene models and 1,839 non-coding gene models
[Jun 22 01:43 PM]: Trimmomatic will be skipped
[Jun 22 01:43 PM]: Read normalization will be skipped
[Jun 22 02:04 PM]: Converting transcript alignments to GFF3 format
[Jun 22 02:04 PM]: Converting Trinity transcript alignments to GFF3 format
[Jun 22 02:05 PM]: Existing PASA database contains 180,374 gene models, validated FASTA headers match
[Jun 22 02:05 PM]: Running PASA annotation comparison step 1
[Jun 22 10:09 PM]: CMD ERROR: /venv/opt/pasa-2.4.1/Launch_PASA_pipeline.pl -c /dev/shm/funannotate_tmp_plant/funannotate/update_misc/pasa/annotCompare.txt -g /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.fa -t /dev/shm/funannotate_tmp_plant/funannotate/update_misc/trinity.fasta.clean -A -L --CPU 1 --annots /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.gff3
[Jun 22 10:09 PM]: -connecting to MySQL db: *_softmasked_copy_pasa
-*** Running PASA pipeine:
* [Tue Jun 22 14:05:50 2021] Running CMD: samtools faidx /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.fa
* [Tue Jun 22 14:05:52 2021] Running CMD: samtools faidx /dev/shm/funannotate_tmp_plant/funannotate/update_misc/trinity.fasta.clean
* [Tue Jun 22 14:05:54 2021] Running CMD: /venv/opt/pasa-2.4.1/scripts/Load_Current_Gene_Annotations.dbi -c /dev/shm/funannotate_tmp_plant/funannotate/update_misc/pasa/annotCompare.txt -g /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.fa -P /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.gff3  > pasa_run.log.dir/output.annot_loading.2054428.out

* [Tue Jun 22 14:08:28 2021] Running CMD: /venv/opt/pasa-2.4.1/scripts/cDNA_annotation_comparer.dbi -G /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.fa --CPU 1 -M '*_softmasked_copy_pasa'  > pasa_run.log.dir/*_softmasked_copy_pasa.annotation_compare.2054428.out
Fatal Error reading input file.
PASA died on input file.  See pasa_killer.inputThread 6 terminated abnormally: Died at /venv/opt/pasa-2.4.1/PerlLib/CDNA/PASA_alignment_assembler.pm line 262.
ERROR, thread 6 exited with error Died at /venv/opt/pasa-2.4.1/PerlLib/CDNA/PASA_alignment_assembler.pm line 262.

Error, there were 1 threads (contig jobs) that failed...  See error messages above in order to troubleshoot furtherFailed thread (6) info:
Thread(6)       FAILED  CMD: unknown    Time to complete: 1861 seconds
Error, cmd: /venv/opt/pasa-2.4.1/scripts/cDNA_annotation_comparer.dbi -G /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.fa --CPU 1 -M 'plantsoftmasked_copy_pasa'  > pasa_run.log.dir/*_softmasked_copy_pasa.annotation_compare.2054428.out died with ret 256 No such file or directory at /venv/opt/pasa-2.4.1/PerlLib/Pipeliner.pm line 187.
        Pipeliner::run(Pipeliner=HASH(0x55df5e34be80)) called at /venv/opt/pasa-2.4.1/Launch_PASA_pipeline.pl line 1044

```

I looked at my file system for any relevant file:

ll  /dev/shm/funannotate_tmp_plant/funannotate/update_misc/
```
total 1744104
drwxr-xr-x 3 user group       480 Jun 22 14:05 ./
drwxr-xr-x 8 user group       160 Jun 22 13:42 ../
-rw-rw-r-- 1 user group      1187 Jun 22 13:50 err_seqcl_trinity.fasta.log
-rw-r--r-- 1 user group   6887818 Jun 22 13:43 genome.exons
-rw-r--r-- 1 user group 575379101 Jun 22 13:42 genome.fa
-rw-r--r-- 1 user group      2767 Jun 22 14:05 genome.fa.cidx
-rw-r--r-- 1 user group       721 Jun 22 14:05 genome.fa.fai
-rw-r--r-- 1 user group  46945274 Jun 22 13:43 genome.gff3
-rw-r--r-- 1 user group 196083712 Jun 22 14:06 genome.gff3.2054749.inx
-rw-r--r-- 1 user group  16461725 Jun 22 13:43 genome.proteins.fa
-rw-r--r-- 1 user group   5437496 Jun 22 13:43 genome.ss
-rw-r--r-- 1 user group    497716 Jun 22 13:43 genome.trna.gff3
-rw-rw-r-- 1 user group      7080 Jun 22 13:50 outparts_cln.sort
drwxr-xr-x 4 user group       200 Jun 22 17:25 pasa/
-rw-rw-r-- 1 user group      1009 Jun 22 13:50 seqcl_trinity.fasta.log
lrwxrwxrwx 1 user group        91 Jun 22 14:04 transcript.alignments.bam -> /dev/shm/funannotate_tmp_plant/funannotate/update_misc/trinity.alignments.bam
-rw-r--r-- 1 user group  50439792 Jun 22 14:04 transcript.alignments.gff3
-rw-r--r-- 1 user group  74402443 Jun 22 14:04 trinity.alignments.bam
-rw-r--r-- 1 user group  50439792 Jun 22 14:05 trinity.alignments.gff3
-rw-r--r-- 1 user group 363897954 Jun 22 13:43 trinity.fasta
-rw-rw-r-- 1 user group  10066250 Jun 22 13:43 trinity.fasta.cidx
-rw-rw-r-- 1 user group 369399769 Jun 22 13:50 trinity.fasta.clean
-rw-r--r-- 1 user group   8176607 Jun 22 14:05 trinity.fasta.clean.fai
-rw-rw-r-- 1 user group  11394548 Jun 22 13:50 trinity.fasta.cln

```
ll  /dev/shm/funannotate_tmp_plant/funannotate/update_misc/pasa/
```
total 252568
drwxr-xr-x 4 user group       200 Jun 22 17:25 ./
drwxr-xr-x 3 user group       480 Jun 22 14:05 ../
-rw-r--r-- 1 user group       590 Jun 22 14:05 alignAssembly.txt
-rw-r--r-- 1 user group      1377 Jun 22 14:05 annotCompare.txt
-rw-r--r-- 1 user group 258594864 Jun 22 14:05 existing_pasa.gff3
-rw-r--r-- 1 user group         0 Jun 22 14:05 pasa-comparison1.log
-rw-r--r-- 1 user group     17502 Jun 22 17:25 pasa_killer.input
drwxr-xr-x 2 user group        80 Jun 22 14:08 pasa_run.log.dir/
drwxr-xr-x 2 user group       100 Jun 22 14:08 __pasa_plant_copy_pasa_mysql_chkpts/
-rw-r--r-- 1 user group       834 Jun 22 14:08 __pasa_plant_copy_pasa_mysql_chkpts.cmds_log
ll  /dev/shm/funannotate_tmp_plant/funannotate/update_misc/pasa/pasa_run.log.dir/
total 701784
drwxr-xr-x 2 user group        80 Jun 22 14:08 ./
drwxr-xr-x 4 user group       200 Jun 22 17:25 ../
-rw-r--r-- 1 user group   3348083 Jun 22 14:08 output.annot_loading.2054428.out
-rw-r--r-- 1 user group 715276256 Jun 22 22:09 plant_copy_pasa.annotation_compare.2054428.out
```

head  /dev/shm/funannotate_tmp_plant/funannotate/update_misc/pasa/pasa_run.log.dir/plant_copy_pasa.annotation_compare.2054428.out 
```
Settings for annot compare:
min_percent_overlap: 50
min_percent_prot_coding: 40
min_percent_length_nonfl_compare: 70
min_perid_prot_compare: 70
min_percent_align_length: 70
min_percent_length_fl_compare: 70
min_FL_orf_size: 
annotation_version: 1
max_utr_exons: 2
```

tail   /dev/shm/funannotate_tmp_plant/funannotate/update_misc/pasa/pasa_run.log.dir/plant_copy_pasa.annotation_compare.205442
8.out 

```
Method: get_latest_gene_models (FUN_048104, SCALAR(0x55faa91b7808))
Retrieving FUN_048104-T1 gene_obj from annot_db.
skipping asmbl_180288, didn't validate as a FL-cdna should have.
Sorry, no alignments to choose from for subcluster: 83657.
skipping asmbl_180289, didn't validate as a FL-cdna should have.
Sorry, no alignments to choose from for subcluster: 83658.
skipping asmbl_180372, didn't validate as a FL-cdna should have.
Sorry, no alignments to choose from for subcluster: 83741.
Warning, only 0 cdna objs linked to current gene.
Skipping splitting prospect.

```

head   /dev/shm/funannotate_tmp_plant/funannotate/update_misc/pasa/pasa_run.log.dir/output.annot_loading.2054428.out
```
CMD: /venv/opt/pasa-2.4.1/scripts/Annotation_store_preloader.dbi -c /dev/shm/funannotate_tmp_plant/funannotate/update_misc/pasa/annotCompare.txt
Now ready to load annotation version: 1
examining lib: /venv/opt/pasa-2.4.1/SAMPLE_HOOKS
adding lib: /venv/opt/pasa-2.4.1/SAMPLE_HOOKS
Required and Imported /venv/opt/pasa-2.4.1/SAMPLE_HOOKS/GFF3/GFF3_annot_retriever.pm
Calling hook: GFF3::GFF3_annot_retriever::get_annot_retriever(HASH(0x558ef7a89e68),/dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.gff3
// Retrieving genes for asmbl: plant_v11_ch06
```

tail   /dev/shm/funannotate_tmp_plant/funannotate/update_misc/pasa/pasa_run.log.dir/output.annot_loading.2054428.out
```
Loading persistent obj: FUN_048131, FUN_048131-T1, 457250, 457901, -
Loading persistent obj: FUN_048132, FUN_048132-T1, 457989, 463181, -
Loading persistent obj: FUN_048133, FUN_048133-T1, 463352, 466721, +
Loading persistent obj: FUN_048134, FUN_048134-T1, 467344, 467888, +
Loading persistent obj: FUN_048135, FUN_048135-T1, 469214, 473763, +
Loading persistent obj: FUN_048136, FUN_048136-T1, 477452, 478571, +
Loading persistent obj: FUN_048137, FUN_048137-T1, 478723, 479188, -
Loading persistent obj: FUN_048138, FUN_048138-T1, 481938, 483675, -
Finished.
```

**Comment by nextgenusfs** [comment]
Is there more information in the `update_misc/pasa` folder?  I thought there is another pasa log file written there.

**Comment by HenrivdGeest** [comment]
I posted the complete list of the files in my post, I just checked again. 
Here are some contents of files in the update_misc/pasa folder:

 └─ $ ▶ head   /update_misc/pasa/pasa_killer.input (# it has just 2 lines, but its a long list of numbers)
```
FUN_026049-T1,-,6216436-6216616,6216700-6216833,6216982-6217107,6217269-6217450,6217549-6217702,6217775-6217845,6218029-6218140,6218176-6218231,6218265-6218322,6............
<--manual CUT here --> 
..............723-6420896,6420919-6421038,6421072-6421233,6421262-6421372,6421395-6421457,6421487-6421563,6421592-6421604,6421640-6422038,6422060-6422346,6422368-6422464,6422494-6422870,6422909-6423314,6423355-6423360,6423461-6423466
asmbl_71275,+,6221084-6221440
```

 └─ $ ▶ cat  /update_misc/pasa/alignAssembly.txt
```

## templated variables to be replaced exist as <__var_name__>

# database settings
DATABASE=plant_softmasked_copy_pasa

#######################################################
# Parameters to specify to specific scripts in pipeline
# create a key = "script_name" + ":" + "parameter" 
# assign a value as done above.

#script validate_alignments_in_db.dbi

validate_alignments_in_db.dbi:--NUM_BP_PERFECT_SPLICE_BOUNDARY=3
validate_alignments_in_db.dbi:--MIN_PERCENT_ALIGNED=90
validate_alignments_in_db.dbi:--MIN_AVG_PER_ID=95

#script subcluster_builder.dbi
subcluster_builder.dbi:-m=50
```
 └─ $ ▶ cat /update_misc/pasa/annotCompare.txt
```

## templated variables to be replaced exist as <__var_name__>

# database settings
DATABASE=plant_softmasked_copy_pasa

#######################################################
# Parameters to specify to specific scripts in pipeline
# create a key = "script_name" + ":" + "parameter" 
# assign a value as done above.


#script cDNA_annotation_comparer.dbi
cDNA_annotation_comparer.dbi:--MIN_PERCENT_OVERLAP=<__MIN_PERCENT_OVERLAP__>
cDNA_annotation_comparer.dbi:--MIN_PERCENT_PROT_CODING=<__MIN_PERCENT_PROT_CODING__>
cDNA_annotation_comparer.dbi:--MIN_PERID_PROT_COMPARE=<__MIN_PERID_PROT_COMPARE__>
cDNA_annotation_comparer.dbi:--MIN_PERCENT_LENGTH_FL_COMPARE=<__MIN_PERCENT_LENGTH_FL_COMPARE__>
cDNA_annotation_comparer.dbi:--MIN_PERCENT_LENGTH_NONFL_COMPARE=<__MIN_PERCENT_LENGTH_NONFL_COMPARE__>
cDNA_annotation_comparer.dbi:--MIN_FL_ORF_SIZE=<__MIN_FL_ORF_SIZE__>
cDNA_annotation_comparer.dbi:--MIN_PERCENT_ALIGN_LENGTH=<__MIN_PERCENT_ALIGN_LENGTH__>
cDNA_annotation_comparer.dbi:--MIN_PERCENT_OVERLAP_GENE_REPLACE=<__MIN_PERCENT_OVERLAP_GENE_REPLACE__>
cDNA_annotation_comparer.dbi:--STOMP_HIGH_PERCENTAGE_OVERLAPPING_GENE=<__STOMP_HIGH_PERCENTAGE_OVERLAPPING_GENE__>
cDNA_annotation_comparer.dbi:--TRUST_FL_STATUS=<__TRUST_FL_STATUS__>
cDNA_annotation_comparer.dbi:--MAX_UTR_EXONS=<__MAX_UTR_EXONS__>
cDNA_annotation_comparer.dbi:--GENETIC_CODE=<__GENETIC_CODE__>
```
 └─ $ ▶ cat  /update_misc/pasa/__pasa_plant_softmasked_copy_pasa_mysql_chkpts.cmds_log
```

samtools faidx /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.fa
samtools faidx /dev/shm/funannotate_tmp_plant/funannotate/update_misc/trinity.fasta.clean
/venv/opt/pasa-2.4.1/scripts/Load_Current_Gene_Annotations.dbi -c /dev/shm/funannotate_tmp_plant/funannotate/update_misc/pasa/annotCompare.txt -g /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.fa -P /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.gff3  > pasa_run.log.dir/output.annot_loading.2054428.out
/venv/opt/pasa-2.4.1/scripts/cDNA_annotation_comparer.dbi -G /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.fa --CPU 1 -M 'plant_softmasked_copy_pasa'  > pasa_run.log.dir/plant_softmasked_copy_pasa.annotation_compare.2054428.out
```

 └─ $ ▶ head  /update_misc/pasa/existing_pasa.gff3
```
plant_v11_ch00 .       gene    11024   11362   .       +       .       ID=gene_asmbl_1;Name=pasa%20asmbl_1%20%285prime_partial_allowed%3A1%2C%203prime_partial_allowed%3A1%29
plant_v11_ch00 .       mRNA    11024   11362   .       +       .       ID=model_asmbl_1;Parent=gene_asmbl_1;Name=pasa%20asmbl_1%20%285prime_partial_allowed%3A1%2C%203prime_partial_allowed%3A1%29
plant_v11_ch00 .       five_prime_UTR  11024   11162   .       +       .       ID=model_asmbl_1.utr5p1;Parent=model_asmbl_1
plant_v11_ch00 .       exon    11024   11362   .       +       .       ID=model_asmbl_1.exon1;Parent=model_asmbl_1
plant_v11_ch00 .       CDS     11163   11362   .       +       0       ID=cds.model_asmbl_1;Parent=model_asmbl_1;3_prime_partial=true

plant_v11_ch00 .       gene    615725  616733  .       +       .       ID=gene_asmbl_2;Name=pasa%20asmbl_2%20%285prime_partial_allowed%3A1%2C%203prime_partial_allowed%3A1%29
plant_v11_ch00 .       mRNA    615725  616733  .       +       .       ID=model_asmbl_2;Parent=gene_asmbl_2;Name=pasa%20asmbl_2%20%285prime_partial_allowed%3A1%2C%203prime_partial_allowed%3A1%29
plant_v11_ch00 .       five_prime_UTR  615725  616424  .       +       .       ID=model_asmbl_2.utr5p1;Parent=model_asmbl_2
plant_v11_ch00 .       exon    615725  616733  .       +       .       ID=model_asmbl_2.exon1;Parent=model_asmbl_2

```
 └─ $ ▶ tail  update_misc/pasa/existing_pasa.gff3
```
plant_v11_mt01 .       gene    479228  481409  .       -       .       ID=gene_asmbl_180374;Name=pasa%20asmbl_180374%20%285prime_partial_allowed%3A1%2C%203prime_partial_allowed%3A1%29
plant_v11_mt01 .       mRNA    479228  481409  .       -       .       ID=model_asmbl_180374;Parent=gene_asmbl_180374;Name=pasa%20asmbl_180374%20%285prime_partial_allowed%3A1%2C%203prime_partial_allowed%3A1%29
plant_v11_mt01 .       five_prime_UTR  481149  481409  .       -       .       ID=model_asmbl_180374.utr5p1;Parent=model_asmbl_180374
plant_v11_mt01 .       five_prime_UTR  480777  480842  .       -       .       ID=model_asmbl_180374.utr5p2;Parent=model_asmbl_180374
plant_v11_mt01 .       exon    481149  481409  .       -       .       ID=model_asmbl_180374.exon1;Parent=model_asmbl_180374
plant_v11_mt01 .       exon    479228  480842  .       -       .       ID=model_asmbl_180374.exon2;Parent=model_asmbl_180374
plant_v11_mt01 .       CDS     480609  480776  .       -       0       ID=cds.model_asmbl_180374;Parent=model_asmbl_180374
plant_v11_mt01 .       three_prime_UTR 479228  480608  .       -       .       ID=model_asmbl_180374.utr3p1;Parent=model_asmbl_180374
```

**Comment by nextgenusfs** [comment]
Sorry @HenrivdGeest I don't really see anything here that is obvious. You could try to run the PASA command outside of funannotate and see if there is a more intelligible error.  
```
/venv/opt/pasa-2.4.1/Launch_PASA_pipeline.pl \
    -c /dev/shm/funannotate_tmp_plant/funannotate/update_misc/pasa/annotCompare.txt \
    -g /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.fa \
    -t /dev/shm/funannotate_tmp_plant/funannotate/update_misc/trinity.fasta.clean \
    -A -L --CPU 1 --annots /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.gff3
```
But as you said it is only failing on one of your genomes -- which implies it is a gene model/alignment/contig/etc in that particular one causing a problem.

**Comment by HenrivdGeest** [comment]
I ran the command separately, and that does reviel a new error:
```
....
* [Mon Jul  5 07:55:49 2021] Running CMD: /venv/opt/pasa-2.4.1/scripts/cDNA_annotation_comparer.dbi -G /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.fa --CPU 1 -M 'plant_softmasked_copy_pasa'  > pasa_run.log.dir/plant_softmasked_copy_pasa.annotation_compare.3736489.out
DBD::mysql::st execute failed: Table 'plant_softmasked_copy_pasa.annotation_updates' doesn't exist at /venv/opt/pasa-2.4.1/PerlLib/DB_connect.pm line 178.
====
Failed query: <select update_id from annotation_updates where gene_id = ? and model_id = ? and is_valid = ? and alt_splice_flag = ? and is_novel_flag = ? and compare_id = ?>   values: FUN_017383 FUN_017383-T1 1 0 0 3
Errors: Table 'plant_softmasked_copy_pasa.annotation_updates' doesn't exist
====
Thread 3 terminated abnormally: Failed query: <select update_id from annotation_updates where gene_id = ? and model_id = ? and is_valid = ? and alt_splice_flag = ? and is_novel_flag = ? and compare_id = ?>   values: FUN_017383 FUN_017383-T1 1 0 0 3
Errors:
...some more errors ending in:
Error, cmd: /venv/opt/pasa-2.4.1/scripts/cDNA_annotation_comparer.dbi -G /dev/shm/funannotate_tmp_plant/funannotate/update_misc/genome.fa --CPU 1 -M 'plant_softmasked_copy_pasa'  > pasa_run.log.dir/plant_softmasked_copy_pasa.annotation_compare.3736489.out died with ret 256 No such file or directory at /venv/opt/pasa-2.4.1/PerlLib/Pipeliner.pm line 187
```
So it seems that it failes at the a select statement from the 'plant_softmasked_copy_pasa.annotation_updates' table, which somehow does not seem to exist? 

From within the mysql database:
```

mysql> use plant_softmasked_copy_pasa
mysql> show tables;
+---------------------------------------+
| Tables_in_plant_softmasked_copy_pasa |
+---------------------------------------+
| URL_templates                         |
| URL_var_names                         |
| align_link                            |
| alignment                             |
| alt_splice_FL_compare                 |
| alt_splice_FL_to_FL_compare           |
| alt_splice_link                       |
| alt_splice_token_assignment           |
| alt_splice_tokens                     |
| annotation_admin                      |
| annotation_compare                    |
| annotation_link                       |
| annotation_store                      |
| annotation_updates                    |
| asmblPolyA                            |
| asmbl_gene_objs                       |
| asmbl_link                            |
| cdna_info                             |
| cdna_sequence                         |
| clusters                              |
| splice_variation                      |
| splice_variation_support              |
| status                                |
| status_link                           |
| subcluster_link                       |
| subclusters                           |
| transcriptPolyA                       |
+---------------------------------------+
27 rows in set (0,00 sec)
```
So the table does seem to be there, but its empty:
```
mysql> select update_id from annotation_updates where gene_id = "FUN_017383";
Empty set (0,00 sec)

mysql> select * from annotation_updates
    -> ;
Empty set (0,00 sec)

```
Hopes this helps? If you need anything more please say so.

**Comment by nextgenusfs** [comment]
I don't think I can help debug this - mostly likely will need Brian Haas' help as this seems like a PASA problem.
