### ISSUE TITLE
Test failure during funannotate predict using RNA-seq training data

### ISSUE THREAD

**Issue by alanorth** [nextgenusfs/funannotate#623]
**Are you using the latest release?**
Yes I am using 1.8.9 via Singularity from Docker hub.

**Describe the bug**
Test failure during `funannotate predict` using RNA-seq training data. The tests ran for an hour or two and then failed here.

**What command did you issue?**

```console
$ singularity exec docker://nextgenusfs/funannotate funannotate test -t all --cpus 12
```

**Logfiles**
```console
-------------------------------------------------------
#########################################################
Now running `funannotate predict` using RNA-seq training data
CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o rna-seq --cpus 12 --min_training_models 150 --species Awesome rna
#########################################################
-------------------------------------------------------
[Aug 03 05:18 PM]: OS: Debian GNU/Linux 10, 64 cores, ~ 264 GB RAM. Python: 3.8.10
[Aug 03 05:18 PM]: Running funannotate v1.8.9
[Aug 03 05:18 PM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[Aug 03 05:18 PM]: Found training files, will re-use these files:
  --rna_bam rna-seq/training/funannotate_train.coordSorted.bam
  --pasa_gff rna-seq/training/funannotate_train.pasa.gff3
  --stringtie rna-seq/training/funannotate_train.stringtie.gtf
  --transcript_alignments rna-seq/training/funannotate_train.transcripts.gff3
[Aug 03 05:18 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program        Training-Method
  augustus       pasa           
  codingquarry   rna-bam        
  glimmerhmm     pasa           
  snap           pasa           
[Aug 03 05:18 PM]: perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "en_US",
        LC_ALL = (unset),
        LC_CTYPE = "C.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
[Aug 03 05:18 PM]: ERROR: rna-seq/training/funannotate_train.pasa.gff3 is not a properly formatted PASA GFF file, please consult EvidenceModeler docs
Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/test.py", line 409, in main
    runRNAseqTest(args)
  File "/venv/lib/python3.8/site-packages/funannotate/test.py", line 347, in runRNAseqTest
    assert 1630 <= countGFFgenes(os.path.join(
  File "/venv/lib/python3.8/site-packages/funannotate/test.py", line 45, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-rna_seq_6e83f01d-887c-46e9-8b53-9f22cb020700/rna-seq/predict_results/Awesome_rna.gff3'
```

**OS/Install Information**

```console
$ singularity exec docker://nextgenusfs/funannotate funannotate check --show-versions
INFO:    Using cached SIF image
-------------------------------------------------------
Checking dependencies for 1.8.9
-------------------------------------------------------
You are running Python v 3.8.10. Now checking python packages...
biopython: 1.79
goatools: 1.1.6
matplotlib: 3.4.2
natsort: 7.1.1
numpy: 1.21.1
pandas: 1.3.1
psutil: 5.8.0
requests: 2.26.0
scikit-learn: 0.24.2
scipy: 1.5.3
seaborn: 0.11.1
All 11 python packages installed


You are running Perl v b'5.026002'. Now checking perl modules...
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
   ERROR: Bio::Perl not installed, install with cpanm Bio::Perl


Checking Environmental Variables...
$FUNANNOTATE_DB=/opt/databases
$PASAHOME=/venv/opt/pasa-2.4.1
$TRINITYHOME=/venv/opt/trinity-2.8.5
$EVM_HOME=/venv/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/venv/config
        ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "en_US",
        LC_ALL = (unset),
        LC_CTYPE = "C.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "en_US",
        LC_ALL = (unset),
        LC_CTYPE = "C.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "en_US",
        LC_ALL = (unset),
        LC_CTYPE = "C.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "en_US",
        LC_ALL = (unset),
        LC_CTYPE = "C.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Traceback (most recent call last):
  File "/venv/bin/ete3", line 6, in <module>
    from ete3.tools.ete import main
  File "/venv/lib/python3.8/site-packages/ete3/tools/ete.py", line 55, in <module>
    from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,
  File "/venv/lib/python3.8/site-packages/ete3/tools/ete_view.py", line 48, in <module>
    from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,
ImportError: cannot import name 'TextFace' from 'ete3' (/venv/lib/python3.8/site-packages/ete3/__init__.py)
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.8
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.9.1-internal
kallisto: 0.46.1
mafft: v7.487 (2021/Jul/25)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.21-r1071
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.10
snap: 2006-07-28
stringtie: 2.1.7
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 26
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: emapper.py not installed
        ERROR: ete3 not installed
        ERROR: gmes_petap.pl not installed
        ERROR: signalp not installed
```

**Comment by nextgenusfs** [comment]
Hmm. So I didn't get this with my docker test? So is the Perl locale issue specific to singularity? You should just be able to set your locale in your singularity build recipe.

**Comment by alanorth** [comment]
@nextgenusfs I'm not using a Singularity recipe—just running it straight from Docker hub:

```console
$ singularity exec docker://nextgenusfs/funannotate funannotate test -t all --cpus 12
```

I'm on a CentOS 7 system. I don't know if locale has anything to do with this. Here is before and after entering the Singularity environment:

```console
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
$ singularity shell docker://nextgenusfs/funannotate 
localeINFO:    Using cached SIF image
Singularity> locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by nextgenusfs** [comment]
It should build and push to docker in the next ~30 minutes, so try to pull the latest after it gets updated and see if that fixes it.

**Comment by alanorth** [comment]
Tests passing with 1.8.9 in Singularity now. Thanks @nextgenusfs!
