### ISSUE TITLE
Final step of writing genome annotation table breaks

### ISSUE THREAD

**Issue by fmobegi** [nextgenusfs/funannotate#627]
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**
There seems to be a problem with creating the annotations table. Probably an InterproScan output issue
```
funannotate annotate --fasta 15CUR002.fna --out 15CUR002 --species 'Ascochyta rabiei' --isolate 15CUR002 --gff 15CUR002.gff3 --cpus 14 --rename 15CUR002 --phobius 15CUR002.phobius.txt
-------------------------------------------------------
[Aug 11 08:44 AM]: OS: Ubuntu 20.04, 12 cores, ~ 33 GB RAM. Python: 3.8.10
[Aug 11 08:44 AM]: Running 1.8.9
[Aug 11 08:44 AM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[Aug 11 08:44 AM]: Found existing output directory 15CUR002. Warning, will re-use any intermediate files found.
[Aug 11 08:44 AM]: Parsing annotation and preparing annotation files.
[Aug 11 08:44 AM]: Found 11,216 gene models from GFF3 annotation
[Aug 11 08:44 AM]: Adding Functional Annotation to Ascochyta rabiei, NCBI accession: None
[Aug 11 08:44 AM]: Annotation consists of: 11,216 gene models
[Aug 11 08:44 AM]: 11,216 protein records loaded
[Aug 11 08:44 AM]: Existing Pfam-A results found: 15CUR002/annotate_misc/annotations.pfam.txt
[Aug 11 08:44 AM]: 11,979 annotations added
[Aug 11 08:44 AM]: Running Diamond blastp search of UniProt DB version 2021_02
[Aug 11 08:44 AM]: 730 valid gene/product annotations from 1,063 total
[Aug 11 08:44 AM]: Existing Eggnog-mapper results found: 15CUR002/annotate_misc/eggnog.emapper.annotations
[Aug 11 08:44 AM]: Parsing EggNog Annotations
[Aug 11 08:44 AM]: EggNog version parsed as 2.1.4-2-6-g05f27b0
[Aug 11 08:44 AM]: 20,490 COG and EggNog annotations added
[Aug 11 08:44 AM]: Combining UniProt/EggNog gene and product names using Gene2Product version 1.69
[Aug 11 08:44 AM]: 2,693 gene name and product description annotations added
[Aug 11 08:44 AM]: Existing MEROPS results found: 15CUR002/annotate_misc/annotations.merops.txt
[Aug 11 08:44 AM]: 363 annotations added
[Aug 11 08:44 AM]: Existing CAZYme results found: 15CUR002/annotate_misc/annotations.dbCAN.txt
[Aug 11 08:44 AM]: 501 annotations added
[Aug 11 08:44 AM]: Existing BUSCO2 results found: 15CUR002/annotate_misc/annotations.busco.txt
[Aug 11 08:44 AM]: 1,296 annotations added
[Aug 11 08:44 AM]: Existing Phobius results found: 15CUR002/annotate_misc/phobius.results.txt
[Aug 11 08:44 AM]: Existing SignalP results found: 15CUR002/annotate_misc/signalp.results.txt
[Aug 11 08:44 AM]: 1,096 secretome and 2,387 transmembane annotations added
[Aug 11 08:44 AM]: InterProScan error, 15CUR002/annotate_misc/iprscan.xml is empty, or no XML file passed via --iprscan. Functional annotation will be lacking.
[Aug 11 08:44 AM]: Found 0 duplicated annotations, adding 72,471 valid annotations
[Aug 11 08:44 AM]: Converting to final Genbank format, good luck!
[Aug 11 08:45 AM]: Creating AGP file and corresponding contigs file
[Aug 11 08:45 AM]: Writing genome annotation table.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/funannotate/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/opt/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 1574, in main
    lib.annotationtable(final_gbk, FUNDB, NoteHeaders, INTERPRO,
  File "/opt/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py", line 7641, in annotationtable
    Protein = v['protein'][i]
IndexError: list index out of range

```
**What command did you issue?**
Copy/paste the command used.

**Logfiles**
Please provide relevant log files of the error. 

**OS/Install Information**
 -  output of `funannotate check --show-versions`
```
funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.8.9
-------------------------------------------------------
You are running Python v 3.8.10. Now checking python packages...
biopython: 1.79
goatools: 1.1.6
matplotlib: 3.4.2
natsort: 7.1.1
numpy: 1.21.1
pandas: 1.2.4
psutil: 5.8.0
requests: 2.26.0
scikit-learn: 0.24.2
scipy: 1.7.0
seaborn: 0.11.1
All 11 python packages installed


You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/ppgdata/fredrick/funannotate_db
$PASAHOME=/opt/miniconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/opt/miniconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/opt/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/opt/miniconda3/envs/funannotate/config/
$GENEMARK_PATH=/opt/gmes_linux_64
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.8
emapper.py: 2.1.4-2-6-g05f27b0
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.68_lic
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.487 (2021/Jul/25)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.22-r1101
proteinortho: 6.0.31
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.10
signalp: 5.0b
snap: 2006-07-28
stringtie: 2.1.7
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 26
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 36 external dependencies are installed
```

**Comment by nextgenusfs** [comment]
It seems to be choking on parsing a particular gene model, ie a gene model that it thinks should have a protein (amino acid) sequence does not.  I put a check for that and will output an error to stdout and should keep going (hopefully).

**Comment by fmobegi** [comment]
The problem seems to affect comparative analysis as well..

```
funannotate compare -i */annotate_results/*.gbk -o fun_compare/ --cpus 14
-------------------------------------------------------
[Aug 11 01:17 PM]: OS: Ubuntu 20.04, 12 cores, ~ 33 GB RAM. Python: 3.8.10
[Aug 11 01:17 PM]: Running 1.8.9
[Aug 11 01:17 PM]: Now parsing 13 genomes
[Aug 11 01:17 PM]: working on Ascochyta rabiei 15CUR002
Traceback (most recent call last):
  File "/opt/miniconda3/envs/funannotate/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/opt/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/compare.py", line 252, in main
    lib.gb2proteinortho(GBK, protortho, name)
  File "/opt/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py", line 7845, in gb2proteinortho
    (item, k, v['protein'][i]))
IndexError: list index out of range
```

**Comment by fmobegi** [comment]
I repeated the antiSMASH analysis and reran the annotation.. everything seems OK now. 

```
[Aug 11 03:26 PM]: Now parsing antiSMASH v5 results, finding SM clusters
[Aug 11 03:26 PM]: Found 29 clusters, 68 biosynthetic enyzmes, and 91 smCOGs predicted by antiSMASH
[Aug 11 03:26 PM]: Found 0 duplicated annotations, adding 72,471 valid annotations
[Aug 11 03:26 PM]: Converting to final Genbank format, good luck!
[Aug 11 03:27 PM]: Creating AGP file and corresponding contigs file
[Aug 11 03:27 PM]: Cross referencing SM cluster hits with MIBiG database version 1.4
[Aug 11 03:27 PM]: Creating tab-delimited SM cluster output
[Aug 11 03:27 PM]: Writing genome annotation table.
[Aug 11 03:27 PM]: Funannotate annotate has completed successfully!

        We need YOUR help to improve gene names/product descriptions:
           0 gene/products names MUST be fixed, see 15CUR002/annotate_results/Gene2Products.must-fix.txt
           1 gene/product names need to be curated, see 15CUR002/annotate_results/Gene2Products.need-curating.txt
           100 gene/product names passed but are not in Database, see 15CUR002/annotate_results/Gene2Products.new-names-passed.txt

        Please consider contributing a PR at https://github.com/nextgenusfs/gene2product
```
### The only notable difference is the version of antiSMASH output. The previous `funannotate v1.8.7` used to run `antiSMASH 6.0.0alpha`.

```
COMMENT     'Annotated using 1.8.4'.
            ##antiSMASH-Data-START##
            Version      :: 6.0.0alpha1-fd5c907
            Run date     :: 2021-04-28 02:12:28
            ##antiSMASH-Data-END##
```
### `v1.8.9` runs `antismash v 5`
```
COMMENT     'Annotated using 1.8.7'.
            ##antiSMASH-Data-START##
            Version      :: 5.2.0
            Run date     :: 2021-08-11 06:41:24
            ##antiSMASH-Data-END##
```
