### ISSUE TITLE
funannotate compare doesn't work on sample data

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#63]
```
~/data/sample_data$ funannotate compare -i genome1 genome2
-------------------------------------------------------
[06:07:05 PM]: OS: linux2, 4 cores, ~ 4 GB RAM. Python: 2.7.12
[06:07:06 PM]: Running funannotate v0.6.0
[06:07:06 PM]: Now parsing 2 genomes
[06:07:06 PM]: working on Genome one genome
[06:07:06 PM]: working on Genome two genome
[06:07:07 PM]: No secondary metabolite annotations found
[06:07:07 PM]: Summarizing PFAM domain results
[06:07:07 PM]: Summarizing InterProScan results
[06:07:07 PM]: Loading InterPro descriptions
[06:07:11 PM]: Summarizing MEROPS protease results
Traceback (most recent call last):
  File "/home/osboxes/.linuxbrew/Cellar/funannotate/0.6.0/libexec/bin/funannotate-compare.py", line 419, in <module>
    lib.drawStackedBar(meropsShort, 'MEROPS families', MEROPS, ymax, os.path.join(args.out, 'merops', 'MEROPS.graph.pdf'))
  File "/home/osboxes/.linuxbrew/Cellar/funannotate/0.6.0/libexec/lib/library.py", line 1837, in drawStackedBar
    SBG.stackedBarPlot(ax,panda,color_palette,xLabels=panda.index.values,endGaps=True,gap=0.25,xlabel="Genomes",ylabel=YLabel,yTicks=yticks) 
  File "/home/osboxes/.linuxbrew/Cellar/funannotate/0.6.0/libexec/lib/stackedBarGraph.py", line 228, in stackedBarPlot
    data_stack[0],
IndexError: index 0 is out of bounds for axis 0 with size 0

```

**Comment by nextgenusfs** [comment]
Not seen this one before.  Looks like MEROPS is empty for each one of those.  Can you add genome3 from the test data and see if that also fails.  There may not be any MEROPS proteins in the first two genomes.  Either way it could be a bug.

**Comment by nextgenusfs** [comment]
I can't replicate this error?
```
jon@Jons-MacBook-Pro:~/funannotate/sample_data$ funannotate compare -i genome1 genome2
-------------------------------------------------------
[09:32:34 AM]: OS: MacOSX 10.12.3, 8 cores, ~ 17 GB RAM. Python: 2.7.12
[09:32:34 AM]: Running funannotate v0.6.0
[09:32:34 AM]: Now parsing 2 genomes
[09:32:34 AM]: working on Genome one genome
[09:32:35 AM]: working on Genome two genome
[09:32:36 AM]: No secondary metabolite annotations found
[09:32:36 AM]: Summarizing PFAM domain results
[09:32:39 AM]: Summarizing InterProScan results
[09:32:39 AM]: Loading InterPro descriptions
[09:32:43 AM]: Summarizing MEROPS protease results
[09:32:44 AM]: found 5 MEROPS familes
[09:32:44 AM]: Summarizing CAZyme results
[09:32:44 AM]: found 16 CAZy familes
[09:32:44 AM]: No SignalP annotations found
[09:32:44 AM]: Summarizing fungal transcription factors
[09:32:45 AM]: Running GO enrichment for each genome
[09:32:45 AM]: Running orthologous clustering tool, ProteinOrtho5.  This may take awhile...
[09:32:45 AM]: Compiling all annotations for each genome
[09:32:51 AM]: Compressing results to output file: funannotate_compare.tar.gz
[09:32:57 AM]: Funannotate compare completed successfully!
```
Which means it could be a matplotlib library error.  You can check which version of matplotlib is installed via `funannotate check`
```
jon@Jons-MacBook-Pro:~/funannotate/sample_data$ funannotate check
-----------------------
Python Version:
-----------------------
2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:43:17) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)]
-----------------------
Modules installed:
-----------------------
numpy => 1.12.0
pandas => 0.19.2
matplotlib => 1.5.1
scipy => 0.18.1
scikit-learn => 0.18.1
psutil => 5.0.1
natsort => 5.0.1
goatools => 0.6.10
seaborn => 0.7.1
biopython => 1.68
-----------------------
External Dependencies:
-----------------------
tblastn v2.4.0+
blastp v2.4.0+
blastn v2.4.0+
makeblastdb v2.4.0+
rmblastn v2.2.27+
exonerate v2.2.0
bedtools v2.26.0
bamtools v2.4.0
AUGUSTUS v3.2.1
braker.pl v1.9
GMAP v 2017-01-14
RepeatModeler v1.0.8
RepeatMasker v4.0.7
diamond v0.8.36
ete3 v3.0.0b36
GeneMark-ES Suite v4.30
BLAT v36
HMMER 3.1b2 (February 2015)
```

**Comment by nextgenusfs** [comment]
Is this still a problem?
