### ISSUE TITLE
funannotate predict failed

### ISSUE THREAD

**Issue by gengce** [nextgenusfs/funannotate#633]
-------------------------------------------------------
Checking dependencies for 1.8.9
-------------------------------------------------------
You are running Python v 3.7.10. Now checking python packages...
biopython: 1.76
goatools: 1.0.15
matplotlib: 3.4.1
natsort: 7.1.1
numpy: 1.20.2
pandas: 1.2.4
psutil: 5.7.0
requests: 2.25.1
scikit-learn: 0.24.1
scipy: 1.6.2
seaborn: 0.11.1
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/train/DATA/funDB
$PASAHOME=/opt/biosoft/miniconda/envs/funannotate/fun3/opt/pasa-2.4.1
$TRINITY_HOME=/opt/biosoft/miniconda/envs/funannotate/fun3/opt/trinity-2.8.5
$EVM_HOME=/opt/biosoft/miniconda/envs/funannotate/fun3/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/opt/biosoft/miniconda/envs/funannotate/fun3/config/
$GENEMARK_PATH=/opt/biosoft/gm_et_linux_64/gmes_linux_64:/opt/biosoft/eggnog-mapper:/opt/biosoft/miniconda/envs/funannotate/fun3/bin:/opt/biosoft/eggnog-mapper:/opt/biosoft/eggnog-mapper:/home/miniconda3/condabin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/opt/biosoft/gm_et_linux_64/gmes_linux_64:/root/bin
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
  File "/opt/biosoft/eggnog-mapper/emapper.py", line 64
    print dbpath
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(dbpath)?
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.4.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.11
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.65_lic
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.1
kallisto: 0.46.1
mafft: v7.475 (2020/Nov/23)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.18-r1015
proteinortho: 6.0.30
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.12
signalp: 4.1
snap: 2006-07-28
stringtie: 2.1.5
tRNAscan-SE: 2.0.7 (Oct 2020)
tantan: tantan 26
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: emapper.py not installed

[08/24/21 08:11:23]: /opt/biosoft/miniconda/envs/funannotate/fun3/bin/funannotate predict -i Aspcad1mask -o Aspcad1predict --busco_seed_species=aspergillus_oryzae -s Aspergillus candidus --name ASPcad1 --genemark_gtf genemark.gtf --cpus 30

[08/24/21 08:11:23]: OS: CentOS 6.10, 80 cores, ~ 529 GB RAM. Python: 3.7.10
[08/24/21 08:11:23]: Running funannotate v1.8.9
[08/24/21 08:11:24]: GeneMark path: /opt/biosoft/gm_et_linux_64/gmes_linux_64:/opt/biosoft/eggnog-mapper:/opt/biosoft/miniconda/envs/funannotate/fun3/bin:/opt/biosoft/eggnog-mapper:/opt/biosoft/eggnog-mapper:/home/miniconda3/condabin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/opt/biosoft/gm_et_linux_64/gmes_linux_64:/root/bin
[08/24/21 08:11:24]: Full path to gmes_petap.pl: /opt/biosoft/gm_et_linux_64/gmes_linux_64:/opt/biosoft/eggnog-mapper:/opt/biosoft/miniconda/envs/funannotate/fun3/bin:/opt/biosoft/eggnog-mapper:/opt/biosoft/eggnog-mapper:/home/miniconda3/condabin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/opt/biosoft/gm_et_linux_64/gmes_linux_64:/root/bin/gmes_petap.pl
[08/24/21 08:11:24]: GeneMark appears to be functional? False
[08/24/21 08:11:24]: {'augustus': 1, 'hiq': 2, 'genemark': 0, 'pasa': 6, 'codingquarry': 0, 'snap': 1, 'glimmerhmm': 1, 'proteins': 1, 'transcripts': 1}
[08/24/21 08:11:24]: Skipping CodingQuarry as no --rna_bam passed
[08/24/21 08:11:24]: {'augustus': 'busco', 'snap': 'busco', 'glimmerhmm': 'busco'}
[08/24/21 08:11:24]: Parsed training data, run ab-initio gene predictors as follows:
[08/24/21 08:11:26]: {'augustus': 1, 'hiq': 2, 'genemark': 0, 'pasa': 6, 'codingquarry': 0, 'snap': 1, 'glimmerhmm': 1, 'proteins': 1, 'transcripts': 1}
[08/24/21 08:11:34]: Loading genome assembly and parsing soft-masked repetitive sequences
[08/24/21 08:11:36]: Genome loaded: 268 scaffolds; 27,317,772 bp; 5.38% repeats masked
[08/24/21 08:11:47]: Existing protein alignments found: Aspcad1predict/predict_misc/protein_alignments.gff3
[08/24/21 08:11:48]: join_mult_hints.pl
[08/24/21 08:11:48]: /opt/biosoft/miniconda/envs/funannotate/fun3/lib/python3.7/site-packages/funannotate/aux_scripts/genemark_gtf2gff3.pl genemark.gtf
[08/24/21 08:11:49]: perl /opt/biosoft/miniconda/envs/funannotate/fun3/opt/evidencemodeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl Aspcad1predict/predict_misc/genemark.gff
[08/24/21 08:11:52]: Existing BUSCO results found: Aspcad1predict/predict_misc/busco.final.gff3 containing 1 predictions
[08/24/21 08:11:52]: Not enough gene models 1 to train Augustus (200 required), exiting

can you help me to find why "No enough gene model happen",

**Comment by nextgenusfs** [comment]
Likely a few things.

1) GeneMark is not installed properly
2) Augustus 3.4 does not work with BUSCO in funannotate, use v3.3.3

**Comment by nhungdoan1905** [comment]
[Mar 25 12:25 PM]: Mapping 557,938 proteins to genome using diamond and exonerate
[Mar 25 12:35 PM]: Found 281,811 preliminary alignments with diamond in 0:08:18 --> generated FASTA files for exonerate in 0:01:04
     Progress: 281811 complete, 0 failed, 0 remaining
[Mar 25 03:08 PM]: Exonerate finished in 2:33:17: found 2,006 alignments
[Mar 25 03:08 PM]: Running BUSCO to find conserved gene models for training ab-initio predictors
[Mar 25 03:56 PM]: 1,285 valid BUSCO predictions found, validating protein sequences
[Mar 25 03:58 PM]: 1,283 BUSCO predictions validated
[Mar 25 03:58 PM]: Training Augustus using BUSCO gene models
[Mar 25 03:58 PM]: Augustus initial training results:
  Feature       Specificity   Sensitivity
  nucleotides   99.1%         95.5%
  exons         90.0%         83.3%
  genes         81.2%         67.1%
[Mar 25 03:58 PM]: Running Augustus gene prediction using penicillin_herquei parameters
Traceback (most recent call last):
  File "/datausers2/ibt/pbngoc/.local/lib/python3.8/site-packages/funannotate/aux_scripts/augustus_parallel.py", line 9, in <module>
    from Bio import SeqIO
ImportError: No module named Bio
[Mar 25 03:58 PM]: CMD ERROR: perl /datausers2/ibt/pbngoc/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl /datausers2/ibt/pbngoc/data/12C_funannotate/predict_misc/augustus.gff3
[Mar 25 03:58 PM]: Error, cannot open file /datausers2/ibt/pbngoc/data/12C_funannotate/predict_misc/augustus.gff3 at /datausers2/ibt/pbngoc/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl line 23.

i got these err when running funannotate, how can i solve it
