### ISSUE TITLE
SignalP v6? 

### ISSUE THREAD

**Issue by Dikaryotic** [nextgenusfs/funannotate#650]
Hi John,

I've got some SingalP6 output I'd like to include in my annotate stage. I've tried the --signalp method but it threw an error. I'm using funannotate v1.8.7. I'll pop in the error then a head of the singalp output file. Maybe you can advise? I suspect it's something to do with the format but can't quite figure it out. Ideally I wouldve liked funannotate to run it natively but it didnt want to pickup the installation. 

Existing SignalP results found: Predict/annotate_misc/signalp.results.txt
Traceback (most recent call last):
  File "/home/chris/miniconda3/envs/Funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/chris/miniconda3/envs/Funannotate/lib/python3.7/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/home/chris/miniconda3/envs/Funannotate/lib/python3.7/site-packages/funannotate/annotate.py", line 963, in main
    lib.parseSignalP(signalp_out, secreted_out)
  File "/home/chris/miniconda3/envs/Funannotate/lib/python3.7/site-packages/funannotate/library.py", line 5634, in parseSignalP
    if col[9] == 'Y':  # then there is signal peptide
IndexError: list index out of range

head signalp.results.txt 
# SignalP-6.0	Organism: Eukarya	Timestamp: 20211008163009
# ID	Prediction	OTHER	SP(Sec/SPI)	CS Position
FUN_000001-T1_FUN_000001	NO_SP	1.000034	0.000000	
FUN_000002-T1_FUN_000002	NO_SP	1.000061	0.000000	
FUN_000003-T1_FUN_000003	NO_SP	1.000047	0.000000	
FUN_000004-T1_FUN_000004	NO_SP	1.000045	0.000000	
FUN_000005-T1_FUN_000005	NO_SP	0.999985	0.000069	
FUN_000006-T1_FUN_000006	NO_SP	1.000068	0.000000	
FUN_000007-T1_FUN_000007	NO_SP	1.000054	0.000000	
FUN_000008-T1_FUN_000008	NO_SP	1.000050	0.000001

Cheers,
Chris

**Comment by nextgenusfs** [comment]
Looks like another new format.... is it tab delimited or space? And what does a "has signal peptide" look like?

**Comment by Dikaryotic** [comment]
It's tab delimited. Here are the first two identified with signal peptides. 

# SignalP-6.0	Organism: Eukarya	Timestamp: 20211008163009
# ID	Prediction	OTHER	SP(Sec/SPI)	CS Position
FUN_000010-T1_FUN_000010	SP	0.000237	0.999737	CS pos: 21-22. Pr: 0.9766
FUN_000017-T1_FUN_000017	SP	0.000320	0.999666	CS pos: 25-26. Pr: 0.4228

**Comment by nextgenusfs** [comment]
Thanks can you attach file so I can make sure the parser gets the last column correctly? I do t want to make any assumptions based on if GitHub stripped any formatting, etc.

**Comment by Dikaryotic** [comment]
[signalp.results.txt](https://github.com/nextgenusfs/funannotate/files/7318426/signalp.results.txt)

**Comment by nextgenusfs** [comment]
Thanks.  How about the call to signalP v6, this is what is being run on v5:
```
cmd = ['signalp', '-stdout', '-org', 'euk', '-format', 'short', '-fasta']
```
Does that still work with v6?

**Comment by fteufel** [comment]
Hey @Dikaryotic , saw this issue by chance, could you provide me with the sequences that show no CS being predicted? This is definitely unexpected behaviour.

**Comment by hassantarabai** [comment]
Hello,

I recently installed funannotate and it appear the signalp6 pursing error is still there "ValueError: not enough values to unpack (expected 5, got 4)" when passing signalp6 results to funannotate annotate.

Have anybody managed a solution for it ?

**Comment by lukaskon** [comment]
I am also having the same issue. What is the exact input file type or path supposed to be for --signalp ?

```
--signalp predict_results/signalp/prediction_results.txt \
```


```
Existing SignalP results found: /mnt/ufs18/rs-008/Hausbeck_group/Lukasko/BotrytisDNASeq/CCR7/Predict_Annotate/AI7_fun/annotate_misc/signalp.results.t
xt
-------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/home/lukaskon/anaconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/mnt/home/lukaskon/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/mnt/home/lukaskon/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 1341, in main
    lib.parseSignalP(signalp_out, secreted_out)
  File "/mnt/home/lukaskon/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py", line 7299, in parseSignalP
    pos = components[2].split("-")[0]
IndexError: list index out of range
```

**Comment by hyphaltip** [comment]
would help to have a snapshot of your failed file and what version of funannotate you are running. are you running signalp outside of funannotate then?

 I just ran an annotation with signalp6 installed but I think I had to tweak something in the latest code release so you might need to grab code from github to make sure it is all working.

**Comment by lukaskon** [comment]
I am running funannotate v1.8.15 and yes, signalp6 outside of funannotate.

Here is the annotate log file:
[B5_signalp_annotate_slurm.txt](https://github.com/nextgenusfs/funannotate/files/11807957/B5_signalp_annotate_slurm.txt)
Here are the signalp results from annotate_misc:
![image](https://github.com/nextgenusfs/funannotate/assets/92044283/abc6eccc-198a-47c7-a9f0-ed3807ae4176)
[signalp.results.txt](https://github.com/nextgenusfs/funannotate/files/11807959/signalp.results.txt)


If the issue is the signalp file format, maybe I can reformat to make this compatible for the time being.

Let me know if anything else would be helpful. Thank you!

**Comment by blemmond** [comment]
Hello, I am having a similar error but with Funannotate version 1.8.17. I ran signalp6 outside of funannotate:
signalp6 --version
SignalP 6.0 Signal peptide prediction tool 6.0h

Signalp output file: ﻿https://www.dropbox.com/scl/fi/guk9hbjhyzng158iwral5/Aatr-1_signalp.results.txt?rlkey=rosi1gz0lkkxz1to2wjle42qd&dl=0

Command used:
 funannotate annotate -i funannotate/predicted/Aatr-1_S1_L001/predict_results/ -o funannotate/annotated/Aatr-1_S1_L001 \
        -s Antrelloides --sbt funannotate/annotations_template.sbt \
        --eggnog funannotate/predicted/Aatr-1_S1_L001/eggnog/Aatr-1_S1_L001.emapper.annotations \
        --iprscan funannotate/predicted/Aatr-1_S1_L001/iprscan/Aatr-1_S1_L001.xml \
        --antismash funannotate/predicted/Aatr-1_S1_L001/antismash/Aatr-1_S1_L001.gbk \
        --signalp funannotate/predicted/Aatr-1_S1_L001/annotate_misc/signalp.results.txt \
        --cpus 8  --tmpdir funannotate_tmp --force

logfile:
Annotating Aatr-1_S1_L001
[Oct 15 09:50 PM]: OS: Red Hat Enterprise Linux 8.9, 64 cores, ~ 527 GB RAM. Python: 3.9.19
[Oct 15 09:50 PM]: Running 1.8.17
[Oct 15 09:50 PM]: Found existing output directory /blue/matthewsmith/blemmond/pezizales/funannotate/predicted/Aatr-1_S1_L001. Warning, will re-use any intermediate files found.
[Oct 15 09:50 PM]: Parsing input files
[Oct 15 09:50 PM]: Existing tbl found: /blue/matthewsmith/blemmond/pezizales/funannotate/predicted/Aatr-1_S1_L001/predict_results/Antrelloides_atroceracea.tbl
[Oct 15 09:50 PM]: Adding Functional Annotation to Antrelloides_atroceracea, NCBI accession: None
[Oct 15 09:50 PM]: Annotation consists of: 9,294 gene models
[Oct 15 09:50 PM]: 9,131 protein records loaded
[Oct 15 09:50 PM]: Existing Pfam-A results found: /blue/matthewsmith/blemmond/pezizales/funannotate/predicted/Aatr-1_S1_L001/annotate_misc/annotations.pfam.txt
[Oct 15 09:50 PM]: 9,015 annotations added
[Oct 15 09:50 PM]: Running Diamond blastp search of UniProt DB version 2022_01
[Oct 15 09:50 PM]: 577 valid gene/product annotations from 769 total
[Oct 15 09:50 PM]: Existing Eggnog-mapper results found: /blue/matthewsmith/blemmond/pezizales/funannotate/predicted/Aatr-1_S1_L001/annotate_misc/eggnog.emapper.annotations
[Oct 15 09:50 PM]: Parsing EggNog Annotations
[Oct 15 09:50 PM]: EggNog version parsed as 2.1.12
[Oct 15 09:50 PM]: 14,178  COG and EggNog annotations added
[Oct 15 09:50 PM]: Combining UniProt/EggNog gene and product names using Gene2Product version 1.75
[Oct 15 09:50 PM]: 2,580 gene name and product description annotations added
[Oct 15 09:50 PM]: Existing MEROPS results found: /blue/matthewsmith/blemmond/pezizales/funannotate/predicted/Aatr-1_S1_L001/annotate_misc/annotations.merops.txt
[Oct 15 09:50 PM]: 213 annotations added
[Oct 15 09:50 PM]: Existing CAZYme results found: /blue/matthewsmith/blemmond/pezizales/funannotate/predicted/Aatr-1_S1_L001/annotate_misc/annotations.dbCAN.txt
[Oct 15 09:50 PM]: 229 annotations added
[Oct 15 09:50 PM]: Existing BUSCO2 results found: /blue/matthewsmith/blemmond/pezizales/funannotate/predicted/Aatr-1_S1_L001/annotate_misc/annotations.busco.txt
[Oct 15 09:50 PM]: 1,239 annotations added
[Oct 15 09:50 PM]: Skipping phobius predictions, try funannotate remote -m phobius
[Oct 15 09:50 PM]: Existing SignalP results found: /blue/matthewsmith/blemmond/pezizales/funannotate/predicted/Aatr-1_S1_L001/annotate_misc/signalp.results.txt
-------------------------------------------------------
Traceback (most recent call last):
  File "/apps/funannotate/1.8.17/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/apps/funannotate/1.8.17/lib/python3.9/site-packages/funannotate/funannotate.py", line 717, in main
    mod.main(arguments)
  File "/apps/funannotate/1.8.17/lib/python3.9/site-packages/funannotate/annotate.py", line 1350, in main
    lib.parseSignalP(signalp_out, secreted_out)
  File "/apps/funannotate/1.8.17/lib/python3.9/site-packages/funannotate/library.py", line 7314, in parseSignalP
    pos = components[2].split("-")[0]
IndexError: list index out of range

system info from funannotate check --show-versions:
Checking dependencies for 1.8.17
-------------------------------------------------------
You are running Python v 3.9.19. Now checking python packages...
biopython: 1.79
goatools: 1.4.12
matplotlib: 3.9.2
natsort: 8.4.0
numpy: 1.26.4
pandas: 2.2.3
psutil: 6.0.0
requests: 2.32.3
scikit-learn: 1.5.2
scipy: 1.13.1
seaborn: 0.13.2
All 11 python packages installed


You are running Perl v b'5.032001'. Now checking perl modules...
Carp: 1.50
Clone: 0.46
DBD::SQLite: 1.72
DBD::mysql: 4.050
DBI: 1.643
DB_File: 1.858
Data::Dumper: 2.183
File::Basename: 2.85
File::Which: 1.24
Getopt::Long: 2.58
Hash::Merge: 0.302
JSON: 4.10
LWP::UserAgent: 6.67
Logger::Simple: 2.0
POSIX: 1.94
Parallel::ForkManager: 2.03
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.14
Tie::File: 1.06
URI::Escape: 5.17
YAML: 1.30
local::lib: 2.000029
threads: 2.25
threads::shared: 1.61
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/data/reference/funannotate/v1
$PASAHOME=/apps/funannotate/1.8.17/opt/pasa-2.5.2
$TRINITYHOME=/apps/funannotate/1.8.17/opt/trinity-2.8.5
$EVM_HOME=/apps/funannotate/evidencemodeler/1.1.1
$AUGUSTUS_CONFIG_PATH=/apps/funannotate/1.8.17/config
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
CodingQuarry: 2.0
Trinity: 2.15.2
augustus: 3.5.0
bamtools: bamtools 2.5.2
bedtools: bedtools v2.31.1
blat: BLAT v39x1
diamond: 2.1.8
ete3: 3.1.3
exonerate: exonerate 2.4.0
fasta: 36.3.8g
glimmerhmm: 3.0.4
gmap: 2024-10-10
gmes_petap.pl: 4.71_lic
hisat2: 2.2.1
hmmscan: HMMER 3.4 (Aug 2023)
hmmsearch: HMMER 3.4 (Aug 2023)
java: 22.0.1-internal
kallisto: 0.46.1
mafft: v7.526 (2024/Apr/26)
makeblastdb: makeblastdb 2.16.0+
minimap2: 2.28-r1209
pigz: 2.8
proteinortho: 6.3.2
pslCDnaFilter: no way to determine
salmon: salmon 1.10.3
samtools: samtools 1.21
snap: 2006-07-28
stringtie: 2.2.3
tRNAscan-SE: 2.0.12 (Nov 2022)
tantan: tantan 50
tbl2asn: 25.8
tblastn: tblastn 2.16.0+
trimal: trimAl v1.5.rev0 build[2024-05-27]
trimmomatic: 0.39
	ERROR: /apps/funannotate/1.8.17/opt/pasa-2.5.2/Launch_PASA_pipeline.pl not installed
	ERROR: emapper.py not installed
	ERROR: signalp not installed

**Comment by hyphaltip** [comment]
hi. I am not sure if this got resolved? I can't download the test file so I'm not sure what is different in the output format in your example. You can attach files to the git issue as well if you want to share a snapshot of the data.
