### ISSUE TITLE
Error: Incomplete database file. Database building did not complete successfully

### ISSUE THREAD

**Issue by mictadlo** [nextgenusfs/funannotate#655]
Hi, 
I have just run into `Error: Incomplete database file. Database building did not complete successfully`. I used the following file as protein evidence:

[NbenthamianaGenbankAA.clean.fasta.gz](https://github.com/nextgenusfs/funannotate/files/7415125/NbenthamianaGenbankAA.clean.fasta.gz)

```
  ./funannotate-docker predict -i NbLab330.genome.softmasked.fasta -o annotate --species LAB330 --protein_evidence NbenthamianaGenbankAA.clean.fasta -o annotate --ploidy 2 --cpus 12
-------------------------------------------------------
[Oct 26 03:26 AM]: OS: Debian GNU/Linux 10, 32 cores, ~ 132 GB RAM. Python: 3.8.12
[Oct 26 03:26 AM]: Running funannotate v1.8.10
[Oct 26 03:26 AM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[Oct 26 03:26 AM]: Skipping CodingQuarry as no --rna_bam passed
[Oct 26 03:26 AM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     busco          
  glimmerhmm   busco          
  snap         busco          
[Oct 26 03:36 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Oct 26 03:38 AM]: Genome loaded: 20 scaffolds; 2,836,899,092 bp; 77.56% repeats masked
[Oct 26 03:38 AM]: Mapping 0 proteins to genome using diamond and exonerate
[Oct 26 03:38 AM]: CMD ERROR: diamond blastx --threads 8 -q /mnt/OneTB/annotation/funannotate/annotate/predict_misc/genome.softmasked.fa --db diamond -o diamond.matches.tab -e 1e-10 -k 0 --more-sensitive -f 6 sseqid slen sstart send qseqid qlen qstart qend pident length evalue score qcovhsp qframe
b'diamond v2.0.13.151 (C) Max Planck Society for the Advancement of Science\nDocumentation, support and updates available at http://www.diamondsearch.org\nPlease cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)\n\n#CPU threads: 8\nScoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)\nTemporary directory: \n#Target sequences to report alignments for: unlimited\nOpening the database...  [0s]\nError: Incomplete database file. Database building did not complete successfully.\n'
Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 710, in main
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/predict.py", line 1051, in main
    lib.exonerate2hints(Exonerate, hintsP)
  File "/venv/lib/python3.8/site-packages/funannotate/library.py", line 4026, in exonerate2hints
    with open(file, 'r') as input:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/OneTB/annotation/funannotate/annotate/predict_misc/protein_alignments.gff3'
```

Thank you in advance,

Best wishes,

Michal

**Comment by mictadlo** [comment]
Hi, 
After login inside the funannotate docker container and executing diamond command I got `Error: Error reading input stream at line 2: Invalid character (F) in sequence`

I changed the last in `funannotate-docker` to `exec docker run -ti --rm "${IT[@]}" --user "${USER}" -e TZ="${TZ}" --workdir "${WORKDIR}" --mount "${MOUNT}" nextgenusfs/funannotate:latest bash`. Next, I ran the following commands:


```
$ ./funannotate-docker predict -i NbLab330.genome.softmasked.fasta -o annotate --species LAB330 --protein_evidence NbenthamianaGenbankAA.clean.fasta -o annotate --ploidy 2 --cpus 12 --tmpdir .
I have no name!@03f7b3ce6426:/mnt/OneTB/annotation/funannotate$ ls 
LAB330				      annotate
NbLab330.genome.softmasked.fasta      funannotate-docker
NbenthamianaGenbankAA.clean.fasta     funannotate-setup.log
NbenthamianaGenbankAA.clean.fasta.gz  p2g_3262a5da-9210-4108-8c02-589680e7fe7b
NbenthamianaGenbankAA.fasta	      viridiplantae_odb10
NbenthamianaGenbankAA.fasta.gz	      viridiplantae_odb10.2020-09-10.tar.gz

I have no name!@03f7b3ce6426:/mnt/OneTB/annotation/funannotate$ ls
LAB330				      annotate
NbLab330.genome.softmasked.fasta      funannotate-docker
NbenthamianaGenbankAA.clean.fasta     funannotate-setup.log
NbenthamianaGenbankAA.clean.fasta.gz  p2g_3262a5da-9210-4108-8c02-589680e7fe7b
NbenthamianaGenbankAA.fasta	      viridiplantae_odb10
NbenthamianaGenbankAA.fasta.gz	      viridiplantae_odb10.2020-09-10.tar.gz


I have no name!@03f7b3ce6426:/mnt/OneTB/annotation/funannotate$ diamond makedb --in NbenthamianaGenbankAA.fasta --db diamond -p 8
diamond v2.0.13.151 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: NbenthamianaGenbankAA.fasta
Opening the database file...  [0s]
Loading sequences...  [0.008s]
Masking sequences...  [0.011s]
Writing sequences...  [0s]
Hashing sequences...  [0s]
Loading sequences...  [0s]
Writing trailer...  [0s]
Closing the input file...  [0s]
Closing the database file...  [0s]

Database sequences  1009
  Database letters  459890
     Database hash  4be250d90c5507a46010ef33b2213930
        Total time  0.022000s


I have no name!@03f7b3ce6426:/mnt/OneTB/annotation/funannotate$ diamond blastx --threads 8 -q NbenthamianaGenbankAA.fasta --db diamond -o diamond.matches.tab -e 1e-10 -k 0 --more-sensitive -f 6 sseqid slen sstart send qseqid qlen qstart qend pident length evalue score qcovhsp qframe
diamond v2.0.13.151 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: 
#Target sequences to report alignments for: unlimited
Opening the database...  [0.001s]
Database: diamond.dmnd (type: Diamond database, sequences: 1009, letters: 459890)
Block size = 2000000000
Opening the input file...  [0s]
Opening the output file...  [0s]
Loading query sequences...  [0s]
Error: Error reading input stream at line 2: Invalid character (F) in sequence
I have no name!@03f7b3ce6426:/mnt/OneTB/annotation/funannotate$ diamond blastx --threads 8 -q NbenthamianaGenbankAA.fasta --db diamond -o diamond.matches.tab -e 1e-10 -k 0 --more-sensitive -f 6 sseqid slen sstart send qseqid qlen qstart qend pident length evalue score qcovhsp qframeAA
```
How is it possible to fix it?

Thank you in advance,

Michal

**Comment by nextgenusfs** [comment]
diamond query is your genome against the protein database, here you ran protein against protein.

**Comment by mictadlo** [comment]
Hi,
I am using diamond version 2.0.13 and according to 
https://github.com/nextgenusfs/funannotate/blob/fa4b1e201220f297d1d133e0dda6b175f9b18d95/funannotate/aux_scripts/funannotate-p2g.py#L92-L107
it should have used the frameshift mode but looking at the logs it looks like it did not use it.

```
 funannotate predict -i NbLab330.genome.softmasked.fasta -o annotate --species LAB330 --protein_evidence NbenthamianaGenbankAA.clean.fasta -o annotate --ploidy 2 --cpus 4 --busco_db viridiplantae_odb10
-------------------------------------------------------
[Nov 17 10:44 PM]: OS: Debian GNU/Linux 11, 32 cores, ~ 132 GB RAM. Python: 3.8.12
[Nov 17 10:44 PM]: Running funannotate v1.8.9
[Nov 17 10:44 PM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[Nov 17 10:44 PM]: Skipping CodingQuarry as no --rna_bam passed
[Nov 17 10:44 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     busco          
  glimmerhmm   busco          
  snap         busco          
[Nov 17 10:54 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Nov 17 10:57 PM]: Genome loaded: 20 scaffolds; 2,836,899,092 bp; 77.56% repeats masked
[Nov 17 10:57 PM]: Mapping 0 proteins to genome using diamond and exonerate
[Nov 17 10:57 PM]: CMD ERROR: diamond blastx --threads 4 -q /mnt/OneTB/annotation/funannotate/annotate/predict_misc/genome.softmasked.fa --db diamond -o diamond.matches.tab -e 1e-10 -k 0 --more-sensitive -f 6 sseqid slen sstart send qseqid qlen qstart qend pident length evalue score qcovhsp qframe
b'diamond v2.0.13.151 (C) Max Planck Society for the Advancement of Science\nDocumentation, support and updates available at http://www.diamondsearch.org\nPlease cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)\n\n#CPU threads: 4\nScoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)\nTemporary directory: \n#Target sequences to report alignments for: unlimited\nOpening the database...  [0.004s]\nError: Incomplete database file. Database building did not complete successfully.\n'
Traceback (most recent call last):
  File "/mnt/OneTB/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/mnt/OneTB/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/mnt/OneTB/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/predict.py", line 1049, in main
    lib.exonerate2hints(Exonerate, hintsP)
  File "/mnt/OneTB/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py", line 4026, in exonerate2hints
    with open(file, 'r') as input:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/OneTB/annotation/funannotate/annotate/predict_misc/protein_alignments.gff3'
```

How do make diamond use frameshift mode?

Thank you in advance

**Comment by mictadlo** [comment]
P.S.
```
 >>> '2.0.13' >= '2.0.5'
False
```
Therefore, it does not use frameshift mode. Maybe, it would be a good idea to run it always as frameshift mode.

**Comment by nextgenusfs** [comment]
I believe this is all fixed in master as I rewrote that script https://github.com/nextgenusfs/funannotate/blob/master/funannotate/aux_scripts/funannotate-p2g.py. 

Upgrade with pip to install master from git to see if that fixes it.

**Comment by nextgenusfs** [comment]
Sorry you were right that needed to be wrapped in the version parsing function -- install from master should now work I think, ie
```
python -m pip install git+https://github.com/nextgenusfs/funannotate.git --upgrade --force --no-deps
```

**Comment by mictadlo** [comment]
Thank you the error disappeared. Maybe, it would be a good idea to provide a warning to update diamond because otherwise it can't be used for bigger genomes.

**Comment by nextgenusfs** [comment]
It doesn't seem that you are running the current code in master, v1.8.9 was last release while the master installed version should read v1.8.10.

**Comment by mictadlo** [comment]
Ops, my fault. I updated and it uses now frameshift. Unfortunately, it get again the same error:

```
$ funannotate predict -i NbLab330.genome.softmasked.fasta -o annotate --species LAB330 --protein_evidence NbenthamianaGenbankAA.clean.fasta -o annotate --ploidy 2 --cpus 1 --busco_db viridiplantae_odb10
-------------------------------------------------------
[Nov 20 02:08 AM]: OS: Debian GNU/Linux 11, 32 cores, ~ 132 GB RAM. Python: 3.8.12
[Nov 20 02:08 AM]: Running funannotate v1.8.9
[Nov 20 02:08 AM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[Nov 20 02:08 AM]: Skipping CodingQuarry as no --rna_bam passed
[Nov 20 02:08 AM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     busco          
  glimmerhmm   busco          
  snap         busco          
[Nov 20 02:18 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Nov 20 02:29 AM]: Genome loaded: 20 scaffolds; 2,836,899,092 bp; 77.56% repeats masked
[Nov 20 02:29 AM]: Mapping 0 proteins to genome using diamond and exonerate
[Nov 20 02:29 AM]: CMD ERROR: diamond blastx --threads 1 -q /mnt/OneTB/annotation/funannotate/annotate/predict_misc/genome.softmasked.fa --db diamond -o diamond.matches.tab -e 1e-10 -k 0 --more-sensitive --unal 0 -F 15 -f 6 sseqid slen sstart send qseqid qlen qstart qend pident length evalue score qcovhsp qframe
b'diamond v2.0.13.151 (C) Max Planck Society for the Advancement of Science\nDocumentation, support and updates available at http://www.diamondsearch.org\nPlease cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)\n\n#CPU threads: 1\nScoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)\nTemporary directory: \n#Target sequences to report alignments for: unlimited\nOpening the database...  [0s]\nError: Incomplete database file. Database building did not complete successfully.\n'
Traceback (most recent call last):
  File "/mnt/OneTB/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/mnt/OneTB/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/mnt/OneTB/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/predict.py", line 1049, in main
    lib.exonerate2hints(Exonerate, hintsP)
  File "/mnt/OneTB/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py", line 4026, in exonerate2hints
    with open(file, 'r') as input:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/OneTB/annotation/funannotate/annotate/predict_misc/protein_alignments.gff3'
```
However, when I ran the same command manually, it finished without any errors:
```
(funannotate) debian@appdev:/mnt/OneTB/annotation/funannotate$ diamond blastx --threads 1 -q /mnt/OneTB/annotation/funannotate/annotate/predict_misc/genome.softmasked.fa --db diamond -o diamond.matches.tab -e 1e-10 -k 0 --more-sensitive --unal 0 -F 15 -f 6 sseqid slen sstart send qseqid qlen qstart qend pident length evalue score qcovhsp qframe
diamond v2.0.13.151 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: 
#Target sequences to report alignments for: unlimited
Opening the database...  [0.003s]
Database: diamond.dmnd (type: Diamond database, sequences: 1009, letters: 459890)
Block size = 2000000000
Opening the input file...  [0.042s]
Opening the output file...  [0s]
Loading query sequences...  [13.657s]
Masking queries...  [305.267s]
Algorithm: Double-indexed
Building query histograms...  [279.892s]
Allocating buffers...  [0s]
Loading reference sequences...  [0.001s]
Masking reference...  [0.044s]
Initializing temporary storage...  [0s]
Building reference histograms...  [0.11s]
Allocating buffers...  [0s]
Processing query block 1, reference block 1/1, shape 1/16, index chunk 1/4.
Building reference seed array...  [0.011s]
Building query seed array...  [28.012s]
Computing hash join...  [4.937s]
Masking low complexity seeds...  [0.108s]
Searching alignments...  [0.659s]
Processing query block 1, reference block 1/1, shape 1/16, index chunk 2/4.
Building reference seed array...  [0.015s]
...
Loading reference sequences...  [0s]
Deallocating buffers...  [0.005s]
Deallocating queries...  [0.005s]
Loading query sequences...  [0s]
Closing the input file...  [0s]
Closing the output file...  [0.001s]
Cleaning up...  [0s]
Total time = 7823.18s
Reported 9366 pairwise alignments, 9366 HSPs.
20 queries aligned.
```
What could cause i
[diamond.matches.tab.txt](https://github.com/nextgenusfs/funannotate/files/7574222/diamond.matches.tab.txt)
t?
