### ISSUE TITLE
funannotate mask error

### ISSUE THREAD

**Issue by liuyca1** [nextgenusfs/funannotate#671]
When we use "funannotate mask" to Mask repetitive sequences, an error message appeared [，what's puzzling is that currently this error only appears in the genome of [Flammulina velutipes](https://www.ncbi.nlm.nih.gov/genome/16873?genome_assembly_id=845190) and other species are operating normally.

Running record

(funannotate) [liuyuanchao@master01 /data/liuyuanchao/funannotate_test/Analysis/Flammulina_velutipes]
 $ls -l
total 37712
-rwxr-xr-x 1 liuyuanchao liuyuanchao 38605067 Nov 25 15:57 GCA_011800155.1_ASM1180015v1_genomic.fna
-rwxr-xr-x 1 liuyuanchao liuyuanchao      470 Nov 25 15:53 LongSequence_ID_Rename.pl
-rwxr-xr-x 1 liuyuanchao liuyuanchao      865 Nov 25 15:54 work.sh
(funannotate) [liuyuanchao@master01 /data/liuyuanchao/funannotate_test/Analysis/Flammulina_velutipes]
 $funannotate mask -i GCA_011800155.1_ASM1180015v1_genomic.fna --cpus 48 -o ./GCA_011800155.1_ASM1180015v1_genomic.fna
-------------------------------------------------------
[Nov 25 03:59 PM]: OS: CentOS Linux 7, 160 cores, ~ 958 GB RAM. Python: 3.9.7
[Nov 25 03:59 PM]: Running funanotate v1.8.7
[Nov 25 03:59 PM]: Soft-masking simple repeats with tantan
**Traceback (most recent call last):
  File "/opt/anaconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/funannotate/lib/python3.9/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/opt/anaconda3/envs/funannotate/lib/python3.9/site-packages/funannotate/mask.py", line 189, in main
    percentMask = maskedSize / float(GenomeLength)
ZeroDivisionError: float division by zero**
(funannotate) [liuyuanchao@master01 /data/liuyuanchao/funannotate_test/Analysis/Flammulina_velutipes]
 $ls -l
total 12
-rw-rw-r-- 1 liuyuanchao liuyuanchao 435 Nov 25 15:59 funannotate-mask.log
-rwxr-xr-x 1 liuyuanchao liuyuanchao   0 Nov 25 15:59 GCA_011800155.1_ASM1180015v1_genomic.fna
-rwxr-xr-x 1 liuyuanchao liuyuanchao 470 Nov 25 15:53 LongSequence_ID_Rename.pl
-rwxr-xr-x 1 liuyuanchao liuyuanchao 865 Nov 25 15:54 work.sh

 $funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.8.7
-------------------------------------------------------
You are running Python v 3.9.7. Now checking python packages...
biopython: 1.79
goatools: 1.1.6
matplotlib: 3.4.3
natsort: 8.0.0
numpy: 1.21.4
pandas: 1.3.4
psutil: 5.8.0
requests: 2.26.0
scikit-learn: 1.0.1
scipy: 1.7.0
seaborn: 0.11.2
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/data/liuyuanchao/funannotate_test/all_database
$PASAHOME=/opt/anaconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/opt/anaconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/opt/anaconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/opt/anaconda3/envs/funannotate/config/
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.8
emapper.py: 2.1.3
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2018-07-04
gmes_petap.pl: 4.68_lic
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.490 (2021/Oct/30)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.22-r1101
proteinortho: 6.0.31
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.10
signalp: 5.0b
snap: 2006-07-28
stringtie: 2.1.7
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 26
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 36 external dependencies are installed

**Comment by liuyca1** [comment]
I added a parameter and succeeded inexplicably
 $funannotate mask -i GCA_011800155.1_ASM1180015v1_genomic.fna --cpus 48 -o ./GCA_011800155.1_ASM1180015v1_genomic_masked.fna --debug
-------------------------------------------------------
[Nov 25 04:24 PM]: OS: CentOS Linux 7, 160 cores, ~ 958 GB RAM. Python: 3.9.7
[Nov 25 04:24 PM]: Running funanotate v1.8.7
[Nov 25 04:24 PM]: Soft-masking simple repeats with tantan
[Nov 25 04:24 PM]: Repeat soft-masking finished: 
Masked genome: /data/liuyuanchao/funannotate_test/Analysis/Flammulina_velutipes/GCA_011800155.1_ASM1180015v1_genomic_masked.fna
num scaffolds: 23
assembly size: 38,126,399 bp
masked repeats: 3,364,706 bp (8.83%)
-------------------------------------------------------
