### ISSUE TITLE
funannotate remote errors

### ISSUE THREAD

**Issue by liuyca1** [nextgenusfs/funannotate#677]
we used the latest release
 $funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.8.9
-------------------------------------------------------
You are running Python v 3.7.12. Now checking python packages...
biopython: 1.77
goatools: 1.1.6
matplotlib: 3.4.3
natsort: 8.0.0
numpy: 1.21.4
pandas: 1.3.4
psutil: 5.8.0
requests: 2.26.0
scikit-learn: 1.0.1
scipy: 1.7.0
seaborn: 0.11.2
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.7.8
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/public/home/liuyuanchao/software/funannotate/database
$PASAHOME=/public/home/liuyuanchao/software/anaconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/public/home/liuyuanchao/software/anaconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/public/home/liuyuanchao/software/anaconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/public/home/liuyuanchao/software/anaconda3/envs/funannotate/config/
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.13
emapper.py: 2.1.3
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2021-08-25
gmes_petap.pl: 4.68_lic
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.490 (2021/Oct/30)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.22-r1101
proteinortho: 6.0.31
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.9
signalp: 5.0b
snap: 2006-07-28
stringtie: 2.1.7
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 26
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 36 external dependencies are installed

After successful completed the "funannotate predict" and "funannotate iprscan"
we start the "funannotate remote", but this process has reported errors

 $funannotate remote -i ./fun -m all -o ./fun -e liuyc1020@163.com
-------------------------------------------------------
[Dec 11 12:09 PM]: OS: CentOS Linux 7, 80 cores, ~ 1584 GB RAM. Python: 3.7.12
[Dec 11 12:09 PM]: Running 1.8.9
[Dec 11 12:09 PM]: Output directory ./fun already exists, will use any existing data.  If this is not what you want, exit, and provide a unique name for output folder
[Dec 11 12:09 PM]: Parsing input files
[Dec 11 12:09 PM]: Predicting secreted and transmembrane proteins using Phobius
Traceback (most recent call last):
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4e59b38d90>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fungismash.secondarymetabolites.org', port=443): Max retries exceeded with url: /api/v1.0/version (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4e59b38d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/remote.py", line 242, in main
    version = requests.get(base_address+"/api/v1.0/version")
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='fungismash.secondarymetabolites.org', port=443): Max retries exceeded with url: /api/v1.0/version (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4e59b38d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

 $funannotate remote -i ./fun -m antismash -o ./fun -e liuyc1020@163.com
-------------------------------------------------------
[Dec 11 12:29 PM]: OS: CentOS Linux 7, 80 cores, ~ 1584 GB RAM. Python: 3.7.12
[Dec 11 12:29 PM]: Running 1.8.9
[Dec 11 12:29 PM]: Output directory ./fun already exists, will use any existing data.  If this is not what you want, exit, and provide a unique name for output folder
[Dec 11 12:29 PM]: Parsing input files
Traceback (most recent call last):
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9a65ae85d0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fungismash.secondarymetabolites.org', port=443): Max retries exceeded with url: /api/v1.0/version (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9a65ae85d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/remote.py", line 242, in main
    version = requests.get(base_address+"/api/v1.0/version")
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/public/home/liuyuanchao/software/anaconda3/envs/funannotate/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='fungismash.secondarymetabolites.org', port=443): Max retries exceeded with url: /api/v1.0/version (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9a65ae85d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by nextgenusfs** [comment]
Are you behind a proxy or firewall? It's either that or the remote services have both changed their endpoint urls, I have not used either in quite some time.

**Comment by liuyca1** [comment]
> Are you behind a proxy or firewall? It's either that or the remote services have both changed their endpoint urls, I have not used either in quite some time.

Thank you very much. After testing, it can be run normally after exiting the server node. The error may be the network security settings. This needs to be confirmed with the administrator.
