### ISSUE TITLE
About maker output format!

### ISSUE THREAD

**Issue by sunnycqcn** [nextgenusfs/funannotate#681]
Hello Jon,
Thanks for your updating funannotate. It is awesome pipeline to predict and annotate genome.
I want to use my maker results in my prediction command.
However, I alway get the error about 
```
[Dec 13 11:08 AM]: OS: CentOS Linux 7, 80 cores, ~ 1057 GB RAM. Python: 3.8.12
[Dec 13 11:08 AM]: Running funannotate v1.8.10
[Dec 13 11:08 AM]: Found training files, will re-use these files:
  --rna_bam SH/training/funannotate_train.coordSorted.bam
  --pasa_gff SH/training/funannotate_train.pasa.gff3
  --stringtie SH/training/funannotate_train.stringtie.gtf
  --transcript_alignments SH/training/funannotate_train.transcripts.gff3
[Dec 13 11:08 AM]: Skipping CodingQuarry as --organism=other. Pass a weight larger than 0 to run CQ, ie --weights codingquarry:1
[Dec 13 11:08 AM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     pasa
  genemark     selftraining
  glimmerhmm   pasa
  snap         pasa
[Dec 13 11:12 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Dec 13 11:13 AM]: Genome loaded: 20 scaffolds; 1,022,923,124 bp; 11.76% repeats masked
[Dec 13 11:13 AM]: Parsing Maker2 GFF for use in EVidence Modeler
Traceback (most recent call last):
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/FUN/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/FUN/lib/python3.8/site-packages/funannotate/funannotate.py", line 710, in main
    mod.main(arguments)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/FUN/lib/python3.8/site-packages/funannotate/predict.py", line 829, in main
    source = line.split('\t')[1]
IndexError: list index out of range
`
My maker results is directly gotten using gff3_merge -d -n after I run maker. Some of lines like following :
`##gff-version 3
SH8     .       contig  1       52352739        .       .       .       ID=SH8;Name=SH8
SH8     maker   gene    4112    8514    .       -       .       ID=evm-SH8-processed-gene-0.6;Name=evm-SH8-processed-gene-0.6
SH8     maker   mRNA    4112    8514    .       -       .       ID=evm-SH8-processed-gene-0.6-mRNA-1;Parent=evm-SH8-processed-gene-0.6;Name=evm-SH8-processed-gene-0.6-mRNA-1;_AED=0.08;_eAED=0.08;_QI=2614|1|0.66|1|1|1|3|569|252
SH8     maker   exon    4112    4968    .       -       .       ID=evm-SH8-processed-gene-0.6-mRNA-1:3;Parent=evm-SH8-processed-gene-0.6-mRNA-1
SH8     maker   exon    5063    5299    .       -       .       ID=evm-SH8-processed-gene-0.6-mRNA-1:2;Parent=evm-SH8-processed-gene-0.6-mRNA-1
SH8     maker   exon    5667    8514    .       -       .       ID=evm-SH8-processed-gene-0.6-mRNA-1:1;Parent=evm-SH8-processed-gene-0.6-mRNA-1
SH8     maker   five_prime_UTR  5901    8514    .       -       .       ID=evm-SH8-processed-gene-0.6-mRNA-1:five_prime_utr;Parent=evm-SH8-processed-gene-0.6-mRNA-1
SH8     maker   CDS     5667    5900    .       -       0       ID=evm-SH8-processed-gene-0.6-mRNA-1:cds;Parent=evm-SH8-processed-gene-0.6-mRNA-1
SH8     maker   CDS     5063    5299    .       -       0       ID=evm-SH8-processed-gene-0.6-mRNA-1:cds;Parent=evm-SH8-processed-gene-0.6-mRNA-1
SH8     maker   CDS     4681    4968    .       -       0       ID=evm-SH8-processed-gene-0.6-mRNA-1:cds;Parent=evm-SH8-processed-gene-0.6-mRNA-1
SH8     maker   three_prime_UTR 4112    4680    .       -       .       ID=evm-SH8-processed-gene-0.6-mRNA-1:three_prime_utr;Parent=evm-SH8-processed-gene-0.6-mRNA-1
SH8     maker   gene    27452   29654   .       -       .       ID=evm-SH8-processed-gene-0.5;Name=evm-SH8-processed-gene-0.5
SH8     maker   mRNA    27452   29654   .       -       .       ID=evm-SH8-processed-gene-0.5-mRNA-1;Parent=evm-SH8-processed-gene-0.5;Name=evm-SH8-processed-gene-0.5-mRNA-1;_AED=0.12;_eAED=0.12;_QI=1002|1|1|1|0|0.33|3|656|118
SH8     maker   exon    27452   29057   .       -       .       ID=evm-SH8-processed-gene-0.5-mRNA-1:3;Parent=evm-SH8-processed-gene-0.5-mRNA-1
SH8     maker   exon    29159   29312   .       -       .       ID=evm-SH8-processed-gene-0.5-mRNA-1:2;Parent=evm-SH8-processed-gene-0.5-mRNA-1
SH8     maker   exon    29400   29654   .       -       .       ID=evm-SH8-processed-gene-0.5-mRNA-1:1;Parent=evm-SH8-processed-gene-0.5-mRNA-1
SH8     maker   five_prime_UTR  29400   29654   .       -       .       ID=evm-SH8-processed-gene-0.5-mRNA-1:five_prime_utr;Parent=evm-SH8-processed-gene-0.5-mRNA-1
SH8     maker   five_prime_UTR  29159   29312   .       -       .       ID=evm-SH8-processed-gene-0.5-mRNA-1:five_prime_utr;Parent=evm-SH8-processed-gene-0.5-mRNA-1
SH8     maker   five_prime_UTR  28465   29057   .       -       .       ID=evm-SH8-processed-gene-0.5-mRNA-1:five_prime_utr;Parent=evm-SH8-processed-gene-0.5-mRNA-1
SH8     maker   CDS     28108   28464   .       -       0       ID=evm-SH8-processed-gene-0.5-mRNA-1:cds;Parent=evm-SH8-processed-gene-0.5-mRNA-1
SH8     maker   three_prime_UTR 27452   28107   .       -       .       ID=evm-SH8-processed-gene-0.5-mRNA-1:three_prime_utr;Parent=evm-SH8-processed-gene-0.5-mRNA-1
SH8     maker   gene    43805   44769   .       +       .       ID=maker-SH8-exonerate_protein2genome-gene-0.1;Name=maker-SH8-exonerate_protein2genome-gene-0.1
SH8     maker   mRNA    43805   44769   67.58766        +       .       ID=maker-SH8-exonerate_protein2genome-gene-0.1-mRNA-1;Parent=maker-SH8-exonerate_protein2genome-gene-0
```
Thanks,
Fuyou

**Comment by nextgenusfs** [comment]
How did you pass the maker models to funannotate? It looks like error in GFF3 parsing, ie a line it did not expect.

**Comment by sunnycqcn** [comment]
You mean this line is not expected?
`##gff-version 3
SH8     .       contig  1       52352739        .       .       .       ID=SH8;Name=SH8`

**Comment by nextgenusfs** [comment]
Yeah, its most likely that -- I haven't used the maker pass through in a very long time, so I probably just need to update the GFF parser to make it ignore that stuff.

**Comment by sunnycqcn** [comment]
I see. 
Thanks,
Fuyou

**Comment by sunnycqcn** [comment]
Do you think it is useful to pass maker gff in funannotate pipeline?

**Comment by sunnycqcn** [comment]
In fact, funannotate pipeline looks to use EVM, which is the same as maker. Furthermore, funannotate pipeline use PASA to train dataset. I do not think maker gff is necessary.
Thanks,
Fuyou

**Comment by nextgenusfs** [comment]
I included it early on when I wrote this because I had some predictions already with Maker -- but generally I prefer to let funannotate run augustus, genemark, etc instead of importing those predictions -- by importing maker models it short circuits a lot of the de novo training that is done in funannotate.

**Comment by sunnycqcn** [comment]
OK. I think I got. If I want to know what is missing or different, I can directly compare their results.
Thanks,
Fuyou

**Comment by nextgenusfs** [comment]
So one of the reasons I initially started this project ~ 5 years ago was that maker produced models that did not pass NCBI specifications, ie short exons, short introns, etc. -- which required manual fixes/adjustments to hundreds of gene models.  At that time it did not use EVM. I haven't used maker since that time, so I don't know how it compares now to funannotate. But the maker_gff pass through option should still function, so I'll see if I can find some time to fix the parser.
