### ISSUE TITLE
Funannotate compare COGS error

### ISSUE THREAD

**Issue by fmobegi** [nextgenusfs/funannotate#682]
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**
funannotate compare seems to break when summarizing COGS:
```
[Dec 15 09:36 AM]: found 54/95 MEROPS familes with stdev >= 1.000000
/opt/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py:7917: MatplotlibDeprecationWarning: Calling add_axes() without argument is deprecated since 3.3 and will be removed two minor releases later. You may want to use add_subplot() instead.
  cbar_ax = fig.add_axes(shrink=0.4)
[Dec 15 09:36 AM]: Summarizing CAZyme results
[Dec 15 09:36 AM]: found 80/127 CAZy familes with stdev >= 1.000000
/opt/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py:7917: MatplotlibDeprecationWarning: Calling add_axes() without argument is deprecated since 3.3 and will be removed two minor releases later. You may want to use add_subplot() instead.
  cbar_ax = fig.add_axes(shrink=0.4)
[Dec 15 09:36 AM]: Summarizing COG results
Traceback (most recent call last):
  File "/opt/miniconda3/envs/funannotate/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/opt/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/compare.py", line 656, in main
    lib.donutplot(COGSdf2, resources.COGS, os.path.join(
  File "/opt/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py", line 7971, in donutplot
    plt.pie(data[0], labels=names, colors=color_palette)
  File "/home/fredrick/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 3006, in pie
    return gca().pie(
  File "/home/fredrick/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/fredrick/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 3102, in pie
    w = mpatches.Wedge((x, y), radius, 360. * min(theta1, theta2),
  File "/home/fredrick/.local/lib/python3.8/site-packages/matplotlib/patches.py", line 1167, in __init__
    self._recompute_path()
  File "/home/fredrick/.local/lib/python3.8/site-packages/matplotlib/patches.py", line 1179, in _recompute_path
    arc = Path.arc(theta1, theta2)
  File "/home/fredrick/.local/lib/python3.8/site-packages/matplotlib/path.py", line 950, in arc
    n = int(2 ** np.ceil((eta2 - eta1) / halfpi))
ValueError: cannot convert float NaN to integer
```
**What command did you issue?**
Copy/paste the command used.
`funannotate compare --cpus 14 --input *.gbk -o .`
**Logfiles**
Please provide relevant log files of the error. 

**OS/Install Information**
 -  output of `funannotate check --show-versions`
`1.8.9`

**Comment by nextgenusfs** [comment]
Can you provide a an example? It still works with test data, so I'm assuming either there are no COGS or there is a COG that got incorrectly parsed to NaN.

**Comment by fmobegi** [comment]
I think the problem was fixed by changing antismash version 5 to version 6 in the `remote.py` script.

**Comment by fmobegi** [comment]
You're right. Some isolates were missing COGS ad thus parsed incorrectly. I will update you once I have rerun the project again.
