### ISSUE TITLE
Error in Diamond step

### ISSUE THREAD

**Issue by samkleeman1** [nextgenusfs/funannotate#683]
Hi,

Many thanks for making this package available! I had an error as part of the funannotate predict step - it appears to be one that is mentioned in a previous issue #517 - however, I have the latest version of Diamond and I am still seeing the error.

Are you able to advise how to proceed.

With best wishes,

Sam Kleeman
PhD Student
Cold Spring Harbor Laboratory, NY

```
[Nov 09 09:54 AM]: OS: CentOS Linux 8, 96 cores, ~ 791 GB RAM. Python: 3.8.12
[Nov 09 09:54 AM]: Running funannotate v1.8.9
[Nov 09 09:54 AM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[Nov 09 09:54 AM]: Found training files, will re-use these files:
  --rna_bam BALBie_ragtag_train/training/funannotate_train.coordSorted.bam
  --pasa_gff BALBie_ragtag_train/training/funannotate_train.pasa.gff3
  --stringtie BALBie_ragtag_train/training/funannotate_train.stringtie.gtf
  --transcript_alignments BALBie_ragtag_train/training/funannotate_train.transcripts.gff3
[Nov 09 09:55 AM]: Skipping CodingQuarry as --organism=other. Pass a weight larger than 0 to run CQ, ie --weights codingquarry:1
[Nov 09 09:55 AM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     pasa           
  glimmerhmm   pasa           
  snap         pasa           
[Nov 09 10:08 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Nov 09 10:09 AM]: Genome loaded: 75 scaffolds; 2,720,020,157 bp; 44.10% repeats masked
[Nov 09 10:10 AM]: Parsed 658,535 transcript alignments from: BALBie_ragtag_train/training/funannotate_train.transcripts.gff3
[Nov 09 10:10 AM]: Creating transcript EVM alignments and Augustus transcripts hintsfile
[Nov 09 10:10 AM]: Extracting hints from RNA-seq BAM file using bam2hints
[Nov 09 10:11 AM]: Mapping 552,582 proteins to genome using diamond and exonerate
[Nov 10 08:50 PM]: CMD ERROR: diamond blastx --threads 8 -q /mnt/grid/janowitz/rdata/balbc_assembly/final/funannotate/BALBie_ragtag_train/predict_misc/genome.softmasked.fa --db diamond -o diamond.matches.tab -e 1e-10 -k 0 --more-sensitive -f 6 sseqid slen sstart send qseqid qlen qstart qend pident length evalue score qcovhsp qframe
b'diamond v2.0.13.151 (C) Max Planck Society for the Advancement of Science\nDocumentation, support and updates available at http://www.diamondsearch.org\nPlease cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)\n\n#CPU threads: 8\nScoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)\nTemporary directory: \n#Target sequences to report alignments for: unlimited\nOpening the database...  [0.053s]\nDatabase: diamond.dmnd (type: Diamond database, sequences: 552582, letters: 203471128)\nBlock size = 2000000000\nOpening the input file...  [0.254s]\nOpening the output file...  [0s]\nLoading query sequences...  [14.113s]\nMasking queries...  [41.464s]\nAlgorithm: Double-indexed\nBuilding query histograms...  [82.767s]\nAllocating buffers...  [0s]\nLoading reference sequences...  [0.702s]\nMasking reference...  [2.682s]\nInitializing temporary storage...  [0.002s]\nBuilding reference histograms...  [9.133s]\nAllocating buffers...  [0s]\nProcessing query block 1, reference block 1/1, shape 1/16, index chunk 1/4.\nBuilding reference seed array...  [0.662s]\nBuilding query seed array...  [5.36s]\nComputing hash join...  [1.087s]\nMasking low complexity seeds...  [0.169s]\nSearching alignments...  [8.202s]\nProcessing query block 1, reference block 1/1, shape 1/16, index chunk 2/4.\nBuilding reference seed array...  [0.762s]\nBuilding query seed array...  [6.133s]\nComputing hash join...  [1.131s]\nMasking low complexity seeds...  [0.134s]\nSearching alignments...  [8.301s]\nProcessing query block 1, reference block 1/1, shape 1/16, index chunk 3/4.\nBuilding reference seed array...  [0.801s]\nBuilding query seed array...  [6.351s]\nComputing hash join...  [1.084s]\nMasking low complexity seeds...  [0.151s]\nSearching alignments...  [8.361s]\nProcessing query block 1, reference block 1/1, shape 1/16, index chunk 4/4.\nBuilding reference seed array...  [0.629s]\nBuilding query seed array...  [5.652s]\nComputing hash join...  [1.034s]\nMasking low complexity seeds...  [0.146s]\nSearching alignments...  [8.597s]\nProcessing query block 1, reference block 1/1, shape 2/16, index chunk 1/4.\nBuilding reference seed array...  [0.627s]\nBuilding query seed array...  [6.06s]\nComputing hash join...  [1.086s]\nMasking low complexity seeds...  [0.154s]\nSearching alignments...  [9.153s]\nProcessing query block 1, reference block 1/1, shape 2/16, index chunk 2/4.\nBuilding reference seed array...  [0.721s]\nBuilding query seed array...  [6.735s]\nComputing hash join...  [1.08s]\nMasking low complexity seeds...  [0.157s]\nSearching alignments...  [9.042s]\nProcessing query block 1, reference block 1/1, shape 2/16, index chunk 3/4.\nBuilding reference seed array...  [0.755s]\nBuilding query seed array...  [6.552s]\nComputing hash join...  [1.089s]\nMasking low complexity seeds...  [0.155s]\nSearching alignments...  [7.517s]\nProcessing query block 1, reference block 1/1, shape 2/16, index chunk 4/4.\nBuilding reference seed array...  [0.612s]\nBuilding query seed array...  [5.928s]\nComputing hash join...  [1.073s]\nMasking low complexity seeds...  [0.149s]\nSearching alignments...  [7.714s]\nProcessing query block 1, reference block 1/1, shape 3/16, index chunk 1/4.\nBuilding reference seed array...  [0.643s]\nBuilding query seed array...  [5.47s]\nComputing hash join...  [1.118s]\nMasking low complexity seeds...  [0.148s]\nSearching alignments...  [8.473s]\nProcessing query block 1, reference block 1/1, shape 3/16, index chunk 2/4.\nBuilding reference seed array...  [0.754s]\nBuilding query seed array...  [6.273s]\nComputing hash join...  [1.078s]\nMasking low complexity seeds...  [0.155s]\nSearching alignments...  [8.298s]\nProcessing query block 1, reference block 1/1, shape 3/16, index chunk 3/4.\nBuilding reference seed array...  [0.769s]\nBuilding query seed array...  [7.053s]\nComputing hash join...  [1.055s]\nMasking low complexity seeds...  [0.158s]\nSearching alignments...  [7.844s]\nProcessing query block 1, reference block 1/1, shape 3/16, index chunk 4/4.\nBuilding reference seed array...  [0.625s]\nBuilding query seed array...  [5.228s]\nComputing hash join...  [1.088s]\nMasking low complexity seeds...  [0.156s]\nSearching alignments...  [8.552s]\nProcessing query block 1, reference block 1/1, shape 4/16, index chunk 1/4.\nBuilding reference seed array...  [0.654s]\nBuilding query seed array...  [5.977s]\nComputing hash join...  [1.037s]\nMasking low complexity seeds...  [0.145s]\nSearching alignments...  [7.284s]\nProcessing query block 1, reference block 1/1, shape 4/16, index chunk 2/4.\nBuilding reference seed array...  [0.757s]\nBuilding query seed array...  [6.105s]\nComputing hash join...  [1.145s]\nMasking low complexity seeds...  [0.15s]\nSearching alignments...  [8.3s]\nProcessing query block 1, reference block 1/1, shape 4/16, index chunk 3/4.\nBuilding reference seed array...  [0.772s]\nBuilding query seed array...  [6.488s]\nComputing hash join...  [1.095s]\nMasking low complexity seeds...  [0.156s]\nSearching alignments...  [8.205s]\nProcessing query block 1, reference block 1/1, shape 4/16, index chunk 4/4.\nBuilding reference seed array...  [0.622s]\nBuilding query seed array...  [5.586s]\nComputing hash join...  [1.02s]\nMasking low complexity seeds...  [0.15s]\nSearching alignments...  [8.424s]\nProcessing query block 1, reference block 1/1, shape 5/16, index chunk 1/4.\nBuilding reference seed array...  [0.638s]\nBuilding query seed array...  [5.54s]\nComputing hash join...  [1.175s]\nMasking low complexity seeds...  [0.156s]\nSearching alignments...  [9.171s]\nProcessing query block 1, reference block 1/1, shape 5/16, index chunk 2/4.\nBuilding reference seed array...  [0.755s]\nBuilding query seed array...  [6.274s]\nComputing hash join...  [1.107s]\nMasking low complexity seeds...  [0.159s]\nSearching alignments...  [8.247s]\nProcessing query block 1, reference block 1/1, shape 5/16, index chunk 3/4.\nBuilding reference seed array...  [0.782s]\nBuilding query seed array...  [6.777s]\nComputing hash join...  [1.063s]\nMasking low complexity seeds...  [0.156s]\nSearching alignments...  [8.409s]\nProcessing query block 1, reference block 1/1, shape 5/16, index chunk 4/4.\nBuilding reference seed array...  [0.617s]\nBuilding query seed array...  [5.385s]\nComputing hash join...  [1.084s]\nMasking low complexity seeds...  [0.149s]\nSearching alignments...  [7.972s]\nProcessing query block 1, reference block 1/1, shape 6/16, index chunk 1/4.\nBuilding reference seed array...  [0.638s]\nBuilding query seed array...  [5.559s]\nComputing hash join...  [1.105s]\nMasking low complexity seeds...  [0.162s]\nSearching alignments...  [8.573s]\nProcessing query block 1, reference block 1/1, shape 6/16, index chunk 2/4.\nBuilding reference seed array...  [0.747s]\nBuilding query seed array...  [6.39s]\nComputing hash join...  [1.082s]\nMasking low complexity seeds...  [0.18s]\nSearching alignments...  [8.045s]\nProcessing query block 1, reference block 1/1, shape 6/16, index chunk 3/4.\nBuilding reference seed array...  [0.755s]\nBuilding query seed array...  [6.763s]\nComputing hash join...  [1.082s]\nMasking low complexity seeds...  [0.157s]\nSearching alignments...  [8.085s]\nProcessing query block 1, reference block 1/1, shape 6/16, index chunk 4/4.\nBuilding reference seed array...  [0.606s]\nBuilding query seed array...  [5.634s]\nComputing hash join...  [1.035s]\nMasking low complexity seeds...  [0.142s]\nSearching alignments...  [8.016s]\nProcessing query block 1, reference block 1/1, shape 7/16, index chunk 1/4.\nBuilding reference seed array...  [0.635s]\nBuilding query seed array...  [5.323s]\nComputing hash join...  [1.097s]\nMasking low complexity seeds...  [0.148s]\nSearching alignments...  [8.076s]\nProcessing query block 1, reference block 1/1, shape 7/16, index chunk 2/4.\nBuilding reference seed array...  [0.754s]\nBuilding query seed array...  [7.153s]\nComputing hash join...  [1.043s]\nMasking low complexity seeds...  [0.146s]\nSearching alignments...  [7.749s]\nProcessing query block 1, reference block 1/1, shape 7/16, index chunk 3/4.\nBuilding reference seed array...  [0.778s]\nBuilding query seed array...  [6.913s]\nComputing hash join...  [1.064s]\nMasking low complexity seeds...  [0.159s]\nSearching alignments...  [8.88s]\nProcessing query block 1, reference block 1/1, shape 7/16, index chunk 4/4.\nBuilding reference seed array...  [0.61s]\nBuilding query seed array...  [5.985s]\nComputing hash join...  [1.133s]\nMasking low complexity seeds...  [0.161s]\nSearching alignments...  [8.747s]\nProcessing query block 1, reference block 1/1, shape 8/16, index chunk 1/4.\nBuilding reference seed array...  [0.696s]\nBuilding query seed array...  [5.623s]\nComputing hash join...  [1.014s]\nMasking low complexity seeds...  [0.158s]\nSearching alignments...  [7.184s]\nProcessing query block 1, reference block 1/1, shape 8/16, index chunk 2/4.\nBuilding reference seed array...  [0.701s]\nBuilding query seed array...  [6.602s]\nComputing hash join...  [1.064s]\nMasking low complexity seeds...  [0.149s]\nSearching alignments...  [8.657s]\nProcessing query block 1, reference block 1/1, shape 8/16, index chunk 3/4.\nBuilding reference seed array...  [0.772s]\nBuilding query seed array...  [6.411s]\nComputing hash join...  [1.113s]\nMasking low complexity seeds...  [0.154s]\nSearching alignments...  [7.841s]\nProcessing query block 1, reference block 1/1, shape 8/16, index chunk 4/4.\nBuilding reference seed array...  [0.619s]\nBuilding query seed array...  [5.272s]\nComputing hash join...  [0.987s]\nMasking low complexity seeds...  [0.139s]\nSearching alignments...  [7.407s]\nProcessing query block 1, reference block 1/1, shape 9/16, index chunk 1/4.\nBuilding reference seed array...  [0.699s]\nBuilding query seed array...  [5.87s]\nComputing hash join...  [1.078s]\nMasking low complexity seeds...  [0.146s]\nSearching alignments...  [8.42s]\nProcessing query block 1, reference block 1/1, shape 9/16, index chunk 2/4.\nBuilding reference seed array...  [0.755s]\nBuilding query seed array...  [6.607s]\nComputing hash join...  [1.03s]\nMasking low complexity seeds...  [0.144s]\nSearching alignments...  [9.041s]\nProcessing query block 1, reference block 1/1, shape 9/16, index chunk 3/4.\nBuilding reference seed array...  [0.79s]\nBuilding query seed array...  [6.932s]\nComputing hash join...  [1.095s]\nMasking low complexity seeds...  [0.155s]\nSearching alignments...  [8.486s]\nProcessing query block 1, reference block 1/1, shape 9/16, index chunk 4/4.\nBuilding reference seed array...  [0.607s]\nBuilding query seed array...  [5.978s]\nComputing hash join...  [1.093s]\nMasking low complexity seeds...  [0.145s]\nSearching alignments...  [8.937s]\nProcessing query block 1, reference block 1/1, shape 10/16, index chunk 1/4.\nBuilding reference seed array...  [0.649s]\nBuilding query seed array...  [6.178s]\nComputing hash join...  [1.023s]\nMasking low complexity seeds...  [0.148s]\nSearching alignments...  [8.639s]\nProcessing query block 1, reference block 1/1, shape 10/16, index chunk 2/4.\nBuilding reference seed array...  [0.75s]\nBuilding query seed array...  [6.684s]\nComputing hash join...  [0.996s]\nMasking low complexity seeds...  [0.152s]\nSearching alignments...  [8.461s]\nProcessing query block 1, reference block 1/1, shape 10/16, index chunk 3/4.\nBuilding reference seed array...  [0.777s]\nBuilding query seed array...  [6.961s]\nComputing hash join...  [1.044s]\nMasking low complexity seeds...  [0.144s]\nSearching alignments...  [7.731s]\nProcessing query block 1, reference block 1/1, shape 10/16, index chunk 4/4.\nBuilding reference seed array...  [0.617s]\nBuilding query seed array...  [5.626s]\nComputing hash join...  [1.086s]\nMasking low complexity seeds...  [0.153s]\nSearching alignments...  [8.841s]\nProcessing query block 1, reference block 1/1, shape 11/16, index chunk 1/4.\nBuilding reference seed array...  [0.642s]\nBuilding query seed array...  [5.872s]\nComputing hash join...  [1.118s]\nMasking low complexity seeds...  [0.163s]\nSearching alignments...  [8.051s]\nProcessing query block 1, reference block 1/1, shape 11/16, index chunk 2/4.\nBuilding reference seed array...  [0.754s]\nBuilding query seed array...  [6.527s]\nComputing hash join...  [1.148s]\nMasking low complexity seeds...  [0.158s]\nSearching alignments...  [8.095s]\nProcessing query block 1, reference block 1/1, shape 11/16, index chunk 3/4.\nBuilding reference seed array...  [0.775s]\nBuilding query seed array...  [6.284s]\nComputing hash join...  [1.079s]\nMasking low complexity seeds...  [0.145s]\nSearching alignments...  [8.743s]\nProcessing query block 1, reference block 1/1, shape 11/16, index chunk 4/4.\nBuilding reference seed array...  [0.622s]\nBuilding query seed array...  [6.293s]\nComputing hash join...  [1.171s]\nMasking low complexity seeds...  [0.163s]\nSearching alignments...  [8.698s]\nProcessing query block 1, reference block 1/1, shape 12/16, index chunk 1/4.\nBuilding reference seed array...  [0.632s]\nBuilding query seed array...  [5.667s]\nComputing hash join...  [1.144s]\nMasking low complexity seeds...  [0.164s]\nSearching alignments...  [7.58s]\nProcessing query block 1, reference block 1/1, shape 12/16, index chunk 2/4.\nBuilding reference seed array...  [0.75s]\nBuilding query seed array...  [6.222s]\nComputing hash join...  [1.063s]\nMasking low complexity seeds...  [0.154s]\nSearching alignments...  [7.937s]\nProcessing query block 1, reference block 1/1, shape 12/16, index chunk 3/4.\nBuilding reference seed array...  [0.78s]\nBuilding query seed array...  [6.732s]\nComputing hash join...  [1.067s]\nMasking low complexity seeds...  [0.165s]\nSearching alignments...  [8.413s]\nProcessing query block 1, reference block 1/1, shape 12/16, index chunk 4/4.\nBuilding reference seed array...  [0.616s]\nBuilding query seed array...  [5.537s]\nComputing hash join...  [1.044s]\nMasking low complexity seeds...  

[0.147s]\nSearching alignments...  [7.524s]\nProcessing query block 1, reference block 1/1, shape 13/16, index chunk 1/4.\nBuilding reference seed array...  [0.633s]\nBuilding query seed array...  [5.765s]\nComputing hash join...  [1.192s]\nMasking low complexity seeds...  [0.15s]\nSearching alignments...  [10.014s]\nProcessing query block 1, reference block 1/1, shape 13/16, index chunk 2/4.\nBuilding reference seed array...  [0.717s]\nBuilding query seed array...  [6.231s]\nComputing hash join...  [1.113s]\nMasking low complexity seeds...  [0.164s]\nSearching alignments...  [7.303s]\nProcessing query block 1, reference block 1/1, shape 13/16, index chunk 3/4.\nBuilding reference seed array...  [0.735s]\nBuilding query seed array...  [7.164s]\nComputing hash join...  [1.011s]\nMasking low complexity seeds...  [0.151s]\nSearching alignments...  [7.907s]\nProcessing query block 1, reference block 1/1, shape 13/16, index chunk 4/4.\nBuilding reference seed array...  [0.618s]\nBuilding query seed array...  [5.891s]\nComputing hash join...  [1.097s]\nMasking low complexity seeds...  [0.157s]\nSearching alignments...  [9.006s]\nProcessing query block 1, reference block 1/1, shape 14/16, index chunk 1/4.\nBuilding reference seed array...  [0.641s]\nBuilding query seed array...  [5.99s]\nComputing hash join...  [1.077s]\nMasking low complexity seeds...  [0.152s]\nSearching alignments...  [7.928s]\nProcessing query block 1, reference block 1/1, shape 14/16, index chunk 2/4.\nBuilding reference seed array...  [0.749s]\nBuilding query seed array...  [6.196s]\nComputing hash join...  [1.078s]\nMasking low complexity seeds...  [0.168s]\nSearching alignments...  [8.104s]\nProcessing query block 1, reference block 1/1, shape 14/16, index chunk 3/4.\nBuilding reference seed array...  [0.755s]\nBuilding query seed array...  [7.07s]\nComputing hash join...  [1.102s]\nMasking low complexity seeds...  [0.151s]\nSearching alignments...  [8.478s]\nProcessing query block 1, reference block 1/1, shape 14/16, index chunk 4/4.\nBuilding reference seed array...  [0.62s]\nBuilding query seed array...  [5.654s]\nComputing hash join...  [1.16s]\nMasking low complexity seeds...  [0.166s]\nSearching alignments...  [9s]\nProcessing query block 1, reference block 1/1, shape 15/16, index chunk 1/4.\nBuilding reference seed array...  [0.643s]\nBuilding query seed array...  [5.736s]\nComputing hash join...  [1.14s]\nMasking low complexity seeds...  [0.155s]\nSearching alignments...  [8.959s]\nProcessing query block 1, reference block 1/1, shape 15/16, index chunk 2/4.\nBuilding reference seed array...  [0.742s]\nBuilding query seed array...  [6.377s]\nComputing hash join...  [1.079s]\nMasking low complexity seeds...  [0.154s]\nSearching alignments...  [8.071s]\nProcessing query block 1, reference block 1/1, shape 15/16, index chunk 3/4.\nBuilding reference seed array...  [0.772s]\nBuilding query seed array...  [6.371s]\nComputing hash join...  [1.072s]\nMasking low complexity seeds...  [0.139s]\nSearching alignments...  [7.649s]\nProcessing query block 1, reference block 1/1, shape 15/16, index chunk 4/4.\nBuilding reference seed array...  [0.616s]\nBuilding query seed array...  [5.232s]\nComputing hash join...  [1.019s]\nMasking low complexity seeds...  [0.148s]\nSearching alignments...  [8.422s]\nProcessing query block 1, reference block 1/1, shape 16/16, index chunk 1/4.\nBuilding reference seed array...  [0.633s]\nBuilding query seed array...  [6.399s]\nComputing hash join...  [1.027s]\nMasking low complexity seeds...  [0.159s]\nSearching alignments...  [8.986s]\nProcessing query block 1, reference block 1/1, shape 16/16, index chunk 2/4.\nBuilding reference seed array...  [0.743s]\nBuilding query seed array...  [6.818s]\nComputing hash join...  [1.115s]\nMasking low complexity seeds...  [0.158s]\nSearching alignments...  [7.432s]\nProcessing query block 1, reference block 1/1, shape 16/16, index chunk 3/4.\nBuilding reference seed array...  [0.761s]\nBuilding query seed array...  [7.047s]\nComputing hash join...  [1.112s]\nMasking low complexity seeds...  [0.154s]\nSearching alignments...  [9.039s]\nProcessing query block 1, reference block 1/1, shape 16/16, index chunk 4/4.\nBuilding reference seed array...  [0.603s]\nBuilding query seed array...  [5.782s]\nComputing hash join...  [1.121s]\nMasking low complexity seeds...  [0.168s]\nSearching alignments...  [8.369s]\nDeallocating buffers...  [0.001s]\nClearing query masking...  [0.388s]\nComputing alignments... Error: std::bad_alloc\n'
Traceback (most recent call last):
  File "/grid/wsbs/home_norepl/skleeman/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/grid/wsbs/home_norepl/skleeman/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/grid/wsbs/home_norepl/skleeman/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/predict.py", line 1049, in main
    lib.exonerate2hints(Exonerate, hintsP)
  File "/grid/wsbs/home_norepl/skleeman/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py", line 4026, in exonerate2hints
    with open(file, 'r') as input:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/grid/janowitz/rdata/balbc_assembly/final/funannotate/BALBie_ragtag_train/predict_misc/protein_alignments.gff3'
```

**Comment by nextgenusfs** [comment]
Hi @samkleeman1, I think diamond ran out of memory with this genome.  But I also think there was a bug that was fixed in the master that will help you, https://github.com/nextgenusfs/funannotate/commit/e74f867c9eec614f4b15504562789eb5fc51da21 is a fix for diamond version parsing and running diamond a slightly different way that uses less memory which is helpful with larger genomes. 

You could upgrade your current installation with pip, ie
```
python -m pip install git+https://github.com/nextgenusfs/funannotate.git --upgrade --force --no-deps
```
And then can re-issue the same command and see if that fixes the problem.

**Comment by Rcperez** [comment]
Hello @nextgenusfs, I just got a similar error while using funannotate-docker. Would upgrading via above command work for my fun annotate-docker run?

Thanks and happy holidays!

/rp


-------------------------------------------------------
[Dec 23 11:55 AM]: OS: Debian GNU/Linux 10, 8 cores, ~ 2 GB RAM. Python: 3.8.12
[Dec 23 11:55 AM]: Running funannotate v1.8.10
[Dec 23 11:55 AM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[Dec 23 11:55 AM]: Skipping CodingQuarry as no --rna_bam passed
[Dec 23 11:55 AM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     busco          
  glimmerhmm   busco          
  snap         busco          
[Dec 23 11:55 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Dec 23 11:58 AM]: Genome loaded: 11,706 scaffolds; 42,661,187 bp; 6.16% repeats masked
[Dec 23 11:58 AM]: Mapping 553,202 proteins to genome using diamond and exonerate
[Dec 23 11:59 AM]: CMD ERROR: diamond blastx --threads 8 -q /Users/rcp/fun2/predict_misc/genome.softmasked.fa --db diamond -o diamond.matches.tab -e 1e-10 -k 0 --more-sensitive --unal 0 -c 1 -F 15 -f 6 sseqid slen sstart send qseqid qlen qstart qend pident length evalue score qcovhsp qframe
b'diamond v2.0.13.151 (C) Max Planck Society for the Advancement of Science\nDocumentation, support and updates available at http://www.diamondsearch.org\nPlease cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)\n\n#CPU threads: 8\nScoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)\nTemporary directory: \n#Target sequences to report alignments for: unlimited\nOpening the database...  [0.062s]\nDatabase: diamond.dmnd (type: Diamond database, sequences: 553202, letters: 203792478)\nBlock size = 2000000000\nOpening the input file...  [0.205s]\nOpening the output file...  [0s]\nLoading query sequences...  [0.379s]\nMasking queries...  [0.595s]\nAlgorithm: Double-indexed\nBuilding query histograms...  [1.663s]\nAllocating buffers...  [0s]\nLoading reference sequences...  [0.353s]\nMasking reference...  [1.375s]\nInitializing temporary storage...  [0s]\nBuilding reference histograms...  [4.023s]\nAllocating buffers...  [0s]\nProcessing query block 1, reference block 1/1, shape 1/16.\nBuilding reference seed array...  [3.119s]\nBuilding query seed array... '
Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 710, in main
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/predict.py", line 1051, in main
    lib.exonerate2hints(Exonerate, hintsP)
  File "/venv/lib/python3.8/site-packages/funannotate/library.py", line 4026, in exonerate2hints
    with open(file, 'r') as input:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rcp/fun2/predict_misc/protein_alignments.gff3'

**Comment by nextgenusfs** [comment]
You should just need the latest docker image, so run docker pull nextgenusfs/funannotate and then try command again if that doesn’t run the frame shift mode docker than it might not be fixed. The docker image is automatically updated after every commit using GitHub actions, so as long as you update your local image you will have all changes.

**Comment by Rcperez** [comment]
So far it seems my issue was the memory for the docker VM was set at 2 GB. Thank you!
