### ISSUE TITLE
Funannotate update error

### ISSUE THREAD

**Issue by samkleeman1** [nextgenusfs/funannotate#685]
Hi,

I was running the following command having completed training steps as per tutorial https://funannotate.readthedocs.io/en/latest/tutorials.html#genome-assembly-and-rna-seq:

`funannotate update -i BALBie_ragtag_train --cpus 40`

I then received the following output:

```
[Dec 21 03:51 PM]: OS: CentOS Linux 8, 192 cores, ~ 3169 GB RAM. Python: 3.8.12
[Dec 21 03:51 PM]: Running 1.8.10
[Dec 21 03:51 PM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
[Dec 21 03:51 PM]: Found relevant files in BALBie_ragtag_train/training, will re-use them:
	Forward reads: BALBie_ragtag_train/training/left.fq.gz
	Reverse reads: BALBie_ragtag_train/training/right.fq.gz
	Forward Q-trimmed reads: BALBie_ragtag_train/training/trimmomatic/trimmed_left.fastq.gz
	Reverse Q-trimmed reads: BALBie_ragtag_train/training/trimmomatic/trimmed_right.fastq.gz
	Forward normalized reads: BALBie_ragtag_train/training/normalize/left.norm.fq
	Reverse normalized reads: BALBie_ragtag_train/training/normalize/right.norm.fq
	Trinity results: BALBie_ragtag_train/training/funannotate_train.trinity-GG.fasta
	PASA config file: BALBie_ragtag_train/training/pasa/alignAssembly.txt
	BAM alignments: BALBie_ragtag_train/training/funannotate_train.coordSorted.bam
	StringTie GTF: BALBie_ragtag_train/training/funannotate_train.stringtie.gtf
[Dec 21 03:54 PM]: Reannotating Mus musculus, NCBI accession: None
[Dec 21 03:54 PM]: Previous annotation consists of: 69,846 protein coding gene models and 28,649 non-coding gene models
[Dec 21 03:58 PM]: Converting transcript alignments to GFF3 format
[Dec 21 03:59 PM]: Converting Trinity transcript alignments to GFF3 format
[Dec 21 03:59 PM]: PASA database is SQLite: /mnt/grid/janowitz/rdata/balbc_assembly/final/funannotate/BALBie_ragtag_train/training/pasa/Mus_musculus_BALBc_pasa
[Dec 21 03:59 PM]: Running PASA annotation comparison step 1
[Dec 25 07:19 AM]: Running PASA annotation comparison step 2
[Dec 31 01:08 AM]: Using Kallisto TPM data to determine which PASA gene models to select at each locus
[Dec 31 01:08 AM]: Building Kallisto index
[Dec 31 01:13 AM]: Mapping reads using pseudoalignment in Kallisto
[Dec 31 01:36 AM]: Parsing Kallisto results. Keeping alt-splicing transcripts if expressed at least 10.0% of highest transcript per locus.
[Dec 31 01:36 AM]: Wrote 73,585 transcripts derived from 70,943 protein coding loci.
[Dec 31 01:37 AM]: Validating gene models (renaming, checking translations, filtering, etc)
[Dec 31 01:37 AM]: Writing 99,177 loci to TBL format: dropped 0 overlapping, 6 too short, and 0 frameshift gene models
[Dec 31 01:37 AM]: Converting to Genbank format
Traceback (most recent call last):
  File "/grid/wsbs/home_norepl/skleeman/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/tbl2asn_parallel.py", line 209, in <module>
    runtbl2asn_parallel(args.out, args.sbt, args.discrep, args.species,
  File "/grid/wsbs/home_norepl/skleeman/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/tbl2asn_parallel.py", line 138, in runtbl2asn_parallel
    with open(discrepency, 'a') as discrep:
FileNotFoundError: [Errno 2] No such file or directory: 'BALBie_ragtag_train/update_results/Mus_musculus_BALB/c.discrepency.report.txt'
-------------------------------------------------------
Traceback (most recent call last):
  File "/grid/wsbs/home_norepl/skleeman/miniconda3/envs/funannotate/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/grid/wsbs/home_norepl/skleeman/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 710, in main
    mod.main(arguments)
  File "/grid/wsbs/home_norepl/skleeman/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/update.py", line 2415, in main
    shutil.copyfile(os.path.join(gagdir, 'genome.gbf'), final_gbk)
  File "/grid/wsbs/home_norepl/skleeman/miniconda3/envs/funannotate/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'BALBie_ragtag_train/update_misc/tbl2asn/genome.gbf'
```

**Comment by nextgenusfs** [comment]
It appears to say that `tbl2asn` failed in generating the genbank file.  Do you have the log files for this run by chance? There is usually more information in the log file than what is printed to stdout.
