### ISSUE TITLE
A Funannotate update error!

### ISSUE THREAD

**Issue by sunnycqcn** [nextgenusfs/funannotate#686]
Hi Jon,
When I run funannotate update, I get a new error. I did not met this before.
```
[Jan 06 10:00 AM]: OS: CentOS Linux 7, 80 cores, ~ 1057 GB RAM. Python: 3.8.12
[Jan 06 10:00 AM]: Running 1.8.10
[Jan 06 10:00 AM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
[Jan 06 10:00 AM]: Found relevant files in SH/training, will re-use them:
        Forward reads: SH/training/left.fq.gz
        Reverse reads: SH/training/right.fq.gz
        Forward Q-trimmed reads: SH/training/trimmomatic/trimmed_left.fastq.gz
        Reverse Q-trimmed reads: SH/training/trimmomatic/trimmed_right.fastq.gz
        Forward normalized reads: SH/training/normalize/left.norm.fq
        Reverse normalized reads: SH/training/normalize/right.norm.fq
        Trinity results: SH/training/funannotate_train.trinity-GG.fasta
        PASA config file: SH/training/pasa/alignAssembly.txt
        BAM alignments: SH/training/funannotate_train.coordSorted.bam
        StringTie GTF: SH/training/funannotate_train.stringtie.gtf
[Jan 06 10:04 AM]: Reannotating Striga hermonthica, NCBI accession: None
[Jan 06 10:04 AM]: Previous annotation consists of: 107,758 protein coding gene models and 515 non-coding gene models
[Jan 06 10:04 AM]: Existing BAM alignments found: SH/update_misc/trinity.alignments.bam, SH/update_misc/transcript.alignments.bam
[Jan 06 10:04 AM]: Skipping PASA, found existing output: SH/update_misc/pasa_final.gff3
[Jan 06 10:04 AM]: Existing Kallisto output found: SH/update_misc/kallisto.tsv
[Jan 06 10:04 AM]: Parsing Kallisto results. Keeping alt-splicing transcripts if expressed at least 10.0% of highest transcript per locus.
[Jan 06 10:04 AM]: Wrote 111,849 transcripts derived from 108,471 protein coding loci.
ERROR: ID=SH_029692 has no CDS features, removing gene model
ERROR: ID=SH_033730 has no CDS features, removing gene model
ERROR: ID=SH_030109 has no CDS features, removing gene model
ERROR: ID=SH_033831 has no CDS features, removing gene model
ERROR: ID=SH_031394 has no CDS features, removing gene model
ERROR: ID=SH_031452 has no CDS features, removing gene model
ERROR: ID=SH_029942 has no CDS features, removing gene model
ERROR: ID=SH_029527 has no CDS features, removing gene model
ERROR: ID=SH_031857 has no CDS features, removing gene model
ERROR: ID=SH_029487 has no CDS features, removing gene model
ERROR: ID=SH_034003 has no CDS features, removing gene model
ERROR: ID=SH_028242 has no CDS features, removing gene model
ERROR: ID=SH_033167 has no CDS features, removing gene model
ERROR: ID=SH_028381 has no CDS features, removing gene model
ERROR: ID=SH_028470 has no CDS features, removing gene model
ERROR: ID=SH_029214 has no CDS features, removing gene model
ERROR: ID=SH_029884 has no CDS features, removing gene model
ERROR: ID=SH_032124 has no CDS features, removing gene model
ERROR: ID=SH_030016 has no CDS features, removing gene model
ERROR: ID=SH_028110 has no CDS features, removing gene model
ERROR: ID=SH_030364 has no CDS features, removing gene model
ERROR: ID=SH_031606 has no CDS features, removing gene model
ERROR: ID=SH_034422 has no CDS features, removing gene model
ERROR: ID=SH_034221 has no CDS features, removing gene model
ERROR: ID=SH_031003 has no CDS features, removing gene model
ERROR: ID=SH_028282 has no CDS features, removing gene model
ERROR: ID=SH_030789 has no CDS features, removing gene model
ERROR: ID=SH_028834 has no CDS features, removing gene model
ERROR: ID=SH_033862 has no CDS features, removing gene model
ERROR: ID=SH_031388 has no CDS features, removing gene model
Traceback (most recent call last):
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/FUN/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/FUN/lib/python3.8/site-packages/funannotate/funannotate.py", line 710, in main
    mod.main(arguments)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/FUN/lib/python3.8/site-packages/funannotate/update.py", line 2325, in main
    GFF2tblCombinedNEW(BestModelGFF, fastaout, cleanTRNA, locustag, genenumber,
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/FUN/lib/python3.8/site-packages/funannotate/update.py", line 1159, in GFF2tblCombinedNEW
    gene_inter, Genes = lib.gff2interlapDict(
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/FUN/lib/python3.8/site-packages/funannotate/library.py", line 3984, in gff2interlapDict
    Genes = gff2dict(input, fasta, Genes, gap_filter=True)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/FUN/lib/python3.8/site-packages/funannotate/library.py", line 4503, in gff2dict
    Genes[k]['mRNA'][i] = sortedExons
KeyError: 'SH_031388'
```
If you have some  time, could you check what it happen?
Thanks,
Fuyou

**Comment by nextgenusfs** [comment]
@sunnycqcn did we manage to fix this? I know there was an email chain.

**Comment by sunnycqcn** [comment]
Hello Jon,
I  fixed it.
Thanks,
Fuyou

**Comment by mgarl-10** [comment]
Hello,

I am having the same issue. Could you please share how you solve it?  Thank you!

**Comment by sunnycqcn** [comment]
> Hello,
> 
> I am having the same issue. Could you please share how you solve it? Thank you!

Did you update Funannotate to the latest version? I think Jon have fixed this issue and updated it. If you still have this problem,  let me know.
Best,
Fuyou
