### ISSUE TITLE
Funannotate 1.8.10 Compare TypeError

### ISSUE THREAD

**Issue by ddiazescandon** [nextgenusfs/funannotate#693]
OS: Debian GNU/Linux 10, 64 cores, ~ 264 GB RAM. Python: 3.8.12
Running 1.8.10

Hi, I'm using the docker latest release, which was updated 6 days ago. (Or re-submited)
I pulled the same version back in november it worked fine at that time. I also try the version 1.8.9  and It works percfectly (Today). I think something went wrong in the latest built.

I think the error is when it start plotting heatmaps.

[Feb 21 02:22 AM]: Summarizing secondary metabolism gene clusters
[Feb 21 02:22 AM]: Summarizing PFAM domain results
[Feb 21 02:22 AM]: Summarizing InterProScan results
[Feb 21 02:23 AM]: Loading InterPro descriptions
[Feb 21 02:23 AM]: Summarizing MEROPS protease results
[Feb 21 02:23 AM]: found 37/141 MEROPS familes with stdev >= 1.000000
-------------------------------------------------------
Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 710, in main
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/compare.py", line 540, in main
    lib.drawHeatmap(meropsplot, 'BuPu', os.path.join(
  File "/venv/lib/python3.8/site-packages/funannotate/library.py", line 7941, in drawHeatmap
    cbar_ax = fig.add_axes(shrink=0.4)
  File "/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 619, in add_axes
    raise TypeError(
TypeError: add_axes() missing 1 required positional argument: 'rect'

Stay healthy!

David

**Comment by nextgenusfs** [comment]
Very strange.  I just pushed a new commit, so that will trigger a new build.  Can you test that new build and see if problem persists?

**Comment by giriarteS** [comment]
I have the same error with 1.8.9 version installed with conda (mamba).

"funannotate compare -i Genome_one.gbk Genome_two.gbk Genome_three.gbk -o compare --cpus 4 --outgroup botrytis_cinerea.dikarya
-------------------------------------------------------
[Apr 19 12:22 PM]: OS: Ubuntu 20.04, 56 cores, ~ 132 GB RAM. Python: 3.8.12
[Apr 19 12:22 PM]: Running 1.8.9
[Apr 19 12:22 PM]: Now parsing 3 genomes
[Apr 19 12:22 PM]: working on Genome one
[Apr 19 12:22 PM]: working on Genome two
[Apr 19 12:22 PM]: working on Genome three
[Apr 19 12:22 PM]: No secondary metabolite annotations found
[Apr 19 12:22 PM]: Summarizing PFAM domain results
[Apr 19 12:22 PM]: Summarizing InterProScan results
[Apr 19 12:22 PM]: Loading InterPro descriptions
[Apr 19 12:22 PM]: Summarizing MEROPS protease results
[Apr 19 12:22 PM]: found 4 MEROPS familes
Traceback (most recent call last):
  File "/mnt/DATA/anaconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/mnt/DATA/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/mnt/DATA/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/compare.py", line 540, in main
    lib.drawHeatmap(meropsplot, 'BuPu', os.path.join(
  File "/mnt/DATA/anaconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/library.py", line 7917, in drawHeatmap
    cbar_ax = fig.add_axes(shrink=0.4)
  File "/home/gloria_broders/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 619, in add_axes
    raise TypeError(
TypeError: add_axes() missing 1 required positional argument: 'rect'"

Gloria
