### ISSUE TITLE
funannotate compare

### ISSUE THREAD

**Issue by ShrutiKetan** [nextgenusfs/funannotate#705]
Hi, I have been trying to compare 200 unannotated fungal genomes using fun annotate compare command.
However, I keep running to this error:

[Mar 29 04:09 PM]: Loading InterPro descriptions
[Mar 29 04:09 PM]: Summarizing MEROPS protease results
[Mar 29 04:09 PM]: found 46/173 MEROPS familes with stdev >= 1.000000
-------------------------------------------------------
Traceback (most recent call last):
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/funannotate/funannotate.py", line 710, in main
    mod.main(arguments)
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/funannotate/compare.py", line 540, in main
    lib.drawHeatmap(meropsplot, 'BuPu', os.path.join(
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/funannotate/library.py", line 7941, in drawHeatmap
    cbar_ax = fig.add_subplot(shrink=0.4)
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/matplotlib/figure.py", line 784, in add_subplot
    ax = subplot_class_factory(projection_class)(self, *args, **pkw)
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/matplotlib/axes/_subplots.py", line 36, in __init__
    self._axes_class.__init__(self, fig, [0, 0, 1, 1], **kwargs)
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 471, in wrapper
    return func(*args, **kwargs)
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 648, in __init__
    self.update(kwargs)
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/matplotlib/artist.py", line 1062, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'AxesSubplot' object has no property 'shrink'

I already made the following changes that occured in preceding run of the command:
[Mar 28 10:14 PM]: found 46/173 MEROPS familes with stdev >= 1.000000
/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/funannotate/library.py:7941: MatplotlibDeprecationWarning: Calling add_axes() without argument is d
eprecated since 3.3 and will be removed two minor releases later. You may want to use add_subplot() instead.
 cbar_ax = fig.add_axes(shrink=0.4)

Please help me fix this bug.
Thanks for your time

**Comment by nextgenusfs** [comment]
Do you get that error with funannotate test -t compare? And what if you run something like 10 genomes, same error? I'm not sure why it is erroring out there but I've never come remotely close to 200 genomes. It's unlikely the html output will be very useful with that many genomes, I wrote this 4-5 years ago doing comparative genomics on <10 species.

**Comment by ShrutiKetan** [comment]
I just ran funannotate test -t compare. The same error was repeated

funannotate test -t compare
#########################################################
Running `funannotate compare` unit testing
Downloading: https://osf.io/7s9xh/download?version=1 Bytes: 1020999
CMD: funannotate compare -i Genome_one.gbk Genome_two.gbk Genome_three.gbk -o compare --cpus 2 --outgroup botrytis_cinerea.dikarya
#########################################################
-------------------------------------------------------
[Mar 30 12:07 PM]: OS: CentOS Linux 7, 64 cores, ~ 264 GB RAM. Python: 3.8.12
[Mar 30 12:07 PM]: Running 1.8.10
[Mar 30 12:07 PM]: Now parsing 3 genomes
[Mar 30 12:07 PM]: working on Genome one
[Mar 30 12:07 PM]: working on Genome two
[Mar 30 12:07 PM]: working on Genome three
[Mar 30 12:07 PM]: No secondary metabolite annotations found
[Mar 30 12:07 PM]: Summarizing PFAM domain results
[Mar 30 12:07 PM]: Summarizing InterProScan results
[Mar 30 12:07 PM]: Loading InterPro descriptions
[Mar 30 12:07 PM]: Summarizing MEROPS protease results
[Mar 30 12:07 PM]: found 4 MEROPS familes
Traceback (most recent call last):
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/funannotate/funannotate.py", line 710, in main
    mod.main(arguments)
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/funannotate/compare.py", line 540, in main
    lib.drawHeatmap(meropsplot, 'BuPu', os.path.join(
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/funannotate/library.py", line 7941, in drawHeatmap
    cbar_ax = fig.add_subplot(shrink=0.4)
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/matplotlib/figure.py", line 784, in add_subplot
    ax = subplot_class_factory(projection_class)(self, *args, **pkw)
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/matplotlib/axes/_subplots.py", line 36, in __init__
    self._axes_class.__init__(self, fig, [0, 0, 1, 1], **kwargs)
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 471, in wrapper
    return func(*args, **kwargs)
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 648, in __init__
    self.update(kwargs)
  File "/cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/lib/python3.8/site-packages/matplotlib/artist.py", line 1062, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'AxesSubplot' object has no property 'shrink'
#########################################################
ERROR: `funannotate compare` test failed - check logfiles
#########################################################

**Comment by ShrutiKetan** [comment]
Here is the log file fr the test command:

[03/30/22 12:07:22]: /cm/shared/apps/bio/funannotate/env/envs/funannotate-latest/bin/funannotate compare -i Genome_one.gbk Genome_two.gbk Genome_three.gbk -o compare --cpus 2 --outgroup botrytis_cinerea.dikarya

[03/30/22 12:07:22]: OS: CentOS Linux 7, 64 cores, ~ 264 GB RAM. Python: 3.8.12
[03/30/22 12:07:22]: Running 1.8.10
[03/30/22 12:07:24]: Input files/folders: ['Genome_one.gbk', 'Genome_two.gbk', 'Genome_three.gbk']

[03/30/22 12:07:24]: Now parsing 3 genomes
[03/30/22 12:07:24]: working on Genome one
[03/30/22 12:07:24]: working on Genome two
[03/30/22 12:07:24]: working on Genome three
[03/30/22 12:07:24]: No secondary metabolite annotations found
[03/30/22 12:07:24]: Summarizing PFAM domain results
[03/30/22 12:07:28]: Summarizing InterProScan results
[03/30/22 12:07:28]: Loading InterPro descriptions
[03/30/22 12:07:29]: Summarizing MEROPS protease results
[03/30/22 12:07:29]: found 4 MEROPS familes

**Comment by nextgenusfs** [comment]
Okay,  I think this is fixed in the main/master branch.

**Comment by IanDMedeiros** [comment]
Re: your comment @nextgenusfs on compare not being written for hundreds of genomes, I have added --skip_visualizations and --skip_phylogeny options to my local copy of funannotate, both for debugging purposes and to allow the script to complete with a large number of genomes. (There especially seem to be lots of plotting errors with many genomes, and I want to do those visualizations separate from this pipeline.) Let me know if you want a pull request for this: 

https://github.com/IanDMedeiros/funannotate/tree/compare_edits_1
