### ISSUE TITLE
Funannotate test error

### ISSUE THREAD

**Issue by rissidaniel** [nextgenusfs/funannotate#723]
**Are you using the latest release?** 
1.8.9

**Describe the bug**
When running funannotate test -t all --cpus 90, I endup having the error below, despite of the "funannotate check --show-versions" show everything installed and with all path defined.

[May 16 01:02 PM]: Pulling out high quality Augustus predictions
[May 16 01:02 PM]: Found 314 high quality predictions from Augustus (>90% exon evidence)
[May 16 01:02 PM]: Running SNAP gene prediction, using training data: annotate/predict_misc/busco.final.gff3
[May 16 01:02 PM]: 2 predictions from SNAP
[May 16 01:02 PM]: Running GlimmerHMM gene prediction, using training data: annotate/predict_misc/busco.final.gff3
[May 16 01:04 PM]: 1,773 predictions from GlimmerHMM
[May 16 01:04 PM]: Summary of gene models passed to EVM (weights):
[May 16 01:04 PM]: EVM: partitioning input to ~ 35 genes per partition using min 1500 bp interval
Traceback (most recent call last):
  File "/home/dar21/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 479, in <module>
    cmdinfo = create_partitions(args.fasta, args.genes, partitions,
  File "/home/dar21/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 131, in create_partitions
    SeqRecords = SeqIO.index_db(f_idx, fasta, 'fasta')
  File "/home/dar21/miniconda3/envs/funannotate/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line 1018, in index_db
    return _SQLiteManySeqFilesDict(
  File "/home/dar21/miniconda3/envs/funannotate/lib/python3.8/site-packages/Bio/File.py", line 331, in __init__
    self._build_index()
  File "/home/dar21/miniconda3/envs/funannotate/lib/python3.8/site-packages/Bio/File.py", line 462, in _build_index
    con.execute("CREATE TABLE meta_data (key TEXT, value TEXT);")
sqlite3.OperationalError: database is locked
  ^[[4mSource         Weight   Count^[[0m
  Augustus       1        991
  Augustus HiQ   2        314
  GeneMark       1        1559
  GlimmerHMM     1        1773
  snap           1        2
  Total          -        4639
[May 16 01:04 PM]: Evidence modeler has failed, exiting
Traceback (most recent call last):
  File "/mnt/mountdoom/mnt/work/bioinfo/home/dar21/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/dar21/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/home/dar21/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/predict.py", line 1790, in main
    os.remove(EVM_out)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/mountdoom/mnt/work/bioinfo/home/dar21/genomes/ncbi_genomes/funannotate_test/Margaritispora_aquatica/test-busco_62c37d98-95b0-42a2-bc15-82cbdfd2c369/annotate/predict_misc/evm.round1.gff3'
CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --augustus_species saccharomyces --cpus 90 --species Awesome testicus
#########################################################
#########################################################
SUCCESS: `funannotate predict` test complete.
#########################################################

#########################################################
Running `funannotate predict` BUSCO-mediated training unit testing
CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --cpus 90 --species Awesome busco
#########################################################
#########################################################
Traceback (most recent call last):
  File "/mnt/mountdoom/mnt/work/bioinfo/home/dar21/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/dar21/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/home/dar21/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/test.py", line 407, in main
    runBuscoTest(args)
  File "/home/dar21/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/test.py", line 200, in runBuscoTest
    assert 1500 <= countGFFgenes(os.path.join(
  File "/home/dar21/miniconda3/envs/funannotat
[slurm-51658947.txt](https://github.com/nextgenusfs/funannotate/files/8699516/slurm-51658947.txt)
e/lib/python3.8/site-packages/funannotate/test.py", line 45, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-busco_62c37d98-95b0-42a2-bc15-82cbdfd2c369/annotate/predict_results/Awesome_busco.gff3'
funannotate finished

**What command did you issue?**
funannotate test -t all --cpus 90

**Logfiles**
Done it

**OS/Install Information**
Included in the logfile

**Comment by rissidaniel** [comment]
[slurm-51658947.txt](https://github.com/nextgenusfs/funannotate/files/8699595/slurm-51658947.txt)

**Comment by nextgenusfs** [comment]
Sorry for late response, so in your logfile I see that SNAP seems to be failing, I think on debian systems the conda version of snap is broken.  You can remove it and install with `apt-get` which should fix SNAP and it will hopefully predict genes.  I'm not sure, but I think perhaps EVM choked on some incomplete gene model that the broken SNAP executable generated.
```
[May 16 01:02 PM]: 2 predictions from SNAP
```
In a functioning version of SNAP you should see something like 1500 gene models predicted.
