### ISSUE TITLE
ERROR: ID=FUN_004560 has no CDS features, removing gene model

### ISSUE THREAD

**Issue by zhuofeih** [nextgenusfs/funannotate#727]
Hi, We are using 1.8.9 on the cluster at our university. It reported us the above error when the pipeline ran this step:

funannotate update -i fun_z_11748973 --cpus 20

Below is the part of the log. We are new to funannotate. Could you please take a look for us and let me know what caused the issue and how to get it resolved? If there is already a communication thread on this, could you please forward it to me? Thank you very much in advance for your help!

===============================

[May 23 07:09 AM]: Your next step to capture UTRs and update annotation using PASA:

  funannotate update -i fun_z_11748973 --cpus 20

[May 23 07:09 AM]: Training parameters file saved: fun_z_11748973/predict_results/cryptococcus_neoformans_neoformans_jec21.parameters.json
[May 23 07:09 AM]: Add species parameters to database:

  funannotate species -s cryptococcus_neoformans_neoformans_jec21 -a fun_z_11748973/predict_results/cryptococcus_neoformans_neoformans_jec21.parameters.json

[May 23 07:09 AM]: OS: CentOS Linux 7, 32 cores, ~ 528 GB RAM. Python: 3.7.4
[May 23 07:09 AM]: Running 1.8.9
[May 23 07:09 AM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
[May 23 07:09 AM]: Found relevant files in fun_z_11748973/training, will re-use them:
    Forward reads: fun_z_11748973/training/left.fq.gz
    Reverse reads: fun_z_11748973/training/right.fq.gz
    Forward Q-trimmed reads: fun_z_11748973/training/trimmomatic/trimmed_left.fastq.gz
    Reverse Q-trimmed reads: fun_z_11748973/training/trimmomatic/trimmed_right.fastq.gz
    Forward normalized reads: fun_z_11748973/training/normalize/left.norm.fq
    Reverse normalized reads: fun_z_11748973/training/normalize/right.norm.fq
    Trinity results: fun_z_11748973/training/funannotate_train.trinity-GG.fasta
    PASA config file: fun_z_11748973/training/pasa/alignAssembly.txt
    BAM alignments: fun_z_11748973/training/funannotate_train.coordSorted.bam
    StringTie GTF: fun_z_11748973/training/funannotate_train.stringtie.gtf
[May 23 07:09 AM]: Reannotating cryptococcus_neoformans_neoformans_JEC21, NCBI accession: None
[May 23 07:09 AM]: Previous annotation consists of: 7,063 protein coding gene models and 138 non-coding gene models
[May 23 07:10 AM]: Converting transcript alignments to GFF3 format
[May 23 07:10 AM]: Converting Trinity transcript alignments to GFF3 format
[May 23 07:10 AM]: PASA database is SQLite: /scratch/zhuofei/funannotate_job/fun_z_11748973/training/pasa/cryptococcus_neoformans_neoformans_JEC21_pasa
[May 23 07:10 AM]: Running PASA annotation comparison step 1
[May 23 07:54 AM]: Running PASA annotation comparison step 2
[May 23 09:26 AM]: Using Kallisto TPM data to determine which PASA gene models to select at each locus
[May 23 09:26 AM]: Building Kallisto index
[May 23 09:27 AM]: Mapping reads using pseudoalignment in Kallisto
[May 23 09:29 AM]: Parsing Kallisto results. Keeping alt-splicing transcripts if expressed at least 10.0% of highest transcript per locus.
[May 23 09:29 AM]: Wrote 7,958 transcripts derived from 7,104 protein coding loci.
ERROR: ID=FUN_004560 has no CDS features, removing gene model
-------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/zhuofei/funannotate/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/scratch/zhuofei/funannotate/lib/python3.7/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/scratch/zhuofei/funannotate/lib/python3.7/site-packages/funannotate/update.py", line 2324, in main
    alt_transcripts=args.alt_transcripts)
  File "/scratch/zhuofei/funannotate/lib/python3.7/site-packages/funannotate/update.py", line 1160, in GFF2tblCombinedNEW
    evm, genome, gene_inter, Genes)
  File "/scratch/zhuofei/funannotate/lib/python3.7/site-packages/funannotate/library.py", line 3984, in gff2interlapDict
    Genes = gff2dict(input, fasta, Genes, gap_filter=True)
  File "/scratch/zhuofei/funannotate/lib/python3.7/site-packages/funannotate/library.py", line 4503, in gff2dict
    Genes[k]['mRNA'][i] = sortedExons
KeyError: 'FUN_004560'

**Comment by alexvasilikop** [comment]
Hi I am having the same issue (key error in funannotate update) and I tried to see if the error is fixed but I get another error. I installed the latest commit using
$ python3 -m pip install git+https://github.com/nextgenusfs/funannotate.git

Then I activate funannotate using conda (environment where i previously have installed 1.8.9) for the dependencies.
I run:
$ /home/lege/.local/bin/funannotate update -i $outdir_predict --cpus 1 --left $left --right $right --trinity $trinity_assembly --jaccard_clip --no_trimmomatic

and I get:
-------------------------------------------------------
[Jun 21 04:36 PM]: OS: Ubuntu 18.10, 48 cores, ~ 264 GB RAM. Python: 3.6.8
[Jun 21 04:36 PM]: Running 1.8.11
[Jun 21 04:36 PM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
Traceback (most recent call last):
  File "/home/lege/.local/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/home/lege/.local/lib/python3.6/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/lege/.local/lib/python3.6/site-packages/funannotate/update.py", line 1909, in main
    (inputDir, '\n'.join(files_used)))
UnboundLocalError: local variable 'inputDir' referenced before assignment

What is potentially the problem?

**Comment by alexvasilikop** [comment]
Problem fixed. Thanks!
