### ISSUE TITLE
python errors while "download/setup databases to a writable/readable location"

### ISSUE THREAD

**Issue by maysonlin** [nextgenusfs/funannotate#735]
Greeting, 
             I used conda and mamba installing funannotate v1.8.11 on slurm HPC. Here are all versions of dependencies I have installed:
             
            
```
Checking dependencies for 1.8.9
-------------------------------------------------------
You are running Python v 3.8.12. Now checking python packages...
biopython: 1.77
goatools: 1.2.3
matplotlib: 3.4.3
natsort: 8.1.0
numpy: 1.22.4
pandas: 1.4.2
psutil: 5.9.1
requests: 2.28.0
scikit-learn: 1.1.1
scipy: 1.8.1
seaborn: 0.11.2
All 11 python packages installed
```

```
You are running Perl v b'5.026002'. Now checking perl modules...
Carp: 1.38
Clone: 0.45
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.643
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.67
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
   ERROR: Bio::Perl not installed, install with cpanm Bio::Perl 

```

```
Checking Environmental Variables...
$FUNANNOTATE_DB=/home/slin023/funannotate_db
$PASAHOME=/home/slin023/.conda/envs/funannotate/opt/pasa-2.5.2
$TRINITY_HOME=/home/slin023/.conda/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/slin023/.conda/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/slin023/.conda/envs/funannotate/config/
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
```
-------------------------------------------------------
```
Checking external dependencies...
PASA: 2.5.2
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v35
diamond: 2.0.15
emapper.py: There was an error retrieving eggnog-mapper DB data: not a valid file "/home/slin023/.conda/envs/funannotate/lib/python3.8/site-packages/data/eggnog.db"
Maybe you need to run download_eggnog_data.py
emapper-2.1.8 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: unknown / Diamond found: diamond 2.0.15 / MMseqs2 found: 13.45111
```

```
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2021-08-25
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.9.1-internal
kallisto: 0.46.1
mafft: v7.505 (2022/Apr/10)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.24-r1122
proteinortho: 6.1.0
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.12
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 39
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
	ERROR: gmes_petap.pl not installed
	ERROR: signalp not installed

```

I am installing dependencies currently. However, I followed up the [instruction](https://funannotate.readthedocs.io/en/latest/install.html) using `funannotate setup -d /scratch/mdegenna/slin023/funannotate`. I have received some python errors:

```
[Jun 20 01:47 PM]: OS: CentOS Linux 7, 4 cores, ~ 33 GB RAM. Python: 3.8.12

[Jun 20 01:47 PM]: Running 1.8.9

[Jun 20 01:47 PM]: Database location: /scratch/mdegenna/slin023/funannotate

[Jun 20 01:47 PM]: Retrieving download links from GitHub Repo

[Jun 20 01:47 PM]: Parsing Augustus pre-trained species and porting to funannotate

Traceback (most recent call last):

  File "/home/slin023/.conda/envs/funannotate/bin/funannotate", line 10, in <module>

    sys.exit(main())

  File "/home/slin023/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 705, in main

    mod.main(arguments)

  File "/home/slin023/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/setupDB.py", line 694, in main

    meropsDB(DatabaseInfo, args.force, args=args)

  File "/home/slin023/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/setupDB.py", line 139, in meropsDB

    type, name, version, date, records, checksum = info.get('merops')

TypeError: cannot unpack non-iterable NoneType object

```

 I am not clear if there are errors in python dependencies or  anything missing. If you have any suggestion, please let me know. Thank you!
                     Best, 
                              Mayson

**Comment by hyphaltip** [comment]
don't you need to tell it what DBs to install? or do all? the `-u` does an update
```
funannotate setup -i all -u
-------------------------------------------------------
[Jun 20 07:23 PM]: OS: Rocky Linux 8.5, 64 cores, ~ 528 GB RAM. Python: 3.8.12
[Jun 20 07:23 PM]: Running 1.8.11
```

**Comment by maysonlin** [comment]
Hi, that solved the problem, thank you!
