### ISSUE TITLE
eggnog-mapper issue "TypeError: expected string or bytes-like object"

### ISSUE THREAD

**Issue by SAMtoBAM** [nextgenusfs/funannotate#743]
Hi there

I have installed funannotate and eggnog-mapper with conda

```
mamba create -n funannotate -c bioconda -c conda-forge funannotate eggnog-mapper
conda activate funannotate
```

I then proceeded straight to the annotate step as I already have gene predictions.  Everything looks to be working well until the egg-nog mapper step where is crashes as below

```
funannotate annotate --gff augustus.hints.gff3 --fasta genome.masked.fa --species " Penicillium camemberti var caseifulvum" -o funannotate.output --busco_db fungi --iprscan genome.iprscan
[Jul 02 04:22 PM]: OS: Ubuntu 18.04, 48 cores, ~ 264 GB RAM. Python: 3.8.12
[Jul 02 04:22 PM]: Running 1.8.11
[Jul 02 04:22 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[Jul 02 04:22 PM]: Parsing annotation and preparing annotation files.
[Jul 02 04:23 PM]: Found 13,038 gene models from GFF3 annotation
[Jul 02 04:23 PM]: Adding Functional Annotation to Penicillium camemberti var caseifulvum, NCBI accession: None
[Jul 02 04:23 PM]: Annotation consists of: 13,038 gene models
[Jul 02 04:23 PM]: 13,431 protein records loaded
[Jul 02 04:23 PM]: Running HMMer search of PFAM version 35.0
[Jul 02 04:29 PM]: 15,514 annotations added
[Jul 02 04:29 PM]: Running Diamond blastp search of UniProt DB version 2022_02
[Jul 02 04:31 PM]: 943 valid gene/product annotations from 1,639 total
[Jul 02 03:11 PM]: Running Eggnog-mapper
Traceback (most recent call last):
  File "/home/samuel/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/samuel/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/samuel/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 804, in main
    if parse_version(get_emapper_version()) >= parse_version('2.1.0'):
  File "/home/samuel/miniconda3/envs/funannotate/lib/python3.8/site-packages/pkg_resources/__init__.py", line 121, in parse_version
    return packaging.version.Version(v)
  File "/home/samuel/miniconda3/envs/funannotate/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

Eggnog-mapper version: emapper-2.1.8 

Any ideas?

Thanks

**Comment by nextgenusfs** [comment]
Did you setup databases for eggnog-mapper?

**Comment by SAMtoBAM** [comment]
I did set up the databases but they could not be set in the default location
So for running eggnog outside of funannotate I would supply the database path
Is there a way to do this in funannotate?

**Comment by nextgenusfs** [comment]
You just need to set the eggnog DB ENV variable that points to your data, see their instructions on GitHub wiki.

**Comment by SAMtoBAM** [comment]
ok understood

In the end I just ran eggnog by itself and then fed that to funannotate and it worked too

```
download_eggnog_data.py --data_dir eggnog_db
emapper.py -i augustus.hints.aa -o eggnog --data_dir eggnog_db 
funannotate annotate --gff augustus.hints.gff3 --fasta genome.masked.fa --species " Penicillium camemberti var caseifulvum" -o funannotate.output --busco_db fungi --iprscan genome.iprscan --eggnog eggnog.annotations
```

Thanks
