### ISSUE TITLE
executable file not found in the $PATH

### ISSUE THREAD

**Issue by Skhanal2** [nextgenusfs/funannotate#746]
Hello,
I recently asked the high processing cluster to install Funannotate. They install is as container (I am not sure what that is), I am used to use package as loading modules. 
The Problem started as it is not available to run in computing node and I am required to in login through VNC terminal to access the singularity run. 
The problem I am running is the one I mentioned in the title. Every single command runs into the error saying cannot find the  executable file.

 I am not sure if it is an issue of Funannotate. But I am posting here to get any help regarding this issue I am having.

Few information: funannotate version is 1.8.11 
$path= /sw/hprc/sw/bio/containers/funannotate_v1.8.11.sif

Thank you

Sabin

**Comment by hyphaltip** [comment]
it sounds like you need to run singularity commands on your system - usually you need to prefix any commands with `singularity exec $path 'funannotate'`
here's examples from our system:
https://hpcc.ucr.edu/manuals/hpc_cluster/singularity/

**Comment by Skhanal2** [comment]
Thank you for the reply.
I was missing to add actual 'funannotate' command. Our HPRC didnot have much help in singularity page.
However this has started the another error for me:
Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/clean.py", line 197, in main
    n50 = calcN50(args.input)
  File "/venv/lib/python3.8/site-packages/funannotate/clean.py", line 20, in calcN50
    with open(input, 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'TX_1_genome.fa'

The file TX_1_genome.fa is the genome file and is present in the directory.

command used: singularity exec funannotate_v1.8.11.sif funannotate clean -i TX_1_genome.fa --minlen 1000 -o TX_1.genome.cleaned.fa

**Comment by nextgenusfs** [comment]
I'm not sure as not used singularity, but I would try using the entire path to your files. Sounds like a setup issue, ie if the current volume is available to the singularity image or not.

**Comment by Skhanal2** [comment]
So Idk if anybody in the future will run into similar problem or not. Maybe they will have better clusters to run it.

But I would like to post the solution of what worked for my own problem.

VNC terminal to run singularity as recommended the clusters staff still cannot find the file which is right in the working directory even after the updating the funannotate.

But, I was able to run interactive session with "srun"; Our clusters doenot have singularity as module to load. Hence, we need to get timed job to run the singularity.

Working code:
srun --ntasks-per-node=1  --cpus-per-task=28 --mem=54G --time=12:00:00 --pty bash -i

singularity exec /sw/hprc/sw/bio/containers/funannotate-1.8.11-07122022.sif funannotate clean -i TX_1_genome.fa --minlen 1000 -o TX_1.cleaned.genome.fa


I hope it helps someone else.

Thank you
