### ISSUE TITLE
Funannotate compare-IndexError: list index out of range

### ISSUE THREAD

**Issue by Skhanal2** [nextgenusfs/funannotate#751]
Hello,
I am trying to run Funannotate compare. I have gbk file from seven genome generated by "Funannotate annotate"
However, everytime i run I get the following error saying list index out of range

code: 
singularity exec /sw/hprc/sw/bio/containers/funannotate-1.8.11-07122022.sif funannotate compare -i TX_1_Tilletia_horrida.gbk TX_2_Tilletia_horrida.gbk TX_3_Tilletia_horrida.gbk TX_4_Tilletia_horrida.gbk TX_5_Tilletia_horrida.gbk TX_6_Tilletia_horrida.gbk TX_7_Tilletia_horrida.gbk

error: 
[Jul 19 10:32 AM]: OS: Debian GNU/Linux 10, 28 cores, ~ 65 GB RAM. Python: 3.8.13
[Jul 19 10:32 AM]: Running 1.8.11
[Jul 19 10:32 AM]: Now parsing 7 genomes
[Jul 19 10:32 AM]: working on Tilletia horrida isolate TX_1
Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/compare.py", line 253, in main
    lib.gb2proteinortho(GBK, protortho, name)
  File "/venv/lib/python3.8/site-packages/funannotate/library.py", line 7852, in gb2proteinortho
    (item, k, v['protein'][i]))
IndexError: list index out of range

Thank you

**Comment by hyphaltip** [comment]
where did your genbank files come from - I now there are some parsing challenges at times - but are these annotations you perhaps did with funannotate?

**Comment by Skhanal2** [comment]
Yes, All those annotation were done with funannotate.
