### ISSUE TITLE
Samtools error in funannotate predict

### ISSUE THREAD

**Issue by alexvasilikop** [nextgenusfs/funannotate#758]
Hello I am running version 1.8.11 funannotate predict but without 
pasa training. I only provide an rna bam file but I get the following error

$funannotate predict -i $genome -o $outdir_predict -s "species" --cpus 10 \
        --protein_evidence $uniprot $uniref50 --rna_bam $rna_bam --busco_db metazoa \
        --organism other --ploidy 1 --repeats2evm

-------------------------------------------------------
[Aug 08 10:50 AM]: OS: Ubuntu 18.10, 48 cores, ~ 264 GB RAM. Python: 3.8.12
[Aug 08 10:50 AM]: Running funannotate v1.8.11
[Aug 08 10:50 AM]: Skipping CodingQuarry as --organism=other. Pass a weight larger than 0 to run CQ, ie --weights codingquarry:1
[Aug 08 10:50 AM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     busco          
  genemark     selftraining   
  glimmerhmm   busco          
  snap         busco          
Traceback (most recent call last):
  File "/home/lege/anaconda3/envs/funannotate_alex_1.8.11/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/lege/anaconda3/envs/funannotate_alex_1.8.11/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/lege/anaconda3/envs/funannotate_alex_1.8.11/lib/python3.8/site-packages/funannotate/predict.py", line 739, in main
    if not lib.BamHeaderTest(args.input, args.rna_bam):
  File "/home/lege/anaconda3/envs/funannotate_alex_1.8.11/lib/python3.8/site-packages/funannotate/library.py", line 1575, in BamHeaderTest
    for line in execute(cmd):
  File "/home/lege/anaconda3/envs/funannotate_alex_1.8.11/lib/python3.8/site-packages/funannotate/library.py", line 555, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '['samtools', 'idxstats', '/mnt/sda1/Alex/09.GENOME_ANNOTATIONS/species/02.RNA_MAPPING/species_RNAseq_reads.bam']' returned non-zero exit status 1.

What could potentially be the problem?
Thanks

**Comment by alexvasilikop** [comment]
Ok problem solved. The bam file was not sorted.
