### ISSUE TITLE
Phobius_index-error

### ISSUE THREAD

**Issue by el42008** [nextgenusfs/funannotate#76]
Hi Jon, 

After running funannotate functional command as follows:
/mnt/apps/funannotate/funannotate.py annotate --fasta illumina_new_headers.fasta -i /home/el42208/RNA_data/funannotate/fun_out/predict_results --transcripts potato1.transcripts.fa --proteins potato1.proteins.fa --gff potato1.gff3 -e elena.lopezgirona@hutton.ac.uk --cpus 32 --out funtional --force --genbank potato1.gbk -s potato1

I got the following Error. Do you think it is something about a bad installation?
```
ESC[92m[05:01:28 PM]ESC[0m: OS: linux2, 32 cores, ~ 264 GB RAM. Python: 2.7.13
ESC[92m[05:01:28 PM]ESC[0m: Running funannotate v0.6.0
ESC[92m[05:01:29 PM]ESC[0m: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
ESC[92m[05:01:29 PM]ESC[0m: Output directory /home/el42208/RNA_data/funannotate/fun_out already exists, will use any existing data.  If this is not what you want, exit, and provide a unique name for output folder
ESC[92m[05:01:29 PM]ESC[0m: Parsing input files
ESC[92m[05:02:32 PM]ESC[0m: 51,114 protein records loaded
ESC[92m[05:02:32 PM]ESC[0m: Running HMMer search of PFAM domains
ESC[92m[06:11:56 PM]ESC[0m: 7,364 annotations added
ESC[92m[06:11:57 PM]ESC[0m: Running Blastp search of UniProt DB
ESC[92m[09:21:00 PM]ESC[0m: 8,795 annotations added
ESC[92m[09:21:00 PM]ESC[0m: Running Blastp search of MEROPS protease DB
ESC[92m[09:35:22 PM]ESC[0m: 1,405 annotations added
ESC[92m[09:35:22 PM]ESC[0m: Annotating CAZYmes using dbCAN
ESC[92m[10:31:22 PM]ESC[0m: 1,097 annotations added
ESC[92m[10:31:22 PM]ESC[0m: Annotating proteins with EggNog 4.5 database
ESC[92m[11:18:36 PM]ESC[0m: 6,249 annotations added
ESC[92m[11:18:36 PM]ESC[0m: Annotating proteins with BUSCO dikarya models
ESC[92m[11:20:00 PM]ESC[0m: 1,208 annotations added
ESC[92m[11:20:00 PM]ESC[0m: Predicting secreted and transmembrane proteins using Phobius
Traceback (most recent call last):
  File "/mnt/apps/funannotate/util/phobius-multiproc.py", line 84, in <module>
    result = line[1].split(' ')
IndexError: list index out of range
ESC[92m[11:29:43 PM]ESC[0m: Predicting secreted proteins with SignalP
Traceback (most recent call last):
  File "/mnt/apps/funannotate/bin/funannotate-functional.py", line 318, in <module>
    lib.signalP(Proteins, os.path.join(outputdir, 'annotate_misc'), signalp_out)
  File "/mnt/apps/funannotate/lib/library.py", line 900, in signalP
    runSubprocess2(cmd, '.', log, tmp_out)
  File "/mnt/apps/funannotate/lib/library.py", line 83, in runSubprocess2
    proc = subprocess.Popen(cmd, cwd=dir, stdout=out, stderr=subprocess.PIPE)
  File "/mnt/apps/python/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/mnt/apps/python/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by nextgenusfs** [comment]
The permission denied error looks similar to the one you had before with the subprocess module, I don't know the cause of it - but yes is something to do with installation.  The Phobius module first looks for a local installation of `phobius.pl`, if it is not found, it then uses a remote search via EBI servers.  The same thing may happen with InterProScan.  Due to the large number of protein models that you have, you likely will want to run InterProScan locally and feed those results into `funannotate annotate`.  

A few other things, you don't need to give the script so many inputs and actually most of them are being ignored.  You simply need to provide the `funannotate predict` output folder, like this:
```
funannotate annotate -i /home/el42208/RNA_data/funannotate/fun_out \
    -e elena.lopezgirona@hutton.ac.uk --cpus 32  --iprscan potato.interproscan.xml
```
The output will be produced in the `fun_out/annotate_results` folder.

**Comment by MichaelFokinNZ** [comment]
this errors appears only with local phobius... but doesn't terminate the pipiline
```
Traceback (most recent call last):
  File "/home/osboxes/.linuxbrew/Cellar/funannotate/0.6.1/libexec/util/phobius-multiproc.py", line 84, in <module>
    result = line[1].split(' ')
IndexError: list index out of range
```

**Comment by nextgenusfs** [comment]
@MichaelFokinNZ I think that error was fixed here https://github.com/nextgenusfs/funannotate/commit/34858828653214aeaeed652549e67b4fe808a879, same error should not happen on versions >= 0.6.2

**Comment by iwangtoknow** [comment]
Hi Jon,
The error appeared again in 1.5.2, but it doesn't terminate the pipiline.
```bash
[11:02 AM]: Annotating proteins with BUSCO dikarya models
[11:03 AM]: 1,368 annotations added
[11:03 AM]: Predicting secreted and transmembrane proteins using Phobius
Traceback (most recent call last):
  File "/home/linuxbrew/funannotate/util/phobius-multiproc.py", line 84, in <module>
    result = line[1].split(' ')
IndexError: list index out of range
[11:03 AM]: Predicting secreted proteins with SignalP
[11:08 AM]: 0 secretome and 0 transmembane annotations added
```

**WANG**

**Comment by yingzhang121** [comment]
@nextgenusfs Hi, Jon, I had the same issue as well, see below:

$ funannotate annotate -i zm_hap --busco_db metazoa  --iprscan dp.proteins.fa.xml
-------------------------------------------------------
[10:54 AM]: OS: linux2, 24 cores, ~ 66 GB RAM. Python: 2.7.12
[10:54 AM]: Running funannotate v1.5.0
[10:54 AM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[10:54 AM]: Output directory zm_hap already exists, will use any existing data.  If this is not what you want, exit, and provide a unique name for output folder
[10:54 AM]: Parsing input files
[10:54 AM]: Existing tbl found: zm_hap/update_results/Dreissena_polymorpha.tbl
[10:58 AM]: Adding Functional Annotation to Dreissena polymorpha, NCBI accession: None
[10:58 AM]: Annotation consists of: 195,015 gene models
[10:58 AM]: 189,758 protein records loaded
[10:58 AM]: Existing Pfam-A results found: zm_hap/annotate_misc/annotations.pfam.txt
[10:58 AM]: 43,659 annotations added
[10:58 AM]: Running Diamond blastp search of UniProt DB version 2018_11
[10:58 AM]: 2,221 valid gene/product annotations from 3,214 total
[10:58 AM]: Existing Eggnog-mapper results found: zm_hap/annotate_misc/eggnog.emapper.annotations
[10:58 AM]: Parsing EggNog Annotations
[10:58 AM]: 66,832 COG and EggNog annotations added
[10:58 AM]: Combining UniProt/EggNog gene and product names using Gene2Product version 1.28
[10:58 AM]: 12,744 gene name and product description annotations added
[10:58 AM]: Existing MEROPS results found: zm_hap/annotate_misc/annotations.merops.txt
[10:58 AM]: 1,655 annotations added
[10:58 AM]: Existing CAZYme results found: zm_hap/annotate_misc/annotations.dbCAN.txt
[10:58 AM]: 532 annotations added
[10:58 AM]: Existing BUSCO2 results found: zm_hap/annotate_misc/annotations.busco.txt
[10:58 AM]: 1,025 annotations added
[10:58 AM]: Existing Phobius results found: zm_hap/annotate_misc/phobius.results.txt
[10:58 AM]: Predicting secreted proteins with SignalP
Traceback (most recent call last):
  File "/panfs/roc/msisoft/funannotate/1.5.1/bin/funannotate-functional.py", line 822, in <module>
    lib.signalP(Proteins, os.path.join(outputdir, 'annotate_misc'), signalp_out)
  File "/panfs/roc/msisoft/funannotate/1.5.1/lib/library.py", line 3812, in signalP
    runSubprocess2(cmd, '.', log, tmp_out)
  File "/panfs/roc/msisoft/funannotate/1.5.1/lib/library.py", line 705, in runSubprocess2
    proc = subprocess.Popen(cmd, cwd=dir, stdout=out, stderr=subprocess.PIPE)
  File "/panfs/roc/msisoft/anaconda/anaconda2-4.2/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/panfs/roc/msisoft/anaconda/anaconda2-4.2/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

---------------------------------------------
I checked my Phobius results, and it looked fine. But SignalP is crashing. 

I will try to re-install it and see whether it could resolve my issue.

Best,
Ying

**Comment by nextgenusfs** [comment]
signalP needs to be manually installed and configured, confirm that you can run it from the command line and it is in your PATH.
