### ISSUE TITLE
plantismash 

### ISSUE THREAD

**Issue by zhangwenda0518** [nextgenusfs/funannotate#769]
Dear author
I'm using funannotate remote to run annotation **plantismash**, but an error occurred. 
Could you give me some suggestions?

Thanks very much！！！

Details are as follows

**Are you using the latest release?**

funannotate check --show-versions
-------------------------------------------------------
 **1.8.13**

**Describe the bug**
[Aug 23 10:41 AM]: OS: CentOS Linux 8, 256 cores, ~ 660 GB RAM. Python: 3.6.15
[Aug 23 10:41 AM]: Running 1.8.13
[Aug 23 10:41 AM]: Output directory functional_annotation already exists
[Aug 23 10:41 AM]: Checking GenBank file for annotation
Traceback (most recent call last):
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/urllib3/connection.py", line 467, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/urllib3/connection.py", line 540, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/urllib3/util/ssl_match_hostname.py", line 155, in match_hostname
    raise CertificateError("hostname %r doesn't match %r" % (hostname, dnsnames[0]))
urllib3.util.ssl_match_hostname.CertificateError: hostname 'plantismash.secondarymetabolites.org' doesn't match '*.bioinformatics.nl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='plantismash.secondarymetabolites.org', port=443): Max retries exceeded with url: /api/v1.0/version (Caused by SSLError(CertificateError("hostname 'plantismash.secondarymetabolites.org' doesn't match '*.bioinformatics.nl'",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/funannotate/remote.py", line 242, in main
    version = requests.get(base_address+"/api/v1.0/version")
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/zhangwenda/sysoft/anaconda3/envs/funannotate/lib/python3.6/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
**requests.exceptions.SSLError: HTTPSConnectionPool(host='plantismash.secondarymetabolites.org', port=443): Max retries exceeded with url: /api/v1.0/version (Caused by SSLError(CertificateError("hostname 'plantismash.secondarymetabolites.org' doesn't match '*.bioinformatics.nl'",),))**

**What command did you issue?**
funannotate remote -m antismash  -e ***@gmail.com -g update_results/test.gbk -o functional_annotation --force **-a plants**

**Logfiles**
[08/23/22 10:41:38]: /home/zhangwenda/sysoft/anaconda3/envs/funannotate/bin/funannotate>

[08/23/22 10:41:38]: OS: CentOS Linux 8, 256 cores, ~ 660 GB RAM. Python: 3.6.15
[08/23/22 10:41:38]: Running 1.8.13
[08/23/22 10:41:38]: Output directory functional_annotation already exists
[08/23/22 10:41:38]: Checking GenBank file for annotation

**OS/Install Information**
 -  output of `funannotate check --show-versions`
You are running Python v 3.6.15. Now checking python packages...
biopython: 1.77
goatools: 1.2.3
matplotlib: 3.3.4
natsort: 8.1.0
numpy: 1.19.5
pandas: 1.1.5
psutil: 5.8.0
requests: 2.27.1
scikit-learn: 0.24.2
scipy: 1.1.0
seaborn: 0.11.2
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Carp: 1.38
Clone: 0.45
DBD::SQLite: 1.70
DBD::mysql: 4.046
DBI: 1.643
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.27
Getopt::Long: 2.52
Hash::Merge: 0.302
JSON: 4.02
LWP::UserAgent: 6.61
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.25
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 5.10
YAML: 1.30
local::lib: 2.000029
threads: 2.21
threads::shared: 1.59
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/zhangwenda/database/funannotate_db
$PASAHOME=/home/zhangwenda/sysoft/anaconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/zhangwenda/sysoft/anaconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/zhangwenda/sysoft/anaconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/zhangwenda/sysoft/anaconda3/envs/funannotate/config/
$GENEMARK_PATH=/home/zhangwenda/biosoft/gene_prediction/gmes_linux_64_4
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v36
diamond: 2.0.14
emapper.py: v1.0
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.69_lic
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.1-internal
kallisto: 0.46.1
mafft: v7.490 (2021/Oct/30)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.24-r1122
pigz: pigz 2.6
proteinortho: 6.0.33
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.12
signalp: 5.0b
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 26
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 37 external dependencies are installed

**Comment by IanDMedeiros** [comment]
Came across the same error today while trying to set up funannotate to work with both lichen mycobiont and photobiont genomes. 

The problem seems to be that the plantismash API—if there even is one—is not set up like fungismash, i.e., http://plantismash.secondarymetabolites.org/api/v1.0/version, http://plantismash.secondarymetabolites.org/api/v1.0/stats, and http://plantismash.secondarymetabolites.org/api/v1.0/submit are not valid URLs. 

Might be best to remove the plantismash option for now if there is not a functional API? I would think it should be fine to just submit through the web server and add the results in manually, although I haven't tested that yet.
