### ISSUE TITLE
Failure to import mamba.mamba_api as api

### ISSUE THREAD

**Issue by erinnjordan** [nextgenusfs/funannotate#779]
Using latest release
Importing using mamba, requisite file is not present
mamba create -n funannotate funannotate
Traceback (most recent call last):
  File "/home/nfs/ejordan/.conda/envs/trim/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/nfs/ejordan/.conda/envs/trim/lib/python3.6/site-packages/mamba/mamba.py", line 50, in <module>
    import mamba.mamba_api as api
output N/A, cannot install

**Comment by hyphaltip** [comment]
did you setup the channels in mamba or specify the channel on the cmdline? https://funannotate.readthedocs.io/en/latest/install.html#install

```mamba create -n funannotate -c bioconda -c conda-forge funannotate```
