### ISSUE TITLE
funannotate mask: No such file or directory: 'RepeatMasker'

### ISSUE THREAD

**Issue by dmacguigan** [nextgenusfs/funannotate#786]
**Are you using the latest release?**
Yes

**Describe the bug**
I am using the latest Docker image for funannotate (with Singularity) on a university computing cluster. I am attempting to run the `Funannotate mask` module with RepeatMasker. 

Since the Docker image does not include RepeatMasker, I am using my own install, located at `/projects/academic/tkrabben/software/RepeatMasker`. 

It's a bit convoluted, but I believe the code below works. I have verified that my RepeatMasker install works properly outside of Funannotate. 

Funannotate appears to create the proper subdirectory structure. 
```
[dmacguig@vortex2:~/project/MacGuigan/genome_annotations/HN01/funannotate_1]$ ls -l
total 556
-rw-r--r-- 1 dmacguig grp-tkrabben   5374 Sep 14 15:53 AISO_funannotate.sh
-rw-rw-r-- 1 dmacguig grp-tkrabben    771 Sep 14 15:53 funannotate-mask.log
-rw-rw-r-- 1 dmacguig grp-tkrabben   1116 Aug 18 16:22 funannotate-mask.tantan.log
drwxrwsr-x 1 dmacguig grp-tkrabben   4096 Sep 13 23:31 HN01_assembly
drwxrwsr-x 1 dmacguig grp-tkrabben   4096 Sep 14 00:53 HN01_funannotate
drwxrwsr-x 1 dmacguig grp-tkrabben   4096 Sep 13 16:37 HN01_GeMoMa_output
drwxr-sr-x 1 dmacguig grp-tkrabben   4096 Aug 18 13:56 HN01_RepeatModeler
drwxrwsr-x 1 dmacguig grp-tkrabben   4096 Aug 18 17:50 HN01_transcriptome
drwxrwsr-x 1 dmacguig grp-tkrabben   4096 Sep 14 09:33 HN_funannotate_train
drwxrwsr-x 1 dmacguig grp-tkrabben   4096 Sep 14 15:53 mask_f938bab0-b09e-47d4-9b9e-8c294d36f161
```
```
[dmacguig@vortex2:~/project/MacGuigan/genome_annotations/HN01/funannotate_1]$ ls -l mask_f938bab0-b09e-47d4-9b9e-8c294d36f161
total 0
drwxrwsr-x 1 dmacguig grp-tkrabben 4096 Sep 14 15:53 RepeatMasker
```

But somehow Funannotate is unable to locate the RepeatMasker directory. It spits out the following error message. 

```
[Sep 14 03:53 PM]: OS: Debian GNU/Linux 10, 56 cores, ~ 1056 GB RAM. Python: 3.8.12
[Sep 14 03:53 PM]: Running funanotate v1.8.13
[Sep 14 03:53 PM]: Soft-masking: running RepeatMasker with custom library
Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/mask.py", line 172, in main
    RepeatMask(args.input, args.repeatmodeler_lib,
  File "/venv/lib/python3.8/site-packages/funannotate/mask.py", line 78, in RepeatMask
    subprocess.call(['RepeatMasker', '-e', 'ncbi', '-lib', os.path.abspath(library), '-pa', str(cpus), '-xsmall', '-dir', 'RepeatMasker', input],
  File "/venv/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/venv/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/venv/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'RepeatMasker'
```

**What command did you issue?**
```
#!/bin/bash
#SBATCH --qos=general-compute
#SBATCH --partition=general-compute
#SBATCH --account=tkrabben
#SBATCH --time=72:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48
#SBATCH --cpus-per-task=1
#SBATCH --mem=900G # memory per node, check compute resource availabily here https://ubccr.freshdesk.com/suppor$
#SBATCH --job-name=AISO_funannotate
#SBATCH --output="slurm-%A.out"
#SBATCH --error="slurm-%A.err"

# Pipeline to perform gene prediction and annotation with funannotate
# author: Dan MacGuigan

############################################################
# Input variables                                          #
############################################################
ANNOTATION_DIR="/projects/academic/tkrabben/MacGuigan/genome_annotations/HN01/funannotate_1" # top level directory
FULL_SP_NAME="Hypentelium_nigricans_HiC" # full species name, used to name Augustus HMM files
SPECIES="HN01" # short name for your species
GENOME_DIR="HN01_assembly" # directory containing your genome assembly
GENOME_FILE="HN01_HiC_50Chr_02-18-2022.fasta" # your genome assembly file
CPUS=48 # CPUS/cores for parallel processing 
RM_LIB="/projects/academic/tkrabben/MacGuigan/genome_annotations/HN01/funannotate_1/HN01_RepeatModeler/Hypentel$
RM_SPECIES="vertebrata" # species or clade to use for repeat masking

# a few housekeeping things for Singularity to play nice
module purge
unset TMPDIR

# move to the annotation directory
cd ${ANNOTATION_DIR}

### soft mask repeats ###
singularity run -H ${PWD} -B /projects/academic/tkrabben/software/RepeatMasker:/rm_path \
 --env PREPEND_PATH=/rm_path \
 /projects/academic/tkrabben/software/funannotate_1.8.13/funannotate_latest.sif funannotate mask \
 -i ${ANNOTATION_DIR}/${GENOME_DIR}/${GENOME_FILE} \
 -o ${ANNOTATION_DIR}/${GENOME_DIR}/${SPECIES}.repeatmasker.masked.fasta \
 -l ${RM_LIB} \
 -s ${RM_SPECIES} \
 -m "repeatmasker" \
 --cpus ${CPUS}
```

**Logfiles**
See error message above

**OS/Install Information**
```
-------------------------------------------------------
Checking dependencies for 1.8.13
-------------------------------------------------------
You are running Python v 3.8.12. Now checking python packages...
biopython: 1.79
goatools: 1.2.3
matplotlib: 3.5.3
natsort: 8.1.0
numpy: 1.22.4
pandas: 1.4.3
psutil: 5.9.1
requests: 2.28.1
scikit-learn: 1.1.1
scipy: 1.5.3
seaborn: 0.11.2
All 11 python packages installed


You are running Perl v b'5.026002'. Now checking perl modules...
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
local::lib: 2.000024
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/opt/databases
$PASAHOME=/venv/opt/pasa-2.4.1
$TRINITYHOME=/venv/opt/trinity-2.8.5
$EVM_HOME=/venv/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/usr/share/augustus/config
        ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.2
bamtools: bamtools 2.5.2
bedtools: bedtools v2.30.0
blat: BLAT v35
diamond: 2.0.15
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.505 (2022/Apr/10)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.24-r1122
pigz: pigz 2.6
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.12
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 39
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: emapper.py not installed
        ERROR: gmes_petap.pl not installed
        ERROR: signalp not installed
```

**Comment by nextgenusfs** [comment]
I won't be much help here as it most likely has to do with the path traversal from local file system to the VM, but if it works outside of funannotate than just run RepeatModeler/Masker on your genome and pass the soft masked genome to funannotate.

**Comment by dmacguigan** [comment]
Thanks for the quick reply @nextgenusfs. I was hoping to run everything through funannotate, but masking externally was my backup plan,

**Comment by nextgenusfs** [comment]
Several years ago I more/less abandoned including it because installation is really painful and then the repbase repository became fee-for-usage so it didn't generalize for all users. Funannotate just expects that repeats are soft-masked. You can see in the code base how the scripts were being run, however this is several years old so I'm not sure if those commands generalize to recent releases of repeatmodeler and repeatmasker.
