### ISSUE TITLE
missing signalp6 causes error

### ISSUE THREAD

**Issue by trvinh** [nextgenusfs/funannotate#833]
**Are you using the latest release?**
fun annotate v1.8.14

**Describe the bug**

It seems that the check for signalp6 couldn't pass at lines 362-363 in check.py and 1031-1036 in annotate.py.

The log for `check --show-versions` can be seen at the end of this report. Here is the log when I ran `funannotate annotate` with some existing annotations in annotate_misc folder:

```
[Nov 04 05:32 PM]: Predicting secreted proteins with SignalP
-------------------------------------------------------
Traceback (most recent call last):
  File "/home/vinh/anaconda3/envs/ecoevo/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/home/vinh/anaconda3/envs/ecoevo/lib/python3.7/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/vinh/anaconda3/envs/ecoevo/lib/python3.7/site-packages/funannotate/annotate.py", line 1031, in main
    if os.path.exists(shutil.which('signalp6')) == True:
  File "/home/vinh/anaconda3/envs/ecoevo/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

I have only signalp installed but not signalp6. I am using funannotate v1.8.14 because it solves the issue with Augustus 3.5 #724 #791

**What command did you issue?**

funannotate check --show-versions
funannotate annotate -i fun

**OS/Install Information**
 -  output of `funannotate check --show-versions`
```
Traceback (most recent call last):
  File "/home/vinh/anaconda3/envs/ecoevo/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/home/vinh/anaconda3/envs/ecoevo/lib/python3.7/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/vinh/anaconda3/envs/ecoevo/lib/python3.7/site-packages/funannotate/check.py", line 362, in main
    if os.path.exists(shutil.which('signalp6')) == True:
  File "/home/vinh/anaconda3/envs/ecoevo/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by hyphaltip** [comment]
I don't think I tested combination w signalp5 on fun v1.8.14 (live code) on my system will see if I can on my system.

**Comment by hyphaltip** [comment]
latest code should find that?

**Comment by trvinh** [comment]
@hyphaltip the problem is that `os.path.exists()` cannot work with Nonetype object, which we will get if signalp6 not found using `shutil.which('signalp6')` command

**Comment by hyphaltip** [comment]
still needed to adjust logic, the v7 was not getting set as same logic was applied.  
Have tested now both for v5 and v6 with updated code.
