### ISSUE TITLE
not running,but no error report

### ISSUE THREAD

**Issue by YDD99** [nextgenusfs/funannotate#838]
(funannotate) wangyuanbing@wangyb-System:~/Desktop/CZY/funannotate$ funannotate predict -i '/home/wangyuanbing/Desktop/CZY/funannotate/scaffolds_clean_sort_mask.fasta' --species "Hypocrella raciborskii" -o funannotate --cpus 4
-------------------------------------------------------
[Nov 14 05:10 PM]: OS: Linux Mint 20.3, 8 cores, ~ 33 GB RAM. Python: 3.7.12
[Nov 14 05:10 PM]: Running funannotate v1.8.13

^CTraceback (most recent call last):
  File "/home/wangyuanbing/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/wangyuanbing/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/wangyuanbing/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/predict.py", line 253, in main
    if lib.which('bam2hints'):
  File "/home/wangyuanbing/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/library.py", line 853, in which
    stderr=devnull, universal_newlines=True).communicate()
  File "/home/wangyuanbing/miniconda3/envs/funannotate/lib/python3.7/subprocess.py", line 956, in communicate
    self.wait()
  File "/home/wangyuanbing/miniconda3/envs/funannotate/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/home/wangyuanbing/miniconda3/envs/funannotate/lib/python3.7/subprocess.py", line 1653, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/wangyuanbing/miniconda3/envs/funannotate/lib/python3.7/subprocess.py", line 1611, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
(funannotate) wangyuanbing@wangyb-System:~/Desktop/CZY/funannotate$ ^C

**Comment by hyphaltip** [comment]
it is hard to help here without more info or an example of data that replicates the problem. 
does the `funannotate test` work at all for you (i know on current version it seems slow)
did you run `funannotate check --show-versions` to see that all dependency software is installed properly.

**Comment by YDD99** [comment]
(funannotate) wangyuanbing@wangyb-System:~$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.8.13
-------------------------------------------------------
You are running Python v 3.7.12. Now checking python packages...
biopython: 1.79
goatools: 1.2.3
matplotlib: 3.5.3
natsort: 8.2.0
numpy: 1.21.6
pandas: 1.3.5
psutil: 5.9.2
requests: 2.28.1
scikit-learn: 1.0.2
scipy: 1.7.3
seaborn: 0.12.0
All 11 python packages installed


You are running Perl v b'5.032001'. Now checking perl modules...
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.70
DBD::mysql: 4.046
DBI: 1.643
DB_File: 1.855
Data::Dumper: 2.183
File::Basename: 2.85
File::Which: 1.24
Getopt::Long: 2.52
Hash::Merge: 0.302
JSON: 4.10
LWP::UserAgent: 6.67
Logger::Simple: 2.0
POSIX: 1.94
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.14
Tie::File: 1.06
URI::Escape: 5.12
YAML: 1.30
local::lib: 2.000029
threads: 2.25
threads::shared: 1.61
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/home/wangyuanbing/funannotate_db
$PASAHOME=/home/wangyuanbing/miniconda3/envs/funannotate/opt/pasa-2.5.2
$TRINITY_HOME=/home/wangyuanbing/miniconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/wangyuanbing/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/wangyuanbing/miniconda3/envs/funannotate/config/
$GENEMARK_PATH=/home/wangyuanbing/miniconda3/envs/funannotate/bin:/home/wangyuanbing/miniconda3/bin:/home/wangyuanbing/miniconda3/condabin:/home/wangyuanbing/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.5.2
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.5.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v35
diamond: 2.0.15
emapper.py: 2.1.9
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2021-08-25
gmes_petap.pl: 4.69_lic
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 17.0.3-internal
kallisto: 0.46.1
mafft: v7.508 (2022/Sep/07)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.24-r1122
pigz: pigz 2.6
proteinortho: 6.1.1
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.16.1
signalp: 5.0b
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.11 (Oct 2022)
tantan: tantan 39
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.36
All 37 external dependencies are installed

as you see,i did funannotate check --show-versions, looks like no problem
also i did funannotate test before ,spent almost two days and no results,i will try it again from begining, thank you

**Comment by nextgenusfs** [comment]
Funannotate v1.8.13 and below is not compatible with Augustus v3.4 and above. That's why it doesn't finish. So downgrade Augustus or upgrade funannotate to latest in master.

**Comment by YDD99** [comment]
thank you very much ,thank you!
