### ISSUE TITLE
Funannotate-docker compare NOT running 

### ISSUE THREAD

**Issue by kalonji08** [nextgenusfs/funannotate#842]
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**

[Nov 18 10:02 PM]: OS: Debian GNU/Linux 10, 40 cores, ~ 99 GB RAM. Python: 3.8.12
[Nov 18 10:02 PM]: Running 1.8.14
[Nov 18 10:02 PM]: Now parsing 1 genomes
[Nov 18 10:02 PM]: working on N_albidus_NRRLY1402
[Nov 18 10:02 PM]: No secondary metabolite annotations found
[Nov 18 10:02 PM]: Summarizing PFAM domain results
[Nov 18 10:02 PM]: Summarizing InterProScan results
[Nov 18 10:02 PM]: Loading InterPro descriptions
[Nov 18 10:02 PM]: Summarizing MEROPS protease results
[Nov 18 10:02 PM]: Summarizing CAZyme results
[Nov 18 10:02 PM]: No COG annotations found
[Nov 18 10:02 PM]: No SignalP annotations found
[Nov 18 10:02 PM]: Summarizing fungal transcription factors
[Nov 18 10:02 PM]: No transcription factor IPR domains found
Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/compare.py", line 1067, in main
    stats[i].append("{0:,}".format(singletons))
TypeError: list indices must be integers or slices, not dict

**What command did you issue?**
funannotate-docker compare -i gbkData/ --cpus 37

**Logfiles**
Please provide relavent log files of the error. 
[funannotate-compare.log](https://github.com/nextgenusfs/funannotate/files/10045134/funannotate-compare.log)

**OS/Install Information**
 -  output of `funannotate check --show-versions`

**Comment by nextgenusfs** [comment]
Was this genome annotated with `funannotate annotate`?  It doesn't seem to have any of the proper annotations in the genbank file.

**Comment by kalonji08** [comment]
Hi @nextgenusfs i annotated the genome with funannotate one of our previous colaborator has analysed this genome before and funannotate compare was succesful

**Comment by kalonji08** [comment]
For funannotate compare the input should be the gbk files right ?

**Comment by kalonji08** [comment]
Hi @nextgenusfs i hope you are well,  i wanted to follow up on the above  Error 

I run fun annotate predict and annotate on the genomes then copied the gbk files in that folder

Here is the main error:
Traceback (most recent call last):
  File "/home/kalonjilab2/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/kalonjilab2/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/kalonjilab2/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/compare.py", line 1067, in main
    stats[i].append("{0:,}".format(singletons))
TypeError: list indices must be integers or slices, not str


Its coming from this line

![image](https://user-images.githubusercontent.com/59872248/208148887-ee2abf52-2baf-42c6-8b08-763945821512.png)

**Comment by kalonji08** [comment]
Hi @nextgenusfs I run :  funannotate test -t compare and it was was succesful. see below

Running `funannotate compare` unit testing
Downloading: https://osf.io/7s9xh/download?version=1 Bytes: CMD: funannotate compare -i Genome_one.gbk Genome_two.gbk Genome_three.gbk -o compare --cpus 40 --ml_model LG+G4 --outgroup botrytis_cinerea.dikarya
#########################################################
-------------------------------------------------------
[Dec 16 07:09 PM]: OS: Ubuntu 20.04, 40 cores, ~ 99 GB RAM. Python: 3.8.13
[Dec 16 07:09 PM]: Running 1.8.13
[Dec 16 07:09 PM]: Now parsing 3 genomes
[Dec 16 07:09 PM]: working on Genome one
[Dec 16 07:09 PM]: working on Genome two
[Dec 16 07:09 PM]: working on Genome three
[Dec 16 07:09 PM]: No secondary metabolite annotations found
[Dec 16 07:09 PM]: Summarizing PFAM domain results
[Dec 16 07:09 PM]: Summarizing InterProScan results
[Dec 16 07:09 PM]: Loading InterPro descriptions
[Dec 16 07:09 PM]: Summarizing MEROPS protease results
[Dec 16 07:09 PM]: found 4 MEROPS familes
[Dec 16 07:09 PM]: Summarizing CAZyme results
[Dec 16 07:09 PM]: found 5 CAZy familes
[Dec 16 07:09 PM]: Summarizing COG results
[Dec 16 07:09 PM]: Summarizing secreted protein results
[Dec 16 07:09 PM]: Summarizing fungal transcription factors
[Dec 16 07:09 PM]: Running GO enrichment for each genome
  WARNING: skipping Genome_one.txt as no GO terms
[Dec 16 07:11 PM]: Running orthologous clustering tool, ProteinOrtho.  This may take awhile...
[Dec 16 07:11 PM]: Compiling all annotations for each genome
[Dec 16 07:11 PM]: Inferring phylogeny using iqtree
[Dec 16 07:11 PM]: Found 1 single copy BUSCO orthologs, will use all to infer phylogeny
[Dec 16 07:13 PM]: Compressing results to output file: compare.tar.gz
[Dec 16 07:13 PM]: Funannotate compare completed successfully!
#########################################################
SUCCESS: `funannotate compare` test complete.
#########################################################
