### ISSUE TITLE
Error with gmap when checking dependencies

### ISSUE THREAD

**Issue by tjhinet** [nextgenusfs/funannotate#883]
Hi,

I am having issues with gmap when I am checking Funannotate dependencies. I have created a conda environment for funannotate and installed funannotate with mamba. It looks like gmap (v2021.08.25) and pasa (v2.5.2) have been installed but the following error comes up when I perform "funannotate check --show-versions":

-------------------------------------------------------
Checking dependencies for 1.8.13
-------------------------------------------------------
You are running Python v 3.8.15. Now checking python packages...
biopython: 1.81
goatools: 1.2.3
matplotlib: 3.4.3
natsort: 8.3.1
numpy: 1.24.2
pandas: 1.5.3
psutil: 5.9.4
requests: 2.28.2
scikit-learn: 1.2.2
scipy: 1.10.1
seaborn: 0.12.2
All 11 python packages installed

You are running Perl v b'5.032001'. Now checking perl modules...
Carp: 1.50
Clone: 0.46
DBD::SQLite: 1.72
DBD::mysql: 4.046
DBI: 1.643
DB_File: 1.855
Data::Dumper: 2.183
File::Basename: 2.85
File::Which: 1.24
Getopt::Long: 2.54
Hash::Merge: 0.302
JSON: 4.10
LWP::UserAgent: 6.67
Logger::Simple: 2.0
POSIX: 1.94
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.14
Tie::File: 1.06
URI::Escape: 5.12
YAML: 1.30
local::lib: 2.000029
threads: 2.25
threads::shared: 1.61
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/u4485090/FUNANNOTATE_DB
$PASAHOME=/home/u4485090/conda/envs/funannotate/opt/pasa-2.5.2
$TRINITY_HOME=/home/u4485090/conda/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/u4485090/conda/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/u4485090/conda/envs/funannotate/config/
	ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
	ERROR: gmap found but error running gmap
Traceback (most recent call last):
  File "/home/u4485090/conda/envs/funannotate/bin/ete3", line 6, in <module>
    from ete3.tools.ete import main
  File "/home/u4485090/conda/envs/funannotate/lib/python3.8/site-packages/ete3/tools/ete.py", line 55, in <module>
    from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,
  File "/home/u4485090/conda/envs/funannotate/lib/python3.8/site-packages/ete3/tools/ete_view.py", line 48, in <module>
    from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,
ImportError: cannot import name 'TextFace' from 'ete3' (/home/u4485090/conda/envs/funannotate/lib/python3.8/site-packages/ete3/__init__.py)
PASA: 2.5.2

Can I please get some help with this? I tried downgrading gmap and pasa to an older version but the installer refused to do it.

Thank you very much in advance!

Regards,
Erick

**Comment by hyphaltip** [comment]
Did you install gmap by conda. I don't even think it works as well as exonerate so we don't make it a default.

**Comment by tjhinet** [comment]
I think in my case the gmap and pasa was installed as part of the Funannotate package through conda. I don't know if this error will be critical for what I want to do, but in my past genome annotation, I had performed it with Funannotate that has passed all of the dependencies.
