### ISSUE TITLE
xml.etree.ElementTree.ParseError

### ISSUE THREAD

**Issue by hassantarabai** [nextgenusfs/funannotate#884]
Hello,

I am getting the error "xml.etree.ElementTree.ParseError: mismatched tag: line 27, column 4" on a new funannotate installation when running funannotate annotate on test data " funannotate test -t all --cpus 40"

**Detailed error text**
"Traceback (most recent call last):
  File "/home/miniconda3/envs/funannotate/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 794, in main
    SwissProtBlast(Proteins, args.cpus, 1e-5,
  File "/home/miniconda3/envs/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 75, in SwissProtBlast
    for qresult in SearchIO.parse(results, "blast-xml"):
  File "/home/miniconda3/envs/funannotate/lib/python3.8/site-packages/Bio/SearchIO/__init__.py", line 306, in parse
    yield from generator
  File "/home/miniconda3/envs/funannotate/lib/python3.8/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 240, in __iter__
    yield from self._parse_qresult()
  File "/home/miniconda3/envs/funannotate/lib/python3.8/site-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 289, in _parse_qresult
    for event, qresult_elem in self.xml_iter:
  File "/home/miniconda3/envs/funannotate/lib/python3.8/xml/etree/ElementTree.py", line 1227, in iterator
    yield from pullparser.read_events()
  File "/home/miniconda3/envs/funannotate/lib/python3.8/xml/etree/ElementTree.py", line 1302, in read_events
    raise event
  File "/home/miniconda3/envs/funannotate/lib/python3.8/xml/etree/ElementTree.py", line 1274, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: mismatched tag: line 27, column 4"

**funannotate check --show-versions**
$FUNANNOTATE_DB=/home/fun_db/
$PASAHOME=/home/miniconda3/envs/funannotate3/opt/pasa-2.5.2
$TRINITY_HOME=/home/miniconda3/envs/funannotate3/opt/trinity-2.8.5
$EVM_HOME=/home/miniconda3/envs/funannotate3/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/miniconda3/envs/funannotate3/config/
$GENEMARK_PATH=/home/gene_mark/gmes_linux_64_4/
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
        ERROR: pslDnaFiler found but error running: pslCDnaFilter: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

PASA: 2.5.2
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.5.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.30.0
blat: BLAT v35
diamond: 2.1.4
emapper.py: 2.1.10
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: 36.3.8g
glimmerhmm: 3.0.4
gmap: 2021-08-25
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 17.0.3-internal
kallisto: 0.46.1
mafft: v7.515 (2023/Jan/15)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.24-r1122
pigz: 2.4
proteinortho: 6.2.0
salmon: salmon 0.14.1
samtools: samtools 1.16.1
signalp: 6.0
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.11 (Oct 2022)
tantan: tantan 40
tbl2asn: 25.8
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: gmes_petap.pl not installed
        ERROR: pslCDnaFilter not installed

Any idea of what is causing this error or how to deal withit?

Thank you,

**Comment by nextgenusfs** [comment]
Downgrade diamond I think the xml format is broken in latest versions.

**Comment by mworkentine** [comment]
Had the same issue - upgrading diamond to 2.1.6 solved this for me

**Comment by novigit** [comment]
@nextgenusfs @mworkentine , sorry to be posting in a closed issue.

I am getting the same `xml.etree.ElementTree.ParseError: mismatched tag: line 27, column 4` error when running `funannotate annotate`

My admin upgraded diamond from `2.0.15` to `2.1.6` in the funannotate environment. Version `2.1.6` supposedly fixed the XML tag issue, however, I'm getting the same error.

From issue #872 I read that perhaps rerunning `funannotate setup` was also necessary. My admin did this (pointing `-d` to where the funannotate databases were already stored), but it didn't seem to change anything there. 

Rerunning `funannotate annotate` after that still yielded the same xml error
