### ISSUE TITLE
New 1.8.14 release?

### ISSUE THREAD

**Issue by abretaud** [nextgenusfs/funannotate#885]
**Are you using the latest release?**
That's the point :laughing: 

**Describe the bug**
Is there a plan for officially release a new (1.8.14?) version of funannotate? Currently the galaxy tool/workflow is broken due to different bugs that seem to be fixed on the master branch. As we are preparing for a big training session in may, I'd love to make sure everything's working perfectly before that

**Comment by nextgenusfs** [comment]
Yes I can tag one.  I've not had much time to devote to this.  I was hoping to test the v1.8.14 (current master) with augustus v3.5 myself but haven't had a chance to do it -- if I could get definitive confirmation that it works well with v3.5 than I can tag that in the conda build which should fix a lot of peoples augustus related install issues (hopefully).

**Comment by abretaud** [comment]
Hi!
I don't know if it helps, but I've just run the tests from the `[galaxy tools](https://github.com/galaxyproject/tools-iuc/tree/main/tools/funannotate)` using the current code in master branch.

I did it like that:
- created a conda env with funannotate 1.8.13 and pip (it installs augustus 3.5.0)
- installed latest funannotate with `pip install git+https://github.com/nextgenusfs/funannotate.git`

The tests for `funannotate predict` pass with latest code (though they no longer with 1.8.13)

With `funannotate compare`, I had these errors (maybe due to a minimal test dataset?):

```
[Apr 06 04:55 PM]: Running 1.8.14
[Apr 06 04:55 PM]: Now parsing 4 genomes
[Apr 06 04:55 PM]: working on Genus species
[Apr 06 04:55 PM]: working on Other species
[Apr 06 04:55 PM]: working on Other beast
[Apr 06 04:55 PM]: working on Yet another
[Apr 06 04:55 PM]: No secondary metabolite annotations found
[Apr 06 04:55 PM]: Summarizing PFAM domain results
[Apr 06 04:55 PM]: Summarizing InterProScan results
[Apr 06 04:55 PM]: Loading InterPro descriptions
[Apr 06 04:55 PM]: Summarizing MEROPS protease results
[Apr 06 04:55 PM]: Summarizing CAZyme results
[Apr 06 04:55 PM]: found 0 CAZy familes
[Apr 06 04:55 PM]: No COG annotations found
[Apr 06 04:55 PM]: No SignalP annotations found
[Apr 06 04:55 PM]: Summarizing fungal transcription factors
[Apr 06 04:55 PM]: No transcription factor IPR domains found
[Apr 06 04:55 PM]: Running GO enrichment for each genome
Traceback (most recent call last):
  File "/conda/envs/__funannotate@1.8.13/lib/python3.8/site-packages/funannotate/aux_scripts/enrichment_parallel.py", line 76, in <module>
    lib.runMultiProgress(GO_safe_run, file_list, procs, progress=False)
  File "/conda/envs/__funannotate@1.8.13/lib/python3.8/site-packages/funannotate/library.py", line 1254, in runMultiProgress
    p = multiprocessing.Pool(cpus)
  File "/conda/envs/__funannotate@1.8.13/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/conda/envs/__funannotate@1.8.13/lib/python3.8/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
[Apr 06 04:55 PM]: Running orthologous clustering tool, ProteinOrtho.  This may take awhile...
[Apr 06 04:55 PM]: Calculating dN/dS ratios for each ortholog group, 19 orthologous groups
[Apr 06 04:56 PM]: Compiling all annotations for each genome
[Apr 06 04:56 PM]: Inferring phylogeny using raxml
[Apr 06 04:56 PM]: Found 1 single copy BUSCO orthologs, will use all to infer phylogeny
Traceback (most recent call last):
  File "/conda/envs/__funannotate@1.8.13/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/conda/envs/__funannotate@1.8.13/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/conda/envs/__funannotate@1.8.13/lib/python3.8/site-packages/funannotate/compare.py", line 1268, in main
    t = row[3].split(', ')  # convert Eggnog to list
AttributeError: 'float' object has no attribute 'split'
```

An also found https://github.com/nextgenusfs/funannotate/issues/896

Let me know if I can help by running other tests

**Comment by nextgenusfs** [comment]
Okay I just pushed fix for #896. Lets try to get rest of these addressed and tag a version.  

I can't seem to replicate the errors in `compare` at least with the integrated tests:


```
(py3-funannotate) jon@Jons-MacBook-Pro:~$ funannotate test -t compare --cpus 2
#########################################################
Running `funannotate compare` unit testing
CMD: funannotate compare -i Genome_one.gbk Genome_two.gbk Genome_three.gbk -o compare --cpus 2 --ml_model LG+G4 --outgroup botrytis_cinerea.dikarya
#########################################################
-------------------------------------------------------
[Apr 10 07:05 PM]: OS: MacOSX 10.16, 8 cores, ~ 17 GB RAM. Python: 3.7.12
[Apr 10 07:05 PM]: Running 1.8.14
[Apr 10 07:05 PM]: Now parsing 3 genomes
[Apr 10 07:05 PM]: working on Genome one
[Apr 10 07:05 PM]: working on Genome two
[Apr 10 07:05 PM]: working on Genome three
[Apr 10 07:05 PM]: No secondary metabolite annotations found
[Apr 10 07:05 PM]: Summarizing PFAM domain results
[Apr 10 07:06 PM]: Summarizing InterProScan results
[Apr 10 07:06 PM]: Loading InterPro descriptions
[Apr 10 07:06 PM]: Summarizing MEROPS protease results
[Apr 10 07:06 PM]: found 4 MEROPS familes
[Apr 10 07:06 PM]: Summarizing CAZyme results
[Apr 10 07:06 PM]: found 5 CAZy familes
[Apr 10 07:06 PM]: Summarizing COG results
[Apr 10 07:06 PM]: Summarizing secreted protein results
[Apr 10 07:06 PM]: Summarizing fungal transcription factors
[Apr 10 07:06 PM]: Running GO enrichment for each genome
  WARNING: skipping Genome_one.txt as no GO terms
[Apr 10 07:06 PM]: Running orthologous clustering tool, ProteinOrtho.  This may take awhile...
[Apr 10 07:06 PM]: Compiling all annotations for each genome
[Apr 10 07:06 PM]: Inferring phylogeny using iqtree
[Apr 10 07:06 PM]: Found 1 single copy BUSCO orthologs, will use all to infer phylogeny
[Apr 10 07:06 PM]: Compressing results to output file: compare.tar.gz
[Apr 10 07:06 PM]: Funannotate compare completed successfully!
#########################################################
SUCCESS: `funannotate compare` test complete.
#########################################################

```

**Comment by nextgenusfs** [comment]
Okay, I downloaded your test files -- they don't have enough annotation which is why it is failing. Looks like perhaps `funannotate annotate` was not run on these particular test cases? You can use the test cases from the internal tests if that is useful, they are located here: https://osf.io/7s9xh/download?version=1

**Comment by nextgenusfs** [comment]
> The tests for funannotate predict pass with latest code (though they no longer with 1.8.13)

Yes this would be expected I think because Augustus v3.5 is not compatible.

**Comment by nextgenusfs** [comment]
@abretaud new release is tagged (v1.8.15), let me know if any other problems/issues that need to be addressed. Hope you can get it working on galaxy again.

**Comment by abretaud** [comment]
Super cool, thanks :tada: 
I'll let you know how it goes in galaxy

**Comment by abretaud** [comment]
(it goes well in galaxy, https://github.com/galaxyproject/tools-iuc/pull/4617)
