### ISSUE TITLE
Traceback (most recent call last):   File "/home/hassan/miniconda3/envs/funannotate/bin/funannotate", line 8, in <module>     sys.exit(main())   File "/home/hassan/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/funannotate.py", line 716, in main     mod.main(arguments)   File "/home/hassan/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/update.py", line 2485, in main     transcripts=allGFF3, previous=existingStats)   File "/home/hassan/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/library.py", line 2622, in annotation_summary     for line in execute(cmd):   File "/home/hassan/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/library.py", line 555, in execute     raise subprocess.CalledProcessError(return_code, cmd) subprocess.CalledProcessError: Command '['bedtools', 'intersect', '-a', 'tmp.exon.4182799.bed', '-u', '-f', '0.9', '-s', '-b', '../prediction01/update_misc/transcript.alignments.gff3']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by hassantarabai** [nextgenusfs/funannotate#887]
Hello,

I am having a new error when running funannotate update, The workflow seems to run normally but generate an error when reaching the final step in converting to genebank format and collecting annotation files.

Here is the generated error " 

Traceback (most recent call last):
  File "/home/miniconda3/envs/funannotate/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/update.py", line 2485, in main
    transcripts=allGFF3, previous=existingStats)
  File "/home/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/library.py", line 2622, in annotation_summary
    for line in execute(cmd):
  File "/home/miniconda3/envs/funannotate/lib/python3.7/site-packages/funannotate/library.py", line 555, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '['bedtools', 'intersect', '-a', 'tmp.exon.4182799.bed', '-u', '-f', '0.9', '-s', '-b', '../prediction01/update_misc/transcript.alignments.gff3']' returned non-zero exit status 1."

Anybody faced this error ?

**Comment by hyphaltip** [comment]
have you run `bedtools intersect` on its own?

**Comment by hassantarabai** [comment]
@hyphaltip 

Bedtools intersect indicate "scaffold_11	15750302	15750296	FUN_021423-T1.exon1	.	-" as the error.

Removing it from the file solve the error but am not sure how the error was generated.
