### ISSUE TITLE
Funannotate fails to retrieve results from BUSCO

### ISSUE THREAD

**Issue by lalalagartija** [nextgenusfs/funannotate#894]
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**
annotations.busco.txt is empty wheter I run funannotate annotate after update or in a blank folder giving the fasta and gff. 

**What command did you issue?**
`
/home/oar-jobs/tools/src/singularity/bin/singularity exec -B ${wdir}  funannotate_latest.sif 'funannotate' annotate \
 --gff Acast_HiCseq_annot/update_results/Acanthamoeba_castellanii_Neff.gff3 \
 --fasta Acanthamoeba_castellanii_HiC-Seq.fasta --species "Acanthamoeba castellanii" --strain Neff \
 -o Acast_HiCseq_fun_annotate --cpus ${SLURM_CPUS_PER_TASK}  \
 --iprscan Acanthamoeba_castellanii_HiC-Seq.update.ipscan.xml \
 --busco_db eukaryota -d ./databases
`

**Logfiles**
`
[Apr 05 04:27 PM]: Annotating proteins with BUSCO eukaryota models
-------------------------------------------------------
Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/annotate.py", line 997, in main
    lib.runBUSCO(Proteins, buscoDB, args.cpus, os.path.join(
  File "/venv/lib/python3.8/site-packages/funannotate/library.py", line 5460, in runBUSCO
    with open(os.path.join(tmpdir, 'run_busco', 'full_table_busco.tsv'), 'r') as busco:
FileNotFoundError: [Errno 2] No such file or directory: 'Acast_HiCseq_fun_annotate/annotate_misc/run_busco/full_table_busco.tsv'
`

**OS/Install Information**
 -  output of `funannotate check --show-versions`
 `~/Funannotate_annot_Acast_HiCseq$ /home/oar-jobs/tools/src/singularity/bin/singularity exec -B $wdir -B ${wdir}/signalp-5.0b/bin -B /home/oar-jobs/Tools/conda/bin/  /home/oar-jobs/Tools/funannotate_latest.sif 'funannotate'  check --show-versions 
-------------------------------------------------------
Checking dependencies for 1.8.14
-------------------------------------------------------
You are running Python v 3.8.12. Now checking python packages...
biopython: 1.80
goatools: 1.2.3
matplotlib: 3.6.3
natsort: 8.2.0
numpy: 1.22.4
pandas: 1.5.3
psutil: 5.9.4
requests: 2.28.2
scikit-learn: 1.1.1
scipy: 1.5.3
seaborn: 0.12.2
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
local::lib: 2.000024
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/opt/databases
$PASAHOME=/venv/opt/pasa-2.4.1
$TRINITYHOME=/venv/opt/trinity-2.8.5
$EVM_HOME=/venv/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/usr/share/augustus/config
$GENEMARK_PATH=gmes_linux_64_4
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
/home/oar-jobs/rigou/Tools/conda/bin/java: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory
        ERROR: pslDnaFiler found but error running: pslCDnaFilter: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.2
bamtools: bamtools 2.5.2
bedtools: bedtools v2.30.0
blat: BLAT v35
diamond: 2.0.15
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: 36.3.8g
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.515 (2023/Jan/15)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.24-r1122
pigz: 2.6
proteinortho: 6.0.16
salmon: salmon 0.14.1
samtools: samtools 1.12
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 40
tbl2asn: 25.8
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
        ERROR: emapper.py not installed
        ERROR: gmes_petap.pl not installed
        ERROR: pslCDnaFilter not installed
        ERROR: signalp not installed
        ERROR: trimmomatic not installed
`

**Comment by alephreish** [comment]
Having the same issue under conda, test.py fails as well:

```
$ FUNANNOTATE_DB=analysis/funannotate/data python $CONDA_PREFIX/lib/python3.8/site-packages/funannotate/test.py -t busco
#########################################################
Running `funannotate predict` BUSCO-mediated training unit testing
CMD: funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate --cpus 2 --species Awesome busco
#########################################################
-------------------------------------------------------
[May 14 10:34 AM]: OS: Ubuntu 20.04, 64 cores, ~ 264 GB RAM. Python: 3.8.15
[May 14 10:34 AM]: Running funannotate v1.8.15
[May 14 10:34 AM]: Can't find Repeat Database at analysis/funannotate/data/repeats.dmnd, you may need to re-run funannotate setup
#########################################################
Traceback (most recent call last):
  File "...lib/python3.8/site-packages/funannotate/test.py", line 417, in <module>
    main(sys.argv[1:])
  File "...lib/python3.8/site-packages/funannotate/test.py", line 407, in main
    runBuscoTest(args)
  File "...lib/python3.8/site-packages/funannotate/test.py", line 200, in runBuscoTest
    assert 1500 <= countGFFgenes(os.path.join(
  File "...lib/python3.8/site-packages/funannotate/test.py", line 45, in countGFFgenes
    with open(input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test-busco_22dad601-49fc-4ccd-b009-58f12ecd6291/annotate/predict_results/Awesome_busco.gff3'
```

**Comment by alephreish** [comment]
I did not attempt much debugging, the workaround that I found was to pre-calculate the busco step with `funannotate-BUSCO2.py`:

```
mkdir -p funannotate_results_path/annotate_misc
$CONDA_PREFIX/lib/python*/site-packages/funannotate/aux_scripts/funannotate-BUSCO2.py \
    -i path_to_proteins.faa -m proteins -l funannotate_data_direcotry/lineage -o busco -c 10 -f
mv run_busco funannotate_results_path/annotate_misc/
```
