### ISSUE TITLE
KeyError: 'antismash_generation'

### ISSUE THREAD

**Issue by JWDebler** [nextgenusfs/funannotate#910]
**Are you using the latest release?**
1.8.15 via conda

**What command did you issue?**
funannotate remote -i funannotate_output -m antismash -e my.email@uni.edu

**Logfiles**
funannotate-remote.log
```
[05/04/23 00:18:33]: /home/ubuntu/mambaforge/envs/funannotate/bin/funannotate remote -i funannotate_output -m antismash -e XXX
[05/04/23 00:18:34]: OS: Ubuntu 18.04, 16 cores, ~ 66 GB RAM. Python: 3.8.15
[05/04/23 00:18:34]: Running 1.8.15
[05/04/23 00:18:34]: Output directory funannotate_output already exists, will use any existing data.  If this is not what you want, exit, and provide a unique name for output folder
[05/04/23 00:18:34]: Parsing input files
[05/04/23 00:18:34]: Generating files from funannotate_output/predict_results/Ascochyta_rabiei.tbl
```
That's all that is in that logfile

**OS/Install Information**
 OS: Ubuntu 18.04, 16 cores, ~ 66 GB RAM. Python: 3.8.15

**Crashes with this message**
```
[May 04 12:18 AM]: Parsing input files
Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/mambaforge/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/ubuntu/mambaforge/envs/funannotate/lib/python3.8/site-packages/funannotate/remote.py", line 243, in main
    as_vers = version.json()['antismash_generation']
KeyError: 'antismash_generation'
```

**Comment by nextgenusfs** [comment]
If you are on Linux I'd recommend installing antiSMASH locally. Not sure what error is off top of my head, quite possible the web service changes it's API.

**Comment by vappiah** [comment]
Hello @nextgenusfs 
I have a similar issue. Perhaps if you can give the exact antismash command being used by funnannotate, then we can run that using a locally installed one.
