### ISSUE TITLE
TypeError: list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by Danhfg** [nextgenusfs/funannotate#917]
**Are you using the latest release?**
yes ![image](https://github.com/nextgenusfs/funannotate/assets/17724218/8e684835-501d-4002-86f6-4535df51fe92)

**Describe the bug**
I'm getting the error TypeError: list indices must be integers or slices, not NoneType.

**What command did you issue?**
docker exec 5998245a4a32 funannotate annotate -i *************************/fun/  -o ****************************/output --cpus 24 --eggnog  *******************************/result.emapper.genepred.gff --busco_db actinopterygii --force
**Logfiles**
- [May 24 08:32 PM]: OS: Debian GNU/Linux 10, 24 cores, ~ 132 GB RAM. Python: 3.8.12
[May 24 08:32 PM]: Running 1.8.15
[May 24 08:32 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[May 24 08:32 PM]: Found existing output directory *****************/fun. Warning, will re-use any intermediate files found.
[May 24 08:32 PM]: Parsing input files
[May 24 08:32 PM]: Existing tbl found: **********************/*.tbl
 [May 24 08:39 PM]: Adding Functional Annotation to Brachyplatystoma filamentosum, NCBI accession: None
[May 24 08:39 PM]: Annotation consists of: 61,553 gene models
[May 24 08:39 PM]: 59,412 protein records loaded
[May 24 08:39 PM]: Existing Pfam-A results found: **********************/annotations.pfam.txt
[May 24 08:39 PM]: 28,733 annotations added
[May 24 08:39 PM]: Running Diamond blastp search of UniProt DB version 2023_01
[May 24 08:39 PM]: 8,664 valid gene/product annotations from 11,169 total
[May 24 08:39 PM]: Existing Eggnog-mapper results found: *************************/eggnog.emapper.annotations
[May 24 08:39 PM]: Parsing EggNog Annotations
[May 24 08:39 PM]: EggNog version parsed as None
-Traceback (most recent call last):
  File "/venv/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/venv/lib/python3.8/site-packages/funannotate/annotate.py", line 1055, in main
    EggNog = parseEggNoggMapper(eggnog_result, eggnog_out, GeneProducts)
  File "/venv/lib/python3.8/site-packages/funannotate/annotate.py", line 338, in parseEggNoggMapper
    ID = cols[IDi]
TypeError: list indices must be integers or slices, not NoneType

**OS/Install Information**

- Checking dependencies for 1.8.15

You are running Python v 3.8.12. Now checking python packages...
biopython: 1.81
goatools: 1.2.3
matplotlib: 3.7.1
natsort: 8.3.1
numpy: 1.22.4
pandas: 2.0.0
psutil: 5.9.4
requests: 2.28.2
scikit-learn: 0.24.2
scipy: 1.5.3
seaborn: 0.12.2
All 11 python packages installed

You are running Perl v b'5.026002'. Now checking perl modules...
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.855
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
local::lib: 2.000024
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/opt/databases
$PASAHOME=/venv/opt/pasa-2.4.1
$TRINITYHOME=/venv/opt/trinity-2.8.5
$EVM_HOME=/venv/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/usr/share/augustus/config
        ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir

Checking external dependencies...
        ERROR: pslDnaFiler found but error running: pslCDnaFilter: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.2
bamtools: bamtools 2.5.2
bedtools: bedtools v2.30.0
blat: BLAT v35
diamond: 2.1.6
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: 36.3.8g
glimmerhmm: 3.0.4
gmap: 2017-11-15
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.8-internal
kallisto: 0.46.1
mafft: v7.520 (2023/Mar/22)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.24-r1122
pigz: 2.6
proteinortho: 6.0.16
salmon: salmon 0.14.1
samtools: samtools 1.12
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.9 (July 2021)
tantan: tantan 40
tbl2asn: 25.8
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: emapper.py not installed
        ERROR: gmes_petap.pl not installed
        ERROR: pslCDnaFilter not installed
        ERROR: signalp not installed

**Comment by hyphaltip** [comment]
It looks like eggnog version isn't mapping to what funannotate is expecting. Can you post a snippet of the file you are providing?

**Comment by Danhfg** [comment]
##gff-version 3
    ## created with emapper-2.1.10
    scaffold1       eggNOG-mapper   CDS     1072    1467    95.1    +       .       ID=scaffold1_80;em_target=7994.ENSAMXP00000014982;em_score=95.1;em_evalue=4.78e-15;em_tcov=15.5;em_searcher=diamond
    scaffold1       eggNOG-mapper   CDS     1781    1882    62.4    +       .       ID=scaffold1_81;em_target=7994.ENSAMXP00000014982;em_score=62.4;em_evalue=6.36e-05;em_tcov=5.6;em_searcher=diamond 
    .............

**Comment by nextgenusfs** [comment]
The `--eggnog` argument is expecting the tab delimited eggnog annotations file not GFF3.
