### ISSUE TITLE
the value of 'augustus' is set as 'pasa' in the log of predict

### ISSUE THREAD

**Issue by sqwwww** [nextgenusfs/funannotate#922]
hi, I'm confused about the condition here. in the log of funannotate predict, I saw that the the value of 'augustus' is set as 'pasa', while it was set as 'busco' in many other people's logs. I checked many tutorial and didn't find the explanation, could you please help me to explain it?

you can see there is a line in my log:

> [05/31/23 11:32:53]: {'augustus': 'pasa', 'genemark': 'selftraining', 'snap': 'pasa', 'glimmerhmm': 'pasa'}

where many other people(other issues in the web) showed that:

> {'augustus': 'busco', 'snap': 'busco', 'glimmerhmm': 'busco'}

the whole log I got is :
> [05/31/23 11:32:42]:funannotate predict -i MyAssembly.fa -o fun --species Dun dac --cpus 16 --max_intronlen 500000 --busco_db actinopterygii --organism other --protein_alignments aln_Danio_rerio.gff --repeats2evm --force
> 
> [05/31/23 11:32:42]: OS: CentOS Linux 7, 88 cores, ~ 6241 GB RAM. Python: 3.8.15
> [05/31/23 11:32:42]: Running funannotate v1.8.15
> [05/31/23 11:32:42]: GeneMark path: /home/tools2/gmes_linux_64_4
> [05/31/23 11:32:47]: Full path to gmes_petap.pl: /home/tools2/gmes_linux_64_4/gmes_petap.pl
> [05/31/23 11:32:47]: GeneMark appears to be functional? True
> [05/31/23 11:32:51]: exonerate version=exonerate 2.4.0 path=/home/miniconda3/envs/mamba/envs/fun/bin/exonerate
> [05/31/23 11:32:51]: diamond version=2.1.6 path=/home/miniconda3/envs/mamba/envs/fun/bin/diamond
> [05/31/23 11:32:51]: tbl2asn version=25.8 path=/home/miniconda3/envs/mamba/envs/fun/bin/tbl2asn
> [05/31/23 11:32:51]: bedtools version=bedtools v2.31.0 path=/home/miniconda3/envs/mamba/envs/fun/bin/bedtools
> [05/31/23 11:32:51]: augustus version=3.5.0 path=/home/miniconda3/envs/mamba/envs/fun/bin/augustus
> [05/31/23 11:32:51]: etraining version=NA path=/home/miniconda3/envs/mamba/envs/fun/bin/etraining
> [05/31/23 11:32:51]: tRNAscan-SE version=2.0.11 (Oct 2022) path=/home/miniconda3/envs/mamba/envs/fun/bin/tRNAscan-SE
> [05/31/23 11:32:51]: bam2hints version=NA path=/home/miniconda3/envs/mamba/envs/fun/bin/bam2hints
> [05/31/23 11:32:51]: minimap2 version=2.26-r1175 path=/home/miniconda3/envs/mamba/envs/fun/bin/minimap2
> [05/31/23 11:32:51]: $AUGUSTUS_CONFIG_PATH=/home/miniconda3/envs/mamba/envs/fun/config/
> [05/31/23 11:32:51]: Found training files, will re-use these files:
>   --rna_bam fun/training/funannotate_train.coordSorted.bam
>   --pasa_gff fun/training/funannotate_train.pasa.gff3
>   --stringtie fun/training/funannotate_train.stringtie.gtf
>   --transcript_alignments fun/training/funannotate_train.transcripts.gff3
> [05/31/23 11:32:53]: {'augustus': 1, 'hiq': 2, 'genemark': 1, 'pasa': 6, 'codingquarry': 0, 'snap': 1, 'glimmerhmm': 1, 'proteins': 1, 'transcripts': 1}
> [05/31/23 11:32:53]: Skipping CodingQuarry as --organism=other. Pass a weight larger than 0 to run CQ, ie --weights codingquarry:1
> [05/31/23 11:32:53]: {'augustus': 'pasa', 'genemark': 'selftraining', 'snap': 'pasa', 'glimmerhmm': 'pasa'}
> [05/31/23 11:32:53]: Parsed training data, run ab-initio gene predictors as follows:
> [05/31/23 11:32:53]: augustus --species=anidulans --proteinprofile=/home/miniconda3/envs/mamba/envs/fun/lib/python3.8/site-packages/funannotate/config/EOG092C0B3U.prfl /home/miniconda3/envs/mamba/envs/fun/lib/python3.8/site-packages/funannotate/config/busco_test.fa
> [05/31/23 11:32:56]: perl /home/miniconda3/envs/mamba/envs/fun/opt/evidencemodeler-1.1.1/EvmUtils/gff3_gene_prediction_file_validator.pl /home/06.genomeAnno/02.fun/fun/predict_misc/pasa_predictions.gff3
> [05/31/23 11:33:04]: {'augustus': 1, 'hiq': 2, 'genemark': 1, 'pasa': 6, 'codingquarry': 0, 'snap': 1, 'glimmerhmm': 1, 'proteins': 1, 'transcripts': 1}
> [05/31/23 11:35:12]: Loading genome assembly and parsing soft-masked repetitive sequences
> [05/31/23 11:35:27]: Genome loaded: 161 scaffolds; 670,790,457 bp; 42.37% repeats masked
> [05/31/23 11:35:34]: Parsed 360,939 transcript alignments from: fun/training/funannotate_train.transcripts.gff3
> [05/31/23 11:35:34]: Creating transcript EVM alignments and Augustus transcripts hintsfile
> [05/31/23 11:35:44]: Existing RNA-seq BAM hints found: fun/predict_misc/hints.BAM.gff
> [05/31/23 11:35:44]: Loading protein alignments /home/06.genomeAnno/05.miniprot/aln_Danio_rerio.gff
> [05/31/23 11:36:23]: join_mult_hints.pl
> [05/31/23 11:36:39]: Running GeneMark-ES on assembly
> [05/31/23 11:36:39]: /home/tools2/gmes_linux_64_4/gmes_petap.pl --ES --max_intron 500000 --soft_mask 2000 --cores 16 --sequence
>  /home/06.genomeAnno/02.fun/fun/predict_misc/genome.softmasked.fa

**Comment by hyphaltip** [comment]
this indicates where the training set for training the gene predictor(s) comes from. 

This would be set to pasa because you had done a `train` step before running predict: based on this information in your log:
```
[05/31/23 11:32:51]: Found training files, will re-use these files:
--rna_bam fun/training/funannotate_train.coordSorted.bam
--pasa_gff fun/training/funannotate_train.pasa.gff3
--stringtie fun/training/funannotate_train.stringtie.gtf
```

**Comment by sqwwww** [comment]
hi sir,
thanks for your quick answer, it helps me a lot! I have another problem which is similar to the issue #920 , probably I have more details here. 
you can see that there is a line in my  funannotate-predict.log, it set the  --species=anidulans for augustus, which was not the species I set.

> augustus --species=anidulans --proteinprofile=/home/miniconda3/envs/mamba/envs/fun/lib/python3.8/site-packages/funannotate/config/EOG092C0B3U.prfl /home/miniconda3/envs/mamba/envs/fun/lib/python3.8/site-packages/funannotate/config/busco_test.fa
then I checked the ./fun/logfiles/augustus_training.log, I found it have trained my interested species in augustus. and 
 I can found my species under `./fun/predict_misc/ab_initio_parameters/augustus/species/`. Unfortunately, it failed because of a small error. I fixed the environment by `conda install -c anaconda gsl`.
the augustus_training.log:
> Will create parameters for a EUKARYOTIC species!
> creating directory /home/06.genomeAnno/02.fun/fun/predict_misc/ab_initio_parameters/augustus/species/dun_dac/ ...
> creating /home/06.genomeAnno/02.fun/fun/predict_misc/ab_initio_parameters/augustus/species/dun_dac/dun_dac_parameters.cfg ...
> creating /home/06.genomeAnno/02.fun/fun/predict_misc/ab_initio_parameters/augustus/species/dun_dac/dun_dac_weightmatrix.txt ...
> creating /home/06.genomeAnno/02.fun/fun/predict_misc/ab_initio_parameters/augustus/species/dun_dac/dun_dac_metapars.cfg ...
> The necessary files for training dun_dac have been created.
> Now, either run etraining or optimize_parameters.pl with --species=dun_dac.
> etraining quickly estimates the parameters from a file with training genes.
> optimize_augustus.pl alternates running etraining and augustus to find optimal metaparameters.
> 
> etraining: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
the contents under fun/predict_misc/ab_initio_parameters/augustus/species/
```
ls ./fun/predict_misc/ab_initio_parameters/augustus/species/
anidulans  dun_dac  generic
```

then I rerun the funannotate in another directory (fun2, I soft linked the `training` directory under the fun2, as I didn't want to stop the gmes running under the original `fun` directory) , and this time augustus only trained anidulans, and no training for my interested species, and there was no ./fun2/logfiles/augustus_training.log.
the contents under ./fun2/predict_misc/ab_initio_parameters/augustus/species:
```
ls ./fun2/predict_misc/ab_initio_parameters/augustus/species/
anidulans  generic
```
my command :
```
funannotate predict -i MyAssembly.fa -o fun2 \
    --species "Dun dac" \
    --cpus 8 \
    --max_intronlen 500000 --busco_db actinopterygii --organism other \
    --protein_alignments /home/06.genomeAnno/05.miniprot/aln_Danio_rerio.gff \
    --repeats2evm --force
```

I think I can try to run augustus outside of funannotate, and manually set the species as my target. could you please give me some suggestion about the situation?

**Comment by sqwwww** [comment]
this is an update, It seems that funannotate solve the problem itself. It continue to run augustus from where the program have gave an error after finishing the gmes. Now, every thing goes smoothly.

**Comment by sqwwww** [comment]
hi sir,
I met another error in EVM running, which said "IndexError: list index out of range". Here is my log:

> -------------------------------------------------------
> [May 31 11:32 AM]: OS: CentOS Linux 7, 88 cores, ~ 6241 GB RAM. Python: 3.8.15
> [May 31 11:32 AM]: Running funannotate v1.8.15
> [May 31 11:32 AM]: Found training files, will re-use these files:
>   --rna_bam fun/training/funannotate_train.coordSorted.bam
>   --pasa_gff fun/training/funannotate_train.pasa.gff3
>   --stringtie fun/training/funannotate_train.stringtie.gtf
>   --transcript_alignments fun/training/funannotate_train.transcripts.gff3
> [May 31 11:32 AM]: Skipping CodingQuarry as --organism=other. Pass a weight larger than 0 to run CQ, ie --weights codingquarry:1
> [May 31 11:32 AM]: Parsed training data, run ab-initio gene predictors as follows:
>   [4mProgram      Training-Method[0m
>   augustus     pasa           
>   genemark     selftraining   
>   glimmerhmm   pasa           
>   snap         pasa           
> [May 31 11:35 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
> [May 31 11:35 AM]: Genome loaded: 161 scaffolds; 670,790,457 bp; 42.37% repeats masked
> [May 31 11:35 AM]: Parsed 360,939 transcript alignments from: fun/training/funannotate_train.transcripts.gff3
> [May 31 11:35 AM]: Creating transcript EVM alignments and Augustus transcripts hintsfile
> [May 31 11:35 AM]: Existing RNA-seq BAM hints found: fun/predict_misc/hints.BAM.gff
> [May 31 11:35 AM]: Loading protein alignments /home/06.genomeAnno/05.miniprot/aln_Danio_rerio.gff
> [May 31 11:36 AM]: Running GeneMark-ES on assembly
> [Jun 07 01:12 PM]: 57,909 predictions from GeneMark
> [Jun 07 01:12 PM]: Filtering PASA data for suitable training set
> [Jun 07 01:14 PM]: 5,779 of 44,806 models pass training parameters
> [Jun 07 01:14 PM]: Training Augustus using PASA gene models
> [Jun 07 01:16 PM]: Augustus initial training results:
>   [4mFeature       Specificity   Sensitivity[0m
>   nucleotides   91.6%         90.3%      
>   exons         77.0%         76.2%      
>   genes         15.9%         15.2%      
> [Jun 07 01:16 PM]: Accuracy seems low, you can try to improve by passing the --optimize_augustus option.
> [Jun 07 01:16 PM]: Running Augustus gene prediction using Dun_dac parameters
> [Jun 07 02:28 PM]: 36,128 predictions from Augustus
> [Jun 07 02:28 PM]: Pulling out high quality Augustus predictions
> [Jun 07 02:28 PM]: Found 10,415 high quality predictions from Augustus (>90% exon evidence)
> [Jun 07 02:28 PM]: Running SNAP gene prediction, using training data: fun/predict_misc/final_training_models.gff3
> [Jun 07 03:04 PM]: 101,855 predictions from SNAP
> [Jun 07 03:04 PM]: Running GlimmerHMM gene prediction, using training data: fun/predict_misc/final_training_models.gff3
> [Jun 07 04:25 PM]: 111,590 predictions from GlimmerHMM
> [Jun 07 04:26 PM]: Summary of gene models passed to EVM (weights):
> [Jun 07 04:26 PM]: EVM: partitioning input to ~ 35 genes per partition using min 1500 bp interval
> Traceback (most recent call last):
>   File "/home/miniconda3/envs/mamba/envs/fun/lib/python3.8/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 480, in <module>
>     cmdinfo = create_partitions(args.fasta, args.genes, partitions,
>   File "/home/miniconda3/envs/mamba/envs/fun/lib/python3.8/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 138, in create_partitions
>     interProteins = exonerate_blocks_to_interlap(proteins)
>   File "/home/miniconda3/envs/mamba/envs/fun/lib/python3.8/site-packages/funannotate/aux_scripts/funannotate-runEVM.py", line 46, in exonerate_blocks_to_interlap
>     coords.append(int(cols[3]))
> IndexError: list index out of range
>   [4mSource         Weight   Count [0m
>   Augustus       1        25713 
>   Augustus HiQ   2        10415 
>   GeneMark       1        57909 
>   GlimmerHMM     1        111590
>   pasa           6        44806 
>   snap           1        101855
>   Total          -        352288
> [Jun 07 04:27 PM]: Evidence modeler has failed, exiting
> Traceback (most recent call last):
>   File "/home/miniconda3/envs/mamba/envs/fun/bin/funannotate", line 10, in <module>
>     sys.exit(main())
>   File "/home/miniconda3/envs/mamba/envs/fun/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
>     mod.main(arguments)
>   File "/home/miniconda3/envs/mamba/envs/fun/lib/python3.8/site-packages/funannotate/predict.py", line 2624, in main
>     os.remove(EVM_out)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/06.genomeAnno/02.fun/fun/predict_misc/evm.round1.gff3'
> /var/spool/slurm/d/job1350207/slurm_script: line 46: 112365 Bus error               (core dumped) funannotate predict -i MyAssembly.fa -o fun --species "Dun dac" --cpus 16 --max_intronlen 500000 --busco_db actinopterygii --organism other --protein_alignments /home/06.genomeAnno/05.miniprot/aln_Danio_rerio.gff --repeats2evm --force

I have no idea why the error happened here, could you please give me some suggestion?

**Comment by hyphaltip** [comment]
potentially out of memory error - does the`funannotate test`  succeed for the predict step on its own?
```
/var/spool/slurm/d/job1350207/slurm_script: line 46: 112365 Bus error (core dumped
```

**Comment by sqwwww** [comment]
hi hyphaltip,

yes, funannotate test succeed for the predict step on its own. 

I have figured it out.  It's a problem related with the format of protein alignment file. I used the gff generated by miniprot, and fed it to the --protein_alignments parameter,  and it failed in the file reading.
I tried to directly feed the protein fasta to the --protein_evidence, and it succeed.

here I have a more question when running the `funannotate update`.  I used mysql database in the pasa training, however in the log of `funannotate update`, it said "PASA database is SQLite", which confused me a lot. it's important because mutithreading is related with the database type(mysql database can be mutithreading).

I can find a  file called `fun/training/pasa/__pasa_Dun_dac_pasa_mysql_chkpts`, which convinces me that I have trained the data by mysql database.

and I find a line in `funannotate-update.log` said that PASA database is SQLite.

> [06/09/23 01:34:43]: PASA database is SQLite: Dun_dac_pasa

and here is my whole log of  `funannotate-update:

> [06/09/23 01:16:16]: /home/miniconda3/envs/mamba/envs/fun/bin/funannotate update -i fun --cpus 16 --species Dun dac --max_intronlen 500000
> 
> [06/09/23 01:16:16]: OS: CentOS Linux 7, 88 cores, ~ 6241 GB RAM. Python: 3.8.15
> [06/09/23 01:16:16]: Running 1.8.15
> [06/09/23 01:16:22]: fasta version=36.3.8g path=/home/miniconda3/envs/mamba/envs/fun/bin/fasta
> [06/09/23 01:16:22]: minimap2 version=2.26-r1175 path=/home/miniconda3/envs/mamba/envs/fun/bin/minimap2
> [06/09/23 01:16:22]: tbl2asn version=25.8 path=/home/miniconda3/envs/mamba/envs/fun/bin/tbl2asn
> [06/09/23 01:16:22]: hisat2 version=2.2.1 path=/home/miniconda3/envs/mamba/envs/fun/bin/hisat2
> [06/09/23 01:16:22]: hisat2-build version=NA path=/home/miniconda3/envs/mamba/envs/fun/bin/hisat2-build
> [06/09/23 01:16:22]: kallisto version=0.46.1 path=/home/miniconda3/envs/mamba/envs/fun/bin/kallisto
> [06/09/23 01:16:22]: Trinity version=2.8.5 path=/home/miniconda3/envs/mamba/envs/fun/bin/Trinity
> [06/09/23 01:16:22]: bedtools version=bedtools v2.31.0 path=/home/miniconda3/envs/mamba/envs/fun/bin/bedtools
> [06/09/23 01:16:22]: java version=11.0.13 path=/home/miniconda3/envs/mamba/envs/fun/bin/java
> [06/09/23 01:16:22]: /home/miniconda3/envs/mamba/envs/fun/opt/pasa-2.5.2/Launch_PASA_pipeline.pl version=NA path=/home/miniconda3/envs/mamba/envs/fun/opt/pasa-2.5.2/Launch_PASA_pipeline.pl
> [06/09/23 01:16:22]: /home/miniconda3/envs/mamba/envs/fun/opt/pasa-2.5.2/bin/seqclean version=NA path=/home/miniconda3/envs/mamba/envs/fun/opt/pasa-2.5.2/bin/seqclean
> [06/09/23 01:16:22]: trimmomatic version=0.39 path=/home/miniconda3/envs/mamba/envs/fun/bin/trimmomatic
> [06/09/23 01:16:22]: minimap2 version=2.26-r1175 path=/home/miniconda3/envs/mamba/envs/fun/bin/minimap2
> [06/09/23 01:16:22]: blat version=BLAT v37x1 path=/home/miniconda3/envs/mamba/envs/fun/bin/blat
> [06/09/23 01:16:22]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
> [06/09/23 01:16:22]: Found relevant files in fun/training, will re-use them:
> 	GFF3: fun/predict_results/Dun_dac.gff3
> 	Genome: fun/predict_results/Dun_dac.scaffolds.fa
> 	Forward reads: fun/training/left.fq.gz
> 	Reverse reads: fun/training/right.fq.gz
> 	Forward Q-trimmed reads: fun/training/trimmomatic/trimmed_left.fastq.gz
> 	Reverse Q-trimmed reads: fun/training/trimmomatic/trimmed_right.fastq.gz
> 	Forward normalized reads: fun/training/normalize/left.norm.fq
> 	Reverse normalized reads: fun/training/normalize/right.norm.fq
> 	Trinity results: fun/training/funannotate_train.trinity-GG.fasta
> 	PASA config file: fun/training/pasa/alignAssembly.txt
> 	BAM alignments: fun/training/funannotate_train.coordSorted.bam
> 	StringTie GTF: fun/training/funannotate_train.stringtie.gtf
> [06/09/23 01:17:28]: Reannotating Dun dac, NCBI accession: None
> [06/09/23 01:17:28]: Previous annotation consists of: 46,665 protein coding gene models and 2,581 non-coding gene models
> [06/09/23 01:17:28]: Existing annotation: locustag=FUN_ genenumber=49246
> [06/09/23 01:17:28]: Input reads: ('fun/training/left.fq.gz', 'fun/training/right.fq.gz', None)
> [06/09/23 01:17:28]: Quality trimmed reads: ('fun/training/trimmomatic/trimmed_left.fastq.gz', 'fun/training/trimmomatic/trimmed_right.fastq.gz', None)
> [06/09/23 01:17:28]: FASTQ headers seem compatible with Trinity
> [06/09/23 01:17:28]: Normalized reads: ('fun/training/normalize/left.norm.fq', 'fun/training/normalize/right.norm.fq', None)
> [06/09/23 01:17:28]: Long reads: (None, None, None)
> [06/09/23 01:17:28]: Long reads FASTA format: (None, None, None)
> [06/09/23 01:17:28]: Long SeqCleaned reads: (None, None, None)
> [06/09/23 01:17:32]: /home/miniconda3/envs/mamba/envs/fun/opt/pasa-2.5.2/bin/seqclean trinity.fasta -c 16
> [06/09/23 01:19:20]: seqclean running options: 
> seqclean trinity.fasta -c 16
>  Standard log file: seqcl_trinity.fasta.log
>  Error log file:    err_seqcl_trinity.fasta.log
>  Using 16 CPUs for cleaning
> -= Rebuilding trinity.fasta cdb index =-
>  Launching actual cleaning process:
>  psx -p 16  -n 1000  -i trinity.fasta -d cleaning -C '/home/06.genomeAnno/02.fun/trinity.fasta:ANLMS100:::11:0' -c '/home/miniconda3/envs/mamba/envs/fun/opt/pasa-2.5.2/bin/seqclean.psx'
> Collecting cleaning reports
> 
> **************************************************1
> Sequences analyzed:    458494
> -----------------------------------
>                    valid:    458316  (15688 trimmed)
>                  trashed:       178
> **************************************************1
> ----= Trashing summary =------1
>                 by 'dust':      123
>               by 'shortq':       55
> ------------------------------1
> Output file containing only valid and trimmed sequences: trinity.fasta.clean
> For trimming and trashing details see cleaning report  : trinity.fasta.cln
> --------------------------------------------------1
> seqclean (trinity.fasta) finished on machine x86_64-conda-linux-gnu
>  in /home/06.genomeAnno/02.fun, without a detectable error.
> 
> [06/09/23 01:19:21]: minimap2 -ax splice -t 16 --cs -u b -G 500000 fun/update_misc/genome.fa fun/update_misc/trinity.fasta.clean | samtools sort --reference fun/update_misc/genome.fa -@ 4 -o fun/update_misc/trinity.alignments.bam -
> [06/09/23 01:32:59]: Converting transcript alignments to GFF3 format
> [06/09/23 01:33:54]: Converting Trinity transcript alignments to GFF3 format
> [06/09/23 01:34:43]: PASA database is SQLite: Dun_dac_pasa
> [06/09/23 01:34:43]: /home/miniconda3/envs/mamba/envs/fun/bin/cdbfasta fun/update_misc/genome.fa
> [06/09/23 01:34:44]: 161 entries from file fun/update_misc/genome.fa were indexed in file fun/update_misc/genome.fa.cidx
> 
> [06/09/23 01:34:44]: Running PASA annotation comparison step 1
> [06/09/23 01:34:44]: /home/miniconda3/envs/mamba/envs/fun/opt/pasa-2.5.2/Launch_PASA_pipeline.pl -c /home/06.genomeAnno/02.fun/fun/update_misc/pasa/annotCompare.txt -g /home/06.genomeAnno/02.fun/fun/update_misc/genome.fa -t /home/06.genomeAnno/02.fun/fun/update_misc/trinity.fasta.clean -A -L --CPU 16 --annots /home/06.genomeAnno/02.fun/fun/update_misc/genome.gff3

Thanks very much!

**Comment by hyphaltip** [comment]
I think you need to pass this option to force MySQL/MariaDB

--pasa_db mysql
