### ISSUE TITLE
eggnog-mapper version parsing broken for 2.11.x versions

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#927]
**Are you using the latest release?**
1.8.15

**Describe the bug**
eggnog-mapper version returns 2.11.1-CODE. This cannot be parsed with current regex in annotate.py 

https://github.com/nextgenusfs/funannotate/blob/23a7b5f228f4be3dd773a48361cb5a231186df7c/funannotate/annotate.py#L462

**What command did you issue?**
running eggnog-mapper 2.11.1 in the `funannotate annotate` step

**Logfiles**

```
[Jun 21 05:18 PM]: Running Eggnog-mapper
-------------------------------------------------------
Traceback (most recent call last):
  File "/opt/linux/rocky/8.x/x86_64/pkgs/funannotate/1.8/env/bin/funannotate", line 8, in <module>
    sys.exit(main())
  File "/opt/linux/centos/8.x/x86_64/pkgs/funannotate/1.8.15/env/lib/python3.8/site-packages/funannotate/funannotate.py", line 717, in main
    mod.main(arguments)
  File "/opt/linux/centos/8.x/x86_64/pkgs/funannotate/1.8.15/env/lib/python3.8/site-packages/funannotate/annotate.py", line 1033, in main
    if parse_version(get_emapper_version()) >= parse_version("2.1.0"):
  File "/opt/linux/centos/8.x/x86_64/pkgs/funannotate/1.8.15/env/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '2.1.11-d503d2c'
```

**Comment by hyphaltip** [comment]
Should be fixed with that commit based on my tests.
