### ISSUE TITLE
funannotate annotate: disappearing iprscan.xml and phobius problems

### ISSUE THREAD

**Issue by igwill** [nextgenusfs/funannotate#932]
Funannotate has been pretty smooth so far, with good outputs to help me along the way when this do get off-track. But these issues kind of baffle me. Any recommendations to get `funannotate annotate` to take in my InterProScan results and run Phobius correctly? Thank you.

**Are you using the latest release?**
funannotate v 1.8.15
interproscan 5.59_91.0 (run through `funannotate iprscan` letting funannoate find the input within predict_results)
phobius 1.01

**Describe the bug**
**1** - the InterProScan5 iprscan.xml file in annotate_misc/ is deleted each time `funannotate annotate` is run, leading to a file not found error. This doesn't seem to happen to any other annotate_misc/ files (when rerunning from failed attempts, funannotate nicely sees the old pieces even).
**2** - Phobius doesn't seem to work correctly within `annotate`, `remote`, or separately locally. But it is in PATH, and tries to run. (I know you all didn't make Phobius, but there isn't a github or much support over there it seems)

```
# funannotate command: /.../envs/funannotate/bin/funannotate annotate -i ECO5_noRNA_predict --cpus 16 --species O c-f --isolate ECO5 --iprscan /.../ECO5_noRNA_predict/annotate_misc/iprscan.xml --antismash /.../antismash/O_c-f_ECO5.gbk --signalp /.../signalp_out/prediction_results.txt

# stdout (not the funannotate-annotate.log):
## printing first line of iprscan.xml, make sure it is there: ##
<?xml version="1.0" encoding="UTF-8"?><protein-matches xmlns="http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5" interproscan-version="5.59-91.0"> # command was: head -1 "/home/igwill/funannotate/ECO5_pilotrun_noRNA/gene_prediction/ECO5_noRNA_predict/annotate_misc/iprscan.xml"
## Checking phobius is findable##
/home/igwill/.conda/envs/mamba/envs/funannotate/bin/phobius # command was: which phobius
[Jul 08 05:27 PM]: OS: Ubuntu 20.04, 64 cores, ~ 528 GB RAM. Python: 3.8.15
[Jul 08 05:27 PM]: Running 1.8.15
[Jul 08 05:27 PM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
[Jul 08 05:27 PM]: Found existing output directory ECO5_noRNA_predict. Warning, will re-use any intermediate files found.
[Jul 08 05:27 PM]: Parsing input files
[Jul 08 05:27 PM]: Existing tbl found: ECO5_noRNA_predict/predict_results/O_c-f_ECO5.tbl
[Jul 08 05:27 PM]: Adding Functional Annotation to O_c-f, NCBI accession: None
[Jul 08 05:27 PM]: Annotation consists of: 7,073 gene models
[Jul 08 05:27 PM]: 6,993 protein records loaded
[Jul 08 05:27 PM]: Existing Pfam-A results found: ECO5_noRNA_predict/annotate_misc/annotations.pfam.txt
[Jul 08 05:27 PM]: 8,664 annotations added
[Jul 08 05:27 PM]: Running Diamond blastp search of UniProt DB version 2023_02
[Jul 08 05:27 PM]: 761 valid gene/product annotations from 985 total
[Jul 08 05:27 PM]: Running Eggnog-mapper
[Jul 08 06:09 PM]: Parsing EggNog Annotations
[Jul 08 06:09 PM]: EggNog version parsed as 2.1.11
[Jul 08 06:09 PM]: 13,906  COG and EggNog annotations added
[Jul 08 06:09 PM]: Combining UniProt/EggNog gene and product names using Gene2Product version 1.91
[Jul 08 06:09 PM]: 2,469 gene name and product description annotations added
[Jul 08 06:09 PM]: Running Diamond blastp search of MEROPS version 12.0
[Jul 08 06:09 PM]: 247 annotations added
[Jul 08 06:09 PM]: Annotating CAZYmes using HMMer search of dbCAN version 11.0
[Jul 08 06:09 PM]: 229 annotations added
[Jul 08 06:09 PM]: Annotating proteins with BUSCO dikarya models
[Jul 08 06:12 PM]: 1,223 annotations added
[Jul 08 06:12 PM]: Skipping phobius predictions, try funannotate remote -m phobius
[Jul 08 06:12 PM]: Existing SignalP results found: ECO5_noRNA_predict/annotate_misc/signalp.results.txt
[Jul 08 06:12 PM]: 624 secretome and 0 transmembane annotations added
-------------------------------------------------------
Traceback (most recent call last):
  File "/home/igwill/.conda/envs/mamba/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/igwill/.conda/envs/mamba/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/home/igwill/.conda/envs/mamba/envs/funannotate/lib/python3.8/site-packages/funannotate/annotate.py", line 1373, in main
    shutil.copyfile(args.iprscan, IPRCombined)
  File "/home/igwill/.conda/envs/mamba/envs/funannotate/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/igwill/funannotate/ECO5_pilotrun_noRNA/gene_prediction/ECO5_noRNA_predict/annotate_misc/iprscan.xml'

```

**2b** - `funannotate remote -m phobius -i ECO5_noRNA_predict` leads to a command error like this for many proteins, but some pass without error, and some actually leave outputs:
```
[07/08/23 15:17:13]: CMD ERROR: perl /home/igwill/.conda/envs/mamba/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/phobius-remote.pl -f short --outfile FUN_001073-T1 FUN_001073-T1.fa
[07/08/23 15:17:13]: JobId: phobius-S20230708-201709-0890-66916018-p1m
QUEUED
Job 'phobius-S20230708-201709-0890-66916018-p1m' is still running at /home/igwill/.conda/envs/mamba/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/phobius-remote.pl line 189.

[07/08/23 15:17:13]: perl /home/igwill/.conda/envs/mamba/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/phobius-remote.pl  -f short --outfile FUN_004671-T1 FUN_004671-T1.fa
[07/08/23 15:17:13]: perl /home/igwill/.conda/envs/mamba/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/phobius-remote.pl -f short --outfile FUN_005709-T1 FUN_005709-T1.fa
[07/08/23 15:17:14]: perl /home/igwill/.conda/envs/mamba/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/phobius-remote.pl -f short --outfile FUN_003579-T1 FUN_003579-T1.fa
[07/08/23 15:17:16]: JobId: phobius-S20230708-201556-0136-28334179-p1m
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
RUNNING
FINISHED
Creating result file: FUN_000599-T1.out.txt
Creating result file: FUN_000599-T1.error.txt
Creating result file: FUN_000599-T1.sequence.txt
Creating result file: FUN_000599-T1.submission.params

[07/08/23 15:17:16]: CMD ERROR: perl /home/igwill/.conda/envs/mamba/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/phobius-remote.pl -f short --outfile FUN_001951-T1 FUN_001951-T1.fa
[07/08/23 15:17:16]: JobId: phobius-S20230708-201712-0509-87142650-p1m
QUEUED
Job 'phobius-S20230708-201712-0509-87142650-p1m' is still queued at /home/igwill/.conda/envs/mamba/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/phobius-remote.pl line 189.

```
Looking into the directory it made had some files, either just protein seqs or sometimes more e.g.:
```
ls "/.../phobius_2c47eb47-25b4-46ed-8aa3-ea784aefd00b/" | head
FUN_000002-T1.fa
FUN_000013-T1.error.txt
FUN_000013-T1.fa
FUN_000013-T1.phobius
FUN_000013-T1.submission.params
FUN_000015-T1.fa
FUN_000018-T1.fa
FUN_000019-T1.fa
FUN_000020-T1.fa
FUN_000021-T1.fa
```
Looking at FUN_000013-T1.error.txt gave a similar error as also seen below when running locally too:
`Use of uninitialized value $predstr in concatenation (.) or string at /nfs/public/ro/es_codon/appbin/linux-x86_64/phobius-1.01/phobius.pl line 250, <SOUT> line 18.`
But FUN_000013-T1.phobius did have something:
```
SEQENCE ID                     TM SP PREDICTION
FUN_000013-T1                   0  Y n169-177c182/183o
```

**2c** - Directly running local phobius required that I rename its decodeanhmm.64bit to decodeanhmm (replacing the original decodeanhmm, which I think was 32-bit) to fix a different error that fully prevented running. But then, I started getting a new error fairly often that was the same related to $predstr, e.g. part of the stdout:
```
//
ID   FUN_007000-T1
FT   DOMAIN        1    538       NON CYTOPLASMIC.
//
ID   FUN_007001-T1
FT   DOMAIN        1    331       NON CYTUse of uninitialized value $predstr in concatenation (.) or string at /home/igwill/.conda/envs/mamba/envs/funannotate/bin/phobius line 216, <SOUT> line 229498.
Use of uninitialized value $predstr in concatenation (.) or string at /home/igwill/.conda/envs/mamba/envs/funannotate/bin/phobius line 216, <SOUT> line 229516.
Use of uninitialized value $predstr in concatenation (.) or string at /home/igwill/.conda/envs/mamba/envs/funannotate/bin/phobius line 216, <SOUT> line 229561.

# or also with -short option
FUN_000175-T1                   1  0 o32-50i
FUN_000176-T1                   0  0 o
FUN_000177-T1                   0  0 o
FUN_00Use of uninitialized value $predstr in concatenation (.) or string at /home/igwill/.conda/envs/mamba/envs/funannotate/bin/phobius line 261, <SOUT> line 5629.
```

Local runs of Signalp6 and Antismash worked fine and don't seem to be causing any errors so far with `annotate`. Although, I thought `annotate `would be able to wrapper for SignalP since it is checked for in `funnannotate check`, but that didn't seem to work on it's own. My local run went just fine in the same funannotate conda env I've been using (ran like this `signalp6 -i proteins.fa/from/funannotate -org euk`).

**OS/Install Information**
```
-------------------------------------------------------
Checking dependencies for 1.8.15
-------------------------------------------------------
You are running Python v 3.8.15. Now checking python packages...
biopython: 1.76
goatools: 1.2.3
matplotlib: 3.4.3
natsort: 8.3.1
numpy: 1.24.3
pandas: 1.5.3
psutil: 5.7.0
requests: 2.31.0
scikit-learn: 1.2.2
scipy: 1.10.1
seaborn: 0.12.2
All 11 python packages installed


You are running Perl v b'5.032001'. Now checking perl modules...
Carp: 1.50
Clone: 0.46
DBD::SQLite: 1.72
DBD::mysql: 4.046
DBI: 1.643
DB_File: 1.858
Data::Dumper: 2.183
File::Basename: 2.85
File::Which: 1.24
Getopt::Long: 2.54
Hash::Merge: 0.302
JSON: 4.10
LWP::UserAgent: 6.67
Logger::Simple: 2.0
POSIX: 1.94
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.14
Tie::File: 1.06
URI::Escape: 5.17
YAML: 1.30
local::lib: 2.000029
threads: 2.25
threads::shared: 1.61
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/home/igwill/funannotate/databases/
$PASAHOME=/home/igwill/.conda/envs/mamba/envs/funannotate/opt/pasa-2.5.2
$TRINITY_HOME=/home/igwill/.conda/envs/mamba/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/igwill/.conda/envs/mamba/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/igwill/.conda/envs/mamba/envs/funannotate/config/
$GENEMARK_PATH=/home/igwill/funannotate/genemark/gmes_linux_64_4/
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.5.2
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.5.0
bamtools: bamtools 2.5.1
bedtools: bedtools v2.31.0
blat: BLAT v37x1
diamond: 2.1.7
emapper.py: 2.1.11
ete3: 3.1.2
exonerate: exonerate 2.4.0
fasta: 36.3.8g
glimmerhmm: 3.0.4
gmap: 2023-04-28
gmes_petap.pl: 4.71_lic
hisat2: 2.2.1
hmmscan: HMMER 3.3.2 (Nov 2020)
hmmsearch: HMMER 3.3.2 (Nov 2020)
java: 11.0.1
kallisto: 0.46.1
mafft: v7.520 (2023/Mar/22)
makeblastdb: makeblastdb 2.14.0+
minimap2: 2.26-r1175
pigz: 2.6
proteinortho: 6.2.3
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.16.1
signalp: 6.0
snap: 2006-07-28
stringtie: 2.2.1
tRNAscan-SE: 2.0.11 (Oct 2022)
tantan: tantan 40
tbl2asn: 25.8
tblastn: tblastn 2.14.0+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 37 external dependencies are installed
```

**Comment by igwill** [comment]
Also, just to show it, the actual funannotate log file did not have anything more insightful than the stdout. Here are the last lines of it:
```
INFO    BUSCO analysis done. Total running time: 152.9240529537201 seconds
INFO    Results written in /home/igwill/funannotate/ECO5_pilotrun_noRNA/gene_prediction/ECO5_noRNA_predict/annotate_misc/run_busco/


[07/08/23 18:12:11]: 1,223 annotations added
[07/08/23 18:12:11]: Skipping phobius predictions, try funannotate remote -m phobius
[07/08/23 18:12:11]: Existing SignalP results found: ECO5_noRNA_predict/annotate_misc/signalp.results.txt
[07/08/23 18:12:11]: 624 secretome and 0 transmembane annotations added
```

**Comment by nextgenusfs** [comment]
> 1 - the InterProScan5 iprscan.xml file in annotate_misc/ is deleted each time funannotate annotate is run, leading to a file not found error. This doesn't seem to happen to any other annotate_misc/ files (when rerunning from failed attempts, funannotate nicely sees the old pieces even).

Hmm, this is not expected behavior.  From your command it seems you have multiple folders going on?  And several nested runs perhaps? Maybe that is the cause of the error/confusion. The idea is that you should just pass the parent output folder to the scripts and any files that are not in that location, ie something like this:
```
# running predict 
$ funannotate predict -i genome.fasta -o output_dir -s "Genus species" 

# running iprscan wrapper
$ funannotate iprscan -i output_dir -m local 

# running annotate
$ funannotate annotate -I output_dir 
```

> 2 - Phobius doesn't seem to work correctly within annotate, remote, or separately locally. But it is in PATH, and tries to run. (I know you all didn't make Phobius, but there isn't a github or much support over there it seems)

Here it is looking for `phobius.pl` in the PATH, if that isn't there it won't run it. So perhaps just a change in how the script was installed or maybe its a different version.  The remote scripts are probably broken and haven't been updated in awhile.  I originally wrote them ~5-6 years ago as I couldn't get those executables to run on OS X (my development machine).  The remote functions won't be included in `funanntoate2`.

**Comment by igwill** [comment]
Thanks - somehow after having to install and setup InterProScan separately, it stuck in my head as a thing that also then needed to be directly feed into the `annotate `command like `signalp` or `antismash`. After removing the redundant `--iprscan` option it worked perfectly.

Got Phobius to work to. For the other folks out there: The phobius installation Readme suggests making a symbolic in /bin/ with `ln -s /usr/local/share/phobius/phobius.pl /usr/local/bin/phobius`
But since funanntoate will look for "`phobius.pl`" your symbolic link needs to have the `.pl` too.

Easy fixes, thank you for the quick response.
