### ISSUE TITLE
Funannotate compare - ValueError: invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by mikaeldahl** [nextgenusfs/funannotate#98]
I upgraded to 0.7.1 today and received a new error I didn't get with 0.6.2. 
When it start parsing the genomes it ends and gives the following error message

##########################
funannotate compare -i Saico_2 Neo_irre2 --cpus 24                                                                                        [10:51]
-------------------------------------------------------
[10:51:47 AM]: OS: linux2, 24 cores, ~ 49 GB RAM. Python: 2.7.13
[10:51:47 AM]: Running funannotate v0.7.1
[10:51:47 AM]: Now parsing 2 genomes
[10:51:50 AM]: working on Saitoella complicata NRRL Y-17804 genome
Traceback (most recent call last):
  File "/home/mikael/.linuxbrew/Cellar/funannotate/0.7.1/libexec/bin/funannotate-compare.py", line 160, in <module>
    if int(genomeStats[9]) == 0:
ValueError: invalid literal for int() with base 10: '7,211'

########################3

**Comment by nextgenusfs** [comment]
`brew upgrade funannotate` should get you past this, sorry about the bug.

**Comment by mikaeldahl** [comment]
Yes I got pass that but unfortuntely I run into a new error.
#################################
mikael@mikael-HP-Z600-Workstation[compare_genomes] funannotate compare -i Saico_2 Neo_irre2 --cpus 24                                                                                        [ 7:57]
-------------------------------------------------------
[07:59:00 PM]: OS: linux2, 24 cores, ~ 49 GB RAM. Python: 2.7.13
[07:59:00 PM]: Running funannotate v0.7.2
[07:59:00 PM]: Now parsing 2 genomes
[07:59:03 PM]: working on Saitoella complicata NRRL Y-17804 genome
Traceback (most recent call last):
  File "/home/mikael/.linuxbrew/Cellar/funannotate/0.7.2/libexec/bin/funannotate-compare.py", line 165, in <module>
    functional = lib.getGBKannotation(GBK)
  File "/home/mikael/.linuxbrew/Cellar/funannotate/0.7.2/libexec/lib/library.py", line 2046, in getGBKannotation
    meropsDict = MEROPS2dict(os.path.join(parentdir, 'DB', 'merops_formatted.fa'))
  File "/home/mikael/.linuxbrew/Cellar/funannotate/0.7.2/libexec/lib/library.py", line 1917, in MEROPS2dict
    with open(input, 'rU') as fasta:
IOError: [Errno 2] No such file or directory: '/home/mikael/.linuxbrew/Cellar/funannotate/0.7.2/libexec/DB/merops_formatted.fa'
###################################################

**Comment by nextgenusfs** [comment]
You need to run funannotate setup again when you upgrade versions.

**Comment by mikaeldahl** [comment]
Which file or files are parsed for the compare?

Skickat från min iPhone

> 21 juli 2017 kl. 23:30 skrev Jon Palmer <notifications@github.com>:
> 
> You need to run funannotate setup again when you upgrade versions. 
>

**Comment by nextgenusfs** [comment]
The script can't find the merops database fasta file, which needs to be in the DB directory.  The DB directory is symlinked (usually), so you can run:
```
funannotate setup -m all -d /path/to/funannotate/DB/folder
```
Which should properly setup the symlink.  If you still get errors, try to remove the symlink first and then re-run, i.e.
```
rm -r /home/mikael/.linuxbrew/Cellar/funannotate/0.7.2/libexec/DB
```

**Comment by nextgenusfs** [comment]
Great.  I tried to make the home-brew upgrade automatically recognize the softlink and link it for you, but it is kind of clunky and doesn't always work.
