### ISSUE TITLE
UnboundLocalError: local variable 'values1' referenced before assignment

### ISSUE THREAD

**Issue by bgruening** [nextgenusfs/funannotate#983]
Hi,

we got the following traceback with one of our runs.

```
Traceback (most recent call last):
  File "/usr/local/tools/_conda/envs/__funannotate@1.8.15/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/usr/local/tools/_conda/envs/__funannotate@1.8.15/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/usr/local/tools/_conda/envs/__funannotate@1.8.15/lib/python3.8/site-packages/funannotate/predict.py", line 2074, in main
    lib.trainAugustus(
  File "/usr/local/tools/_conda/envs/__funannotate@1.8.15/lib/python3.8/site-packages/funannotate/library.py", line 10942, in trainAugustus
    train_results = getTrainResults(
  File "/usr/local/tools/_conda/envs/__funannotate@1.8.15/lib/python3.8/site-packages/funannotate/library.py", line 10679, in getTrainResults
    float(values1[1]),
UnboundLocalError: local variable 'values1' referenced before assignment
```

**Comment by aforestsomewhere** [comment]
I see a similiar error, it looks like there are issues with exon coordinates during augustus training (the log is longer, the issues occurs with 100s of exons):

`Will create parameters for a EUKARYOTIC species!
creating directory /../funannotate/predict_misc/ab_initio_parameters/augustus/species/saccharomyces_uvarum_zp964/ ...
creating /../funannotate/predict_misc/ab_initio_parameters/augustus/species/saccharomyces_uvarum_zp964/saccharomyces_uvarum_zp964_parameters.cfg ...
creating /../funannotate/predict_misc/ab_initio_parameters/augustus/species/saccharomyces_uvarum_zp964/saccharomyces_uvarum_zp964_weightmatrix.txt ...
creating /../funannotate/predict_misc/ab_initio_parameters/augustus/species/saccharomyces_uvarum_zp964/saccharomyces_uvarum_zp964_metapars.cfg ...
The necessary files for training saccharomyces_uvarum_zp964 have been created.
Now, either run etraining or optimize_parameters.pl with --species=saccharomyces_uvarum_zp964.
etraining quickly estimates the parameters from a file with training genes.
optimize_augustus.pl alternates running etraining and augustus to find optimal metaparameters.

Error: In sequence scaffold_1_63445-70692: One CDS exon does not begin properly after the previous CDS exon.602 >= 600
GBProcessor::getGeneList(): Intron has non-positive length.
Encountered error after reading 0 annotations.
Error: In sequence scaffold_1_92820-94373: One CDS exon does not begin properly after the previous CDS exon.602 >= 600
GBProcessor::getGeneList(): Intron has non-positive length.
Encountered error after reading 0 annotations.
Error: In sequence scaffold_1_137998-140189: One CDS exon does not begin properly after the previous CDS exon.1591 >= 1589
GBProcessor::getGeneList(): Intron has non-positive length.
Encountered error after reading 0 annotations.

**Comment by tboonf** [comment]
I am getting a similar error message here. Does any one have any solution to it ?

**Comment by pwkooij** [comment]
it seems to be an issue with the 'augustus' build, but haven't found a solution yet so following
